- css/disciplines-slider.styl
- css/filmstrip.styl
- css/project-list-pages.styl
Should fix wonky layout on phones and allow the filmstrip to be scrolled by swiping.
Fixes #2232 
Fixes #2233
> Project page: small screen layout

- app/components/project-card-list.cjsx
- app/lib/project-sorts.coffee
- app/pages/projects.cjsx
Adds sort by project name to the list of options.
Moves the sort options from app/components to app/lib.
> Sort by project name

- css/filmstrip.styl
- css/project-list-pages.styl
Also, fix the padding on the sort/search container.
Works towards #2433
> Make the filmstrip scroll at all viewport sizes

- app/talk/recents.cjsx
> Make talk-recents request after component mounts

- app/components/project-card-list.cjsx
when searching for projects from the new projects page UI, the launch_approved parameter should be sent to the API call
> search box should specify launch_approved

- README.md
@mcbouslog I think this description of the dropdown task is in sync with what exists in master right now. If the annotation has changed, please keep it updated here.
> Describe combo and dropdown tasks, column tool

- app/components/subject-viewer.cjsx
workflows are not set in talk, just the classification interface.
> test for workflow in talk

- app/components/char-limit.cjsx
- app/pages/lab/project-details.cjsx
These are hardcoded in at the moment, but I wonder if we could do something clever with an options request to get these
related to #2239
> Add char limit info to fields on project builder

- app/classifier/tasks/survey/choice.cjsx
- css/survey-task.styl
Hides radios with absolute position and almost transparent opacity.
Adds names to radio button groups.
> Add survey choice radio buttons to browser tab order

- css/classify.styl
Vertically middle align with text
Add slight padding so that when embeded with text they have room to breathe.
> Updating styling for images in tool labels

- package.json
I was mistaken about the auto-update, @parrish (because of the `~` prefix).
> Bump panoptes-client

- app/classifier/tasks/dropdown/index.cjsx
> add focus to dropdowns

- package.json
Reverts zooniverse/Panoptes-Front-End#2558
> Revert "Bump panoptes-client"

- package.json
With correct OAuth hosts for same-domain and cross-domain access.
> Bump panoptes-client again

- app/pages/lab/workflow.cjsx
> add style to task delete button

- app/pages/lab/talk.cjsx
- css/lab.styl
Probably doesn't make sense until #2580 is merged
> Adds suggested tags to the lab page

- app/pages/project/stats/stats.cjsx
linked to #2591 and #2593
message to users that the ETA may be wrong - happy to change the text on this one.
> message possibly incorrect ETA problem

- app/classifier/tasks/single.cjsx
This probably got missed in a code review somewhere.
> Remove extraneous console log

- app/talk/tags.cjsx
> Ensure talk tag pagination resets to first page when switching tags

- app/talk/quick-subject-comment-form.cjsx
> Add project context to subject comments

- app/pages/lab/workflow-create-form.cjsx
- app/pages/lab/workflow.cjsx
New workflows start with an empty task list. Closes #934.
> Do not create a default workflow task

- app/pages/lab/workflow-create-form.cjsx
> Remove default first_task

- app/pages/admin/user-settings.cjsx
- app/pages/lab/subject-set.cjsx
use defaultValue to set the initial value
> allow admin subject limit field to be updatable

- app/pages/project/classify.cjsx
Just increases the minicourse interval to 5 as requested by Gravity Spy, cc @trouille
> Increase minicourse interval to 5

- app/pages/lab/workflow-viewer/task.cjsx
fixes https://github.com/zooniverse/Panoptes-Front-End/issues/2628
> do not truncate task keys in workflow visualization

- README.md
Updates the READ.ME's descriptions of package.json scripts to be in sync with changes from #2656.
> update docs for package.json

- app/partials/app.cjsx
- package.json
> Updates to the Geordi client

- app/pages/project/index.cjsx
Inactive workflows that were stored as the project's default or in the user's preferences were still be linked from the project-level navigation.
This checks for active-ness before setting the query on that link.
Closes #2658.
> Don't link to inactive workflows

- app/components/char-limit.cjsx
- app/pages/lab/project-details.cjsx
Some string fields come back as `null` when they're empty. Fixed existing instances and added `propTypes` for better errors in the future. Fixes #2681, I believe, but re-reading it I'm not entirely sure. Re-open if it doesn't.
> Fix CharLimit instances

- app/pages/lab/collaborators.cjsx
- app/pages/lab/project.cjsx
Be more specific about which user's roles we are testing where we can. Also added a larger page size to the collaborators page for projects with large numbers of users with roles. This should probably just have paging put on it.
> Lab user roles testing

- app/pages/collections.cjsx
- app/partials/owned-card.cjsx
> Ensure that collection owner name is displayed when we have a mix of owners

- app/components/subject-viewer.cjsx
- css/classify.styl
> Restore fix for IE11

- app/talk/search-input.cjsx
- app/talk/tags.cjsx
It's a small change, but it may help
> Use thumbnails in tag search results and hint at tag search availability

- app/talk/lib/paginator.cjsx
> Ensure logClick is defined in the pagination component

- app/components/pass-router-context.cjsx
Fixes broken account drop down and errors thrown on navbar use.
> Add geordi to childContextTypes

- app/partials/avatar.cjsx
> Fix the URL for the default avatar

- app/pages/dev-classifier/index.cjsx
- app/pages/dev-classifier/mock-data.coffee
- css/survey-task.styl
Closes #2471.
Also fixes the dev classifier on iOS. I don't entirely understand the problem, so I'm going to look into it a bit more, but this'll at least work around it.
> Style long survey choices

- app/pages/notifications.cjsx
- css/talk.styl
Minor style edits to improve visibility on project pages.
> Improve notification visibility.  Closes #1862

- app/pages/admin.cjsx
The admin page was expecting to have a user before one was determined.
> Admin page: check that a user exists

- app/components/step-through.cjsx
- app/lib/tutorial.cjsx
Addresses #2698. Also adds an overflow scroll fix for IE.
> Tutorial scroll fix 2698

- app/components/pass-context.cjsx
Fix for mobile nav.
More robust context passer coming up.
> Pass initialLoadComplete context

- app/pages/lab/visibility.cjsx
- app/router.cjsx
- css/buttons.styl
- css/lab.styl
Adds checkboxes to verify that the user has reviewed policies, best practices, and user feedback forms before requesting project review.
Deployed at https://beta-review-check.pfe-preview.zooniverse.org
cc/ @trouille
> Adds required checks to project visibility "Apply for review" button.

- app/pages/admin/project-status.cjsx
- app/pages/lab/project.cjsx
- app/pages/lab/workflow.cjsx
> Make tutorials available to all projects

- app/pages/lab/mini-course.cjsx
Add instructions for the mini-course editor.
> Add mini-course instructions

- app/classifier/drawing-tools/grid.cjsx
- app/classifier/drawing-tools/index.coffee
- app/classifier/frame-annotator.cjsx
- app/classifier/index.cjsx
- app/classifier/tasks/drawing-task-details-editor.cjsx
- app/classifier/tasks/drawing/grid-buttons.cjsx
- app/classifier/tasks/drawing/icons.cjsx
- app/classifier/tasks/drawing/index.cjsx
- app/classifier/tasks/drawing/marking-initializer.cjsx
- app/classifier/tasks/drawing/markings-renderer.cjsx
- app/classifier/tasks/generic-editor.cjsx
- app/components/frame-viewer.cjsx
- app/pages/admin/project-status.cjsx
- app/pages/dev-classifier/index.cjsx
- app/pages/dev-classifier/mock-data.coffee
- app/pages/project/classify.cjsx
- css/grid-buttons.styl
- css/main.styl
Staged branch (with test project) at:
https://weather-cells-tool.pfe-preview.zooniverse.org/projects/wgranger-test/old-weather-grid-testing/classify
This tool is used to expedite the tedious process of marking cells in a table. Users begin by marking cells, then rows, and finally save a grid to use for future/similar annotations.
> New Grid Tool

- app/pages/lab/workflow-viewer/workflow.cjsx
#2785 remove a needed require from the workflow visualization, this PR puts it back in.
@brian-c could you take a quick look at this?
> fix the workfow visualization

- app/layout/site-nav.jsx
- app/partials/zooniverse-logo.cjsx
Set the title to 'Show navigation' for the nav toggle button.
> Allow the Zoo Logo title to be overridden

- app/subjects/comment-form.cjsx
- app/talk/board.cjsx
- app/talk/comment.cjsx
- app/talk/discussion-new-form.cjsx
As reported [here](https://github.com/zooniverse/Panoptes-Front-End/issues/2612#issuecomment-231884196)
> Pass project context to various comment boxes

- app/classifier/drawing-tools/point.cjsx
- app/classifier/tasks/drawing/markings-renderer.cjsx
- app/classifier/tasks/generic-editor.cjsx
Adds an option to the point tool to allow the size of the points to be specified via a dropdown menu in the project builder.
Closes #2157
> Allow resizing of the point drawing tool

- app/pages/project/stats/index.cjsx
- app/pages/project/stats/stats.cjsx
utilize `getWorkflowsInOrder`  to load workflows for stats page, edit `stats.cjsx` React life cycle events
> Stats page workflows

- app/pages/collections/list.cjsx
Insofar as I can tell, this was never working.  I don't see any issue with just preserving the current path, can you?
> Fixes collection pagination.  Closes #2789

- css/field-guide.styl
Fixed #2570. Staged at: https://fix-field-guide-scroll-ie11.pfe-preview.zooniverse.org/
> Add IE scroll fix

- app/pages/project/stats/index.cjsx
- app/pages/project/stats/stats.cjsx
> get only active workflows for stats page

- css/talk.styl
> fix margin

- app/pages/dev-classifier/mock-data.coffee
Staged at: https://missing-dev-classifier-tools.pfe-preview.zooniverse.org/
> Add Small Point and Image Invert to Dev Classifier

- app/pages/lab/mini-course.cjsx
- app/pages/lab/tutorial.cjsx
Updating instructions so it's clear that the mini-course must be linked to a workflow for it to show up in the project.
> Update mini-course instructions

- app/layout/site-nav.jsx
- app/layout/site-nav.styl
As per @jwbmartin in #2706 [here](https://github.com/zooniverse/Panoptes-Front-End/pull/2706#issuecomment-235339595)
> Remove extra styling on nav "Build a project" link

- app/classifier/world_wide_telescope.cjsx
Staged at: https://adjust-wwt.pfe-preview.zooniverse.org/projects/wgranger-test/old-astro-test/classify
**Note**: In order to work property once merged, the workflow for Astronomy Rewind (in production) will have to include RA1950 and DEC1950 options in the order specified with this PR.
Fixes #2676
> Adjust World Wide Telescope Integration

- app/pages/lab/about/results.cjsx
add in help line for results page
> add in help line for results page

- css/main.styl
- css/video.styl
- package.json
Depends on zooniverse/markdownz#40
Should allow Solar Stormwatch to embed their youtube video tutorial.
> Basic styles for embedded youtube videos

- app/pages/home-not-logged-in/promoted.cjsx
> Use redirect if project has one

- app/classifier/frame-annotator.cjsx
Get the rendered subject image dimensions from the DOM when needed, rather than relying on stored data in component state, which may be out of synch with the rendered DOM.
Fixes #2836
> Get subject image scale dynamically

- app/layout/index.jsx
- app/layout/index.styl
> Remove the main layout overlay

- app/pages/about/team-page.cjsx
Update Meg's details for #2578.
> Update Meg's details

- app/components/frame-viewer.cjsx
- app/components/pan-zoom.jsx
Moves the pan/zoom controls into their own component, rewritten in ES6.
> Move pan/zoom into its own component

- app/pages/admin/project-status.cjsx
> Output version changes without using toString()

- app/talk/private-message-form.cjsx
Untested at the moment. Staging now...
> Change name -> profile_name in PM form

- app/pages/home-logged-in.cjsx
> Hold off rendering until the promises resolve

- app/pages/home-logged-in.cjsx
Fixes the `if` block so that it renders the project cards.
> Bugfix: actually display your recent projects when logged in

- app/pages/notifications/message.cjsx
Currently it's trying to follow a link that doesn't exist.
Fixes #2870.
> Properly fetch message notification users

- app/partials/register-form.cjsx
- app/partials/sign-in-form.cjsx
via zooniverse/Zooniverse#51 - the API errors out if usernames are too long
> Limit username length to 255 characters

- app/pages/about/publications-page.cjsx
Closes #2892 
Adds dates to each publication hash on the publications page.
> Add Dates to Publications

- app/layout/account-bar.jsx
- app/layout/index.jsx
- app/layout/login-bar.jsx
- app/layout/site-nav.jsx
- app/layout/site-nav.styl
Uses a hamburger icon for the toggle button when the top nav is hidden, Zooniverse logo when visible.
Closes #2846
> Hamburger icon to reveal top nav on project pages

- app/components/subject-viewer.cjsx
> Hide subject metadata prefixes when displayed

- app/main.cjsx
> added shouldUpdateScroll to router

- app/pages/lab/field-guide/actions.js
> Remove field guide default item

- css/field-guide.styl
closes #2290 
staged at https://fix-2290.pfe-preview.zooniverse.org/
> Adjust Field Guide Height

- app/pages/admin/project-status.cjsx
- app/pages/lab/project.cjsx
> Make field guides available to all projects

- app/pages/about/team-page.cjsx
> Fix typo - change team to time

- app/components/project-icon.cjsx
- app/pages/home-logged-in.cjsx
Include avatars and owners in the initial API calls.
Update ProjectIcon to use cached resources if possible.
Supersedes #2882
> Optimise recent projects

- app/layout/account-bar.jsx
- app/layout/index.jsx
- app/layout/site-nav.jsx
- app/layout/site-nav.styl
- app/layout/site-subnav.jsx
- app/pages/project/index.cjsx
- app/partials/app.cjsx
- app/talk/lib/notifications-link.cjsx
Fixes #2873.  Closes #2825.  Somewhat helps #2858
Deployed at https://optimize-menu.pfe-preview.zooniverse.org/
> Optimize menu

- app/classifier/index.cjsx
Fixes #2963 .
This check returns true for almost all subjects, showing the 'Done & Talk' button on every project.
> Remove broken Gravity Spy gold standard check

- README.md
Add tip for testing with production data.
> Add tip for testing with production data.

- app/pages/about/about-home.cjsx
Added in a sentence to explicitly say how to volunteer to the About page, with link to the Projects page.
> Addition of Sentence about Volunteering

- app/pages/about/publications-page.cjsx
Adds paper to publications page.
- [N/A] If it's a new component, is it in ES6? Is it clear of warnings from ESLint?
- [N/A] Have you replaced any `ChangeListener` or `PromiseRenderer` components with code that updates component state?
> Adding Galaxy Zoo/Smart Society/Microsoft paper

- app/pages/settings/email.cjsx
Fixes #2483 
https://fix-2483.pfe-preview.zooniverse.org/
> Catch Errors on User Email Settings Page

- app/components/multi-image-subject-options-editor.cjsx
Fixes partially #3014 .
Keep track of clone markers checkbox value or default it to false.
> Remember clone marks checkbox value or default it to false

- app/pages/lab/talk.cjsx
Added in a line to describe what is meant by  a suggested tag on Talk.
Added in line to explain what is a suggested tag
> Added in line to clarify what is meant by suggested tag

- app/partials/markdown-help.cjsx
> add in subscript and superscript into Markdown help

- app/pages/project/index.cjsx
Fixes #3043.
Also fixes long load time from NfN expedition card to classifying interface. Long load time was caused by loading of all active workflows, which in NfN's case (and I think currently unique to NfN) includes many large workflows.
- added conditional to workflow load where if workflow query and either the project accepts queries (like NfN) or user is admin, owner or collaborator (clicked Test Workflow button) then only load that specific workflow
To load one workflow it might be simpler to use `apiClient` and bypass `getAllWorkflows` and `getSelectedWorkflow`, but I thought it would be preferred to keep the refactored flow? I have a different branch that does utilize `apiClient`, if that would be preferred.
mentioning @srallen, @eatyourgreens
> edit workflows request if query

- app/classifier/tasks/drawing/summary.cjsx
- package.json
Following feedback on #2560 / #2536 - Remove the third party dependency. More details in the commit comment
> Improve solution to cleanup drawing summary

- app/pages/admin/project-status.cjsx
Adds `persist answers` to the experimental tools array so feature development can begin for #2956. I want to have this merged in so when Mark is back we can split up work on this.
> Add `persist answers` to experimental tools array

- app/components/project-card-list.cjsx
- app/pages/projects.cjsx
Also remove annoying warning `browser.js?030c:49 Warning: [react-router] props.history and context.history are deprecated. Please use context.router.`
> Remove history mixin.

- package.json
- test/test.js
Add mocha dev dependency for testing our code...
> add mocha for testing

- app/pages/admin/user-settings.cjsx
> Add owned projects to the user admin page

- app/pages/about/publications-page.cjsx
> adds new publications

- webpack.build.js
Since I got the linter to work in Brackets, I thought I'd start fixing some issues.
> Fix some linting issues.

- app/layout/site-subnav.jsx
Fixes # .
The "..." within the header has been altered to "News". This has been okayed by Chris, Grant and Jordan.
> Header changed from ... to News

- app/components/classifications-ribbon.cjsx
- app/components/project-icon.cjsx
- app/pages/profile/stats.cjsx
Should fix project avatars not being shown on the user profile stats page.
> Fix stats avatars

- app/pages/project/stats/stats.jsx
Provides better information on the stats page for `never_retire` workflows (e.g. gravity spy).  Staged at https://stats_never_retire.pfe-preview.zooniverse.org/projects/zooniverse/gravity-spy/stats/?env=production
> better stats for never_retire workflows

- .travis.yml
- README.md
Get travis-ci.org to report test run status in pull requests.
> Add Travis config

- app/pages/about/index.cjsx
- app/pages/about/volunteering-page.cjsx
- app/router.cjsx
Page to describe the Zooniverse volunteering roles a bit more explicitly.
> Volunteering Page

- app/components/subject-viewer.cjsx
> Fix Invert Bug

- app/pages/about/volunteering-page.cjsx
made a few grammar suggested edits to the volunteering page
> minor grammar edits to volunteering page

- app/talk/comment-box.cjsx
> Add missing apostrophe to comment box

- app/pages/collections/list.cjsx
Fixes # .
Request collections when the component mounts, or when props change, and store the list in state.
> Remove PromiseRenderer from the collections List component

- app/pages/home-for-user/my-builds.jsx
- app/pages/home-for-user/recent-projects.jsx
Use the project cards route for the signed in home page for more efficient api resource usage that should speed up the render times (less network time).
> use the projects cards api end points for signed in home page

- app/pages/lab/data-dumps.cjsx
Clarifying that aggregation isn't available for survey tasks as well as text tasks.
> Add note about aggregation for survey tasks

- app/components/pan-zoom.spec.js
Adds unit tests for the PanZoom component.
> tests for pan-zoom

- app/pages/lab/project-details.cjsx
updated list of autogenerated tabs now on the landing page and also included directions on how one reorders the links
updated list of autogenerated tabs now on the landing page and also included directions on how one reorders the links
> updated external link help text

- app/layout/account-bar.jsx
> Link home from account menu.

- app/layout/site-nav.jsx
- app/pages/projects/filtered-projects-list.jsx
- app/pages/projects/index.jsx
- app/pages/projects/status-link.jsx
- app/router.cjsx
- css/secondary-page.styl
> Adds status to query params on projects page.

- app/collections/favorites-button.cjsx
Removes the PromiseRenderer in favour of storing the favourited status, and the favourites collection, in component state.
> Remove PromiseRenderer from the favourites button

- app/lib/publications.js
- app/pages/about/publications-page.cjsx
Hi,
I've added lots of new publications to the list. This also involved creating a new genre, "Physics", and adding a new Project, "Higgs Hunters".
thanks,
Helen
> Update of publications list

- app/pages/about/team-page.cjsx
- css/team-page.styl
Fixes # @trouille wanted Chicago changed to Adler
Changed the About section also fixed some pesky margin issues that were annoying me
> update Chicago and update some margin issues

- app/lib/publications.js
Hi,
Two more publications have been added to the list.
Thanks
Helen
> I've added two more publications to Snapshot Serengeti

- app/pages/about/acknowledgements.cjsx
added in the missing * at the end of the acknowledgements statement. Only one * on the left. Added in the right one.
> fixing the itallics in the new Acknowledgements page

- .travis.yml
- Dockerfile
Updates travis.yml file and Dockerfile to use the correct versions of node.js when testing the code.
> update configs for travis and docker

- app/layout/site-footer.jsx
Fixes #3248 .
Fixes 3 site-footer links.
> Site footer link fixes

- app/pages/profile/stats.cjsx
Removed an unused `PromiseRenderer` import.
cc #3216
> Remove unused PromiseRenderer

- app/classifier/drawing-tools/delete-button.cjsx
- app/classifier/frame-annotator.cjsx
- app/components/subject-viewer.cjsx
- app/pages/project/index.cjsx
- css/classify.styl
- css/project-page.styl
- css/tabbed-content.styl
Fixes several design and usability issues experienced on mobile.
1) Fixes margin issues on About header
2) Provides margin for project stats
3) Adds a line break aside the project name to separate project nav bar onto new line
4) Increases the click area for the "play" button when visible for a subject
5) Allows touch scrolling for subjects with non-drawing tasks
6) Increases delete button size on smaller screens
https://mobile-fixes.pfe-preview.zooniverse.org/
> Mobile usability fixes

- app/pages/home-not-logged-in/social.cjsx
@srallen, Michael's comment on Slack made me realise that it makes sense to sanitise blog excerpts too.
> Decode blog excerpts.

- app/classifier/drawing-tools/index.coffee
- app/classifier/drawing-tools/triangle.cjsx
- app/classifier/tasks/drawing/icons.cjsx
- app/pages/dev-classifier/mock-data.coffee
Fixes pretty much nothing
But it does add a triangle drawing tool
> Add Triangle tool

- app/pages/lab/help/lab-policies.cjsx
update the line of acknowledgements text in the policies page so it matches what's on the acknowledgements page. We decided that it would best to make sure the actual text is still in policies but use the acknowledgements page as a place for people searching for it can easily find this info
> update text on policies page so it matches what's on the acknowledgements page

- app/pages/get-involved/call-for-projects.cjsx
Hi,
I've updated the call for projects to include the Text Transcription call for projects.
Thanks
Helen
> Updated call for projects

- app/pages/project/classify.cjsx
Fixes #3324 
Staged at https://fix-finished-banner-import.pfe-preview.zooniverse.org/
> Use `import` for jsx components

- app/pages/get-involved/call-for-projects.cjsx
I've updated the deadline for VVH's text transcription call for projects.
> Updated the deadline for project proposals

- app/pages/lab/help/lab-policies.cjsx
Hi,
I've given this page a heavy edit, and have included a note on policy review timelines to address PFE issue #3303.
One thought to improve things further - it may be worth splitting this page into two pages "How to Launch your Project" and "Policies". I'm not sure how to do this yet, but if others think this is a good idea I'm happy to give it a go...
H
> Policies page edits

- app/pages/lab/help/lab-policies.cjsx
There's one 'contact us' that didn't have a link to the contact page, so I added it in. Also fixed a typo ';' -->':'
> fixed a typo and added in a missing link

- app/components/pan-zoom.jsx
Fixes pan + zoom being enabled for all projects, regardless of the setting in the project builder.
Check for `this.props.enabled` before adding listeners for the mouse wheel and keyboard.
Fixes a bunch of linter errors too.
> Check if PanZoom is enabled on mount

- css/owned-list-pages.styl
Fixes #3341 .
Removes the large vertical padding from paragraphs.
> Remove massive vertical padding from paragraphs.

- app/pages/admin/project-status-list.jsx
Fixes bugs found by @mrniaboc related to queries on admin pages.
https://fix-admin-pagination.pfe-preview.zooniverse.org/
> Fix admin pagination

- app/pages/about/team-page.cjsx
Hi,
I've just done a couple of minor edits to Laura's biography.
H
> Edits to Laura's biography

- app/main.cjsx
Exposes the talk client for console access
> Expose talk API

- css/forms.styl
- css/secondary-page.styl
Fixes #3346.
Describe your changes. 
Changed the text color to increase contrast between text and background colors for about pages and the project editor.  Staged [here](https://goo.gl/f1FTBi).
> increase text/background contrast for about pages and project editor

- app/pages/lab/project-details.cjsx
This adds a project owner as an an avatar choice in the Words from the Researcher section. 
https://add-owner.pfe-preview.zooniverse.org/
> Expose Owner in Researcher List

- app/pages/lab/project-details.cjsx
Fixes #3385  .
There was an error in how the cjsx code was written here, so it didn't quite behave as expected. This should clear up any errors. This PR also adds a project avatar as a option for the "Words from the Researcher" section.
https://adjust-researcher.pfe-preview.zooniverse.org/
> Fix Owner Bug and Expose Project Avatar

- app/pages/home-for-user/index.jsx
- app/pages/lab/actions/media.js
- app/pages/lab/media-area/index.jsx
- app/pages/lab/media-area/media-area-view.jsx
- app/pages/settings/profile.cjsx
- css/home-page-for-user.styl
- css/site-nav.styl
Closes #3187 
This PR adds a button on a user's homepage to change a profile background. Most of the line changes on this PR is rewriting the user home page into our standard ES6 and abstracting media actions into their own file to make them flexible. There's also some work done to make the button more accessible with focus, which was being difficult with simple `&:focus` styling.
https://edit-background.pfe-preview.zooniverse.org/
> Change Background Button

- app/classifier/index.cjsx
- app/components/multi-image-subject-options-editor.cjsx
- app/components/subject-viewer.cjsx
This PR adds an infinite loop to the subject flipbook so a user doesn't have to keep pressing "play" after `playIterations` has run its course. This was deceptively easy to add, so I'm curious if I'm missing something with the flipbook functionality. Seems to work well though.
I also enlarged the play/pause icon size based on feedback.
https://infinite-loop.pfe-preview.zooniverse.org/projects/wgranger-test/single-task-bug
* The "Infinite Loop" workflow on this project has a flipbook.
> Infinite loop

- app/components/text-viewer.jsx
- css/subject-viewer.styl
- Increase the color contrast between the text and the background of text subjects. 
- Break line at newline characters in text subjects
Staged [here](https://text-subject-styling.pfe-preview.zooniverse.org/).
> style changes for text subjects

- app/components/text-viewer.jsx
Explicitly set CORS mode when fetching text subjects.
> Specify CORS mode on text subject fetch requests

- app/talk/inbox-form.cjsx
- app/talk/lib/message-subject-validations.coffee
Fixes #1954
Validations weren't working correctly with the inbox form. Sometimes you'd get an error from the API, other times from the corresponding validation files. Often times you'd hit an error that would freeze the input form.
Also, the API required a subject field to be at least 3 characters, which is why that validation was added on the frontend.
https://empty-message-bug.pfe-preview.zooniverse.org/
> Fix Validation Errors

- app/components/text-viewer.jsx
- css/subject-viewer.styl
As a follow up to #3411, this PR adds a consistent background color to text subjects. Staged [here](https://text-subject-styling.pfe-preview.zooniverse.org/).
> consistent background color for text subjects

- package.json
> Use latest modal-form 2.4

- app/talk/discussion.cjsx
Indentation was wrong for this API call.
> Fix project roles on Talk discussion pages

- app/classifier/tasks/dropdown/index.spec.js
- app/classifier/tasks/generic-editor.cjsx
- app/classifier/tasks/generic.spec.js
- app/classifier/tasks/multiple.spec.js
- app/classifier/tasks/single.cjsx
- app/classifier/tasks/single.spec.js
Initial rendering tests for a few Project Builder tasks at the moment.
> Rendering tests for single answer, multiple answer and dropdown tasks

- app/classifier/index.cjsx
Fixes #3420  .
https://fix-3420.pfe-preview.zooniverse.org/
> Hide Talk Button if Subject is Flagged

- app/classifier/mini-course-button.jsx
- app/classifier/restart-button.jsx
- app/classifier/tutorial-button.jsx
- app/lib/geordi-logger.coffee
- app/lib/mini-course.cjsx
- app/lib/tutorial.cjsx
- app/pages/project/classify.cjsx
This adds geordi to the mini-course and tutorial to track its completion timestamp in geordi for future analysis. It's a bit more invasive than I'd like, but the modal-form doesn't have access to the app context.
@amyrebecca could you look over to let me know if it's setup correctly and if there's any way to check if it's actually logging? Anything to look for in the network tab in dev tools?
> Track mini-course and tutorial completion

- app/pages/get-involved/call-for-projects.cjsx
Hi,
I've edited the Call for Projects page - I've removed the Transcription Call for Projects for VVH as this is now closed, and I have edited the text slightly for the Biomedical Call for projects.
Thanks
Helen
> Call for projects page edits

- app/lib/publications.js
I've added in some new publications
Helen
> New publications added

- app/components/cropped-image.cjsx
> Pass className down to SVG icons

- app/pages/collections/list.cjsx
> Remove collection thumbnails

- app/pages/project/stats/index.jsx
> fix `props` typo in PR #3509

- .mention-bot
sad times but it's pretty noisy
> add parrish to mention bot ignore list :(

- app/pages/project/classify.cjsx
Panoptes is deployed with this API.
> Fetch subjects to classify using new API

- app/classifier/drawing-tools/circle.cjsx
- app/pages/dev-classifier/mock-data.coffee
An issue came up with mobile browsing that the circle button would sometimes place a delete button out of bounds from the subject, making it difficult to delete a mark.
I also changed the name of ellipse on the dev classifier because it was a bit ridiculous we had it repeating so much.
https://circle-delete-button.pfe-preview.zooniverse.org/
> Move Circle Delete Button When Out of Bounds

- app/pages/lab/workflow-create-form.cjsx
> fix workflow typo

- app/classifier/index.cjsx
Update annotations in component state on classification change instead.
> Remove ChangeListener from classifier

- app/pages/project/index.cjsx
Refactors the requests for the project pages, avatar, and background and moves them into the promise that is fetching other linked resources for the project. Also adds a request for project roles since there are some children components requesting for that too. The intention is to remove duplicate requests in children and just pass these down as props and used where needed. 
https://optimize-project-requests.pfe-preview.zooniverse.org/
> Move pages, avatar, and background requests to index promise

- app/classifier/index.cjsx
- app/classifier/task-nav.jsx
- app/classifier/task.jsx
- app/lib/intervention.cjsx
Builds on #3520 and extracts the Task area to its own component.
> Extract Task component

- .mention-bot
I noticed Sascha was still getting at mentioned :(
> Update ignore list

- .travis.yml
- app/pages/lab/apply-for-beta-form.spec.js
- package.json
Nyancat doesn't render properly and looks mad. :(
Example output: https://travis-ci.org/zooniverse/Panoptes-Front-End/jobs/209433184
> Use default reporter on Travis

- app/classifier/tasks/multiple.jsx
Fixes #3584  .
Highlights selected answers for the multiple task.
https://active-multiple-choice.pfe-preview.zooniverse.org/
> Show Active Answers for Multiple Task

- app/classifier/task-nav.jsx
- app/classifier/tasks/combo/index.cjsx
- app/classifier/tasks/crop/index.cjsx
- app/classifier/tasks/drawing/index.cjsx
- app/classifier/tasks/dropdown/index.cjsx
- app/classifier/tasks/index.spec.js
- app/classifier/tasks/text/index.cjsx
Add some generic tests to run against all the task components.
> Tasks generic tests

- app/talk/active-users.cjsx
don't spam sugar and by proxy the panoptes api.
> only request the active-users once a minute

- css/collections-page.styl
- css/subject-viewer.styl
Fixes #3586  .
Keeps video play bar within container.
https://contain-video-controls.pfe-preview.zooniverse.org/
> Contain Video Play Controls

- app/pages/project/index.cjsx
Fixes bug just introduced in #3556
https://fix-nfn-workflow-query.pfe-preview.zooniverse.org/projects/zooniverse/notes-from-nature/classify?workflow=3330&reload=true&env=production
> Fix nfn workflow query

- app/collections/preview.cjsx
- css/subject-page.styl
Fixes #2869 
https://fix-2869.pfe-preview.zooniverse.org/
> Turn Collections Preview into Link

- app/pages/project/index.cjsx
Check that a user is present to check for an ID.
https://fix-id-issue.pfe-preview.zooniverse.org/
> Check User Present Before Determining Roles

- app/pages/lab/apply-for-beta-form.spec.js
This just comments out the` ApplyForBetaForm` tests that were failing due to timeout. It's noisy when working with tests locally. We can get back to this post SGL and figure out how we want to do async mocking and integration tests.
> Comment out tests failing due to time out

- app/pages/project/index.cjsx
Removes the `project_roles` include that was causing an n+1.
https://remove-include.pfe-preview.zooniverse.org/
> Remove include

- app/pages/project/index.cjsx
This is a follow up to zooniverse/Panoptes#2251. **Do not merge until zooniverse/Panoptes#2251 is deployed to production**. This changes the `selectRandomWorkflow` method to use the newly serialized `active_workflows` links.
https://use-active-workflows-links.pfe-preview.zooniverse.org/
> Used serialized active_workflows for random selection

- package.json
Adds `http_cache=true` to all API requests
> Update panoptes-client to 2.7

- app/pages/admin/project-status.jsx
i always have to open up a network tab to get this information, it would be nice to have it on the page.
> simple summary stats for project

- app/components/frame-viewer.jsx
Fixes: Subjects won't display in Talk when the workflow is undefined.
> Bugfix: check for workflow

- css/home-page.styl
The featured project image is currently too large. This resizes that image to a different max-height.
https://resize-featured-proj-image.pfe-preview.zooniverse.org/
> Resize Featured Project Image

- app/pages/project/index.cjsx
This fixes some workflow selection bugs in a couple of edge cases found with some non-launched approved projects:
- Fixes a `TypeError` when there are no active workflows for a project
- Fixes a loop attempting to fetch an inactive project default
This is a project that I purposely set an inactive workflow as default via console so you can see it now just errors once and stops attempting to load the project default forever:
https://fix-no-active-workflows-error.pfe-preview.zooniverse.org/projects/srallen086/more-testing
I don't want to clear out the project default from the project page since I can't assume the intention of the project owner (maybe they accidentally made the default workflow inactive before it was fixed in the lab?). The lab was fixed so this _can't_ happen in the lab …
> Fix workflow selection edge cases

- app/pages/project/classify.cjsx
Push completed classifications into the stored queue and submit from there.
Don't resubmit 422 errors.
> Always submit classifications via the stored queue

- app/pages/project/classify.cjsx
> Filter the upcoming subject queue for duplicates

- app/lib/publications.js
> Fix Season Spotter avatar not appearing in publications

- app/layout/site-footer.jsx
- app/pages/about/faq-page.cjsx
- app/pages/about/index.cjsx
- app/pages/faq.cjsx
- app/router.cjsx
We probably want to add more FAQ's before merging. Suggestions welcome!
> Add FAQ page

- app/pages/lab/workflow.cjsx
Adds copy letting researchers know they can contact us if they need more complex retirement rules.
> add text about contacting zooniverse for complex retirement rules

- app/pages/lab/workflow-viewer/task.cjsx
Fixes #3785 .
FIxes broken require for the `Resizable` module.
> Fix broken ES6 module

- app/layout/site-footer.jsx
Fixes #3792 .
Fix broken link.
> Fix link to faq page

- app/pages/lab/subject-set.cjsx
> Upload whitelist

- css/home-page-for-user.styl
- css/project-card.styl
Fixes #3783.
Fixing bad rebase, copy of PR #3799.
> Remove border radius from Project Cards.

- app/pages/lab/project.cjsx
- css/lab.styl
Fixes #2292.
Because I've been meaning to do this for ages
> Add view project button to lab

- app/partials/register-form.cjsx
Fixes # 3812.
Match allowed chars with those included in error message.
> Include full stop (.) in allowed chars for usernames

- app/classifier/annotation-renderer/svg.jsx
- app/classifier/frame-annotator.spec.js
- app/classifier/tasks/combo/index.cjsx
- app/classifier/tasks/crop/index.cjsx
- app/classifier/tasks/drawing/index.cjsx
- app/components/frame-viewer.jsx
Fixes #3803
Same as #3808, except this should correctly handle pointer events on subject images.
> Combo task pointer events

- app/classifier/annotation-renderer/svg.jsx
- app/classifier/classification-summary.jsx
- app/classifier/classifier.jsx
- app/classifier/feedback/feedback-ruleset.js
- app/classifier/feedback/helpers.js
- app/classifier/task-nav.jsx
Fixes #3762. Requires #3725 merging first.
> Allow feedback to override skipping classification summaries

- app/pages/home-common/featured-project.jsx
> Adds a meaningful alt text to the feat project img

- app/pages/home-common/featured-project.jsx
- app/pages/home-common/featured-project.spec.js
I could not for the life of me find how to test that `img` tag has both non-empty `alt` and `src` tags. Please send help.
> Add featured project tests

- app/layout/account-bar.jsx
- app/layout/index.jsx
- app/layout/site-nav.jsx
- app/pages/project/project-page.cjsx
- app/talk/lib/notifications-link.cjsx
- css/home-page.styl
- css/layout.styl
- css/modal-form.styl
- css/site-nav.styl
**Describe your changes:**
This branch includes changes to the nav bar to be merged into the new-signed-out-homepage branch. 
_Note_: This branch will merge into that other branch and not master.
https://new-navbar-style.pfe-preview.zooniverse.org/
> [2 of 4] New Signed Out Homepage (new navbar)

- app/pages/lab/data-dumps.cjsx
Add links to our data digging repo example code.
> add link to examples in the data digging repo

- css/site-nav.styl
Fixes #3867 
This PR makes some simple changes on the notification bar to make notifications more prominent. Also, the margins on the messages tab were a bit off.
https://adjust-navbar.pfe-preview.zooniverse.org/
> Tweak the Navbar

- css/project-page.styl
Fixes #3871 
https://mobile-subject-images.pfe-preview.zooniverse.org/
Uses a media query to solve the issue
> Allow Project Talk Images to Fit Mobile Screen

- app/components/file-viewer/audio-player.jsx
- app/components/file-viewer/index.jsx
- app/components/frame-viewer.jsx
- app/components/frame-viewer.spec.js
- app/lib/get-subject-location.coffee
- app/pages/lab/subject-set.cjsx
Fixes #3809 .
Implemented audio subjects for users with Admin access using a similar approach to that used for video subjects.
Replicated the tests that are allocated to video subjects.
Example project staged [here](https://audio-subject.pfe-preview.zooniverse.org/projects/hughdickinson/testing-audio-subjects).
> Audio subject

- app/lib/publications.js
> Fix publications with spaces in URLs

- app/pages/home-not-logged-in/promoted.jsx
- css/home-page.styl
Fixes #3866
This makes a few changes according to the issue above. Note: the addition of the div to wrap project cards is to keep the cards, which are a link, from filling an entire row (including blank space).
https://fix-3866.pfe-preview.zooniverse.org/
> Minor Landing Page Changes

- css/home-page.styl
Fixes #3866 
https://adjust-proj-cards.pfe-preview.zooniverse.org/
A previous PR was made to close this issue; however, that CSS change targeted all child divs of a section, instead of an immediate child, causing some irregular views.
> Fix Project Cards on Landing Page

- app/pages/home-not-logged-in/research.jsx
Fixes #3882, also removed an errant hyphen and full stop (from #3886).
> Fixed typo

- app/layout/site-nav.jsx
- app/pages/home-common/social.jsx
- app/pages/home-not-logged-in/research.jsx
- css/common.styl
- css/home-page.styl
Fixes #3886 
More landing page adjustments based on the issue. This also fixes an issue that is currently visible on mobile view where the project cards don't switch to column view correctly.
https://homepage-updates.pfe-preview.zooniverse.org/
> Make Cross-browser fixes and general adjustments

- app/lib/publications.js
- app/pages/about/publications-page.cjsx
Fixes #3927 .
Added new publications from Google doc as per the issue described.
> added new publications

- .github/CONTRIBUTING.md
Add role descriptions for PFE PRs.
staged [here](https://pfe-pr-roles.pfe-preview.zooniverse.org).
> Add PFE PR role descriptions

- app/pages/lab/workflow.cjsx
added a line to make it clearer you can unlink subjects in an active workflow
> adding a line to the actvie workflow help

- app/lib/publications.js
Fixes #3936 
Added Supernova Hunters from Google doc as per the issue described.
> added supernova hunters to publications

- app/classifier/tasks/highlighter/index.jsx
- app/classifier/tasks/highlighter/label-editor.jsx
- app/classifier/tasks/highlighter/label-renderer.jsx
- app/classifier/tasks/highlighter/selection.jsx
- app/classifier/tasks/highlighter/summary.jsx
Fixes most of the lint errors for the Highlighter task files. For ease of PR review, I wanted to merge these changes before addressing the Edge/IE issues mentioned in PR #3738.
> Highlighter Task Lint Fixes

- app/pages/privacy-policy.cjsx
Remove mention of JISC, add mention of Linode.
> Update mailing list info in Privacy Policy

- .github/PULL_REQUEST_TEMPLATE.md
Adds the Springer commit message guidelines to the PR template.
> Updates the PR template with commit message guidelines

- app/pages/admin.cjsx
- app/pages/admin/organization-status-list.jsx
- app/pages/admin/organization-status.jsx
- app/pages/admin/project-status/toggle.jsx
- app/router.cjsx
- css/admin-page.styl
Adds admin organizations section similar to admin projects section.
Staged branch - https://orgs-admin.pfe-preview.zooniverse.org/admin/organization-status
> organizations admin section

- app/classifier/tasks/generic.jsx
- app/classifier/tasks/multiple.jsx
- app/classifier/tasks/single.jsx
- app/components/tutorial.cjsx
Adds autofocus for question tasks by focusing the question, rather than the first answer, if no answer has been selected yet.
> Autofocus question tasks

- app/pages/project/home/project-home.jsx
Fixes #3990.
On project home page, change featured talk subjects height to match container height.
> edit project home featured talk subjects styling

- app/lib/publications.js
Fixes # 
Updated the publications page as per request.
Viewable at: https://update-pubs.pfe-preview.zooniverse.org/about/publications?env=production
> Updated publications

- app/pages/notifications/index.jsx
> fixes lack of space between sentences in no notifications message

- app/lib/publications.js
Updated the publications page - added publication by Jones+ 2017 under Solar Stormwatch
Viewable at: https://update-pubs.pfe-preview.zooniverse.org/about/publications?env=production
> Update publications page

- .github/PULL_REQUEST_TEMPLATE.md
Adds text and guidelines for resizing and compressing images.
> PR template update: Reminder for processing images

- app/pages/home-not-logged-in/research.jsx
- Removes `img` prop that was left on Thumbnail component.
- Related: #3998.
- Staged [here](https://remove-thumbnail-prop-typo.pfe-preview.zooniverse.org/).
> Remove prop typo.

- app/pages/about/acknowledgements.cjsx
> Fixed typo in Acknowledgements page

- app/classifier/tasks/multiple/index.jsx
- app/classifier/tasks/multiple/index.spec.js
- app/classifier/tasks/single/index.jsx
- app/classifier/tasks/single/index.spec.js
All tasks now live in directories under `app/classifier/tasks/`.
> Rename single and multiple tasks

- app/pages/lab/subject-set.cjsx
Add explicit instructions about what must be selected to make manifests work.
> add explicit note about selecting manifest and media files

- app/locales/es.js
- app/pages/project/index.cjsx
Adds a locale file for Spanish UI translations.
> Add a Spanish locale

- app/pages/admin/project-status/experimental-features.jsx
- app/pages/lab/collaborators.cjsx
Fixes #3884.
What it says on the tin.
> Adds translator role and filter it out from Talk roles.

- app/pages/admin/project-status.jsx
stop typing the lab url out by hand, link to it via the id we already have.
> link from admin page to lab

- app/classifier/world-wide-telescope.jsx
Avoids 0 rendering in the browser when array is empty
> WWT: convert array length to boolean

- .github/stale.yml
I forgot how much I dislike YAML.
> Tell stale-bot to ignore 'help wanted' issues

- app/pages/project/project-page.cjsx
Accidentally removed isAdmin from the project page component.
> Fix bad rebase

- app/pages/project/project-page.cjsx
> Actually fix isAdmin in project-page.cjsx

- app/classifier/feedback/feedback-summary-container.jsx
- app/pages/project/index.cjsx
Fixes https://zooniverse.slack.com/archives/C06LHUC6R/p1510693405000364
> Fix redux-connecting components which use context

- app/classifier/tasks/drawing/grid-buttons.cjsx
- app/classifier/tasks/dropdown/index.cjsx
- app/collections/collection-search.cjsx
- app/components/tag-search.cjsx
- app/components/user-search.cjsx
- app/pages/lab/project-details.cjsx
- package-lock.json
- package.json
Bumps `react-select` from rc.5 to rc.10, which adds [a bunch of bug fixes](/JedWatson/react-select/blob/master/HISTORY.md).
> Update react-select to 1.0.0-rc.10

- app/locales/nl.js
- app/pages/project/index.cjsx
For obvious reasons I left the legalese in English, although that might not be legally binding.
> Add dutch locale

- .github/PULL_REQUEST_TEMPLATE.md
Following recent critical bugs making it into production, I've added a checklist of tests for core functionality which we should go through before merging anything. I've also moved the note about the staging branch to the top of the template to make it impossible to miss.
> Add manual testing checklist to PR template

- app/pages/project/home/index.jsx
- app/pages/project/home/project-home.jsx
- app/pages/project/project-page.cjsx
- css/project-page.styl
Staging branch URL: https://fix-4099.pfe-preview.zooniverse.org/projects/brooke/i-fancy-cats
Fixes #4099.
Applies the project background image to the top section of the home page.
> Adds a new layout for home page

- app/pages/settings/email.jsx
- app/pages/settings/email.spec.js
Updates the project listing tests for #4182
> Update project email settings tests

- app/pages/settings/email.spec.js
Add some tests for the pagination in #4182
> Add some tests for project list pagination.

- app/pages/project/index.cjsx
- app/pages/project/index.spec.js
- app/pages/settings/email.jsx
Staging branch URL: https://catch-errors.pfe-preview.zooniverse.org/
Fixes some of the unhandled Promise rejection errors raised by the tests, replacing them with console warnings instead.
> Catch uncaught errors

- app/lib/confirm.jsx
- app/partials/project-modal-editor.cjsx
Staging branch URL: https://tutorial-delete-modal-confirm.pfe-preview.zooniverse.org/
Fixes #4117.
- Note: I suspect there may be other places on the project builder where delete actions do not have a modal confirm implemented. Should we close this issue when this PR is merged, and reopen when/if another is found?
- Adds a modal confirm for the tutorial delete button in the project builder.
- Note: modal confirm does not display for deleting individual steps of the tutorial. Happy to implement this if desired, but didn't want to assume anything so left the step deletion process as is.
> Add tutorial delete modal confirm.

- app/pages/lab/collaborators.cjsx
add in a line about testers having access to inactive workflows.
Fixes # .
> update tester discription

- app/pages/project/project-page.jsx
- app/pages/project/project-page.spec.js
Fixes broken component import.
Fixes broken default props.
Add some tests for the project disclaimer.
> Add project page tests for the project disclaimer

- app/pages/project/project-page.jsx
Staging branch URL: https://fix-project-nav.pfe-preview.zooniverse.org
Fixes: `props.user` is null in the project navigation, even when logged in.
> Pass user to the project navbar

- app/pages/dev-classifier/index.cjsx
https://fix-dev-classifier.pfe-preview.zooniverse.org/dev/classifier
Fixes the dev classifier after the classifier was connected to the Redux store.
> Fix Classifier in dev classifier

- app/locales/en.js
- app/pages/get-involved/call-for-projects.jsx
- app/pages/get-involved/call-for-projects.spec.js
- Staging branch URL: https://audio-cfp-text-update.pfe-preview.zooniverse.org/get-involved/call-for-projects
- Updates text in `get-involved/call-for-projects` to include both Audio Transcription Project Proposals and Biomedical Project Proposals.
- Updates tests for correct number of Markdown elements.
- Resolves #4242.
Tagging @hrspiers in case you'd like to look over the changes.
> Audio CFP text update

- app/pages/lab/subject-set.cjsx
Staging branch URL: NA
Fixes #4217
adding links for CLI and python utility
> adding links for CLI and python utility

- README.md
Updates README to link to BrowserStack.
> Add note acknowledging BrowserStack

- app/classifier/classifier.jsx
Staging branch URL: https://remove-feedback-hack.pfe-preview.zooniverse.org/
- Fix a bug in `updateAnnotations` by properly copying the annotations array to component state.
- Remove the taskID hack (see #4202) from `componentDidUpdate` and use state changes to detect when the task changes instead.
- Remove _.last() in favour of using `currentAnnotation` for consistency. We shouldn't be using a library for something as simple as getting the last member of an array.
- Fixes #4243 by setting a default for `currentAnnotation` in `updateFeedback`.
I've tested a couple of tasks in the dev classifier, and annotations seem to be working as expected, but this really does need an extra pair of eyes to check that I haven't broken classification annotations.
> Remove feedback hack from classifier

- app/pages/project/workflow-selection.jsx
Staging branch URL: https://fix-4297.pfe-preview.zooniverse.org?env=production
Fixes #4297.
Fetch the correct workflow when project changes
> Fetch workflow when project changes

- app/main.cjsx
- app/pages/organization/organization-container.jsx
- app/pages/organization/organization-page.jsx
- css/organization-page.styl
No rush, not sure needs 2 reviewers (though of course welcome), if first to review is content.
Staging branch URL: https://org-landing-ux-edits.pfe-preview.zooniverse.org/
- demo org with these PR changes: https://org-landing-ux-edits.pfe-preview.zooniverse.org/organizations/markb-panoptes/nfnorgtest
**Changes**:
- Edits organization landing category buttons to radio inputs so user can arrow between, cycle through, as requested by @eatyourgreens.
- Edits scroll behavior so there's no scroll on category change
**Question**
~~Might not be implementing radio buttons correctly, but if so not sure radio buttons preferable to current UX where can tab through categories? The radio inputs work as desired in Chrome, but not in Firefox or Safari, whereas the tabing works in Chrome and Firefox, but …
> Edit org landing category buttons, scroll behavior

- app/pages/organization/organization-page.jsx
- app/pages/organization/organization-page.spec.js
- css/organization-page.styl
Staging branch URLs
- org with announcement: https://org-announcement.pfe-preview.zooniverse.org/organizations/markb-panoptes/mborgtest
- org without announcement: https://org-announcement.pfe-preview.zooniverse.org/organizations/markb-panoptes/nfnorgtest
**Description**
- adds announcement component to organization landing
- adds Helmet
> Add announcement to organization landing

- package-lock.json
- package.json
> Upgrade marked to 0.3.9

- app/components/subject-viewer.cjsx
Staging branch URL: https://fix-subject-pips.pfe-preview.zooniverse.org/projects/zooniverse/gravity-spy?env=production
Fixes the frame buttons for the subject viewer on the classifier according to the reports in this Talk thread: https://www.zooniverse.org/projects/zooniverse/gravity-spy/talk/730/529003?comment=895949&page=2
And this thread: https://www.zooniverse.org/talk/17/535259?comment=895269
This fixes the key used for the mapped subject frames to use an actual unique key, from the array index to the subject location url. I haven't tested any other projects besides the two that reported the issue. I'm not sure why this started to be a noticeable issue, however, the subject viewer is still using array indexes in several places that need to be fixed.
> Fix subject pips

- app/pages/lab/visibility.cjsx
Staging branch URL: https://lab-workflows-link.pfe-preview.zooniverse.org/
Add a link to the new workflows settings location in the Lab.
> Add link to new workflows settings location.

- app/pages/organization/organization-container.jsx
Staging branch URL: https://update-org-proj-query.pfe-preview.zooniverse.org/
- adds sort by launch date
for volunteer (not collaborator):
- adds "live" state to query (to prevent projects in development, paused or finished from showing)
- adds `private: false` (aka public project) so if collaborator is in "View as Volunteer" state it only shows projects a volunteer would see, and excludes any linked private projects the collaborator is also a collaborator on
> update org project query

- app/talk/lib/create-board-form.cjsx
Corrected wording from 'lower' to 'higher'
> Corrected wording on board permissions

- app/pages/home-for-user/index.jsx
Staging branch URL: https://fix-stats-link.pfe-preview.zooniverse.org/
Fixes scroll into view behavior on componentDidMount. 'My stats' links directly to the signed in home page `#projects` section.
> Scroll to anchor tag on mount if in URL

- app/pages/project/components/ProjectNavbar/ProjectNavbar.jsx
- app/pages/project/components/ProjectNavbar/ProjectNavbar.spec.js
- app/pages/project/components/ProjectNavbar/components/ProjectNavbarNarrow/ProjectNavbarNarrow.jsx
- app/pages/project/components/ProjectNavbar/components/ProjectNavbarNarrow/ProjectNavbarNarrow.spec.js
- app/pages/project/components/ProjectNavbar/components/ProjectTitle/ProjectTitle.jsx
- app/pages/project/components/ProjectNavbar/components/Wrapper/Wrapper.jsx
Closes #4381. Related to #4371. This removes the max-width: 1200px. This still doesn't stop some projects collapsing into the mobile dropdown because they still have lots of links. We'll explore more design options in a follow up with these cases.
https://project-nav-sizing-updates.pfe-preview.zooniverse.org/projects/meredithspalmer/snapshot-gondwana?env=production
https://project-nav-sizing-updates.pfe-preview.zooniverse.org/projects/zooniverse/snapshot-serengeti?env=production
https://project-nav-sizing-updates.pfe-preview.zooniverse.org/projects/mschwamb/planet-four-ridges?env=production
> Project nav sizing updates

- app/pages/home-common/featured-project.jsx
> Fix SCOTUS

- app/locales/en.js
Edited text from 'Noone' to 'No one'
> Minor edit

- app/lib/classification-queue.js
- app/lib/classification-queue.spec.js
- app/pages/project/classify.cjsx
- test/fake-api-client.js
- test/fake-local-storage.js
Extracts a ClassificationQueue, making the classify page a little lighter on the logic. Also means that this process is now more easily tested.
Staging branch URL: https://classification-queue.pfe-preview.zooniverse.org
Fixes # .
> Classification queue

- app/pages/organization/organization-container.jsx
- app/pages/organization/organization-container.spec.js
- app/pages/organization/organization-page.jsx
Staging branch URL: https://all-org-roles.pfe-preview.zooniverse.org/
- demo project: https://all-org-roles.pfe-preview.zooniverse.org/organizations/markb-panoptes/nfnorgtest
To test I edited the org roles request (new line 173) to include `page_size: 2`. Unsure of how to write related actual tests.
Added code to paginate through org role responses to ensure all roles are collected for checking if user is an org collaborator.
> Edit org roles request to paginate through all roles

- app/lib/publications.js
Also, fix Whales FM link.
Staging branch URL: https://update-publications.pfe-preview.zooniverse.org/?env=production
> Add Bat Detective to the list of publications.

- app/lib/publications.js
Hi,
I've updated the publications page.
> updates to publication page

- app/pages/lab/actions/media.js
https://warn-large-media.pfe-preview.zooniverse.org
Fixes #4458.
Check file size on media upload and warn if it's greater than 500k.
Store the file size with the linked media resource.
> Warn against large media uploads

- app/components/thumbnail.jsx
- app/pages/lab/actions/media.js
- app/pages/lab/media-area/media-area-view.jsx
- app/pages/lab/media-area/media-icon.jsx
- app/pages/lab/media.jsx
- package-lock.json
- package.json
Staging branch URL: https://audio-video-media.pfe-preview.zooniverse.org/
Fixes #4420.
~Waiting on https://github.com/zooniverse/markdownz/pull/66 to merge.~
Allow audio and video file uploads to the project media area, and preview the files using `<audio>` or `<video>` tags.
> Add audio and video support to the project media area

- app/classifier/classifier.jsx
- app/classifier/task-nav.jsx
https://update-annotations.pfe-preview.zooniverse.org
Get the current task, and corresponding annotation, from classifier state.
Add handlers for task navigation changes, so that feedback can hook into the Next and Done buttons.
Continuation of #4440, slowly getting rid of all code which would block us from deprecating combo task annotations.
~@rogerhutchings this PR can also add hooks to fire off feedback checks when navigating backward and forward through a workflow, rather than checking for prop changes and assuming that those correspond to navigation buttons being pressed.~
> Store workflow task history in Classifier state.

- css/talk.styl
Staging branch URL: https://show-subject-notes.pfe-preview.zooniverse.org
Fixes a bug where deleting the first comment in a Notes discussion hides the linked subject, even though it's still present in the HTML. See https://www.zooniverse.org/projects/amyrobey996/numbat-discovery/talk/1571/579469
compared with
https://show-subject-notes.pfe-preview.zooniverse.org/projects/amyrobey996/numbat-discovery/talk/1571/579469?env=production
Removes `display:none` from the subject viewer in deleted Talk comments.
Moves `opacity: 0.5` down to the markdown content of the deleted comment.
> Always show linked subjects in deleted Talk comments

- app/components/subject-viewer.cjsx
Fixes incompatibility with internet explorer.
> Remove object.values from subject-viewer

- app/pages/admin/featured-project-toggle.jsx
- app/pages/admin/featured-project-toggle.spec.js
- app/pages/admin/project-status.jsx
- app/pages/admin/project-status.spec.js
- app/pages/home-for-user/index.jsx
Staging branch URL: https://fix-4466.pfe-preview.zooniverse.org/
Fixes #4466 .
Wait for new state to update before setting the new feat project.
> Wait for promises to resolve before setting new featured project.

- app/classifier/task-nav.jsx
Staging branch URL: https://fix-4502-mb-wip.pfe-preview.zooniverse.org/projects/markb-panoptes/focus-testing-project/classify?workflow=3182
Fixes #4502 ?
Related #4503
> edit task-nav actions for shortcut annotation

- Dockerfile
- Dockerfile.deps
They rarely change and there's no point in every deploying waiting on
them.
Fixes # .
> Split dependencies into separate docker build

- app/locales/en.js
> Adding Resources page

- app/classifier/experimental-voice-command-listener.jsx
I can't commit to the main repo, but here's the cached code.
> Add cached string to voice over

- app/locales/en.js
- app/pages/about/index.jsx
- app/pages/about/index.spec.js
- app/pages/about/resources-page.jsx
- app/pages/about/resources-page.spec.js
- app/router.cjsx
Staging branch URL: https://resources-page.pfe-preview.zooniverse.org/about/resources
This adds the resources page! @beckyrother @snblickhan and @hrspiers
> Resources page

- app/pages/lab/field-guide/article-list-item.cjsx
Staging branch URL: https://thumbnail-images.pfe-preview.zooniverse.org
> Fix CroppedImage require in ArticleListItem

- app/classifier/tasks/survey/editor.cjsx
- app/lib/get-all-linked.js
- app/lib/get-workflows-in-order.js
- app/pages/lab/collaborators.cjsx
- app/pages/lab/field-guide/index.cjsx
- app/pages/lab/project-details.cjsx
- app/pages/project/index.cjsx
Staging branch URL: https://getalllinked.pfe-preview.zooniverse.org/
Towards #4376 (3/4)
Closes #4377 
This PR is ~for conversational purposes~ ready for review.
Abstracts the concept behind `getWorkflowsInOrder` refactor to cycle through API requests until no `next_page` in response meta.
Fully acknowledge abstraction is not always the right solution and we should avoid requesting all linked resources in favor of pagination UI.
However, there might be a few unique situations we do want to get all linked resources, and a `getAllLinked` helper could help standardize those API requests and specifically let the `page_size` quantity be set by the back-end.
> Create getAllLinked helper

- app/pages/organization/organization-page.jsx
- css/organization-page.styl
Staging branch URLs: 
with avatar - https://org-avatar-fix.pfe-preview.zooniverse.org/organizations/markb-panoptes/nfnorgtest
without avatar - https://org-avatar-fix.pfe-preview.zooniverse.org/organizations/markb-panoptes/noavnoback
Fixes - https://www.zooniverse.org/organizations/meredithspalmer/snapshot-safari.
Staged - https://org-avatar-fix.pfe-preview.zooniverse.org/organizations/meredithspalmer/snapshot-safari?env=production.
- adds `alt` text
- consolidates to one class for org avatar
- adds ZooniverseLogo as placeholder 
- refactors styling, improves mobile styling
> Org avatar fix

- app/classifier/components/TaskNavButtons/TaskNavButtons.jsx
- app/classifier/components/TaskNavButtons/components/BackButton/BackButton.jsx
- app/classifier/components/TaskNavButtons/components/BackButton/BackButton.spec.js
- app/classifier/components/TaskNavButtons/components/TalkLink/TalkLink.jsx
- app/classifier/task-nav.jsx
- app/classifier/tasks/components/TaskHelpButton/TaskHelpButton.jsx
- css/classify.styl
Staging branch URL: https://back-button-fixes.pfe-preview.zooniverse.org/
Fixes a few of the issues listed in #4570:
- if no task help, Back and Next/Done very close to task
- Reworked bottom margins between components
- The Back button isn't disabled on the first task of a workflow, even though it can't be used. It also responds to hover on the first task, and displays the warning message.
- Back button is now hidden on first task
- Line heights don't match for the task navigation buttons. (Done & Talk)
- Added explicit line height
- "Going back..." warning remains even if not hover on Back button, disappears on hover 
- Now using separate explicit handlers for mouseenter and focus vs mouseleave and blur.
> Back button fixes

- app/classifier/tasks/drawing/markings-renderer.cjsx
Staging branch URL: https://delete-out-of-bounds.pfe-preview.zooniverse.org
Fixes #4579 .
Check deleteIfOutOfBounds on every drawing tool update and delete the current tool if outside the subject.
> Add deleteIfOutOfBounds to drawing tool root

- app/classifier/components/TaskTabs/TaskTabs.jsx
- app/classifier/components/TaskTabs/TaskTabs.spec.js
- app/classifier/components/TaskTabs/components/QuestionTab/index.js
- app/classifier/components/TaskTabs/components/TaskTab/TaskTab.jsx
- app/classifier/components/TaskTabs/components/TaskTab/TaskTab.spec.js
- app/classifier/components/TaskTabs/components/TaskTab/index.js
- app/classifier/components/TaskTabs/components/TutorialTab/TutorialTab.jsx
- app/classifier/components/TaskTabs/components/TutorialTab/TutorialTab.spec.js
- app/locales/en.js
- app/locales/es.js
- app/locales/it.js
- app/locales/nl.js
- app/theme/colors.js
Staging branch URL: https://task-tabs-updates.pfe-preview.zooniverse.org/
Fixes #4586, #4589, and makes the tutorial button disabled instead of hidden if there isn't a tutorial (as noted in #4570).
How it looks on Planet Four: Terrains: https://task-tabs-updates.pfe-preview.zooniverse.org/projects/mschwamb/planet-four-terrains/classify?env=production
> Task tabs updates

- app/talk/comment.cjsx
Staging branch URLs: 
- https://talk-profile-link-fix.pfe-preview.zooniverse.org/talk/14/611412?env=production
- https://talk-profile-link-fix.pfe-preview.zooniverse.org/projects/zooniverse/notes-from-nature/talk/438/623200?env=production
- https://talk-profile-link-fix.pfe-preview.zooniverse.org/projects/markb-panoptes/focus-testing-project/talk/145/199
- https://talk-profile-link-fix.pfe-preview.zooniverse.org/projects/rafe-dot-lafrance/notes-from-nature-on-staging/talk/150/236
Fixes https://www.zooniverse.org/talk/17/624311.
I should have caught in #4566.
> Edit talk profile_link set

- app/pages/project/workflow-selection.spec.js
Check that general logged-in users only request active workflows.
> Update workflow selection tests when logged-in

- app/pages/project/workflow-selection.jsx
Staging branch URL: https://fix-workflow-infinite-loop.pfe-preview.zooniverse.org/
This is an alternative fix to #4628. 
I've added `parseInt()` to the workflow id variables in the class method for `clearInactiveWorkflow`. I also did a tiny refactor to request the correct workflow id endpoint for the known workflow rather than the search query param.
I think there's a few refactors that could be considered, but to keep this in scope of just a bug fix, let's do those refactors in follow up PRs. 
Here's how to test this:
https://fix-workflow-infinite-loop.pfe-preview.zooniverse.org/projects/tkotwim/the-american-soldier/classify?env=production
In the JS console, update your own project preferences to store an inactive workflow (6627 is inactive for project 5551):
```
const upp = …
```
> Fix workflow infinite loop

- css/field-guide.styl
Staging branch URL: https://fix-4592.pfe-preview.zooniverse.org/
Fixes #4592. Updates styles for the field guide button.
> Improved field guide button styles

- app/lib/publications.js
Updating publications page to include SGL publication
> Updating publications page

- app/lib/publications.js
Addition of a second SGL publication
> Second SGL publication added

- app/pages/project/workflow-selection.jsx
- app/pages/project/workflow-selection.spec.js
Staging branch URL: https://workflow-selection.pfe-preview.zooniverse.org
> Rewrite workflow selection

- app/locales/it.js
Fixes # .ITA translation
Made fixes on italian translation and complete it.
- [x ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [x ] Does it work on mobile?
> ITA: translation fix

- app/lib/ga-log-adapter.js
- app/lib/ga-log-adapter.spec.js
- app/lib/zooniverse-logging.js
- app/lib/zooniverse-logging.spec.js
- app/partials/app.cjsx
- package.json
Staging branch URL: https://google-analytics.pfe-preview.zooniverse.org/
Makes the Google Analytics log adapter for zooniverse logging more resilient (because Google Analytics is kind of temperamental when deployed via google tag manager). Added tests for GALogAdapter and ZooniverseLogging.
> Google analytics

- app/lib/geordi-log-adapter.js
Staging branch URL:  https://fix-zoo-talk.pfe-preview.zooniverse.org/
- https://fix-zoo-talk.pfe-preview.zooniverse.org/talk/17/651006?env=production
- https://fix-zoo-talk.pfe-preview.zooniverse.org/projects/mschwamb/comet-hunters/talk/213/433579?env=production
- (not broken, but confirming still works) https://fix-zoo-talk.pfe-preview.zooniverse.org/projects/tkotwim/the-american-soldier/talk/1668/631769?env=production
Fixes broken zooTalk, Comet Hunters, Gravity Spy and Snapshot Wisconsin.
Geordi logger expects logEvent.data to be an object, if receives logEvent.data as anything other than an object, converts logEvent.data to object with type as key and data as value.
> Convert Geordi logEntry data to object if not object

- app/lib/zooniverse-logging.js
Staging branch URL: https://ga-blacklist.pfe-preview.zooniverse.org
> change google analytics logging from whitelist to blacklist

- app/classifier/components/TaskNavButtons/components/NextButton/NextButton.jsx
- app/classifier/drawing-tools/components/DetailsSubTaskForm/DetailsSubTaskForm.jsx
- app/classifier/drawing-tools/components/DetailsSubTaskForm/DetailsSubTaskForm.spec.js
- app/classifier/tasks/slider/index.jsx
- app/locales/en.js
- app/locales/es.js
- app/locales/it.js
- app/locales/nl.js
- css/classify.styl
- css/slider-task.styl
- test/setup.js
Staging branch URL: https://drawing-subtask-theming.pfe-preview.zooniverse.org/
Dev classifier using the circle drawing tool: https://drawing-subtask-theming.pfe-preview.zooniverse.org/dev/classifier
Whales as Individuals uses a drawing subtask: https://drawing-subtask-theming.pfe-preview.zooniverse.org/projects/tedcheese/whales-as-individuals/classify?env=production
@beckyrother is the styling ok?
Fixes #4544.
I found writing tests to be a bit tricky because of the modal-form dependency, so I only added a basic scaffold for just checking it renders without crashing. I'll follow up with fixing the keyboard focus bug separately.
> Drawing subtask theming

- .eslintrc
Add babel-eslint so that ESlint can parse static class properties.
> Add babel to ESlint

- package-lock.json
- package.json
Staging branch URL: https://geordi-client.pfe-preview.zooniverse.org/
> Uninstall zooniverse-geordi-client

- app/classifier/drawing-tools/anchored-ellipse.jsx
- app/classifier/drawing-tools/index.coffee
- app/classifier/tasks/drawing/icons.cjsx
- app/classifier/tasks/drawing/marking-initializer.cjsx
- app/classifier/tasks/generic-editor.cjsx
- app/pages/admin/project-status/experimental-features.jsx
- app/pages/dev-classifier/mock-data.coffee
Staging branch URL: https://add-anchored-ellipse-tool.pfe-preview.zooniverse.org/
Supersedes #4681. This adds a new type of ellipse tool that is centered in the subject and can't be moved. 
It's the second step on my test project: https://add-anchored-ellipse-tool.pfe-preview.zooniverse.org/projects/srallen086/srallen-testing/classify
- I have two kinds of subjects, one envelope and one letter, so you can see it centers in various kinds of subjects.
Also testable in the dev classifier: https://add-anchored-ellipse-tool.pfe-preview.zooniverse.org/dev/classifier
@tlalka I've enabled the tool on production using this staged branch for Spiral Graph (using `?env=production` query param in the URL): https://add-anchored-ellipse-tool.pfe-preview.zooniverse.org/?env=production
I've converted it …
> Add anchored ellipse tool

- README.md
Fixes the heading on the 'Developing with Docker' section.
> Fix a heading in the readme

- package.json
Staging branch URL: https://check-engines.pfe-preview.zooniverse.org/
> Accept npm 5 for builds

- app/lib/publications.js
Staging branch URL: https://add-pub-cox-et-al.pfe-preview.zooniverse.org/
> Add Cox et al 2017

- app/lib/notifications-counter.js
Staging branch URL: https://notifications.pfe-preview.zooniverse.org
Fixes #4727 .
Refactor the `NotificationsCounter` to make the chained calls on update easier to follow. Add explicit return values that are passed down the chain.
Ignore the section parameter for API calls if it's undefined or null.
Lint the `NotificationsCounter` code.
> Refactor NotificationsCounter

- app/locales/de.js
- app/locales/fr.js
Adds a couple of new locale files.
> Add French and German locales

- app/classifier/classification-summary.jsx
Staging branch URL: https://fix-custom-summary.pfe-preview.zooniverse.org/
Fixes issue found while testing #4746.
Import the `Markdown` component in the `ClassificationSummary`. Can be tested with the Where are my Body Organs? project:
https://fix-custom-summary.pfe-preview.zooniverse.org/projects/h-spiers/where-are-my-body-organs/classify?env=production
I suggest turning on demo mode so you can quickly click through the workflow to get to the summary. It currently crashes the site.
> Import Markdown component for ClassificationSummary

- app/classifier/task.jsx
Force the classifier task component to mount again whenever the task changes.
See https://reactjs.org/blog/2018/06/07/you-probably-dont-need-derived-state.html#recommendation-fully-uncontrolled-component-with-a-key
Staging branch URL: https://tasks.pfe-preview.zooniverse.org
> Add a key to task components

- app/classifier/tasks/drawing-task-details-editor.cjsx
Staging branch URL: https://drawing-subtask.pfe-preview.zooniverse.org
Fixes #4760
> Fix broken require for text subtasks

- app/classifier/tasks/multiple/index.jsx
- app/classifier/tasks/multiple/index.spec.js
- app/classifier/tasks/testHelpers/mockObjects.js
Staging branch URL: https://multiple-choice-task.pfe-preview.zooniverse.org/
Fixes #4767.
Set a minimum number of required multiple choice answers. 1 if `task.required` is true, 0 otherwise.
Update the mock data to match tasks that are produced by the project builder.
Update the multiple choice tests.
> Fix required multiple choice tasks

- app/classifier/classifier.jsx
- app/classifier/classifier.spec.js
- app/classifier/components/Intervention/Intervention.jsx
- app/classifier/components/Intervention/index.js
- app/classifier/index.cjsx
- app/main.cjsx
- app/pages/project/classify.jsx
- app/pages/project/index.jsx
- app/pages/project/index.spec.js
- app/pages/project/project-page.jsx
- app/pages/project/project-page.spec.js
- app/redux/ducks/interventions.js
- app/redux/reducers.js
Staging branch URL: https://interventions.pfe-preview.zooniverse.org
First steps towards adding interventions/notifications to PFE projects.
- Add a redux store, and a few actions, for the Sugar client.
- Moves Sugar project channel subscriptions, and tests, over to Redux.
- Adds a simple notifications listener, which simply stores an array of received notifications.
- Adds a very simple Intervention component, which simply renders the latest Sugar message during the classification summary step. If summaries are hidden, it interrupts the 'Done' and 'Done & Talk' buttons in order to show a message.
TODO, either in this PR or later.
> Add simple interventions to the classifier

- package-lock.json
- package.json
`react-rendered-size` appears to be unused, this PR removes it.
> Remove react-rendered-size

- app/partials/project-modal-editor.cjsx
Set a soft limit to file size of 1000kB.
Prompt to confirm any upload larger than that size.
I forgot to include this in #4802, so you can currently upload tutorial videos of any size. Want your volunteers to watch an entire movie? No problem!
Staging branch URL: https://tutorial-videos.pfe-preview.zooniverse.org/
> Add a size limit to tutorial videos

- app/redux/ducks/classify.js
- app/redux/ducks/interventions.js
Staging branch URL: https://subject-queue-intervention.pfe-preview.zooniverse.org/
Updates the sugar notifications listener to look for experiments messages of the following type:
```javascript
{"experiments": 
[{
"user_id": "1", 
"message": {
"type": "subject_queue", 
"subject_ids": [1,2],
"workflow_id": "1234"
}, 
"url": "test", 
"delivered": "false"
}]
}
```
The subjects are requested from the API, then added to the upcoming subject queue if the workflow ID matches the current workflow.
TODO: 
~~Requires #4781 and #4790.~~
> Add subject queue interventions

- app/classifier/drawing-tools/components/Fan/fan.jsx
- app/classifier/drawing-tools/components/Fan/fan.spec.jsx
- app/classifier/drawing-tools/components/Fan/index.js
- app/classifier/drawing-tools/index.coffee
- app/classifier/tasks/drawing/icons.cjsx
- app/classifier/tasks/generic-editor.cjsx
- app/pages/admin/project-status/experimental-features.jsx
- app/pages/dev-classifier/mock-data.coffee
Add the 'ice cream cone' drawing tool from Planet Four. Tool annotation params will be radius, rotation angle and spread angle.
ToDo:
Staging branch URL: https://fan-tool.pfe-preview.zooniverse.org/dev/classifier
(Choose 'Draw stuff', 'Next' then 'Fan tool' at the bottom of the list.
Fixes #4329.
> Planet Four fan tool

- app/redux/ducks/classify.spec.js
Adds tests for the Redux reducers that update the subject queue, classification and workflow.
> Test the classifier reducers

- app/lib/sanitize-array-input.coffee
- app/lib/sanitize-array-input.js
- app/pages/lab/project-details.cjsx
Staging branch URL: https://fix_4801.pfe-preview.zooniverse.org/
Fixes #4801 Fixes #4907
Just moved this to be an inline function, so the tag array doesn't get converted to a string. @srallen is this the type of thing you had in mind as a solution?
> Fix handleTagChange

- package.json
> Add nyc to the test-travis script

- app/classifier/drawing-tools/components/Fan/fan.jsx
Move the delete button from the end of the fan to just outside the curved top of the shape. 
Staging branch URL: https://fan-tool.pfe-preview.zooniverse.org/
Fixes #4912.
> Move the fan tool delete button

- app/features/feedback/shared/components/checkbox-input.jsx
- app/features/feedback/shared/components/select-input.jsx
- app/features/feedback/shared/components/text-input.jsx
- package-lock.json
- package.json
Remove redundant `for` attributes from form labels, then uninstall `uuid`.
Staging branch URL: https://remove-uuid.pfe-preview.zooniverse.org
Supersedes #4922.
> Remove UUID

- package-lock.json
- package.json
Bump chai to 4.2.0.
Bump request to 2.88.0.
Remove webpack-dev-middleware.
> Update outdated dev dependencies

- app/pages/dev-classifier/ClassificationViewer.jsx
- app/pages/dev-classifier/index.jsx
- app/redux/ducks/classify.js
- app/redux/ducks/classify.spec.js
- webpack.dev.js
Staging branch URL: https://dev-classifier.pfe-preview.zooniverse.org
- Connects the dev classifier up to the Redux store, so that it uses the stored classification, workflow and subject queue.
- Creates a new classification and queue when the component mounts and also whenever the classification is reset to null (login/logout resets the subject queue and classification.)
- Fixes the Next button so that it reloads the mock subject with a new classification.
- Adds a simple error handler that catches any errors and prints the component stack to the page when the classifier component crashes.
- Also fixes the RESUME_CLASSIFICATION action so that it uses the passed classification, rather than assuming that the correct classification is already stored in state.
- Updates the Webpack source …
> Connect the dev classifier to the classify store

- Jenkinsfile
Linked to #5004 - this will actually run on jenkins as PR's from forked repos don't for security reasons.
~I'll either close this once tested or switch to this one.~
Ensure master branch autodeploys via npm run deploy and branches deploy via npm run stage-with-jenkins
Staged at: https://add-production-deploy-via-jenkinsfile.pfe-preview.zooniverse.org/
> Add production deploy via jenkinsfile - test jenkins

- README.md
let folks know how the deployment system works with jenkins and update some heading formatting
> add link to deployment docs

- app/lib/publications.js
More publications have been added.
> More publications

- app/components/user-search-admin.cjsx
- app/pages/admin/user-settings-list.jsx
add user-search-admin component with some slightly different filtering / lookup behaviour vs the normal user-search component
I had to relax the option filtering to handle the value being an email address vs the option label, https://github.com/JedWatson/react-select/tree/v1.0.0-rc.10#advanced-filters
I'm not super happy with this implementation but i've sunk a few hours into it already. Ideally i'd have some shared behaviour that i can override in each component (user-search vs user-search-admin) but i haven't got a decent idea to do that. thoughts / directions / suggestions appreciated. 
Fixes the ability to find users by their emails for admin users - quite a common issue when dealing with unsubscription requests.
> allow admins to find users by email address

- app/classifier/drawing-tools/components/Fan/fan.spec.jsx
- app/classifier/drawing-tools/generic-tests.spec.js
This PR adds a loop through all drawing tools to test basic functionality of the drawing tool API. As all drawing tools perform differently, the checks made here are all very general.
This is a basic first stab, and I'm open to any suggestions to improve these tests.
> Test Drawing Tool API

- app/features/feedback/shared/strategies/dud/README.md
- app/features/feedback/shared/strategies/radial/README.md
- app/features/feedback/shared/strategies/single-answer-question/README.md
Adds a note on the feedback docs on how to name the manifest header cells.
> Add note on metadata field naming format

- app/classifier/tasks/index.spec.js
Updates the generic task tests to use Chai.
Drops the mock workflow in favour of looping through all registered task components and testing the default values for each one.
> Update generic task tests

- app/talk/board.cjsx
- app/talk/lib/paginator.cjsx
Move componentWillMount to componentDidMount.
Remove componentWillReceiveProps in favour of componentDidUpdate.
Set discussions state when discussions are received from the API.
Request user, role and subject info in componentDidUpdate, if discussions state changed.
Break up setState calls to isolate discussions from discussions metadata.
Limit the pagination page selector to show only 10 pages.
Staging branch URL: https://pr-5079.pfe-preview.zooniverse.org/projects/panthera-research/camera-catalogue/talk/591?env=production
That page takes ~35s to render on master because the page selector has 8217 options.
> refactor Talk board API requests, fix slow pagination rendering

- css/typography.styl
Staging branch URL: 
- (metadata info) https://metadata-link-styling.pfe-preview.zooniverse.org/projects/marckuchner/backyard-worlds-planet-9/talk/subjects/13772456?env=production
- (last page of tutorial) https://metadata-link-styling.pfe-preview.zooniverse.org/projects/zooniverse/notes-from-nature/classify?reload=1&workflow=6014&env=production
Fixes #4691, #5095 
Adds `word-break: break-word` and `overflow-wrap: break-word` styling to anchors.
Would a new/specific class for the above linked instances be preferred? 
The anchors are nested with `markdownz`.
I navigated around the site and anchors appear to look normal otherwise, but certainly could be missing something.
> Add break-word styling to anchor

- app/components/ExternalLinksBlock/components/ExternalLink/ExternalLink.jsx
- app/components/ExternalLinksBlock/components/ExternalLink/ExternalLink.spec.jsx
- app/lib/nav-helpers/socialIcons.json
- app/pages/lab/social-links-editor.jsx
This are the changes requested from #5148
> Project external links changes

- app/components/ExternalLinksBlock/components/ExternalLink/ExternalLink.jsx
- app/components/ExternalLinksBlock/components/ExternalLink/ExternalLink.spec.jsx
- app/lib/nav-helpers/socialIcons.json
- app/pages/lab/social-links-editor.jsx
Social media URLs could link to any site, so construct the link destination from our list of social media sites and the supplied username.
Staging branch URL: https://pr-5148.pfe-preview.zooniverse.org
> Don't trust social URLs

- app/pages/project/components/ProjectNavbar/components/NavLink/NavLink.jsx
External link markup changed, so this updates the nav CSS to match the new markup.
Staging branch URL: https://pr-5160.pfe-preview.zooniverse.org
Fixes #5147.
> Fix external links in project navigation

- app/classifier/tasks/drawing/hide-previous-marks-toggle.jsx
- app/pages/project/classify.jsx
- app/pages/project/home/home-workflow-button.jsx
- app/pages/project/home/home-workflow-button.spec.js
- app/pages/project/workflow-selection.jsx
- app/pages/project/workflow-selection.spec.js
- app/redux/ducks/classify.js
Remove the API client from workflow selection. Instead, use the loadWorkflows redux action once a workflow ID has been selected.
Remove user preference code from workflow selection, since the loadWorkflows action also updates preferences with the selected workflow, if successful.
Update the home workflow buttons to check the stored workflow and only load the classifier if the stored workflow matches the workflow for that button.
Check workflow assignment prompt state on the classify page before checking whether to show a new prompt.
Validate the stored workflow against the project before rendering the classifier.
Staging branch URL: https://pr-5198.pfe-preview.zooniverse.org
Fixes #5188.
> Workflow selection updates and bug fixes

- app/pages/about/team-members.js
> Update my Twitter username

- app/pages/project/index.jsx
Catch project errors, which would otherwise crash the React app. Display the error message and stack trace (if available.) It's ugly, but better than a blank page.
Staging branch URL: https://pr-5235.pfe-preview.zooniverse.org
> Add an error boundary to the project container

- README.md
Make the Docker instructions more prominent.
Add Node/npm versions.
Tidy up the text layout.
Add notes about Jenkins builds, eslint and code styles.
> Update Readme: how to get started

- css/secondary-page.styl
Fixes #5271 .
Just copies the style updates for the sub nav bar to make sure they get applied to the project context scope too for the user profile.
> Make sure styles are applied to project context user profile

- app/classifier/components/Intervention/Intervention.jsx
- app/classifier/components/Intervention/Intervention.spec.js
Switch to using markdown rendering component for message interventions
> use markdown for intervention messages

- app/classifier/tasks/crop/initializer.cjsx
Staging branch URL: https://pr-5283.pfe-preview.zooniverse.org
Fixes #5282.
> Fix broken require in the crop task

- app/constants/languageMenu.js
> Add Arabic to language menu

- app/lib/publications.js
Staging branch URL: https://pr-5289.pfe-preview.zooniverse.org
Fixes # .
Adding new papers to Exoplanet Explorers and Planet Hunters. Needed ahead of talk this evening.
> Add new exoplanet papers

- app/lib/notifications-counter.js
- app/pages/notifications/notification-section.jsx
- app/partials/app.cjsx
Staging branch URL: https://pr-5294.pfe-preview.zooniverse.org/
Towards #4727, specifically [this comment](https://github.com/zooniverse/Panoptes-Front-End/issues/4727#issuecomment-430651987).
Let me know if you'd like a few notifications on staging, I have multiple testing accounts, I can create notifications while you're testing to see if/how count updates.
- remove project context (`section`) of notification counter
- counter is in global header nav, shouldn't be project specific, looks strange when changes as navigate around site
- remove marking notifications as read if shown
- the notification property `delivered` is meant for if related email sent, marking as true when shown on notifications page (without user clicking anything) has caused some confusion, …
> Refactor notifications, keep unread

- app/locales/pt.js
- app/pages/project/index.jsx
Staging branch URL: https://pr-5317.pfe-preview.zooniverse.org
> Add a Portugese locale

- app/partials/register-form.cjsx
- css/forms.styl
Adds text changes to the registration form when a user is under 16.
https://docs.google.com/presentation/d/1t4u2L9TPZ1j7qq5yfzw7MvyTocDGY78Af8SPdC97x9A/edit#slide=id.p
Normally, this component would be rewritten into ES6 with tests. However, we're trying to make these changes quickly, and a rewrite will have to wait.
> Update Registration to Include Under 16

- app/talk/active-users.jsx
Fixes(?) a bug where the side bar active user links was trying to render after a user was banned and crashing.
> Add existential check to active users link render

- app/features/feedback/shared/strategies/datavis/graph2drange/README.md
- app/features/feedback/shared/strategies/datavis/graph2drange/index.js
- app/features/feedback/shared/strategies/index.js
- PFE staging project lab: https://pr-5352.pfe-preview.zooniverse.org/lab/1810/workflows/3318
- frontend-rewrite: https://fe-project.preview.zooniverse.org/projects/markb-panoptes/feedback-testing-mb/classify?env=staging
Fixes #5330.
- adds minimal code to allow Graph2dRange general feedback editing from workflow/task editor
> Add Graph2dRange feedback editor

- package-lock.json
- package.json
Ran NPM audit fix, which we hadn't done in a while.
> Ran npm audit fix

- css/subject-viewer.styl
Staging branch URL: http://pr-5361.pfe-preview.zooniverse.org
audio projects to test on:
- http://pr-5361.pfe-preview.zooniverse.org/projects/markb-panoptes/test-project-1-mb/classify?reload=0&workflow=3333
- http://pr-5361.pfe-preview.zooniverse.org/projects/trouille/wartburg-audio-project/classify?reload=0&workflow=11250&env=production
- http://pr-5361.pfe-preview.zooniverse.org/projects/cetalingua/manatee-chat/classify?env=production
- http://pr-5361.pfe-preview.zooniverse.org/projects/vivitang/earthquake-detective/talk/subjects/32893323?env=production
Fixes audio player not showing scrubber and controls.
Adds `min-width: 300px` to audio player.
> Add audio player min-width

- app/router.cjsx
Sets up the redirect for the new classifier on Planet Hunters TESS.
**Please do not merge until we're ready to go!**
> Setup redirect for Planet Hunters TESS - DO NOT MERGE

- app/classifier/tasks/dropdown/index.jsx
- app/classifier/tasks/dropdown/index.spec.js
Staging branch URL:  https://pr-5363.pfe-preview.zooniverse.org
- staging test project:  https://pr-5363.pfe-preview.zooniverse.org/projects/markb-panoptes/test-project-3-mb/classify?reload=0&workflow=3163
- production project noted in issue:  https://pr-5363.pfe-preview.zooniverse.org/projects/brbcornell/prothonotary-warbler/classify?reload=0&workflow=11219&env=production
Fixes #5362.
- adds option value check for strict equality to zero, in addition to existing truthy option value check
Notes
- It was not showing the option as selected, but it was saving the selection to the annotation.
- Only way to have an option value of `0` is with preset "Range of numbers" otherwise manually entering a custom option of "0" would be an option of `{ label: "0", value: …
> Refactor dropdown task bug with option value of 0

- app/pages/lab/visibility.cjsx
Edited post-beta instructions on visibility page to have teams properly request launch via contact email.
While editing this page, I also removed the temporary "workflow controls have moved" notice, as that change is now over a year old (Feb 2018; PR https://github.com/zooniverse/Panoptes-Front-End/pull/4331).
> Edit Visibility Page Text

- app/classifier/tasks/multiple/index.jsx
- app/classifier/tasks/single/index.jsx
Staging branch URL: https://pr-5420.pfe-preview.zooniverse.org
- production (second step): https://pr-5420.pfe-preview.zooniverse.org/projects/md68135/notes-from-nature-capturing-californias-flowers/classify?reload=1&workflow=11379
- staging: https://pr-5420.pfe-preview.zooniverse.org/projects/markb-panoptes/focus-testing-project/classify?reload=0&workflow=3345
Fixes #5419 
> Focus question task if have true autoFocus prop

- views/index.ejs
Staging branch URL: https://pr-5425.pfe-preview.zooniverse.org
Fixes https://github.com/zooniverse/Panoptes-Front-End/issues/5249
Adds meta tags for improved Twitter cards by adding logo image.
> Update OG and Twitter meta tags

- app/pages/lab/data-exports.jsx
> Change wording about export times and rate limit.

- app/pages/lab/mobile/mobile-section-container.jsx
- app/pages/lab/mobile/mobile-section-container.spec.js
Staging branch URL: https://pr-5375.pfe-preview.zooniverse.org
Fixes #5374.
- adds test for validating multiple task type for mobile
- adds multiple task as valid option for mobile tasks
- adds validations (same as single task) for multiple task on mobile
> Update valid mobile task types for multiple

- package-lock.json
- package.json
Staging branch URL: https://pr-5424.pfe-preview.zooniverse.org
> update modal-form to 2.9

- app/locales/de.js
- app/pages/project/index.jsx
Provides a German translation for major parts of Panoptes Front-End. Missing texts will be provided in a second commit in a few days (FAQ, Education in the Zooniverse, How to volunteer). I will also hopefully catch any typos in this second commit.
Note: lines 266 – 287 (about publications) are part of the English en.js version, but not in the de.js file that I translated. I added these and translated them, but did not compare both documents furthermore. If there are other differences that need to be taken into account for the translation, please let me know.
Staging branch URL: https://pr-5460.pfe-preview.zooniverse.org
Fixes #5452.
> Adds German translation to PFE

- .github/CONTRIBUTING.md
- README.md
This updates the guidelines to note that we are no longer developing new features with this app and link to the monorepo.
> Update readme and contributing guidelines

- app/features/feedback/shared/helpers/metadata-to-rules.js
- app/features/feedback/shared/helpers/metadata-to-rules.spec.js
Staging branch URL: https://pr-5517.pfe-preview.zooniverse.org
Updates PFE to reflect changes made in FEM related to feedback metadata-to-rules helper:
- [checking for null or undefined feedback value](https://github.com/zooniverse/front-end-monorepo/pull/1113)
- [checking `ruleIndex` is appropriately formatted](https://github.com/zooniverse/front-end-monorepo/pull/1070)
While originally we did not plan to update PFE as well, these bugs are preventing a TESS related research project from advancing (warning: depending on which subject set linked to workflow, refreshing to get bug or sim with feedback may be necessary):
- with bug: https://www.zooniverse.org/projects/mollysimon/planet-hunters-research-experience/classify?reload=0&workflow=12157
- with fix: …
> Update feedback metadate-to-rules validations

- app/classifier/annotation-renderer/svg.jsx
- app/classifier/tasks/drawing/index.cjsx
- app/lib/draggable.jsx
- app/lib/draggable.spec.js
- css/frame-annotator.styl
https://pr-5411.pfe-preview.zooniverse.org
Cancel drag events so that you can draw on a touchscreen without scrolling the page.
Moves the drag event listeners from the body down to the PFE app container div. Cancels move events, but not start events, and stops them from propagating up to the body.
Adds `touch-action: pinch-zoom` to the drawing/zooming styles so that panning is disabled but pinch-zoom is allowed while drawing. I'm not sure how usable this is, so it needs testing.
This [stackoverflow discussion about cancelling touch scrolling](https://stackoverflow.com/questions/16348031/disable-scrolling-when-touch-moving-certain-element) is useful.
> Drawing: cancel drag events to prevent window scrolling

- app/classifier/tasks/survey/choice.jsx
- app/classifier/tasks/survey/chooser/Choices.jsx
- app/classifier/tasks/survey/chooser/Chooser.jsx
- app/classifier/tasks/survey/image-flipper.jsx
- app/classifier/tasks/survey/index.jsx
Reverts zooniverse/Panoptes-Front-End#5533
The issues described in this Talk thread start with the merge commit for #5533. Reverting to get the survey task functioning as expected, then we can debug.
https://www.zooniverse.org/talk/18/1161362?comment=1894558&page=1
> Revert "Improve accessibility of survey task example photos"

- app/locales/index.js
- app/locales/zh-cn.js
- app/locales/zh-tw.js
Staging branch URL: https://pr-5552.pfe-preview.zooniverse.org
Fixes #5550  .
> Add Chinese Translations

- .travis.yml
- Dockerfile
- package.json
Staging branch URL: https://pr-5559.pfe-preview.zooniverse.org
This updates the package.json, dockerfile, and travis config to use node 10. Node 12 is actually LTS now, but incremental bumps is safer.
> Update to node 10

- app/locales/en.js
- app/pages/organization/organization-container.jsx
- app/pages/organization/organization-container.spec.js
- app/pages/organization/organization-page.jsx
- app/pages/organization/organization-project-cards.jsx
- app/pages/organization/organization-project-cards.spec.js
Staging branch URL: https://pr-5555.pfe-preview.zooniverse.org
Helpful links:
- staging testing project: https://pr-5555.pfe-preview.zooniverse.org/organizations/markb-panoptes/urban-wildlife-org-test
- Snapshot Serengeti: https://pr-5555.pfe-preview.zooniverse.org/organizations/meredithspalmer/snapshot-safari?env=production
- Notes from Nature: https://pr-5555.pfe-preview.zooniverse.org/organizations/md68135/notes-from-nature?env=production
- remove filter on project state from request for organization linked projects
- move category filter functionality from container to page state (reducing API requests)
- add project sections to organization landing page
Note there are intentionally no styling updates in this PR.
> Add project state sections to organization landing page - 1

- css/typography.styl
Staging branch URL: https://pr-5575.pfe-preview.zooniverse.org
Fixes #5314
This adds a bit of simple CSS to change the font-family to Arial, sans-serif as suggested in #5314.
> Add css to change font-family for Czech

- app/locales/ar.js
- app/locales/cs.js
- app/locales/de.js
- app/locales/en.js
- app/locales/es.js
- app/locales/fr.js
- app/locales/he.js
- app/locales/it.js
- app/locales/ja.js
- app/locales/nl.js
- app/locales/pt.js
- app/locales/zh-cn.js
- app/locales/zh-tw.js
- app/pages/about/donate.jsx
- app/pages/about/donate.spec.js
Staging branch URL: https://pr-5578.pfe-preview.zooniverse.org
This PR makes a few changes to the copy on the donate about page.
> Update Donate Page Copy

- app/locales/ar.js
- app/locales/cs.js
- app/locales/de.js
- app/locales/en.js
- app/locales/es.js
- app/locales/fr.js
- app/locales/he.js
- app/locales/it.js
- app/locales/ja.js
- app/locales/nl.js
- app/locales/pt.js
- app/locales/zh-cn.js
- app/locales/zh-tw.js
Staging branch URL: https://pr-5579.pfe-preview.zooniverse.org
Fixes # .
Made some final changes to the copy on the "donation" tab
> Final Donate Page Edits

- app/locales/en.js
- app/pages/organization/organization-page.jsx
- app/pages/organization/organization-page.spec.js
- app/pages/organization/organization-project-cards.jsx
- app/pages/organization/organization-project-cards.spec.js
- css/organization-page.styl
Staging branch URL: https://pr-5556.pfe-preview.zooniverse.org
Helpful links:
- staging testing project: https://pr-5556.pfe-preview.zooniverse.org/organizations/markb-panoptes/urban-wildlife-org-test
- Snapshot Serengeti: https://pr-5556.pfe-preview.zooniverse.org/organizations/meredithspalmer/snapshot-safari?env=production
- Notes from Nature: https://pr-5556.pfe-preview.zooniverse.org/organizations/md68135/notes-from-nature?env=production
- updates styling to [InVision organization landing page redesign](https://projects.invisionapp.com/d/main/default/#/console/12924056/391430827/preview)
- refactors about section from collapsable to two column
> Update organization landing page style - 2

- app/components/ExternalLinksBlock/ExternalLinksBlock.jsx
- app/components/ExternalLinksBlock/ExternalLinksBlockContainer.jsx
- app/components/ExternalLinksBlock/components/ExternalLink/ExternalLink.jsx
- app/components/ExternalLinksBlock/components/ExternalLink/ExternalLink.spec.jsx
- app/pages/organization/organization-page.jsx
- css/organization-page.styl
Staging branch URL: https://pr-5557.pfe-preview.zooniverse.org
Helpful links:
- staging testing project: https://pr-5557.pfe-preview.zooniverse.org/organizations/markb-panoptes/urban-wildlife-org-test
- Snapshot Serengeti: https://pr-5557.pfe-preview.zooniverse.org/organizations/meredithspalmer/snapshot-safari?env=production
- Notes from Nature: https://pr-5557.pfe-preview.zooniverse.org/organizations/md68135/notes-from-nature?env=production
- refactors ExternalLinks component in accordance with [InVision organization landing page redesign](https://projects.invisionapp.com/d/main/default/#/console/12924056/391430827/preview)
> Refactor external links section for organization redesign - 3

- app/locales/en.js
- app/pages/organization/organization-metadata.jsx
- app/pages/organization/organization-metadata.spec.js
- css/organization-page.styl
Staging branch URL: https://pr-5577.pfe-preview.zooniverse.org
Helpful links:
- staging testing project: https://pr-5577.pfe-preview.zooniverse.org/organizations/markb-panoptes/urban-wildlife-org-test
- Snapshot Serengeti: https://pr-5577.pfe-preview.zooniverse.org/organizations/meredithspalmer/snapshot-safari?env=production
- Notes from Nature: https://pr-5577.pfe-preview.zooniverse.org/organizations/md68135/notes-from-nature?env=production
- refactor org landing stats section in accordance with [InVision organization landing page redesign](https://projects.invisionapp.com/d/main/default/#/console/12924056/391430827/preview)
- clean-up styling for mobile, headings and misc.
> Refactor stats section for organization redesign - 4

- app/locales/index.js
Staging branch URL: https://pr-5636.pfe-preview.zooniverse.org
> Register the Polish locale

- app/locales/en.js
- app/pages/admin/project-status.jsx
- app/pages/projects/index.jsx
- app/pages/projects/projects-welcome.jsx
- css/main.styl
- css/projects-page.styl
Add a featured projects banner to the projects page.
Add some projects page styles.
Add projects page text to the English locale file.
Staging branch URL: https://pr-5650.pfe-preview.zooniverse.org
> Featured projects: welcome banner

- app/pages/admin/featured-project-toggle.jsx
Don't disable the featured project checkbox for featured projects.
Staging branch URL: https://pr-5662.pfe-preview.zooniverse.org
> Allow featured projects to be removed

- package-lock.json
- package.json
Install React 16.13.1.
Staging branch URL: https://pr-5658.pfe-preview.zooniverse.org
> Upgrade to React 16.13

- app/constants/languageMenu.js
- app/locales/index.js
- app/locales/sv.js
Staging branch URL: https://pr-5675.pfe-preview.zooniverse.org
Enables Swedish translations.
> Enable Swedish translations.

- app/classifier/tasks/survey/editor.cjsx
Staging branch URL: https://pr-5682.pfe-preview.zooniverse.org
Fixes #5646.
- for each row/choice (i.e. animal) in characteristics CSV, get characteristic value index (i.e. index of "red" in "color" characteristic array, `-1` if not in array)
- if characteristic is set (i.e. "Y") and not already included for choice's characteristics, then add it
- **if characteristic is not set (i.e. "N") but it is in choice's characteristics, then remove it**
Noting CSVs included in task instructions - http://bit.ly/1QSpevJ
__This needs some more testing to confirm not breaking existing survey task__
- while troubleshooting I've focused on animal related survey tasks, are there other types of survey tasks this can be tested against?
> Edit survey task characteristics import for existing value change

- app/constants/languageMenu.js
- app/locales/hr.js
- app/locales/index.js
Staging branch URL: https://pr-5704.pfe-preview.zooniverse.org
Fixes #5703 .
Adds Croatian (hr) locale file.  All content remains in English, but will allow future translation of these shared components.
> add locale: hr

- app/pages/organization/organization-page.jsx
Staging branch URL: https://pr-5711.pfe-preview.zooniverse.org
- https://pr-5711.pfe-preview.zooniverse.org/organizations/md68135/notes-from-nature?env=production
Fixes #5709.
> Fix organization researcher quote link

- app/locales/hr.js
- app/locales/pt.js
Staging branch URL: https://pr-5730.pfe-preview.zooniverse.org
Closes #5700, related to #5703
Adds translated content: Croatian (hr) as contributed by [ISTROX](https://www.zooniverse.org/projects/sandorkruk/istrox) team via @sandorkruk, and Portuguese (pt) as contributed by [WildCam Gorongosa](https://www.zooniverse.org/projects/zooniverse/wildcam-gorongosa) team via Meredith Palmer.
Created as part of Excel-enabled translation processing workflow -- ping me (@lcjohnso) for more information or if interested in using for other language files.
> Add translated content for hr and pt locales

- .github/workflows/codeql-analysis.yml
enable GH security scanning features on PRs and master branch changes (similar to travis CI)
> enable GH security scanning

- app/locales/pt.js
Staging branch URL: https://pr-5763.pfe-preview.zooniverse.org
Updates translated string for "Done and Talk" -- original translation had identical strings for "Done" and "Done and Talk".
> Minor edit to pt.js

- views/index.ejs
Staging branch URL: https://pr-5770.pfe-preview.zooniverse.org
In preparation for some major back-end migration, we're going to put up a "maintenance mode" message on the Zooniverse.org website. Almost all paths (including project paths, but not including favicon.ico, etc) will display the maintenance page.
DO NOT MERGE UNTIL @adammcmaster SAYS SO. (Or maybe let Adam click the Merge button? Wait, that makes more sense.)
This PR should be reverted as soon as the migration is complete. (Again, check with Adam.)
> Maintenance Mode - Jul 2020

- views/index.ejs
Getting this ready to go for when the maintenance is finished,
> Remove maintenance message

- views/index.ejs
To be merged tomorrow morning.
> Add maintenance page again for database migrations

- views/index.ejs
This reverts commit 9bb78e5c5a7956b6fdab987e438fa9995486767c.
Fixes # .
> Revert "Add maintenance page again for database migrations"

- package-lock.json
Staging branch URL: https://pr-5804.pfe-preview.zooniverse.org
Upgrade some outdated packages to fix security warnings.
> run npm audit

- app/pages/about/team-members.js
Staging branch URL: https://pr-5853.pfe-preview.zooniverse.org
Fixes # .
> Move marten to alumni

- package-lock.json
- package.json
Staging branch URL: https://pr-5851.pfe-preview.zooniverse.org
> Upgrade webpack to 4.44

- app/locales/ur.js
Makes edits as suggested by Sajjad Zaheer Photo Archive project team -- see Freshdesk Ticket 5770 for details.
Staging branch URL: https://pr-5883.pfe-preview.zooniverse.org
Suggested test project: https://pr-5883.pfe-preview.zooniverse.org/projects/sajjadzaheerarchive/sajjad-zaheer-photo-archive?language=ur&env=production
> Edit ur locale file

- app/main.cjsx
- app/pages/project/index.jsx
Comment out Sentry start-up in main.csjx and the error logger for project pages.
Staging branch URL: https://pr-5887.pfe-preview.zooniverse.org
> Turn off Sentry logging

- views/index.ejs
DO NOT MERGE UNTIL CLEARED BY @nciemniak + Team Backend at conclusion of downtime.
Reverts zooniverse/Panoptes-Front-End#5889
> Revert "Maintenance Mode - Feb 2021"

- app/pages/admin/project-status/experimental-features.jsx
This is in preparation for adding a basic UI in the lab for the transcription task.
> Adds transcription-task to experimental feature flag list

- app/classifier/tasks/generic-editor.cjsx
- app/classifier/tasks/index.jsx
- app/classifier/tasks/index.spec.js
- app/classifier/tasks/transcription/SubtaskEditor.jsx
- app/classifier/tasks/transcription/editor.jsx
- app/classifier/tasks/transcription/index.jsx
Staging branch URL: https://pr-5903.pfe-preview.zooniverse.org
This is an initial pass at the UI for editor:
~Note changes to the text in the text inputs here are non-functional. Right now this is just implementing the basic UI.~ Actually I got the input change handler working! 
This can be previewed at https://pr-5903.pfe-preview.zooniverse.org/lab/1764/workflows/3392
> Transcription task editor view

- app/locales/hi.js
- app/locales/ur.js
- app/redux/ducks/translations.js
Changing `ur` locale to RTL language, and editing platform `ur` and `hi` translations.
Staging branch URL: https://pr-5890.pfe-preview.zooniverse.org
Project-specific test URLs:
https://pr-5890.pfe-preview.zooniverse.org/projects/sajjadzaheerarchive/sajjad-zaheer-photo-archive?env=production&language=ur
https://pr-5890.pfe-preview.zooniverse.org/projects/sajjadzaheerarchive/sajjad-zaheer-photo-archive?env=production&language=hi
> Add ur as rtl language, edit ur + hi translations

- .travis.yml
- Dockerfile
- app/classifier/world-wide-telescope.spec.js
- package.json
Staging branch URL: https://pr-5917.pfe-preview.zooniverse.org
Upgrades to Node 14, the current LTS.
> Upgrade to node 14

- package-lock.json
- package.json
Staging branch URL: https://pr-5936.pfe-preview.zooniverse.org
> Upgrade Panoptes API client to 3.3.1

- package-lock.json
- package.json
Staging branch URL: https://pr-5937.pfe-preview.zooniverse.org
Supersedes #5931.
> [Security] Upgrade engine.io-client to 5.1

- .github/workflows/ci-tests.yml
- .github/workflows/deploy_branch.yml
- .github/workflows/deploy_production.yml
- .github/workflows/deploy_staging.yml
Use npm ci instead of npm install. Fix a typo in the name of the tests job. Cache packages across workflows.
This updates the deploy workflows so that they're in line with the CI test workflow. Packages installed for the tests should be reused by deployments, rather than downloaded again.
Staging branch URL: https://pr-5942.pfe-preview.zooniverse.org
> Update build actions

- app/collections/collection-search.cjsx
- app/collections/collections-manager.jsx
Staging branch URL: https://pr-5947.pfe-preview.zooniverse.org
Fixes https://www.zooniverse.org/talk/17/1990968?comment=3246122
This PR disambiguates the collection names by providing the owner display name as well. 
Possible improvements to this PR: 
1. Since the data is already available for the component, i was thinking this could be a checkbox behaviour toggle as well as most of the time this will be redundant information (as folks normally don't collaborate on collections). 
2. Alternatively - this could be automated and only add the owner suffix when the logged in user and the collection owner differ (we have this information). 
I'd be happy to iterate on this solution, thoughts?
> add owner display name to collection search

- package-lock.json
Staging branch URL: https://pr-5957.pfe-preview.zooniverse.org
> [Security] Run npm audit fix

- app/router.cjsx
Staging branch URL: https://pr-5963.pfe-preview.zooniverse.org
Request from @snblickhan. We have to setup the Frontdoor configuration still.
> Add redirect for Beyond Borders

- .github/workflows/deploy_branch.yml
- .github/workflows/deploy_production.yml
- .github/workflows/deploy_staging.yml
Upload `index.html` and `commit_id.txt` with a cache lifetime of 60s. Delete them after upload then upload the rest of the build with a cache lifetime of 60,4800s (1 week.)
This should fix any scenarios where `index.html` could be served out to the CDN with a lifetime of 1 week, before it's overwritten with a cache lifetime of 60s.
Staging branch URL: https://pr-5965.pfe-preview.zooniverse.org
> Delete index.html and commit_id.txt after upload

- app/components/ExternalLinksBlock/components/ExternalLink/ExternalLink.spec.jsx
- package-lock.json
- package.json
Security patch for markdownz, including adding `noreferrer` to external links. See https://github.com/zooniverse/how-to-zooniverse/issues/143
Staging branch URL: https://pr-5968.pfe-preview.zooniverse.org
To test this, try the link to IPAC in this thread. On master, it redirects back to zooniverse.org.
https://pr-5968.pfe-preview.zooniverse.org/talk/17/2024167?env=production
Also fixed is the IRSA Finder Chart link for each Backyard Worlds subject.
eg. https://pr-5968.pfe-preview.zooniverse.org/projects/marckuchner/backyard-worlds-planet-9/talk/subjects/28039200?env=production
> [Security] Upgrade markdownz to 7.7.2

- app/components/pan-zoom.spec.js
- package-lock.json
- package.json
Staging branch URL: https://pr-5973.pfe-preview.zooniverse.org
Describe your changes:
- run npm audit fix to fix some ws package dependencies
- upgrade jsdom to v16.6.0 to fix ws package dependency
- fix PanZoom broken test per jsdom upgrade
> [Security] Updates related to ws package vulnerability

- README.md
> use GH actions CI status badge

- app/locales/pt.js
Staging branch URL: https://pr-6006.pfe-preview.zooniverse.org
Closes #6005 
Incorporating edits from P4 translator for pt.js locale file.
> Locale Edit: pt

- app/MonorepoRoute.jsx
- app/router.cjsx
`MonorepoRoute` is a [custom `Route` component](https://marmelab.com/blog/2016/09/20/custom-react-router-component.html) which takes a project path and redirects it to our NextJS project app. It handles both the home page and the Classify and About page URLs, which reduces router config down to one line of code for new projects:
```jsx
<MonorepoRoute path="/projects/nora-dot-eisner/planet-hunters-tess" />
```
Staging branch URL: https://pr-6016.pfe-preview.zooniverse.org/projects/nora-dot-eisner/planet-hunters-tess/talk?env=production
Try navigating to the Collect page, the About page, the Classify page and the project home page. The last three should redirect to NextJS. You can also try navigating to the Projects page, where HMS NHS should redirect too.
> Add custom MonorepoRoute to the router

- app/MonorepoRoute.jsx
- app/router.cjsx
Redirect `rachaelsking/corresponding-with-quakers` to fe-project.zooniverse.org.
Linked to https://github.com/zooniverse/static/pull/244 -- **please wait until that PR merges before merging this PR**.
Staging branch URL: https://pr-6017.pfe-preview.zooniverse.org
For Testing: Visit links below and check that from Talk (PFE) you are correctly sent to FEM.
https://pr-6017.pfe-preview.zooniverse.org/projects/rachaelsking/corresponding-with-quakers/talk?env=production
https://pr-6017.pfe-preview.zooniverse.org/projects/nora-dot-eisner/planet-hunters-tess/talk?env=production
> FEM redirect: add Corresponding With Quakers

- .github/workflows/deploy_branch.yml
- .github/workflows/deploy_production.yml
- .github/workflows/deploy_staging.yml
> Revert to previous AzureCLI version

- .github/workflows/deploy_branch.yml
- .github/workflows/deploy_production.yml
- .github/workflows/deploy_staging.yml
- app/pages/admin/user-settings.jsx
- app/pages/admin/user-settings.spec.js
- app/pages/admin/user-settings/stats.js
Fetch `UserProjectPreferences` on the user admin page and show a list of per-project classification counts. Page through the full set of preferences, incrementally setting state as each page is received.
Revert `azcliversion` to `latest` for all the deploys. 2.29.2 doesn't work with the latest `azure/login`.
Staging branch URL: https://pr-6038.pfe-preview.zooniverse.org
Test user profile: https://pr-6038.pfe-preview.zooniverse.org/admin/users/123?env=production
> User admin: add project classification counts

- app/monorepoUtils.js
Related to : https://github.com/zooniverse/static/pull/254
View: https://pr-6047.pfe-preview.zooniverse.org/projects/emhaston/the-rbge-herbarium-exploring-gesneriaceae-the-african-violet-family/classify
Fixes # .
> update utils to include rgbe herbarium

- .github/workflows/azure_deploy.yml
- .github/workflows/deploy_branch.yml
- .github/workflows/deploy_production.yml
- .github/workflows/deploy_staging.yml
- .github/workflows/npm_build.yml
- .github/workflows/slack_notification.yml
Move builds, deploys and slack notifications into their own reusable workflows. The build job saves the build as a [workflow artifact](https://docs.github.com/en/actions/advanced-guides/storing-workflow-data-as-artifacts), which can be downloaded by the deploy job.
Builds are archived by GitHub for 90 days, and can be downloaded from the Actions panel.
Staging branch URL: https://pr-6066.pfe-preview.zooniverse.org
> Split up the azure_deploy workflow

- app/monorepoUtils.js
Staging branch URL: 
https://pr-6109.pfe-preview.zooniverse.org/
Redirecting manuscripts of medieval spain 
**Related to PR on static https://github.com/zooniverse/static/pull/264**
> update utils to add manuscripts of medieval spain

- app/monorepoUtils.js
Staging branch URL: https://pr-6125.pfe-preview.zooniverse.org
Describe your changes: Redirect for Ottoman Turkish Crowdsourcing
> Add Ottoman Turkish crowdsourcing redirect

- views/index.ejs
switch to an current owner (me) for google site verification. 
This is used to ensure we can access the search console and add more owners etc, https://support.google.com/webmasters/answer/9008080#meta_tag_verification&zippy=%2Chtml-tag
> switch google site verification code

- app/pages/admin/project-status.jsx
Staging branch URL: https://pr-6130.pfe-preview.zooniverse.org
See related [FEM DigiLeap project](https://github.com/zooniverse/front-end-monorepo/projects/17) and specifically documentation related [FEM PR 3008](https://github.com/zooniverse/front-end-monorepo/pull/3008).
- see workflow [3548: Text](https://pr-6130.pfe-preview.zooniverse.org/admin/project_status/markb-panoptes/digileap-testing) that has the `singleText` viewer selected
- adds (FEM subject viewers) `singleText` and `imageAndText` options to admin project workflow settings
> Add singleText and imageAndText viewers to admin project workflow settings

- app/router.jsx
Add project Home, About and Classify to the i18n routes. These were missed in #6145.
Try them out with Every Name Counts:
https://pr-6149.pfe-preview.zooniverse.org/projects/de/arolsen-archives/every-name-counts?env=production
Staging branch URL: https://pr-6149.pfe-preview.zooniverse.org
> Use i18n routes for all project page paths.

- app/pages/lab/index.cjsx
Staging branch URL: https://pr-6165.pfe-preview.zooniverse.org
Fixes #6098 
Problem - the text boxes on the ProjectCreationForm spill over when the screen size is reduced. See #6098 for screenshot.
Analysis - the max width of the form was fixed at 90% of the viewport which was too big
Solution - reducing the max width from 90% to 50% of the view port so that the modal could be seen on smaller screens. 
Please see attached screenshots:
View on an iPhoneXR 414x896 at 50%
Desktop view of form
> Fix ProjectCreationForm modal to make responsive on smaller screens

- app/constants/languageMenu.js
- app/locales/index.js
- app/locales/tr.js
Adds Turkish (tr) locale file and platform-level translated content.
Staging branch URL: https://pr-6160.pfe-preview.zooniverse.org
Project-specific test URLs: TBD
> Add Turkish (tr) Locale

- app/classifier/tasks/survey/editor.cjsx
Update Survey Task template file download location to new Drive location after GSuite migration.
> Update link for Survey Task example files

- app/locales/ja.js
Staging branch URL: https://pr-6173.pfe-preview.zooniverse.org
Updates to Japanese locale file, as contributed by Atsushi Ebihara.
> Update ja Locale

- app/classifier/tasks/generic-editor.cjsx
Staging branch URL: https://pr-6222.pfe-preview.zooniverse.org
- preview/production testing project - https://pr-6222.pfe-preview.zooniverse.org/lab/4312/workflows
- local testing project/workflow (feel free to create new workflow or add tasks) - https://local.zooniverse.org:3735/lab/1779/workflows/3688
Continues on #6221 .
Currently in the question task editor the toggle checkbox for "Allow multiple" and "Allow hiding marks" is broken, doesn't update the task or workflow.
- refactors generic task editor replacing `workflow.update 'tasks'` with `@props.onChange @props.task`
I think to test these changes one should create a single task, multiple task, and drawing task, toggle required and hide previous marks, add drawing tools and subtasks, edit drawing tool min/max, …
> Refactor task generic editor for task changes and workflow update

- app/pages/lab/project.jsx
- Fix a typo in the query that gets project roles for a project.
- Tidy up the code that gets owners and collaborators from Panoptes.
Staging branch URL: https://pr-6238.pfe-preview.zooniverse.org
Supersedes #6235.
Closes #6239.
> lab/projects: Fix the query for project owners

- app/pages/lab/actions/media.js
- app/pages/lab/media-area/index.jsx
- app/pages/lab/media.jsx
Filter selected files by MIME type before calling the `addFile` action in the project builder's Media page.
You can test this out by dragging and dropping files into the upload area. Only image, audio or video files should be uploaded.
Staging branch URL: https://pr-6257.pfe-preview.zooniverse.org
> [Security] Validate uploaded media by MIME type

- .github/workflows/ci-tests.yml
- .github/workflows/deploy_branch.yml
- .github/workflows/deploy_production.yml
- .github/workflows/deploy_staging.yml
- Dockerfile
- package.json
- Upgrade CI workflows to Node 18 (`lts/hydrogen`.)
- Upgrade Dockerfile to `node:18-alpine`.
- Upgrade `package.json` to Node 18 for development and deployment.
Staging branch URL: https://pr-6417.pfe-preview.zooniverse.org
> Build with Node 18

- app/pages/lab-fem/components/fem-multi-image-subject-options-editor.jsx
- app/pages/lab-fem/fem-multi-image-subject-options-editor.jsx
- app/pages/lab-fem/workflow.jsx
Staging branch URL: https://pr-6418.pfe-preview.zooniverse.org
Related Slack Convo: https://zooniverse.slack.com/archives/C06LHUC6R/p1674576134599589
Merging this PR will be followed up with: https://github.com/zooniverse/front-end-monorepo/pull/4181
I created a multi-image-subject-options-editor specifically for fem-lab to add autoplay to flipbook projects. This component only includes features that are already built into FEM (flipbook for non-transcription multi-image subjects, play iterations, and the upcoming addition of autoplay). This component excludes "separate frames view first" because that feature is not built in FEM yet.
You can test this branch by loading a project with `femLab=true` in the url and viewing the Multi-Image Options section. I recommend my test project locally: …
> FEM Lab: build fem-version of multi-image subject options

- app/classifier/classifier.jsx
- app/components/file-viewer/image-viewer.jsx
- app/lib/init-sentry.js
- app/lib/preloadSubject.js
- app/pages/project/index.jsx
- Remove `componentWillUnmount`.
- Refactor `componentWillReceiveProps` as `componentDidUpdate`.
- Return the loaded subject from the preloader.
- Log slow-loading subjects to Sentry.
- Log failed images with extra context, including the URL.
- Add [custom tags](https://docs.sentry.io/platforms/javascript/enriching-events/scopes/#using-with-scope) for easier event grouping and counting in Sentry.
To do:
Staging branch URL: https://pr-6458.pfe-preview.zooniverse.org
> Extend error logging for subject images

- app/components/file-viewer/canvas-viewer.jsx
- app/features/modelling/line-plot/index.js
- app/pages/collections/collection-card.jsx
- update the modelling feature to display JSON data subjects using ChartJS.
- update the canvas viewer to support light curve data from SuperWASP Black Hole Hunters and Superluminous Supernovae.
Staging branch URL: https://pr-6440.pfe-preview.zooniverse.org
Example subjects:
- https://pr-6440.pfe-preview.zooniverse.org/projects/camallen/talk-test-project/talk/subjects/80709319
- https://pr-6440.pfe-preview.zooniverse.org/projects/mrniaboc/superluminous-supernovae/talk/subjects/85828868
- https://pr-6440.pfe-preview.zooniverse.org/projects/hughdickinson/superwasp-black-hole-hunters/talk/subjects/69806211
Closes #6439.
> Add JSON subjects to Talk

- app/lib/put-file.js
Reverts zooniverse/Panoptes-Front-End#6479
> Revert "Sanitise SVG file uploads"

- app/lib/put-file.js
Update the `putFile` helper to sanitise SVG files and remove unsafe tags, such as `script`.
Allow [`<animate>`](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/animate), [`<use>`](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/use) and discrete interpolation with [`calcMode`](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/calcMode).
Uploaded test subjects:
- Sanitised: https://panoptes-uploads-staging.zooniverse.org/subject_location/9fe0372b-1bc0-4607-a484-303d3afb6d4a.svg
- Unsanitised: https://panoptes-uploads-staging.zooniverse.org/subject_location/1c58d687-10ed-4276-8ed9-5e400d17fd7c.svg
Towards https://github.com/zooniverse/panoptes/security/advisories/GHSA-85fr-5pvp-fmjm
You can test this out by uploading an SVG file, containing unsafe content, via any …
> [Security] Sanitise SVG file uploads

- app/pages/admin/project-status.jsx
- Add the new `jsonData` viewer type to the workflow admin form.
- Deprecate the old, individual subject viewers.
- Link up the help text to the select menu with `aria-describedby`.
Staging branch URL: https://pr-6652.pfe-preview.zooniverse.org/admin
Here's a screenshot for [Planet Hunters: TESS](https://pr-6652.pfe-preview.zooniverse.org/admin/project_status/nora-dot-eisner/planet-hunters-tess).
> Admin: deprecate individual JSON subject viewers

- views/index.ejs
Updating the `google-site-verification` key used to verify site ownership for Google Search Console / Webmaster service. Similar to previous #6136 and #1466.
> Update google site verification (2023)

- app/constants/languageMenu.js
A first pass at South African languages for the dropdown menu that we show to volunteers.
Staging branch URL: https://pr-6738.pfe-preview.zooniverse.org
> South African language menu

- app/monorepoUtils.js
Status: HOLD -- DO NOT MERGE! Target for merge is Thursday July 27, but confirm with Cliff before merging.
Related to https://github.com/zooniverse/static/pull/325
Staging branch URL: https://pr-6741.pfe-preview.zooniverse.org
> Add FEM redirect for Snapshot Serengeti

- app/monorepoUtils.js
Status: HOLD -- DO NOT MERGE! Target for merge is Wed Sep 6, but confirm with Cliff before merging.
Related to https://github.com/zooniverse/static/pull/328
Staging branch URL: https://pr-6810.pfe-preview.zooniverse.org/
> Add FEM redirect for Knitting Leaflet and Solar Jet Hunter

- app/locales/pt.js
Staging branch URL: https://pr-6841.pfe-preview.zooniverse.org
The pt translation of collect should be colecionar not coleccionar. Based on Slack convo: https://zooniverse.slack.com/archives/C583QHN49/p1695418335475919
> Correct pt translation of collect

- app/locales/es.js
Staging branch URL: https://pr-6846.pfe-preview.zooniverse.org/projects/es/tedcheese/snapshots-at-sea-historic
> Add Explore The Project to es.js

- .github/workflows/ci-tests.yml
- .github/workflows/deploy_branch.yml
- .github/workflows/deploy_production.yml
- .github/workflows/deploy_staging.yml
- Dockerfile
Upgrade the build scripts from `lts/hydrogen` to `lts/iron`.
Staging branch URL: https://pr-6895.pfe-preview.zooniverse.org
> Build and deploy with Node 20

- .github/dependabot.yml
Staging branch URL: https://pr-6921.pfe-preview.zooniverse.org
> Add dependabot for GH Actions

- app/monorepoUtils.js
Staging branch URL: https://pr-6952.pfe-preview.zooniverse.org
Related to https://github.com/zooniverse/static/pull/336 and https://github.com/zooniverse/static/pull/337
> Edit FEM redirect: Black Hole Hunters

- app/locales/en.js
- app/locales/hi.js
- app/locales/ja.js
- app/locales/kn.js
- app/locales/ko.js
- app/locales/pl.js
- app/locales/ru.js
- app/locales/sv.js
- app/locales/tr.js
- app/locales/ur.js
- app/pages/organization/stats/OrganizationStats.jsx
- app/pages/organization/stats/components/BarChart/BarChartContainer.jsx
- edit translations for stats type change from `classification` and `comment` to `classifications` and `comments`
- update OrganizationStats and BarChartContainer per ^
> Refactor translations for stats type

- app/monorepoUtils.js
Add FEM redirects for correct-a-machine projects:
Etch a Cell - Correct a Cell (Project 21184)
Galaxy Zoo: Clump Scout II (Project 22358)
Staging branch URL: https://pr-6992.pfe-preview.zooniverse.org/
Target Deploy Time: Dec 12 at 10am Central
> FEM redirects: GZ Clump Scout II and Correct-a-Cell

- app/monorepoUtils.js
Add FEM redirects for Elephant ID EY (Project 22977)
Staging branch URL: https://pr-7001.pfe-preview.zooniverse.org/
Staging URL for Project: https://pr-7001.pfe-preview.zooniverse.org/projects/zookeeper/elephant-id-ey
Target Link: https://www.zooniverse.org/projects/zookeeper/elephant-id-ey
Project Lab Link: https://www.zooniverse.org/lab/22977
Target Deploy Date: Dec 20
> FEM redirect: Elephant ID EY

- app/monorepoUtils.js
Add FEM redirects for Arctic Archives (Project 21696)
Staging branch URL: https://pr-7022.pfe-preview.zooniverse.org/
Staging URL for Project: https://pr-7022.pfe-preview.zooniverse.org/projects/johandmi/arctic-archives-unraveling-greenlands-weather-history
Target Link: https://www.zooniverse.org/projects/johandmi/arctic-archives-unraveling-greenlands-weather-history
Project Lab Link: https://www.zooniverse.org/lab/21696
**Target Deploy Date: Jan 18**
> FEM redirect: Arctic Archives

- app/monorepoUtils.js
Static PR here: https://github.com/zooniverse/static/pull/348
> FEM redirects for April 24 migration

- app/monorepoUtils.js
Add FEM redirect for FISHstory (Project 9606)
Staging branch URL: https://pr-7094.pfe-preview.zooniverse.org/
Staging URL for Project: https://pr-7094.pfe-preview.zooniverse.org/projects/safmcadmin/fishstory
Target Link: https://www.zooniverse.org/projects/safmcadmin/fishstory
Project Lab Link: https://www.zooniverse.org/lab/9606
Static PR: https://github.com/zooniverse/static/pull/352
> FEM Redirect for FISHstory

- app/monorepoUtils.js
Add FEM redirect for Stereovision (Project 23052)
Staging branch URL: https://pr-{NUMBER}.pfe-preview.zooniverse.org/
Staging URL for Project: https://pr-{NUMBER}.pfe-preview.zooniverse.org/projects/juliehgibb/stereovision
Target Link: https://www.zooniverse.org/projects/juliehgibb/stereovision
Project Lab Link: https://www.zooniverse.org/lab/23052
> FEM redirect: Stereovision

- app/monorepoUtils.js
Staging branch URL: https://pr-7138.pfe-preview.zooniverse.org/
Add FEM redirect for talkietoaster/void-orchestra (Project 24246)
Staging branch URL: https://pr-7149.pfe-preview.zooniverse.org/
Staging URL for Project: https://pr-7149.pfe-preview.zooniverse.org/projects/talkietoaster/void-orchestra
Target Link: https://www.zooniverse.org/projects/talkietoaster/void-orchestra
Project Lab Link: https://www.zooniverse.org/lab/24246
> FEM redirect: void orchestra

- app/monorepoUtils.js
Add FEM redirect for hjsmith/the-material-culture-of-wills-england-1540-1790 (Project 23012)
Staging branch URL: https://pr-7152.pfe-preview.zooniverse.org/
Staging URL for Project: https://pr-7152.pfe-preview.zooniverse.org/projects/hjsmith/the-material-culture-of-wills-england-1540-1790
Target Link: https://www.zooniverse.org/projects/hjsmith/the-material-culture-of-wills-england-1540-1790
Project Lab Link: https://www.zooniverse.org/lab/23012
> FEM redirect: wills

- app/monorepoUtils.js
Add FEM redirect for Node Code Breakers (Project 14934)
Staging branch URL: https://pr-7155.pfe-preview.zooniverse.org/
Staging URL for Project: https://pr-7155.pfe-preview.zooniverse.org/projects/effeli/node-code-breakers-looking-for-patterns-in-lymph-nodes
Target Link: https://www.zooniverse.org/projects/effeli/node-code-breakers-looking-for-patterns-in-lymph-nodes
Project Lab Link: https://www.zooniverse.org/lab/14934
> Add redirect for Node Code Breakers

- app/monorepoUtils.js
FEM redirect for md68135/notes-from-nature-ranges-mammal-traits-from-western-north-america (Project 23782)
Staging branch URL: https://pr-7177.pfe-preview.zooniverse.org/
Staging URL for Project: https://pr-7177.pfe-preview.zooniverse.org/projects/md68135/notes-from-nature-ranges-mammal-traits-from-western-north-america
Target Link: https://www.zooniverse.org/projects/md68135/notes-from-nature-ranges-mammal-traits-from-western-north-america
Project Lab Link: https://www.zooniverse.org/lab/23782
> FEM redirect for NfN Mammal Traits

- app/partials/app.cjsx
- views/index.ejs
Staging branch URL: https://pr-7188.pfe-preview.zooniverse.org/projects
- Defines icon files now that PFE is not the root of the Zooniverse website.
You should see the following in `<head>`:
```
<link rel="icon" href="https://www.zooniverse.org/icon.svg">
<link rel="apple-touch-icon" href="https://www.zooniverse.org/touch-icon.png">
```
> Define icons in head element

- app/layout/index.jsx
Staging branch URL: https://pr-7221.pfe-preview.zooniverse.org/projects
Reverts: https://github.com/zooniverse/Panoptes-Front-End/pull/7217
Corresponding FEM PR: https://github.com/zooniverse/front-end-monorepo/pull/6479
The temporary banner should no longer be visible at the above staged url.
> Remove temporary banner from layout

- app/layout/site-footer.jsx
Staging branch URL: https://pr-7254.pfe-preview.zooniverse.org
Slack: https://zooniverse.slack.com/archives/C4RJRAGKA/p1738087706161429?thread_ts=1737988588.679469&cid=C4RJRAGKA
Corresponds to: https://github.com/zooniverse/front-end-monorepo/pull/6654
- Added a SocialAnchor for bluesky to ZooFooter.
- To review, see https://pr-7254.pfe-preview.zooniverse.org/projects and scroll to the footer. Check that the Bluesky icon links to Zooniverse's account.
> Add a bluesky icon to the footer

- app/monorepoUtils.js
FEM redirect for met-rhonda/irish-weather-rescue(Project 24686)
Static PR: https://github.com/zooniverse/static/pull/390
Staging branch URL: https://pr-7270.pfe-preview.zooniverse.org/
Staging URL for Project: https://pr-7270.pfe-preview.zooniverse.org/projects/cmcbrain/axonal-pathfinders
Target Link: https://www.zooniverse.org/projects/met-rhonda/irish-weather-rescue
Project Lab Link: https://www.zooniverse.org/lab/24686
Fixes # .
> Add redirect for Irish Weather Rescue 

- app/monorepoUtils.js
FEM redirect for pmason/woodpecker-cavity-cam-learning (Project 21409).
PFE PR: https://github.com/zooniverse/Panoptes-Front-End/pull/7286
Staging branch URL: https://pr-7286.pfe-preview.zooniverse.org/
Staging URL for Project: https://pr-7286.pfe-preview.zooniverse.org/projects/pmason/woodpecker-cavity-cam-learning
Target Link: https://www.zooniverse.org/projects/pmason/woodpecker-cavity-cam-learning
Project Lab Link: https://www.zooniverse.org/lab/21409
static PR: https://github.com/zooniverse/static/pull/391
> FEM redirect for Woodpecker learning

- app/monorepoUtils.js
Staging branch URL: https://pr-7306.pfe-preview.zooniverse.org
> Add FEM redirect for cmc/mind-mapper

- app/monorepoUtils.js
FEM redirect for healion90/weather-archive-africa (Project 24961).
PFE PR: https://github.com/zooniverse/Panoptes-Front-End/pull/7336
Staging branch URL: https://pr-7336.pfe-preview.zooniverse.org/
Staging URL for Project: https://pr-7336.pfe-preview.zooniverse.org/projects/healion90/weather-archive-africa
Target Link: https://www.zooniverse.org/projects/healion90/weather-archive-africa
Project Lab Link: https://www.zooniverse.org/lab/24961
Static PR: https://github.com/zooniverse/static/pull/399
> Weather Archive Africa redirect

- app/classifier/tasks/drawing-task-details-editor.cjsx
- app/classifier/tasks/subjectGroupComparison/editor.jsx
- app/classifier/tasks/subjectGroupComparison/index.jsx
- app/pages/lab-fem/workflow.jsx
Staging branch URL: https://pr-7357.pfe-preview.zooniverse.org/lab/2007/workflows/3867?env=staging
- Milestone [#31](https://github.com/zooniverse/front-end-monorepo/milestone/31)
- Related PR's: [#6985](https://github.com/zooniverse/front-end-monorepo/pull/6985), [#6979](https://github.com/zooniverse/front-end-monorepo/pull/6979), and [#7050](https://github.com/zooniverse/front-end-monorepo/pull/7050)
When in a workflow with a SubjectGroupViewer Task, the volunteer can add Sub-Tasks just like for Drawing tasks. When you load up PFE, you can see this locally with: https://local.zooniverse.org:3735/lab/2007/workflows/3867.
Note - you should be able to add / edit / remove subtasks with the same behavior as drawing tasks.
> SGV 3: Workflow Editor - Add SubTasks to SGV Task
