zooniverse/Panoptes-Front-End

- app/pages/home-for-user/index.jsx
- css/home-page-for-user.styl
Fixes #3664.
- Adds a FontAwesome down arrow to user homepage, at bottom of content section, to indicate the presence of featured projects below the content section (13 inch displays only show a small portion of the featured project section).
- I modified the margin on both `home-page-for-user__menu` and `home-page-for-user__down-arrow`, to get the look of an arrow vertically centered between "my collections" and the bottom of the teal box. I played around with other margin adjustments, eg no bottom-margin on `__menu` and identical top- and bottom-margins on `__down-arrow`, and went with what's currently on this branch as what I thought looked best - but happy to change if anyone prefers otherwise.
- Staged …
> Add down-arrow on user homepage.

- app/pages/home-common/featured-project.jsx
- app/pages/home-common/featured-project.spec.js
- app/pages/home-not-logged-in/discover.jsx
- app/pages/home-not-logged-in/research.jsx
Fixes #3994 .
Renders home page images using the Thumbnail component, with a reasonable maximum width set.
Ideally, we should not be committing large images into this repo in the first place, so the originals might need some optimisation.
> Resize home page images

- app/classifier/tasks/survey/chooser.jsx
Fixes a typo when I converted the survey task Chooser, which inverted the true/false logic for filtering by characteristics.
Rejects a choice if the filter value is _not_ in the choice characteristics.
> Fix survey filters

- app/pages/project/stats/charts.jsx
- app/pages/project/stats/stats.jsx
avoid converting to the client / browsers timezone, use UTC for consistency in reporting the event times.
Fixes issue report on talk - https://www.zooniverse.org/talk/17/441417?comment=736400
> convert all stats API times to UTC

- app/classifier/tasks/generic-editor.cjsx
- css/highlighter-task.styl
- package-lock.json
This PR increases and changes the color options available for highlighter tool labels. In order to provide more high contrast options, I switched the background and text colors for subjects. I also added a color preview to the workflow editor label selection dropdown.
@eatyourgreens, will these changes work for the Diagnosis London project?
> increase highlighter tool label color options

- app/pages/project/classify.cjsx
Picks up from my last PR that added the user group id to the classification metadata in #3979. The group id from the query param will now be checked with API to see if the group exists and if the logged in user is a member of the group.
For manual testing, the easiest to use to test is your own user group since all users are also member of their own group. It can be retrieved in the javascript console:
`zooAPI.type('user_groups').get({name: 'yourUserLogin'})`
And then just add your user group id as a query param to the classify page of a project: `?group=groupID`
Staged at: https://validate-user-group-membership.pfe-preview.zooniverse.org/
The only thing I'm unsure about is the naming part. I made the query param simple `group` but it's specifically the `user_group` that is being worked …
> Validate user group membership

- app/pages/project/index.cjsx
Fixes #4056.
If a selected workflow 404s, then it is cleared out of the user project preferences and selection is attempted again. 
I checked the project builder and it is removing deleted workflows from project default already: 
https://github.com/zooniverse/Panoptes-Front-End/blob/4a6719f3acbcbd175e655eb730e39e13c8bea2c6/app/pages/lab/workflow.cjsx#L687-L689
So this was only an issue on the volunteer side. 
Staged: https://fix-4056.pfe-preview.zooniverse.org/
> If workflow request 404s, clear out from prefs and try again

- app/classifier/annotation-renderer/svg.jsx
- app/components/file-viewer/audio-player.jsx
- app/components/file-viewer/progress-indicator.jsx
- app/components/file-viewer/video-player.jsx
- app/components/subject-viewer.cjsx
- css/subject-viewer.styl
Fixes #4054 
Fixes #4067 
Reverses one of the changes in #3995 so that the subject frame viewer is rendered after the SVG marking surface in the DOM.
I'm not 100% sure why this works, so it may need careful checking.
This PR also fixes ESLint warnings in the `ProgressIndicator` component and removes some redundant HTML from the audio player.
Some if logic is also reversed in the subject viewer so that we check for a mixed media audio file before deciding to render the flipbook slideshow. This fixes audio subject rendering on Talk.
> Fix audio player SVG rendering

- app/classifier/drawing-tools/polygon.cjsx
Fixes #3983.
Adds `pointerEvents='painted'` prop to drawing tool.
Note: Haven't tested Edge.
> Allow to draw concave polygons.

- app/classifier/classifier.jsx
Fixes #4078 .
Kind of a hacky fix, but makes sure that `props.onComplete` is always called by the classifier for a completed classification.
> Always submit a classification

- app/classifier/drawing-tools/root.cjsx
- app/classifier/tasks/drawing-task-details-editor.cjsx
- css/modal-form.styl
Fixes #3962.
This PR adds the dropdown task as a possible drawing subTask. The dropdown subTask can only be added to a workflow if the dropdown task is enabled for the project.
You can try it out with this demo project: https://dropdown-subtask.pfe-preview.zooniverse.org/projects/scribe-2/demo-for-dropdown-subtask/classify
> dropdown subTask

- css/image-selector.styl
Fixes #4077.
Add a `min-height` to `image-selector` CSS class.
Stages [here](https://fix-image-selector.pfe-preview.zooniverse.org/).
> Make lab image-selector always clickable

- app/classifier/tasks/shortcut/index.jsx
- app/classifier/tasks/shortcut/summary.jsx
Sorry, I missed this in #4084
Moves the shortcut summary component  into its own file.
> Move shortcut summary into its own file

- app/classifier/tasks/survey/summary.spec.js
Adds test cases for no, one or two identifications to the survey task summary.
> Expand survey task summary tests

- app/subjects/comment-form.cjsx
- app/subjects/index.jsx
- css/tabbed-content.styl
- css/talk.styl
Fixes #3849.
- Related: https://github.com/zooniverse/Panoptes-Front-End/issues/3425
- Disable functionality for user to create a discussion for a subject if the project team has not enabled additional discussion boards.
- If additional discussion boards have been created, display them as radio buttons, one of which must be selected to create the discussion.
- Defaults to first button being selected.
- A bug was fixed in this PR, where on initial landing on the `talk/subject/{subjectId}` page from the classifier, the Subject GET request was not returning the linked project. On refresh, the Subject GET request does return the linked project. Adding `{ include: 'project' }` to the `setSubject` GET request renders the additional Boards that a user can pick from on …
> Fix create discussion site hang

- app/classifier/drawing-tools/root.cjsx
- app/components/modal-focus.jsx
Fixes a focus bug found in #4075 
ModalFocus ignores disabled form controls, but doesn't update if those controls switch disabled state.
This PR updates the component to query the DOM on keydown, so that the list of focusable elements is always up-to-date. It also removes the tabindex that was added as a workaround in #4075
> Update modal focus

- app/pages/project/about/index.jsx
- app/pages/project/index.cjsx
Fixes #4111.
This uses the side loaded project roles already requested in the `ProjectPageController` parent and passes it down as props, rather than request for the project roles again. The side loaded project roles has all 32 roles.
https://fix-4111.pfe-preview.zooniverse.org/projects/penguintom79/seabirdwatch/about/team?env=production
As a side note, it seems we need to do a review of the API calls on the about pages to make sure we're being efficient and not making unnecessary API calls.
> Refactor about team page to use project roles from parent. Fixes #4111

- app/pages/home-common/featured-project.spec.js
Fixes tests that were broken by #4113 
Changes `Thumbnail` to `img` in the tests.
> Fix Featured Project tests

- app/pages/lab/project-details.cjsx
Closes #4103.
Adds message to top of project's Details section in the Project Builder if project is linked to an organization.
> add message in lab if project linked to organization

- app/components/pan-zoom.jsx
In response to feedback from Seabird Watch, this removes the check on `panEnabled` from the keydown handler for pan/zoom. The keyboard controls should work as long as the pan-zoom component has focus.
> Always listen for keyboard events with the pan-zoom tool

- app/classifier/tasks/survey/choice.jsx
- app/classifier/tasks/survey/chooser.jsx
Fixes a bug where undefined confusions in a survey task choice would cause the interface to hang.
Sets a default choice object if `otherChoiceID` does not correspond to a valid choice.
Also fixes a bug where the filter components would hang if choice characteristics were undefined (possibly due to a typo in the `characteristicID`.)
> Set a sane default for confusion choices

- css/highlighter-task.styl
This PR increases the font-weight property of the cursor icon for the highlighter tool in order to increase the visibility of the icon against the task area background. These changes are motivated from feedback received during the DCW highlighter tool beta test.
Assigns a `font-weight` property of `bolder` to the cursor icons.
Current Cursor Icon
Bolder Cursor Icon
> increase visibility of the cursor icon for the highlighter tool

- app/classifier/drawing-tools/root.cjsx
Focus them when they are first created, and whenever they are selected.
Allows keyboard events from the drawing tools to bubble up to containing elements, in turn allowing the pan-zoom keys to continue working while you are drawing.
Makes Seabird Watch much, much easier and is the first step towards implementing keyboard shortcuts for drawing (#3369)
> Allow drawing tools to receive focus

- app/classifier/drawing-tools/root.cjsx
Add #focusDrawingTool() to maintain the window scroll when drawing tools are created, selected, or deleted.
Fixes #4123 and closes #4124.
#focusDrawingTool() records the window scroll position before a drawing tool is focused, then applies the scroll position after focusing the drawing tool. 
In the future, we should look into how `ModalFocus` returns focus to the previously active element.
> Add method #focusDrawingTool to maintain the window scroll

- app/classifier/drawing-tools/root.cjsx
- css/drawing-tool.styl
Follow-up to #4122 
Remove the blue focus ring from the selected mark. We can style the selected mark to make it obvious that it has focus, if it isn't obvious already.
Returns focus to the current mark when the details form closes.
Checks whether the details form is open before assigning focus, since keyboard focus should go to that form if it is open.
> Focus drawing tools

- package-lock.json
- package.json
Turns out the npm package is only needed for simplifying any advanced config, [we don't actually need it](https://github.com/zalmoxisus/redux-devtools-extension#13-use-redux-devtools-extension-package-from-npm).
> Remove redux-devtools-extension

- app/classifier/tasks/drawing/index.cjsx
Group all drawing tool radio buttons as a single `drawing-tool` input field, so that they can be selected using the cursor keys.
> Group drawing tool radio buttons

- app/locales/en.js
- app/locales/it.js
- app/pages/profile/recents.jsx
- app/pages/project/project-page.cjsx
- app/router.cjsx
Add a /recents route to projects 
eg. https://recents.pfe-preview.zooniverse.org/projects/sandiegozooglobal/wildwatch-kenya/recents?env=production
Add a basic component to render subjects from the user recents API endpoint.
Allows volunteers to see their recently classified subjects and link through to Talk.
> Add recent classifications to projects

- app/pages/lab/project-details.cjsx
A few project builders have had the issue where they've added an external link for their project's subnav, and mistakenly omitted `https://` or `http://` which throws no warning or error, and instead of a sub-nav link to `https://example.com/` it is `https://www.zooniverse.org/projects/markb-panoptes/example.com/`.
This PR adds an additional sentence to the External Links instructions to hopefully reduce the instances of the issue noted.
https://external-links-instruction.pfe-preview.zooniverse.org/
Not sure if https:// and http:// should be wrapped in quotes or `<code>` tags, open to suggestion!
> clarify project external link url requirements

- app/pages/admin/project-status.jsx
- app/pages/admin/project-status.spec.js
- Adds tests for the ProjectStatus component in Admin.
- Tests are divided into a group that checks the presence of the basic page layout elements, and a group that focuses on the Workflow Settings section (where I've recently implemented changes  regarding toggling active status of default workflows)
- RFC: Not sure if testing page layout elements is necessary, or a good practice. Happy to remove if not needed/wanted.
- RFC: So far I haven't been able to write tests that simulate a user clicking the WorkflowToggle checkbox, getting the WorkflowDefaultDialog modal to open, and testing its functionality.
- Are tests of the modal functionality (eg, user clicks the 'active' toggle for a default workflow, modal opens, user clicks 'ok', and default_workflow gets removed from project) outside …
> ProjectStatus unit tests

- .github/stale.yml
Adds "lintott-trouille" issue label to probot-stale config's exemptLabels
> add lintott-trouille label to stale-bot exempt labels

- app/talk/popular-tags.jsx
Fixes #3791.
Converts the array length to a boolean, rather than just rendering array length in the HTML.
> Fix Talk popular tags for empty array

- app/pages/lab/data-dumps.cjsx
- app/partials/data-export-button.cjsx
Related backend issue: https://github.com/zooniverse/Panoptes/pull/2521
This removes aggregation dumps entirely, rather than leaving them unrequestable but still downloadable.
Since all I did was delete a few bits of code, and not write a single line of new code, I left these files as CoffeeScript. If that's unacceptable let me know.
> Remove aggregation dumps

- app/locales/en.js
- app/locales/es.js
- app/locales/it.js
- app/pages/project/project-page.cjsx
Fixes #3363 -  adds top level links to lab for project owner / collabs and the admin page for admin mode users. 
I'm not keen on the extra nav tabs but couldn't think of a nice place to put these..thoughts appreciated.
Please don't make me rewrite this so it's not coffescript, even though it made me :sadpanda:
> add lab and admin page links

- app/pages/project/project-page.cjsx
Fixes #4151 changes that show the lab link to people that don't have rights. Only show the lab links to users that possess the roles, not just if those roles exist you muppet cam.
> actually check i am the user with the roles for lab links

- app/layout/account-bar.jsx
Fixes a bug reported on email by @yshish. 
don’t show the count of the limited page_size (1), show the count of the number of unread conversations. Noting that notifications deals with this already in https://github.com/zooniverse/Panoptes-Front-End/blob/7b0427857765f6a41e477f0f8c0e3ef1764795d9/app/lib/notifications-counter.js#L59
> correctly show the count of unread conversations

- app/pages/project/index.cjsx
- app/pages/project/project-navbar.spec.js
I noticed this while working on something else using a staged project. This fixes a PropType warning being thrown when a project doesn't have an avatar. Adds test for it. 
Just a side note:
- I don't think using the Thumbnail component is really necessary for the avatar. The upload process for the avatar already limits the image to 50KB. 
- Chai API prefers the use of its `lengthOf` over `length`
https://missing-project-avatar.pfe-preview.zooniverse.org/
> Missing project avatar

- package-lock.json
- package.json
Fixes a security vulnerability in moment 2.9.0
> Upgrade moment to 2.18

- app/pages/project/classify.cjsx
This is follow up to #4061 and in support of the Intro2Astro use of projects with classroom user groups. If the user signs out, the group state should be set to false and the query param cleared.
I am a bit unsure about clearing the query param in case the student first arrives to the project not signed in and it may be difficult to remind them to make sure to use the project URL with the correct query param so they get credit for their classification. For now, I'll try it out with the query param cleared too.
This can be tested using the zootester1 account and at this staged path:
https://clear-user-group-on-logout.pfe-preview.zooniverse.org/projects/srallen086/intro2astro-hubble-testing/classify?group=1326233
I can share the account credentials in person when you're ready to test.
> Clear out user group query and state on sign out

- app/components/model-renderer.jsx
Safari was throwing a CORS error, this PR fixes that.
Fixes #4030.
Fix for https://github.com/zooniverse/Panoptes-Front-End/pull/4030 which introduced functionality for a project, but did not work on Safari.
Fixed by simply moving `crossorigin="anonymous"` to before the `src` attribute in the hidden `<img>` tag.
> Fixes #4030 incompatibility with Safari

- app/classifier/drawing-tools/polygon.cjsx
Staging branch URL: https://fix-4165.pfe-preview.zooniverse.org
Fixes #4165 .
Checks whether the polygon tool is disabled or not before setting `pointerEvents` to `painted`.
> Ignore pointer events when the polygon tool is disabled

- app/pages/lab/workflow.cjsx
Staging branch URL: https://fix-4155.pfe-preview.zooniverse.org
Fixes #4155 .
Lists all tutorials and mini-courses as radio buttons in the workflow editor, where the first button is the 'No linked tutorial' option.
> Add an option to remove tutorials and mini-courses

- app/pages/project/project-navbar.jsx
- app/pages/project/project-navbar.spec.js
Staging branch URL: https://project-nav.pfe-preview.zooniverse.org
Extract Avatar, ProjectName and ClassifyTab to functional components.
Fix some linter warnings.
> Tidy up project navigation

- app/pages/project/home/project-home.jsx
- app/pages/project/project-page.cjsx
Staging branch URL: https://project-announcement-fix.pfe-preview.zooniverse.org/projects/markb-panoptes/survey-task-test-project
Moves announcement banner below project sub-nav on project home.
> fix announcement banner on project home

- app/pages/project/project-navbar.jsx
Staging branch URL: https://project-urls-icon.pfe-preview.zooniverse.org/
Staged project with external and social project urls/links: https://project-urls-icon.pfe-preview.zooniverse.org/projects/markb-panoptes/nfnorgtest-moths
Per design discussion with @beckyrother - in project's sub-nav:
- adds external-link fa-icon to external project url links
- makes external-link fa-icon default icon for social project url links if link's icon is not in [SOCIAL_ICONS](https://github.com/zooniverse/Panoptes-Front-End/blob/master/app/lib/social-icons.js)
> refactor project urls sub-nav icon

- app/lib/handle-input-change.coffee
- app/pages/settings/email.spec.js
Staging branch URL: https://email-settings.pfe-preview.zooniverse.org/
Adds tests for the email settings page, as part of the work towards rewriting it for #3216
Specifically, this loads a mock user with Talk and project preferences, then tests that the user details, Talk preferences and project email preferences are displayed correctly.
EDIT: also tests for changes to project and Talk email preferences.
> Tests for user email settings form

- app/pages/settings/profile.spec.js
Add sinon.
Test that the clear media buttons call the clear handler with the correct arguments.
> Fix evergreen user profile tests

- app/pages/organizations/organization-container.jsx
- app/pages/organizations/organization-container.spec.js
- app/pages/organizations/organization-page.jsx
- app/pages/organizations/organization-page.spec.js
- css/organization-page.styl
Towards #2970.
Related to https://github.com/zooniverse/pfe-lab/pull/137.
If categories added to an organization, shows category buttons on organization landing.
If no categories on an organization, organization landing shows no category buttons.
On initial load the "All" button should be active, then when a category is clicked the projects should be filtered by the category selected.
https://org-categories.pfe-preview.zooniverse.org/organizations/markb-panoptes/nfnorgtest
> add categories to organization landing

- app/pages/project/home/index.jsx
Staging branch URL: https://fix-navbar-links.pfe-preview.zooniverse.org/
Pass `user` and `projectRoles` to the home page component. That's needed Because the project homepage navigation bar is rendered separately from the other page, which tbh isn't great.
> Fix lab and recent links

- app/locales/en.js
- app/pages/project/home/index.jsx
- app/pages/project/home/project-home.jsx
- app/pages/project/index.cjsx
- app/pages/project/project-navbar.jsx
- app/pages/project/project-page.cjsx
- css/project-page.styl
Closes #3968.
If project linked to organization with `listed: true`, adds project sub-nav link to organization, display organization title above project description.
- https://project-landing-org-links.pfe-preview.zooniverse.org/projects/markb-panoptes/nfnorgtest-moths
- (with announcement banner) https://project-landing-org-links.pfe-preview.zooniverse.org/projects/markb-panoptes/nfnorgtest-wedigflplants
> add project sub-nav link to org, display org title above description

- app/pages/settings/email.jsx
- app/pages/settings/email.spec.js
Extracts components for Talk preferences, project preferences and pagination.
Fixes array sort being called more than once for Talk preferences.
Adds a footer to the project listing table.
Fixes page number being passed as a string, instead of a number, in the page change event handler.
> Extract functional components

- app/talk/inbox-conversation.cjsx
I know this has been discussed before, but it still bugs me that this button is labelled "archive" when it does nothing of the sort. "Archive" implies that there is an actual archive where you can find old messages and refer back to them, but in this case messages are gone forever unless the other user happens to reply again.
In my opinion "delete" is an accurate description of what this does. I'd also settle for "remove" or something along those lines.
> Rename "Archive" to "Delete"

- app/classifier/annotation-renderer/index.jsx
- app/classifier/annotation-renderer/svg.jsx
- css/frame-annotator.styl
Staging branch URL: https://audio-drawing-task.pfe-preview.zooniverse.org
Add the SVG marking renderer for annotations on audio subjects.
Make the SVG background transparent for audio subjects.
> Allow drawing on audio subjects

- app/classifier/tasks/translations.jsx
- app/classifier/tasks/translations.spec.js
https://update-task-translations.pfe-preview.zooniverse.org
Workflow translations are now flat dictionaries of the form
```
{
display_name: 'A test workflow',
'tasks.survey.choices.ar.label': 'Translated Armadillo',
'tasks.survey.questions.ho.answers.one.label': 'Translated 1'
}
```
This PR updates the tests to reflect the new format, and updates the task translation component to extract task strings properly from the translations object.
> Update task translations

- app/pages/project/index.cjsx
- app/pages/project/index.spec.js
- app/pages/project/project-page.cjsx
- app/router.cjsx
Staging URL: https://project-page-controller.pfe-preview.zooniverse.org
Adds tests for some workflow selection cases in the project page controller.
Adds 'tester' to the roles that are allowed to load inactive workflows.
Fixes #4180
> Project page controller tests

- app/pages/admin/project-status.jsx
- app/pages/admin/project-status.spec.js
- css/admin-page.styl
Staging branch URL: https://project-status-admin.pfe-preview.zooniverse.org/
Fixes @mrniaboc and @camallen eyeballing me as soon as I entered the office this morning.
Adds some radio buttons to the project admin page so an admin can set a project's state to either live (`''`), paused (`'paused'`) or finished (`'finished'`)
I found some other states on projects on the staging server, e.g. `'live'` and `'development'`. Should these be supported as well @camallen?
> Add project state radio buttons to admin

- app/pages/organizations/organization-container.jsx
- app/pages/organizations/organization-page.jsx
- app/pages/organizations/organization-page.spec.js
Staging branch URLs:
- org with projects (all have avatars): https://org-projects-request-refactor.pfe-preview.zooniverse.org/organizations/markb-panoptes/nfnorgtest
- org with projects (one does not have an avatar): https://org-projects-request-refactor.pfe-preview.zooniverse.org/organizations/markb-panoptes/mborgtest
- org with no projects: https://org-projects-request-refactor.pfe-preview.zooniverse.org/organizations/markb-panoptes/noavnoback
Refactors organization affiliated projects request from project `card: true` to full project resource, with include for projects' avatars.
> Org projects request refactor

- app/locales/en.js
- app/pages/organizations/organization-container.jsx
- app/pages/organizations/organization-page.jsx
- app/pages/organizations/organization-page.spec.js
- css/organization-page.styl
Staging branch URLs:
- with projects with quotes: https://org-researcher-quote.pfe-preview.zooniverse.org/organizations/markb-panoptes/nfnorgtest
- without projects with quotes: https://org-researcher-quote.pfe-preview.zooniverse.org/organizations/markb-panoptes/mborgtest
Towards #4089.
Add researcher quote section to organization landing page. Randomly selects organization affiliated project with `.researcher_quote` attribute defined, or doesn't render section. Researcher quote displayed similarly to project landing page.
Open Items
> add organization researcher quote section

- app/locales/en.js
- app/locales/es.js
- app/locales/it.js
- app/locales/nl.js
- app/pages/project/about/about-nav.jsx
- app/pages/project/about/index.jsx
- app/pages/project/index.cjsx
- app/redux/ducks/translations.js
Staging branch URL: https://translations-project-pages.pfe-preview.zooniverse.org/
Loads project page translations after pages have loaded. Connects the project about page container to the redux store and loads in translations, where available, for page content. Should fall back to using existing page content for projects that are not using translations.
Also fixes a small bug where project pages were being requested again from the API, rather than using the prop passed down from the project page container.
> Add translations for project page content

- app/pages/project/field-guide.cjsx
- app/pages/project/index.cjsx
- app/pages/project/potential-field-guide.cjsx
- app/redux/ducks/translations.js
Staging branch URL: https://translations-fieldguides.pfe-preview.zooniverse.org/
Connect up field guides to the translations API, using the classifier's Translations component.
Render field guide items from the translations prop.
> Add field guide translations

- app/partials/sign-in-form.cjsx
Staging branch URL: https://email-address-caps.pfe-preview.zooniverse.org/
Makes "email address" lower case on sign in form.
> Fix caps in sign in form

- app/pages/organizations/organization-container.jsx
Staging branch URL: https://org-projects-in-beta.pfe-preview.zooniverse.org/organizations/markb-panoptes/nfnorgtest
**IMPORTANT** - see [Panoptes issue 2573](https://github.com/zooniverse/Panoptes/issues/2573) and PFE issue #3977 for additional details.
This PR changes the organization project query from `launch_approved` to `beta_approved`,  `: true`.
This PR will allow Snapshot Serengeti to beta test it's projects as well as organization. 
However, this change will likely need to be reverted before an organization is fully launched and featured on zooniverse.org/projects or equivalent, as I believe our intent is to only show `launch_approved` projects in a fully launched organization. 
Mentioning @trouille, @camallen.
> edit org project query to beta_approved

- app/pages/project/about/index.jsx
- app/pages/project/about/index.spec.js
Staging branch URL: https://empty-project-pages.pfe-preview.zooniverse.org
Fixes a bug where projects stop working if you navigate to a page that hasn't yet been created in the project builder.
Defaults a project page to an empty object, if no matching page is found in Panoptes.
Adds some tests that render the `AboutProject` component for a project with no pages.
Cleans up linter warnings and defines sensible default props for `AboutProject`.
> Fix fatal project page bug

- app/classifier/tasks/combo/index.cjsx
- app/classifier/tasks/combo/summary.jsx
Staging branch URL: https://fix-4195.pfe-preview.zooniverse.org/projects/markb-panoptes/test-project-3-mb/classify?reload=0&workflow=3120
Fixes #4195.
Add TaskTranslations component around TaskComponent in combo task render.
> add TaskTranslations to combo task render

- app/pages/settings/email.spec.js
Set preferences in component state rather than breaking the talk client by overriding `talkClient.type()`.
Required for #4233 to work.
> Fix email settings tests

- app/pages/project/home/index.jsx
- app/pages/project/index.cjsx
- app/pages/project/project-page.jsx
This PR fixes three mostly minor (mostly non-breaking) warnings/errors when using the PFE Classifier. These warnings/errors mostly appear in the console and is mostly invisible to users (except for the last one).
**Issue 1:** Projects with no Field Guide have a console error saying, "Cannot read property 'id' of undefined"
Analysis: This line - `actions.translations.load('field_guide', guide.id, translations.locale)` doesn't confirm the existence of `guide` before calling `guide.id`
Solution: `guide?.id`
Impact: minimal.
Testing:
- On production's [WildCam Darien](https://fix-warnings.pfe-preview.zooniverse.org/projects/wildcam/wildcam-darien/classify?env=production) (which does not have a Field Guide), the warning should not appear.
- On production's [Elephant …
> Fix three (mostly minor) warnings

- app/pages/project/project-page.jsx
- app/pages/project/project-page.spec.js
Closes #4228 - Ensure consistent sugar project channel subscriptions on notifications.zooniverse.org. 
Lifecycle methods:
1. Mount: subscribe to project page channel
0. Unmount unsubscribe from the project channel
0. On new props unsubscribe the previous project channel and subscribe on the new project channel.
Staging branch URL: https://sugar-section-notification.pfe-preview.zooniverse.org/
> Ensure consistent sugar project channel subscriptions for project pages

- app/pages/settings/email.spec.js
Stub out resource methods so that the tests don't make API requests.
Clean up the spec file a bit.
Fixes # .
> Mock Panoptes resources in email settings tests

- app/pages/project/index.spec.js
- app/pages/settings/email.spec.js
Mock Panoptes resources to stub out API method calls.
Stub API client requests during the tests.
Clean up the test code.
Fixes various API warnings that are echoed to the console when the tests run.
> Fix warnings from workflow tests

- app/pages/settings/email.spec.js
Missed in #4253. This should fix the `Error: not allowed to index this SubscriptionPreference` warning that appears when running the email settings tests.
> Stub Talk requests during email settings tests

- app/pages/lab/subject-set.cjsx
Staging branch URL: https://fix-4239.pfe-preview.zooniverse.org/
Fixes #4239  .
The issue above concerns the wiggling "you should sign-in" prompt from appearing in the project builder's subject preview. The issue was that we were reusing the `SubjectViewer` component for the preview without passing in the user prop, so the SV had no idea if a user was present or not.
> Fix Sign-in Prompt from Subject Preview

- app/collections/collections-manager.jsx
- app/collections/collections-manager.spec.js
- app/collections/show-list.cjsx
- app/collections/show.jsx
Staging branch URL: https://fix-4070.pfe-preview.zooniverse.org/
Fixes #4070  .
The linked issue concerns the inability to add a subject to an empty collections set. This branch solves the issue, however, there seems to also be a caching issue affecting how the collections page is updated. This seemed to be a bigger issue (which I saved for another PR), but I can look into it more with this PR if desired. 
The additional bug mentioned above appears to have already been documented as #4039.
> Allow Subject to Be Added to Empty Collection

- app/classifier/drawing-tools/root.cjsx
Staging branch URL: https://subtask-translations.pfe-preview.zooniverse.org
Quick patch to fix the Milky Way Project (and others, presumably) as reported on Talk: https://www.zooniverse.org/talk/17/512942?comment=853156
Drawing subtasks were broken in #4200.
> Add missing translations prop to drawing subtasks

- app/pages/settings/email.jsx
Staging branch URL: https://email-proj-prefs.pfe-preview.zooniverse.org/
Fixes #4263 .
It displays project names keyed with `projectPref.links.project`
> Match project pref and project correctly

- app/pages/settings/email.spec.js
- css/home-page.styl
…ck for nicer keyboard focus. Fixes #4105
Fixes #4105 .
> Keyboard focus now working/looking better on home-page for app store icons and project cards

- app/classifier/annotation-renderer/svg.jsx
- app/classifier/drawing-tools/delete-button.cjsx
- app/classifier/drawing-tools/drag-handle.cjsx
- app/classifier/tasks/drawing/markings-renderer.cjsx
- app/components/subject-viewer.cjsx
Staging branch URL: https://fix-4266.pfe-preview.zooniverse.org/
Fixes #4266 .
Tries to set sensible defaults for non-finite image scaling, and holds off rendering delete buttons and drag handles until the screen transformation matrix is defined. Also disables the flipbook buttons until the subject has loaded.
> Fix broken SVG rendering in Firefox

- app/classifier/tasks/next-task-selector.cjsx
Staging branch URL: https://next-task-reword.pfe-preview.zooniverse.org/
It might not be clear what "End of classification" means in the "next task" option in the workflow editor -- some people might interpret that as meaning the user will exit the classification page. This changes it to say "next subject" instead.
> Change "End of classification" to "Next subject"

- app/locales/en.js
- app/pages/project/home/home-workflow-button.jsx
- app/pages/project/home/home-workflow-button.spec.js
- app/pages/project/home/home-workflow-buttons.jsx
- app/pages/project/home/home-workflow-buttons.spec.js
- app/pages/project/home/index.jsx
- app/pages/project/home/project-home.jsx
- app/pages/project/home/talk-status.jsx
- app/pages/project/index.cjsx
- css/project-page.styl
Fixes a Gravity Spy bug found while reviewing another PR. When on the Gravity Spy home page, you should see the workflow buttons, but if you click to log out, the buttons aren't correctly hidden.
I took a pass at refactoring to fix this bug, make sure the user prop is used consistently over context, setup translations, added some new tests, refactored some of the CSS classes to be more BEM-like, and also consulted with @beckyrother to get rid of the inconsistent behavior of Get Started button styled link. 
Can be manually tested by going to the staging URL for Gravity Spy:
https://project-workflow-buttons-refactor.pfe-preview.zooniverse.org/projects/zooniverse/gravity-spy?env=production @beckyrother is the Get Started header above the workflow buttons ok?
If you're signed in, you should …
> Project workflow buttons refactor

- css/home-page.styl
Staging branch URL: https://landing-page-width.pfe-preview.zooniverse.org/
Fixes #4262  .
This was a tricky little CSS bug to figure out. Looks like there were some items in the social section that were keeping the page from shrinking.
> Adjust Width of Items in Social Section

- app/pages/project/classify.cjsx
Staging branch URL: https://rename-user-group-metadata.pfe-preview.zooniverse.org/
Requested in zooniverse/education-api#86. This updates the metadata property name that is added to the classification if a user is classifying as a part of a user group. I2A classrooms use this feature. In debugging the classification counts done by the education api, we found that Panoptes updates the classification metadata with an array of user group ids that the user is a part of ([see here](https://github.com/zooniverse/Panoptes/blob/d77b16687bf8be1cebe91468e81f7a0683430b11/lib/classification_lifecycle.rb#L117-L120)). This is used by the education api for the Wildcam projects, however, with the I2A projects we want to know specifically which user group the user classified as. This renaming clarifies …
> Renamed user_group to selected_user_group_id

- app/classifier/drawing-tools/root.cjsx
- app/classifier/tasks/drawing/markings-renderer.cjsx
Staging branch URL: https://subtask-translations.pfe-preview.zooniverse.org/
Connects up drawing subtasks to the translations API, by wrapping the task component in a translations wrapper.
> Add task translations to drawing subtasks

- app/classifier/index.cjsx
Staging branch URL: https://fix-tutorial-translations.pfe-preview.zooniverse.org
Required `store` arg was missing from `Tutorial.startIfNecessary` in `componentWillReceiveProps` for the classifier.
> Add missing store arg to tutorial start

- app/classifier/classifier.jsx
- app/classifier/task-nav.jsx
- app/classifier/task.jsx
- app/classifier/tasks/crop/initializer.cjsx
- app/classifier/tasks/drawing/marking-initializer.cjsx
- app/classifier/tasks/drawing/markings-renderer.cjsx
- app/classifier/tasks/highlighter/label-editor.jsx
- app/classifier/tasks/survey/annotation-view.cjsx
Staging branch URL: https://classification-update.pfe-preview.zooniverse.org/
This builds on #4272 (which needs to be merged first.)
Removes the classification change listener from the classifier. Tasks are updated to modify annotations via the `onChange` callback, instead of calling `classification.update('annotations')`.
> Remove classification change listener

- app/locales/en.js
- app/locales/es.js
- app/locales/it.js
- app/locales/nl.js
- app/pages/project/home/home-workflow-buttons.jsx
- app/pages/project/home/home-workflow-buttons.spec.js
- app/pages/project/home/project-home.jsx
- app/pages/project/home/project-home.spec.js
Staging branch URL: https://fix-redirect-home-button.pfe-preview.zooniverse.org/
Fixes an issue found while debugging Anti-slavery Manuscripts. If the project has a redirect, then only the button for that redirect should be visible on its PFE home page. I also added unit tests for all the conditionals for this component and fixed a missing translation.
https://fix-redirect-home-button.pfe-preview.zooniverse.org/projects/bostonpubliclibrary/anti-slavery-manuscripts/?env=production
> Only show redirect button for projects with redirect

- app/talk/active-users.spec.js
Fixes a broken stub in the ActiveUsers tests. This got merged after the sinon version update and was still using the stub API.
> Fix broken stub in ActiveUsers spec

- app/classifier/classifier.jsx
- app/classifier/task-nav.jsx
- app/classifier/task.jsx
- app/classifier/tasks/crop/initializer.cjsx
- app/classifier/tasks/drawing/marking-initializer.cjsx
- app/classifier/tasks/drawing/markings-renderer.cjsx
- app/classifier/tasks/highlighter/label-editor.jsx
- app/classifier/tasks/survey/annotation-view.cjsx
Reverts zooniverse/Panoptes-Front-End#4277
This didn't handle shortcut tasks properly and thus broke some existing workflows, notably project plumage as reported here https://www.zooniverse.org/talk/18/522232?comment=867269
> Revert "Remove classification change listener"

- app/pages/project/home/project-home.jsx
- css/project-page.styl
Staging branch URL: https://external-link-icon.pfe-preview.zooniverse.org/
After merging #4285, it was decided that an external link icon would be a better solution that a URL.
> Use External Link Icon on Redirect Button

- app/pages/settings/email.spec.js
Mock resources in local vars, not globals.
Check component state for expected state changes.
Tidy up user.get() function stub.
> Cleanup email settings tests

- app/collections/collaborators.spec.js
- app/collections/collections-create-form.spec.js
- app/collections/collections-manager.spec.js
- app/collections/favorites-button.spec.js
- app/collections/settings.spec.js
- app/components/filmstrip.spec.js
- app/pages/admin/project-status.spec.js
- app/pages/project/home/home-workflow-button.spec.js
- app/pages/project/project-page.spec.js
- app/pages/settings/email.spec.js
- app/pages/settings/profile.spec.js
- app/talk/discussion-comment.spec.js
This contains work necessary to [get the mocha `--watch` flag working](https://github.com/zooniverse/Panoptes-Front-End/pull/4233).
Clean up spies and stubs after the first test run.
> Tear down tests properly

- package.json
Adds a test script which watches .js, .jsx, .coffee and .cjsx files for changes.
Supersedes #4233.
> Add 'test-and-watch' as an npm script

- app/classifier/drawing-tools/root.cjsx
- app/classifier/mini-course.cjsx
- app/classifier/tutorial.cjsx
- app/pages/project/potential-field-guide.cjsx
Staging branch URL: https://redux-provider.pfe-preview.zooniverse.org/
Alternative to #4280.
Passes the Redux store to field guides, mini courses and tutorials by wrapping them in a `Provider` that takes the current store as a prop.
> Use Provider to pass the Redux store to modals

- app/pages/project/workflow-selection.jsx
- app/pages/project/workflow-selection.spec.js
Staging branch URL: https://workflow-selection.pfe-preview.zooniverse.org
Switches the workflow selection tests from shallow to full DOM rendering, which should allow us to test the full component lifecycle. Also fixes a small bug in workflow selection, which wasn't caught by shallow rendering.
> Workflow selection

- app/pages/project/workflow-selection.spec.js
Fixes infinite loop in workflow selection tests. Since the workflow selection tests were updated to use mount instead of shallow, the spy for `getWorkflow` I think was actually attempting to do a network request for the mocked workflow ids. Of course this would not result in a successful response, so the code is written to attempt to select another random workflow. That will fail, hence an infinite loop. I updated the spy to be a stub instead that calls a fake anonymous function.
> Use stub for getWorkflow

- package-lock.json
- package.json
Staging branch URL: https://upgrade-api-client.pfe-preview.zooniverse.org
Fixes #4179.
Fixes bearer token expiration problems with the Talk client.
> Upgrade Panoptes client to 2.8.1

- app/pages/admin/user-settings.jsx
- app/pages/admin/user-settings/details.jsx
- app/pages/admin/user-settings/details.spec.js
Staging branch URL: https://user-admin-details.pfe-preview.zooniverse.org/
This displays a few additional details about the user that's being editted. Particularly, we need to verify their email address for delete requests.
> Add details about editted user to admin page

- app/pages/lab/workflows.jsx
- app/pages/lab/workflows.spec.js
Staging branch URL: https://fix-4303.pfe-preview.zooniverse.org/
Fixes #4303, counts toward #4221. 
This is the first step to improve the workflow page. Moving the workflow settings from their current place (the visibility page) to the workflows seems a good idea, but I'll do that in a separate PR.
Changes:
1. Display workflow completeness.
2. Add note about making workflows inactive.
> Improve workflows page

- app/classifier/classifier.jsx
- app/classifier/task-nav.jsx
- app/features/feedback/classifier/components/feedback-modal.jsx
- css/feedback.styl
Staging branch URL: https://modal-feedback.pfe-preview.zooniverse.org/
Fixes some of the points raised in #4320.
Adds autofocus behaviour to the feedback popup, and traps focus until the modal is closed. Changes the order in which feedback is checked, so that feedback can steal focus from the task navigation buttons when it opens.
Also adds some basic styling to the OK button and restricts the height of large subjects to around 60% of the viewport height.
> Modal feedback: keyboard focus management and styling

- app/classifier/classifier.jsx
- app/features/feedback/shared/strategies/radial/reducer.js
Staging branch URL: https://modal-feedback.pfe-preview.zooniverse.org/
Fixes #4327 
Fixes a bug noticed by @mcbouslog where feedback shows twice if triggered on the last task of a workflow.
Remove the call to `checkForFeedback()` when a classification is submitted.
Catch undefined variables in the radial reducer and `updateFeedback()` and handle them.
> Modal feedback: only trigger feedback once

- css/survey-task.styl
Staging branch URL: https://survey-task-button-text-align.pfe-preview.zooniverse.org/
- to project with issue: https://survey-task-button-text-align.pfe-preview.zooniverse.org/projects/amyrobey996/numbat-discovery?env=production
Fixes https://www.zooniverse.org/projects/amyrobey996/numbat-discovery.
- add `text-align: left` to `survey-task-chooser-choice-button` class
> add text-align left to survey task button

- app/pages/admin/project-status/experimental-features.jsx
- app/pages/lab/workflow.cjsx
Staging branch URL: https://fix-4240.pfe-preview.zooniverse.org/
Fixes #4240.
Makes `hide classification summaries` public.
> Make hide classification summaries public

- app/pages/organization/organization-container.jsx
Staging branch URL: https://org-projects-launch-approved.pfe-preview.zooniverse.org/
Reverts #4227, if reverting that PR would be preferable please do.
The org landing project query was temporarily changed to filter by `beta_approved` to allow Snapshot Safari to beta test with beta_approved (but not launch approved) projects. Snapshot Safari is now ready to launch and those projects are now launch approved, so the org landing should be filtering projects by launch approved as always intended.
> change org landing default project query to launch approved

- package-lock.json
- package.json
Staging branch URL:https://drag-reorderable.pfe-preview.zooniverse.org
Upgrades drag-reorderable to remove React.PropTypes.
> Upgrade drag-reorderable to 0.2

- app/pages/project/index.cjsx
- app/pages/project/project-navbar.jsx
Staging branch URL: https://beta-approved.pfe-preview.zooniverse.org
Checks `project.launch_approved` before applying beta review styles and wording to a project. Should make launching a project a little easier, as suggested by @mcbouslog.
> Hide beta styles for launch approved projects

- app/pages/project/index.cjsx
Staging branch URL: https://project-loading.pfe-preview.zooniverse.org
Fixes a race condition where workflow selection would fail if the component mounted before project preferences had loaded.
Adds a boolean flag to the project container, to indicate when project resources have loaded and the page is safe to render.
> Add a ready flag to the project container

- package-lock.json
- package.json
Staging branch URL: https://modal-form.pfe-preview.zooniverse.org
Upgrades `modal-form` to remove React.PropTypes.
> Upgrade modal-form to 2.5

- app/classifier/tasks/survey/choice.jsx
- app/classifier/tasks/survey/choice.spec.js
Staging branch URL: https://survey-radio-toggle.pfe-preview.zooniverse.org
Fixes a bug reported by Snapshot Wisconsin: https://www.zooniverse.org/talk/17/535525
Adds handlers to the survey choice radio buttons so that a selected answer can be cleared on click, space or backspace.
Removes some old code which cleared the current answer but was never actually called.
Removes named refs from the `Choice` component.
> Allow survey tasks to clear radio button answers

- app/components/svg-image.jsx
Staging branch URL: https://fix-color-invert.pfe-preview.zooniverse.org/
The previous version of color inversion was done in `linearRGB` space
and produced the incorrect results (inverted image was too white/"blown
out").  This forces the filter to be calculated in the correct `sRGB`
color space.  This change is required for Galaxy Zoo to move overt to
PFE.
Original method:
New method:
> Use correct color space for image inversion

- app/pages/project/index.cjsx
- app/pages/project/index.spec.js
Staging branch URL: https://project-controller-tests.pfe-preview.zooniverse.org
Updates the project page controller tests to spy directly on calls to `fetchProjectData`. For this to work, you have to export the bare component config object, then wrap it in `createReactClass` after you've bound your wrapped stubs and spies to it.
> Update project controller test spies

- app/components/loading-indicator.jsx
- app/components/media-card.jsx
Staging branch URL: https://remove-proptypes.pfe-preview.zooniverse.org
Removes a couple of instances of `React.PropTypes` that had crept back in to the Media Card and Loading Indicator.
> Remove React.PropTypes

- app/classifier/tasks/single/index.jsx
Staging branch URL: https://fix-4351.pfe-preview.zooniverse.org/
Fixes #4351 .
This PR makes the keyboard work as expected for the radio buttons. A random number is assigned to the task as a `_key` so this still works when multiple questions are in a combo task.
A test workflow with two single question tasks in combo: https://fix-4351.pfe-preview.zooniverse.org/projects/cmk24/test-project-2/classify?reload=0&workflow=3161
> Add name to single question's input element

- app/pages/lab/mobile/mobile-section-container.jsx
- app/pages/lab/mobile/mobile-section-container.spec.js
Staging branch URL: https://workflow-mobile-friendly.pfe-preview.zooniverse.org/
Related to https://github.com/zooniverse/mobile/issues/151.
Adds functionality so workflow editor mobile section edits `workflow.mobile_friendly` boolean similarly to `workflow.configuration.swipe_enabled`. This will allow API request in mobile app for projects' workflows to be filtered by `mobile_friendly`.
> edit workflow.mobile_friendly with workflow.configuration.swipe_enabled

- app/pages/settings/email.jsx
- app/pages/settings/email.spec.js
Staging branch URL: https://fix-project-email.pfe-preview.zooniverse.org/
Fixes #4263.
Previous code relied on preferences and projects having the same length and order, which will not be the case for real arrays returned from Panoptes.
Updates the email settings tests to check the case where preferences and projects are of different lengths, and have a different order. Updates the email settings component to pass the tests.
> Update project email settings correctly

- app/locales/en.js
- app/pages/settings/email.jsx
Staging branch URL: https://layout-email-settings.pfe-preview.zooniverse.org/settings/email
Fixes #4220.
From the issue:
>Move the "Get email updates from the Projects you classify on" tick box option to be directly above the "Project email preferences" section so people realise they can choose to get emails from specific projects and not from others.
>Remove the 'Project' header from the 'Project email preferences section'. It's in the wrong place and isn't really useful.
> Change a couple of headers in the email settings layout

- app/pages/project/finished-banner.jsx
Staging branch URL: https://remove-unused-import.pfe-preview.zooniverse.org/
- remove unused getWorkflowsInOrder import
- remove unused projectIsComplete prop
> Remove unused import and prop

- app/talk/lib/display-roles.cjsx
Staging branch URL: https://dedupe-talk-roles.pfe-preview.zooniverse.org
Fixes #3898 
Dedupes the array of display names, not the original roles array, before listing someone's Talk roles.
https://lodash.com/docs/4.17.5#uniqBy
> Replace uniq with uniqBy for Talk roles

- app/pages/lab/apply-for-beta-form.jsx
- app/pages/lab/apply-for-beta-form.spec.js
- app/pages/lab/visibility.cjsx
- app/pages/lab/workflows-container.jsx
Staging branch URL: https://visibility-page.pfe-preview.zooniverse.org/
Fixes #4360 .
Get active workflows and subject count from project instead of workflows, which isn't available anymore.
I'm not sure this is working properly. I'm seeing some strange behaviour when I pass from no active workflows to even just one active. When I check the visibility page the checkbox takes ages to update or doesn't update at all, even if the project does have `active_workflows`.
> Use project instead of workflows in Apply For Beta form

- app/pages/project/project-page.jsx
- app/pages/project/project-page.spec.js
Staging branch URL: https://home-field-guide.pfe-preview.zooniverse.org/
Fixes #4372 .
Hide the field guide if the project's only child component is ProjectHomeContainer.
Compares the component functions directly, since the production version is an anonymous function and has no name.
> Hide the field guide on the project home page

- app/pages/project/components/ProjectNavbar/ProjectNavbar.jsx
- app/pages/project/components/ProjectNavbar/ProjectNavbarContainer.jsx
- app/pages/project/components/ProjectNavbar/components/NavLink/NavLink.jsx
- app/pages/project/components/ProjectNavbar/components/NavLink/NavLink.spec.js
- app/pages/project/components/ProjectNavbar/components/ProjectNavbarWide/ProjectNavbarWide.jsx
- app/pages/project/components/ProjectNavbar/helpers/getProjectLinks.js
- app/pages/project/components/ProjectNavbar/helpers/getProjectLinks.spec.js
- app/pages/project/components/ProjectNavbar/testHelpers/helperFunctions.js
Staging branch URL: https://fix-breakpoint-calculation.pfe-preview.zooniverse.org/
Fixes projects that are already collapsed into the drop down menu because of number of links to switch to the flex column layout for mobile sized screens. I also changed the classify link to use a disabled placeholder while the workflow is loading rather than appear later. This was causing some odd blips between layout styles.
Project to test this with: https://fix-breakpoint-calculation.pfe-preview.zooniverse.org/projects/meredithspalmer/snapshot-grumeti?env=production
> Fix breakpoint calculation

- package-lock.json
- package.json
Staging branch URL: https://upgrade-markdownz.pfe-preview.zooniverse.org
Fixes findDOMNode errors when Markdown is unmounted.
> upgrade markdownz to 7.4.2

- app/pages/lab/help/example.cjsx
- app/pages/lab/mobile/mobile-section-container.jsx
Staging branch URL: https://remove-proptypes.pfe-preview.zooniverse.org
Removes a couple more instances of `React.createClass` and `React.PropTypes` that have crept back in.
> Remove React.createClass and React.PropTypes

- app/talk/inbox-conversation.cjsx
Otherwise all you can see is the display name, making it easy to
impersonate another user.
Staging branch URL: https://talk-pm-login-name.pfe-preview.zooniverse.org
> Show login names next to display names in private messages

- app/pages/project/components/ProjectNavbar/ProjectNavbarContainer.jsx
Staging branch URL: https://fix-org-nav-link.pfe-preview.zooniverse.org/projects/markb-panoptes/calbug
Fixes "Each of the Snapshot Safari projects has a link in the project navigation that says Snapshot Safari but opens the project home in a new tab. https://www.zooniverse.org/projects/shuebner729/snapshot-apnr"
org nav link prop of `to` was set when I think should be `url` similar to other nav links
> edit project nav org link

- app/pages/project/project-page.spec.js
avoid the "Attempted to wrap subscribeTo which is already wrapped" error when running `npm run test-and-watch`
> setup the spies in before functions

- test/mocha.opts
See https://github.com/mochajs/mocha/wiki/compilers-deprecation
> Replace mocha --compilers with --require

- app/talk/board.cjsx
- app/talk/discussion.cjsx
Note that this doesn't include the project name in the title for project
Talk pages because otherwise the title will be kind of long.
Staging branch URL: https://talk-title.pfe-preview.zooniverse.org/talk
> Put Talk discussion and board titles in the page title

- app/locales/en.js
- app/locales/es.js
- app/locales/nl.js
- app/pages/reset-password/new-password-form.jsx
- app/pages/reset-password/new-password-form.spec.js
- app/pages/reset-password/reset-password.jsx
Staging branch URL:  https://email-reset-errors.pfe-preview.zooniverse.org/reset-password?reset_password_token=H6GtX
Fixes #4390 and lots of email reports of problems with email password resets, specifically no API error reports, no length checking or password match checks. 
This PR adds:
1. the API failure messages to the form
0. HTML5 input password length validation before form submission
0. Checks the passwords match before attempting to contact the API.
> add email password reset form errors

- app/classifier/tasks/dropdown/index.cjsx
- app/classifier/tasks/dropdown/index.spec.js
Staging branch URL: https://dropdown-default-update-fix.pfe-preview.zooniverse.org/projects/markb-panoptes/test-project-1-mb/classify?reload=1&workflow=3165
Closes #4401. 
- check and if annotations not present, set default annotations (`{ option: false, value: null }`) on component update
> Add dropdown task default annotations on update

- app/pages/lab/social-links-editor.jsx
Staging branch URL: https://fix-wordpress.pfe-preview.zooniverse.org/
Fixes #4406 
This is a quick fix that accounts for social websites that have the route coming before the site name. I tried to make it as flexible as possible, in case we add more social websites with URL paths similar to Wordpress.
> Handle Social Sites with Preceding Routes

- app/classifier/classifier.jsx
Staging branch URL: https://fix-4410.pfe-preview.zooniverse.org
Fixes #4410 .
Check the default annotation for feedback after loading a new subject.
Wait for `state.annotations` to change before updating feedback rules.
> Update feedback after annotations

- app/pages/project/home/project-home.jsx
Staging branch URL: https://talk-preview-images.pfe-preview.zooniverse.org
Fixes a problem mentioned on Talk, where previews don't display for audio projects, even if the subjects do have linked images. https://www.zooniverse.org/talk/18/565262
Use the first image listed in a subject's locations for the Talk preview thumbnail. Fall back to displaying video, for video subjects, if no image is available.
> Fix Talk preview images on project home

- app/pages/project/components/ProjectNavbar/components/ProjectNavbarNarrow/NarrowMenu.jsx
Staging branch URL: https://fix-4397.pfe-preview.zooniverse.org/
Fixes #4397
Changes the z-index so the narrow menu used on small resolutions or screen sizes appears correctly in Edge.
> Change z-index to work in Edge

- app/classifier/index.cjsx
- app/pages/project/classify.cjsx
Staging branch URL: https://classifier-export.pfe-preview.zooniverse.org
Fixes my earlier attempt to export the wrapped and unwrapped components together.
Export the connected component for the project classify page.
Export the bare component for the dev classifier.
> Fix classifier exports

- app/features/feedback/classifier/components/feedback-modal.jsx
- css/feedback.styl
Moves the OK button to the bottom right of the feedback modal, as per #4430.
> Align feedback OK button to the bottom right of modal

- app/classifier/classifier.jsx
- app/classifier/task.jsx
Staging branch URL: https://update-annotations.pfe-preview.zooniverse.org
Use `annotation.task` to determine which annotation to update when changing a classification, rather than automatically using the last annotation in the annotations array.
First step towards allowing the classifier to operate on more than one annotation at a time, when making a classification. That would allow us to deprecate combo task annotations, in favour of each task being responsible for updating its own annotation in the annotations array.
> Use task key to update annotations

- app/classifier/index.cjsx
- app/pages/project/classify.cjsx
- app/pages/project/index.cjsx
- app/pages/project/project-page.jsx
This is an ugly hack, but I think it'll work for checking if the user has updated project preferences. This is related to #4428, but I won't tag for closing since I don't think this should be the long term solution.
@amyrebecca could you check to see if this works for Snapshot WI's workflow promotion project?
> Add UPP request after every 10 classifications

- app/features/feedback/shared/strategies/radial/create-rule.js
Staging branch URL: https://fix-multi-step-workflow.pfe-preview.zooniverse.org/
Staging project: https://fix-multi-step-workflow.pfe-preview.zooniverse.org//projects/rogerhutchings/feedback-test
Adds in a default value for the feedback `hideSubjectViewer` property, since it was breaking when not actively set on the workflow.
> Add default value for hideSubjectViewer

- app/classifier/classifier.jsx
Staging branch URL: https://persist-workflow-history.pfe-preview.zooniverse.org/
Fixes #4464.
Workflow history (introduced in #4450) tracks which tasks you've done for the current subject, but isn't persisted outside the classifier. This maps annotations to workflow history when the classifier loads, so that the current task persists even if the classifier unmounts. This is a quick patch for #4464 but it should work.
> Classifier: initialise workflow history from annotations

- app/pages/project/classify.jsx
Staging branch URL: https://remove-simulate-failure.pfe-preview.zooniverse.org/
The prop was literally never read.
> Remove simulateSaveFailure

- app/classifier/tasks/drawing/markings-renderer.cjsx
- app/pages/dev-classifier/index.cjsx
- app/pages/dev-classifier/mock-data.coffee
Fixes #4094.
Added check so that drawing sub-tasks clone in multiple frames when multi_image_clone_markers enabled and separate frames disabled
There are cases not covered so far which might be useful - i.e. switching between flipbook and separate frames enabled and cloning markers enabled. This would require threading the flag in the state of `SubjectViewer` down to MarkingsRenderer.
> Correctly clone sub-tasks when multi_image_clone_markers enabled

- app/pages/project/components/ProjectNavbar/components/Background/Background.jsx
Staging branch URL: https://increase-contrast-project-navbar.pfe-preview.zooniverse.org/
This in response to some volunteers reporting eye strain with the new project navbar that has the project background blurred behind it. @beckyrother and I are looking for a possible remedy. We're hoping an increase in contrast will help. 
IE does not support the blur filter nor background blend modes, so it is just a teal overlay:
Edge does not support background blend modes, so it's a blurred image background with a teal overlay:
All other browsers blend the blurred image background and a teal color at 30% opacity
Here's how it looks now for comparison: https://master.pfe-preview.zooniverse.org/projects/brooke/i-fancy-cats
@beckyrother this can be tested on production with our users using this url: …
> Add more contrast to the project navbar

- app/classifier/classifier.jsx
- app/classifier/task.jsx
Staging branch URL: https://fix-4469.pfe-preview.zooniverse.org/
- sane workflow: https://fix-4469.pfe-preview.zooniverse.org/projects/markb-panoptes/test-project-2-mb/classify?workflow=3173
- copy of production workflow: https://fix-4469.pfe-preview.zooniverse.org/projects/markb-panoptes/test-project-2-mb/classify?workflow=3172
Fixes #4469.
Replace lodash's `findIndex` with `findLastIndex` when selecting annotation, fixes recursive workflows.
> Fix recursive workflows

- app/lib/get-workflows-in-order.js
- app/pages/admin/project-status-list.jsx
- app/pages/lab/workflows-container.jsx
Staging branch URL: https://remove-page-sizes.pfe-preview.zooniverse.org/
- with the refactor of `getWorkflowsInOrder` to cycle through requests until no `next_page` in meta, I think we can remove the following `page_size` query params
> Remove unnecessary page_size query params

- app/classifier/tasks/text/index.cjsx
I just tried this out on the dev classifier, and although there's a (tunable) delay on the next button disabled status, it does work for required tasks
> Do a debounced annotation update onChange instead of onBlur

- app/classifier/tasks/text/index.cjsx
https://fix-text-input.pfe-preview.zooniverse.org/
Update text task value in local state while typing. Update the annotation on blur, or when the component unmounts.
This fixes performance problems by updating the classifier less frequently. However, testing on the dev classifier shows that it also breaks the Next button for required tasks.
> Store text task value in component state

- app/classifier/tasks/translations.jsx
- app/classifier/tasks/translations.spec.js
- app/classifier/translations.jsx
- app/redux/ducks/translations.js
https://parse-translations-once.pfe-preview.zooniverse.org
Update the translations actions to explode translation keys to objects once, on load from Panoptes. Remove `explodeTranslationKeys` from the translation components, so that it doesn't run on every render.
Update the task translation tests to reflect that translations are now nested objects, matching the task object structure for convenience.
Fixes a performance problem on AACW. Translations were being parsed into objects and re-rendered each time you typed a new character. Exploding the dropdown task strings into objects, for that workflow, takes ~0.5s, leading to delays of several seconds between typing a letter and seeing the display update.
Some testing URLs:
Wildcam Darien in Spanish: …
> Parse translation keys once, on load

- app/classifier/tasks/text/index.cjsx
Staging branch URL: https://text-tagging.pfe-preview.zooniverse.org
Fixes a problem where text tags are not added to a text task annotation unless you type something after adding the tags.
Updates the task annotation after adding the tags to the text.
> Update text annotations after adding tags

- app/locales/en.js
- app/locales/es.js
- app/locales/nl.js
- app/pages/reset-password/submit-email-form.jsx
- app/pages/reset-password/submit-email-form.spec.js
lots of users report they can't reset emails via contact@ most of the time it's cause they signed up with a different email address
Staging branch URL: https://unsubscribe-page-text-updates.pfe-preview.zooniverse.org/reset-password
Fixes: reports from contact @ emails, where some users signed up with different email addresses but try to reset their current one.
> Explain why reset password emails may not be sent on the reset form

- app/pages/project/components/ProjectNavbar/components/NavLink/NavLink.jsx
https://fix-4491.pfe-preview.zooniverse.org/
Pass the custom click handler down to nav links.
Remove the unused site prop.
Fixes #4491
> Add onClick prop to NavLink

- app/pages/lab/media.jsx
- css/markdown-video.styl
https://video-css.pfe-preview.zooniverse.org
Set a max width for embedded video tags in Markdown sections, so that they don't overflow tutorials and field guides. Requested by cetalingua so that they can upload their own video examples rather than relying on YouTube: https://www.zooniverse.org/projects/cetalingua/manatee-chat/talk/1508/576330
https://video-css.pfe-preview.zooniverse.org/projects/eatyourgreens/-project-testing-ground/classify has a video in the tutorial (fourth slide) and also in the field guide (section one.)
> Set a max-width for video

- app/classifier/tasks/generic-editor.cjsx
- app/pages/admin/project-status/experimental-features.jsx
https://hide-previous-marks.pfe-preview.zooniverse.org
Remove the experimental flag for the Hide Previous Marks option on drawing tasks.
> Make Hide Previous Marks public

- views/index.ejs
Follow up to #4490. Adds Object.values to the polyfill.io service we're using so that we don't forget that this isn't apart of the default set provided.
> Add Object.values to polyfill service

- app/components/file-viewer/index.jsx
- app/components/frame-viewer.jsx
https://update-annotations.pfe-preview.zooniverse.org/
Remove classification prop. Pass annotations down to FileViewer from the classifier.
This should fix Galaxy Builder, which renders your annotations to the subject viewer while you are classifying.
Needs checking to make sure the subject viewer hasn't broken anywhere that annotations are not available eg. Talk, collections, recents.
> Pass annotations to FileViewer

- app/pages/home-not-logged-in.jsx
- app/pages/home-not-logged-in/research.jsx
Fixes #3926  .
Added static classification counts from Ouroboros, Juggernaut, and other very early projects (e.g. GZ1) to not-logged-in zooniverse home page. May not include every project, and there are still a few Ouroboros projects that are active and those changes won't be updated, but this is much closer than before.
> update non-logged-in zoohome classification count

- app/pages/home-not-logged-in.jsx
Set the base classification count to 0, as it's already covered by the constants in the HomePageResearch component. Currently, zooniverse.org shows (2 * 250,469,827) as the initial classification count, instead of 250,469,827. See https://master.pfe-preview.zooniverse.org while not logged in.
Staging branch URL: https://zoohome-classcount.pfe-preview.zooniverse.org/
> Home page: Don't count older classifications twice

- app/classifier/tasks/survey/chooser.jsx
- app/components/thumbnail.jsx
Staging branch URL: https://fix-thumbnail-src-default.pfe-preview.zooniverse.org/projects/markb-panoptes/survey-task-test-project/classify?reload=0&workflow=3114
Fixes https://www.zooniverse.org/talk/17/605346.
> add default string to src in Thumbnail.getThumbnailSrc

- app/classifier/classifier.jsx
- app/classifier/task-nav.jsx
Some tasks process the annotations array once classification is complete. This commit moves that code out of the task nav and up into the classifier.
Staging branch URL: https://process-annotations.pfe-preview.zooniverse.org
Follows on from #4504
> Process annotations in the classifier

- app/classifier/tasks/survey/chooser.jsx
- app/components/cropped-image.jsx
- app/components/thumbnail.jsx
Return undefined from Thumbnail.getThumbnailSrc if there's no image src. This avoids returning invalid image URLs when src is an empty string.
Staging branch URL: https://thumbnail-images.pfe-preview.zooniverse.org
> Require img src for getThumbnailSrc

- app/classifier/classifier.jsx
- app/features/feedback/classifier/components/feedback-modal.jsx
- app/features/feedback/classifier/helpers/open-feedback-modal.jsx
Use the frame viewer component to display feedback for drawing tasks. Always use the first subject frame to show feedback.
Staging branch URL: https://feedback-subject-viewer.pfe-preview.zooniverse.org
Fixes #4509
> Use frame viewer to display drawing feedback

- app/pages/lab/mobile/mobile-section-container.jsx
- app/pages/lab/mobile/mobile-section.jsx
Staging branch URL: https://remove_launch_approved_from_mobile.pfe-preview.zooniverse.org/
I am making this change so the mobile preview feature I'm building can work. 
The way this feature will work is that project builders will be able to preview their projects on mobile is they are mobile enabled and in development. This causes an issue with how we allow project builders to mobile enable a workflow. Currently we are checking if a project is launch approved before we allow users to enable it on mobile. This poses a problem for users who just want to preview their project on mobile.
Besides for this preview mode, we will still check on mobile if a project is launch approved before displaying it to a classifying user.
> Remove launch_approved from mobile validation

- app/talk/comment.cjsx
- app/talk/discussion.cjsx
Scroll the last comment into view when scrollToLastComment is set, rather than scrolling to the bottom of the page.
Staging branch URL: https://scroll-last-comment.pfe-preview.zooniverse.org
Fixes #4515 .
> Add ScrollIntoView to Comment component

- app/components/file-viewer/canvas-viewer.jsx
- app/features/modelling/baseReglModel.jsx
- app/features/modelling/galaxy-builder/galaxyRegls.js
- app/features/modelling/galaxy-builder/index.js
Fixes #4542
Added error catching for canvas-viewer where text is displayed rather than any image. Howerver, volunteers could still hypothetically complete a classification.
Added a dynamic scaling to the maximum number of points in a spiral arm. This will not fix mobile classifying, as PSF convolution requires a minimum of 121 uniforms, which significantly eats into the 256 most mobile devices allow.
> Galaxy builder bugfixes

- app/features/feedback/shared/strategies/dud/create-rule.js
- app/features/feedback/shared/strategies/radial/create-rule.js
Staging branch URL: https://optional-feedback-fix.pfe-preview.zooniverse.org/
Staging branch project URL: https://optional-feedback-fix.pfe-preview.zooniverse.org/projects/aprajita/space-warps-hsc/classify?reload=0&workflow=6605env=production
Fixes a bug which caused feedback to crash and break the "Done" button. This was caused by an optional property being treated as required, so the `SpaceFriday` workflow (which has a third success-only feedback rule) was breaking 🐼 
cc @aprajita
> Optional feedback fix

- app/classifier/components/TaskNavButtons/TaskNavButtons.jsx
- app/classifier/components/TaskNavButtons/TaskNavButtons.spec.jsx
Staging branch URL: https://disable-next-button.pfe-preview.zooniverse.org
Fixes #4575 .
Adds Task Nav tests for the case where the task is required but the task has not been answered yet.
Fixes a typo in the props for the Next button.
> Disable next button for required tasks

- app/pages/project/classify.jsx
Staging branch URL: https://seen-subjects.pfe-preview.zooniverse.org
Filters the incoming subject queue for any subjects that have been seen this session, but not yet marked as seen by Panoptes.
Also fixes some linter warnings for the classifier page:
- uses named class methods instead of anonymous functions.
- removes the unused `Translate` component.
- removes some semicolons and commas.
> Filter out seen subjects from the subject queue

- app/classifier/classifier.jsx
- app/components/frame-viewer.jsx
Staging branch URL: https://feedback-subject-viewer.pfe-preview.zooniverse.org
Fixes #4509 .
Adds a `zoomControls` boolean prop to the frame viewer, which allows display of the pan/zoom buttons to be turned on or off.
> Turn pan/zoom controls off in the feedback subject viewer

- app/pages/project/components/ProjectNavbar/ProjectNavbar.jsx
- app/pages/project/components/ProjectNavbar/ProjectNavbar.spec.js
- app/pages/project/components/ProjectNavbar/ProjectNavbarContainer.jsx
- app/pages/project/components/ProjectNavbar/ProjectNavbarContainer.spec.js
- app/pages/project/components/ProjectNavbar/components/ProjectNavbarNarrow/ProjectNavbarNarrow.jsx
- app/pages/project/components/ProjectNavbar/components/ProjectNavbarWide/index.js
- package-lock.json
- package.json
Staging branch URL: https://react-measure.pfe-preview.zooniverse.org/
Uses `react-sizeme` instead of `react-rendered-size` to determine which nav bar to show on the project home page.
The current design specifies that the contents of the nav bar change, which necessitates a dynamic breakpoint - let's get that working for React 16 (#4543 ), and move the discussion of whether that's actually a good idea to a separate issue.
This still needs the tests finishing, but is enough to test in browser.
Still to do:
> Remove react-rendered-size

- app/classifier/classifier.jsx
This stops the feedback subject viewer from rendering marks as editable.
Staging branch URL: https://feedback-subject-viewer.pfe-preview.zooniverse.org
Fixes #4535
> Feedback: set current annotation to empty object

- app/classifier/components/TaskNavButtons/components/BackButton/BackButton.jsx
- app/classifier/components/TaskNavButtons/components/NextButton/NextButton.jsx
- app/classifier/components/TaskNavButtons/components/TalkLink/TalkLink.jsx
- app/classifier/components/TaskNavButtons/components/TalkLink/TalkLink.spec.jsx
Staging branch URL: https://more-button-style-fixes.pfe-preview.zooniverse.org/
Fixes more from #4570:
- Back button smaller on second step (Penguin Watch, Manatee Chat, Galaxy Zoo), intended?
- Adds `white-space: nowrap` to the styles for the TalkLink component
- dark theme - Done & Talk filled with blue, Back and Done transparent (Penguin Watch), should all these buttons be transparent, then fill on hover?
- Added Redux connect and ThemeProvider as well as variant styles for the TalkLink component for light and dark themes.
- Back Button: the warning message extends below the box making it harder to read (tested in Firefox 59.0.2).
- Added a specific vendor prefixed style for Firefox to get the width correct. Firefox will now use `width: -moz-max-content` and IE and Edge continue to …
> Fix wrapping and warning on back button. Fix Talk link styles

- css/survey-task.styl
Staging branch URL: https://fix-4596.pfe-preview.zooniverse.org/projects/coloradocorridorsproject/colorado-corridors-project/classify?env=production
Fixes #4596. The survey task redesign is up next, so we shouldn't spend too much time trying to come up with a prettier fix.
> A temporary fix for the overflowing survey task choice

- app/features/modelling/baseReglModel.jsx
- app/features/modelling/galaxy-builder/index.js
Addresses concerns raised in  #4550 
Changed error message from 
> We’re afraid your browser doesn’t support the WebGL we need to render galaxies. You can comment on photos (the second image) in Talk, but won’t be able to classify.
To
> Sorry, this project requires features which are not supported by your device. Please try again on a desktop computer, and let us know in talk if you're still having problems. You can comment on photos (the second image) in Talk, but please do not classify!
> Changed galaxy-builder webgl error message to be more specific and helpful

- app/classifier/tasks/drawing/markings-renderer.cjsx
Reverts zooniverse/Panoptes-Front-End#4580
This reversion removes the `deleteIfOutOfBounds` logic in the `markings-renderer.cjsx` component, which was introduced to fix Issue #4579. (i.e. users could place markings outside of the Subject bounds, noted on Space Warps.)
Unfortunately, the introduction of `deleteIfOutOfBounds` introduced a _new, more serious issue,_ where if a user zoomed into Subject image, any markings that _are outside the field of view_ start to disappear. (i.e. the problem is that `deleteIfOutOfBounds` checks for the bounds of the _subject viewer/viewport,_ not the _subject image itself._ )
This newly introduced issue has significant impact on projects like Penguin Watch (see issue #4607), so we need to undo these changes.
- This should fix #4607 
- This should re-open …
> Revert "Add deleteIfOutOfBounds to drawing tool root"

- app/classifier/tasks/survey/chooser/CharacteristicsFilter.jsx
- app/classifier/tasks/survey/chooser/Choices.jsx
- app/classifier/tasks/survey/chooser/Chooser.jsx
- app/classifier/tasks/survey/chooser/index.jsx
Staging branch URL: https://survey-task.pfe-preview.zooniverse.org/
Splits the survey task chooser up into a CharacteristicsFilter and Choices component.
This also fixes a bug where you can't tab into the filtered choice list if your currently selected choice isn't present in the filtered list (every item is set to tabindex -1.)
> Split up the survey task chooser

- app/talk/comment.cjsx
Hide login and display names for deleted comment authors. Don't link through to the deleted profile.
Staging branch URL: https://talk-deleted-author.pfe-preview.zooniverse.org
> Talk: hide details for deleted authors

- app/pages/project/workflow-selection.jsx
- app/pages/project/workflow-selection.spec.js
Parse `workflow_id` as an integer before using it in comparisons, or storing it in user preferences. Fixes a bug where a malformed ID could cause an infinite loop of requests to `/api/workflows`.
Staging branch URL: https://workflow-selection.pfe-preview.zooniverse.org/
> Workflow Selection: parse IDs as numbers

- app/classifier/components/TaskNavButtons/components/BackButton/BackButton.jsx
- app/classifier/components/TaskNavButtons/components/DoneButton/DoneButton.jsx
- app/classifier/components/TaskNavButtons/components/NextButton/NextButton.jsx
- app/classifier/components/TaskNavButtons/components/TalkLink/TalkLink.jsx
- app/classifier/components/TaskTabs/components/TutorialTab/TutorialTab.jsx
- app/classifier/tasks/components/TaskInputField/TaskInputField.jsx
- app/theme/colors.js
Staging branch URL: https://classifier-button-styles.pfe-preview.zooniverse.org/dev/classifier
Fixes #4590 and fixes #4600.
This updates the classifier task buttons to have improved contrast for readability, makes the Talk button styles more consistent with the others, adds a gradient to the task buttons in the dark theme. Also fixes the broken hover and focus styles for the tutorial button.
> Improved classifier button styles

- app/classifier/drawing-tools/root.cjsx
- app/classifier/tasks/components/TaskInputField/TaskInputField.jsx
- app/classifier/tasks/components/TaskInputField/TaskInputField.spec.jsx
Staging branch URL: https://fix-edge-drawing-input-bug.pfe-preview.zooniverse.org/projects/penguintom79/penguin-watch?env=production
Select the Time Lapse workflow to try specifically in Edge and IE.
I initially thought the issue was an undefined ref, but not entirely (this PR still has a fix and tests for that). Fixes a nasty bug where a TypeError was being thrown in Edge and IE on this line:
https://github.com/zooniverse/Panoptes-Front-End/blob/126b2e179f3b8519791cd23214e3476b7bc284c3/app/classifier/drawing-tools/root.cjsx#L125
IE and Edge do not support focus and blur on SVG elements. I have no idea how long this may have been preventing classification submission in drawing task workflow projects in Edge, but based on what I know from reports that it may have been this last week or so. …
> Fix edge drawing input bug

- app/classifier/tutorial.cjsx
- app/components/step-through.jsx
- css/tutorial.styl
- package-lock.json
- package.json
https://fix-tutorial-width.pfe-preview.zooniverse.org/
The tutorial content wasn't displaying because the div wrapper that is the immediate child of the `ReactSwipe` component wasn't getting its width style set. I couldn't figure out how the width was getting set before. I don't see any width style property set in the `StepThrough`, `Tutorial`, modal-form's `Dialog`, or in the `ReactSwipe` library. It is a mystery! But this is a workaround by overwriting the `width: 0` property in the CSS styles. 
I also fixed the string props in `Tutorial` and `StepThrough` and fixed various lint errors.
> [WIP] Update to modal-form 2.6.0. Fix tutorial width

- css/mini-course-dialog.styl
- css/tutorial.styl
Staging branch URL: https://fix-4585.pfe-preview.zooniverse.org/projects/zooniverse/gravity-spy/classify?env=production
Fixes #4585. Sets a max-width for the tutorial on the step container. Sets a max-width for the mini-course.
> Set a max-width for tutorial and mini-course

- app/pages/dev-classifier/ClassificationViewer.jsx
- app/pages/dev-classifier/index.jsx
- css/classify.styl
Staging branch URL: https://fix-dev-classifier-annotation-preview.pfe-preview.zooniverse.org/dev/classifier
This fixes the dev classifier layout and the annotation preview that I broke in a previous theme update.
> Fix dev classifier annotation preview

- app/classifier/tasks/highlighter/index.jsx
- app/classifier/tasks/highlighter/label-renderer.jsx
- app/pages/dev-classifier/mock-data.coffee
- public/assets/dev-classifier/algernon.txt
Add the highlighter task to the dev classifier.
Add a text file to the mock subject locations.
Staging branch URL: https://highlighter-task.pfe-preview.zooniverse.org
> Add text highlighter to dev classifier

- app/lib/get-social-data.js
- app/pages/home-common/social.jsx
Staging branch URL: https://readd-non-logged-in-recent-project.pfe-preview.zooniverse.org/
Reinstates recent projects to non-logged in home page, this time with just the cards api data instead of the full resource response (no workflow links, etc).
> Re-add recent projects to non-logged in home page

- app/pages/admin/project-status.jsx
On the project admin page, avoid requesting data we don't need for a project, instead request the project resource card representation for setting the featured project.
> use cards request for featured project

- app/pages/lab/export-workflows-dialog.jsx
Staging branch URL: https://fix-workflow-classification-timestamp.pfe-preview.zooniverse.org/
Fixes https://www.zooniverse.org/talk/17/639332
> Fix timestamps for workflow classification exports

- app/components/workflow-assignment-dialog.jsx
Simple change to text message when users are promoted in snapshot wisconsin challenge workflow.
> fix promotion message for snapshot wi

- app/classifier/index.cjsx
Staging branch URL: https://fix-4648.pfe-preview.zooniverse.org/
Fixes #4648. UPP shouldn't be requested every 5 classifications unless it's a project with workflow assignment enabled.
> Only request for UPP for workflow assignment projects

- app/pages/project/stats/charts.jsx
rc-slider now uses different components to render range and single value sliders.
Staging branch URL: https://fix-stats.pfe-preview.zooniverse.org
> Update stats to use Range component

- app/components/step-through.jsx
The tutorial renders much too narrow, unless you call swipe.setup() twice.
Staging branch URL: https://fix-tutorial-width.pfe-preview.zooniverse.org
> Fix tutorial rendering bug

- app/classifier/restart-button.jsx
- app/pages/project/project-page.jsx
- app/pages/project/project-page.spec.js
Staging branch URL: https://fix-project-token-logging.pfe-preview.zooniverse.org/
Related to #4637. Fixes geordi key `projectToken` so it's set dynamically based on project, as opposed to currently where `projectToken` remains as `'zooHome'` within all projects. 
This will prevent logging within projects that are not [specified in `enabledTokens`](https://github.com/zooniverse/Panoptes-Front-End/blob/fix-project-token-logging/app/lib/zooniverse-logging.js#L1).
To test I added a console.log before and within [this conditional](https://github.com/zooniverse/Panoptes-Front-End/blob/fix-project-token-logging/app/lib/zooniverse-logging.js#L30), logging the `projectToken`, and added a test project within [`enabledTokens`](https://github.com/zooniverse/Panoptes-Front-End/blob/fix-project-token-lo …
> Fix projectToken remember for projects

- app/talk/board.cjsx
- app/talk/comment-box.cjsx
- app/talk/discussion-new-form.cjsx
- app/talk/discussion-preview.cjsx
- app/talk/discussion.cjsx
- app/talk/popular-tags.jsx
- app/talk/quick-subject-comment-form.cjsx
- app/talk/search-input.cjsx
Staging branch URL: https://add-easy-sw-analytics.pfe-preview.zooniverse.org/
Towards requested Snapshot Wisconsin analytics requests.
- add log for viewing Discussion
- add log for new Discussion title
- add log boolean in TalkQuickSubjectCommentForm's CommentBox component, to enable logging 
- edit SW requested log events data from objects to strings
> Edit analytics data from object to string, add discussion log events

- app/classifier/drawing-tools/root.jsx
Staging branch URL: https://fix-subtasks.pfe-preview.zooniverse.org
Fixes a syntax error I missed in #4662, which breaks drawing subtasks.
> Fix tasks require in drawing tool root

- app/pages/project/workflow-selection.jsx
- app/pages/project/workflow-selection.spec.js
Staging branch URL: https://log-selection-errors.pfe-preview.zooniverse.org/projects/srallen086/untitled-project-5-10-2018-11-53-20-am
Instead of throwing an `Error` object, just log to the console instead when there are no active workflows. I also discovered another way an infinite loop could be caused, which are projects without any workflows at all. So I fixed this and wrote a test for it.
> Log rather than throw error. Fix infinite loop bug

- app/pages/lab/visibility.cjsx
- app/pages/lab/workflow.cjsx
Staging branch URL: https://improve-wording-on-lab-workflow.pfe-preview.zooniverse.org/
Add better messaging around how to edit workflow tasks for a live project. Summary is tell the user to deactivate the workflow but leave the project live.
> Improve lab wording for workflow task editing on workflows

- app/collections/manager-icon.jsx
Staging branch URL: https://fix-collections-dialog.pfe-preview.zooniverse.org
Fixes #4665.
Prevent click events propagating up from the close button to the parent button in the React tree. Also fixes linter warnings for the manager icon component.
> Fix Add To Collections close button

- app/classifier/drawing-tools/components/DetailsSubTaskForm/DetailsSubTaskForm.jsx
Apply `pointer-events: none` to drawing subtasks, allowing interaction with the underlying drawing tool.
Staging branch URL: https://drawing-subtask.pfe-preview.zooniverse.org
Fixes #4683.
> Ignore pointer events on drawing subtasks

- app/pages/project/workflow-selection.jsx
- app/pages/project/workflow-selection.spec.js
Staging branch URL: https://fix-infinite-loop-bug.pfe-preview.zooniverse.org/
Fixes regression introduced in #4672. #4672 attempted to fix a workflow selection infinite loop by checking first if a project had a linked workflows array before calling `getSelectedWorkflow`. This stopped the workflow selection loop in a scenario when a project has no workflows, but it has a few issue:
- Empty arrays in javascript evaluate true, so you have to check that the array exists and the length of it (oops). So the previous conditional always evaluated true.
- Even if you check the length for `project.links.workflows`, it introduced a new infinite loop with projects that have a linked workflow that is not active like http://zooniverse.org/projects/rolando-dot-tokez/canna-if-i-juanna
- What the actual …
> Only call getWorkflows if selectedWorkflowID is defined and truthy

- app/collections/show.jsx
Fix an error where the collections page crashed if `props.user` is null. Only checks `user.id` if user is defined.
Staging branch URL: https://collections.pfe-preview.zooniverse.org
Fixes #4682.
> Fix type error on collections page

- app/classifier/classifier.jsx
- app/classifier/classifier.spec.js
- app/classifier/task-nav.jsx
Sync classifier annotation state when a classification loads.
Hide summaries if classification summaries are disabled.
Add tests for annotation state when the classifier mounts, when classifications are received, when subjects load and when a classification completes.
Staging branch URL: https://classifier-state.pfe-preview.zooniverse.org
Fixes #4668.
Fixes #4634.
> Reset classifier annotation state when new classifications load

- app/pages/about/team-page.cjsx
Hey, I had some free time, so...
Staging branch URL: Tests are passing, but I'm getting an error when running stage command. It seems a problem with `publisssh`. Has anyone seen this before?
```
Local: ./dist
Bucket: zooniverse-static
Prefix: preview.zooniverse.org/panoptes-front-end/add-alumni
/Users/simone.duca/Documents/Projects/Panoptes-Front-End/node_modules/aws-sdk/lib/request.js:30
throw err;
^
TypeError: Cannot read property 'Contents' of null
at Response.<anonymous> (/Users/simone.duca/Documents/Projects/Panoptes-Front-End/node_modules/publisssh/lib/publish.iced:126:16)
at Request.<anonymous> (/Users/simone.duca/Documents/Projects/Panoptes-Front-End/node_modules/aws-sdk/lib/request.js:353:18)
```
Adds Simone to the Alumni section.
> Add alumni

- app/classifier/classification-summary.jsx
Staging branch URL: https://enable-custom-summary-hook.pfe-preview.zooniverse.org/
Looks for the `configuration.custom_summary` property on the workflow resource, and renders it as Markdown on the classification summary if present.
cc @hrspiers
> Use summariesHook to show a workflow-defined custom summary

- app/pages/home-common/social.jsx
- package-lock.json
- package.json
Staging branch URL: https://remove-blog-tags.pfe-preview.zooniverse.org/
Fixes https://www.zooniverse.org/talk/17/638676
> Strip HTML from blog excerpts

- app/classifier/classifier.jsx
Use the last task key stored in workflow history to look up the current annotation.
Staging branch URL: https://update-feedback.pfe-preview.zooniverse.org
> Use workflowHistory to update feedback

- app/classifier/index.cjsx
- app/constants/languageMenu.js
- app/locales/en.js
- app/locales/es.js
- app/locales/it.js
- app/locales/nl.js
- app/pages/lab/translations/index.jsx
- app/pages/project/components/LanguagePicker/LanguagePicker.jsx
- app/pages/project/components/LanguagePicker/LanguagePicker.spec.js
- app/pages/project/components/LanguagePicker/index.js
- app/pages/project/components/ProjectNavbar/ProjectNavbar.jsx
- app/pages/project/components/ProjectNavbar/ProjectNavbarContainer.jsx
- app/pages/project/components/ProjectNavbar/components/ProjectNavbarNarrow/ProjectNavbarNarrow.jsx
- app/pages/project/components/ProjectNavbar/components/ProjectNavbarWide/ProjectNavbarWide.jsx
- app/pages/project/components/ProjectNavbar/components/StyledHeader/Header.jsx
- app/pages/project/components/ProjectNavbar/components/Wrapper/Wrapper.jsx
- app/pages/project/index.jsx
- app/pages/project/project-page.spec.js
- app/pages/project/workflow-selection.jsx
Staging branch URL: https://language-picker.pfe-preview.zooniverse.org
https://language-picker.pfe-preview.zooniverse.org/projects/y-dot-liefting/snapshot-hoge-veluwe?env=production is available in English and Dutch
> Language picker

- app/classifier/classifier.jsx
Staging branch URL: https://feedback-classifier-state.pfe-preview.zooniverse.org/
Fixes #4668. (Hopefully)
This should have been obvious, but this removes the call to update feedback from subject load, and instead updates just before we check whether to show the feedback modal or not.
I'll add tests once #4699 is in
> Move feedback update out of subject load

- app/pages/lab/index.cjsx
Staging branch URL: https://lab-page-fix.pfe-preview.zooniverse.org/
Fixes lab issues with pagination for owned or collaborator projects lists, as well as redirect after creating new project.
Replaces use of `@props.history` with react-router's `browserHistory`.
> Replace lab index use of history with browserHistory

- package.json
Staging branch URL: https://check-engines.pfe-preview.zooniverse.org/
Changes the `engines` property for npm in `package.json` to allow versions 5+.
> Make npm `engines` property more relaxed

- app/classifier/tasks/survey/chooser/Choices.jsx
- app/classifier/tasks/survey/index.spec.js
Fixes a React warning about an invalid data attribute in the survey task choices.
Staging branch URL: https://data-attributes.pfe-preview.zooniverse.org/
> Change data-choiceID to data-choiceid

- app/classifier/tasks/components/TaskInputField/components/TaskInputLabel/TaskInputLabel.jsx
Staging branch URL: https://fix-4694.pfe-preview.zooniverse.org/
Fixes #4694.
Changes the CSS pseudo-selector to `only-child` from `first-of-type`. Can be tested on the Cairo Geniza workflow (must be logged in and admin mode or collab on project):
https://fix-4694.pfe-preview.zooniverse.org/projects/judaicadh/scribes-of-the-cairo-geniza/classify?env=production&workflow=6529
And still applies the background color on Galaxy Zoo:
https://fix-4694.pfe-preview.zooniverse.org/projects/zookeeper/galaxy-zoo/classify?env=production
> Change pseudo-selector to only-child

- app/classifier/index.cjsx
- app/pages/dev-classifier/mock-data.coffee
Staging branch URL: https://dev-classifier.pfe-preview.zooniverse.org/dev/classifier
Fixes a couple of small bugs, one of which crashes the entire React app if you visit the dev classifier.
Adds a default locale to the classifier (this one crashes PFE.)
Adds spacing to the test for long drawing tool labels (the ellipse tool.)
> Dev classifier bugfixes

- app/lib/handle-input-change.coffee
- app/partials/display-name-slug-editor.jsx
- package-lock.json
- package.json
Staging branch URL: https://fix-xss-vulnerability.pfe-preview.zooniverse.org/
Fixes issue brought to our attention from an email to the security group. **This must be tested in Firefox.** I couldn't get the XSS vulnerability to trigger in Chrome.
The example project:
https://www.zooniverse.org/projects/martenveldthuis/-svg-onload-equals-confirm-xss
This PR adds sanitation to the value that is saved in the project builder so it prevents this from happening in the future. If you make a new project and try to save `"'>'"><sVg/oNLoad=confirm(/xss/)>`, it will sanitize the value before saving it. However, I haven't figured out how to stop existing projects with this display name from executing the script.
> Clean input values to prevent XSS vulnerability

- app/locales/en.js
- app/locales/es.js
- app/locales/it.js
- app/locales/nl.js
- app/pages/project/home/talk-status.jsx
Replace HTML with Markdown in talk status template strings on the project home page. Any markup in project titles, or the number of active users, is now rendered as plain strings rather than parsed as HTML.
Staging branch URL: https://talk-status.pfe-preview.zooniverse.org/projects/martenveldthuis/-svg-onload-equals-confirm-xss?env=production
> Use Markdown for talk status

- app/pages/profile/user.jsx
Display the profileUser's name, not the logged in user's name.
Staging branch URL: https://profile-titles.pfe-preview.zooniverse.org/
> Fix page title of profile pages

- app/talk/inbox-conversation.cjsx
Staging branch URL: https://talk-pm-titles.pfe-preview.zooniverse.org/
Adds page titles for private messages, so they will have the subject in the title rather than just saying "Zooniverse".
> Add page titles for private messages

- views/index.ejs
Staging branch URL: https://remove-opengraph.pfe-preview.zooniverse.org/
Having this outdated image of the home page, which loads as the preview for every page, is worse than having no image at all. One day we should set up some server-side rendering to generate proper previews dynamically, but right now we should just remove this.
> Remove opengraph image

- package-lock.json
- package.json
Staging branch URL: https://upgrade-client.pfe-preview.zooniverse.org
Bump the Panoptes client to 2.10.
Otherwise, identical to #4713 for testing.
> panoptes-client 2.10.0

- webpack.build.js
Staging branch URL: https://fix-build.pfe-preview.zooniverse.org/
Fixes the broken build from the updated markdownz #4712. The latest version of markdown-it-anchor includes a security fix so I don't think we should revert it, however, markdown-it-anchor has to be included in the babel compiling now.
> Fix production build

- app/classifier/tutorial.jsx
Tutorial preferences might be undefined, rather than null, so set default values if `preferences.tutorials_completed_at` is falsy.
Staging branch URL: https://fix-4721.pfe-preview.zooniverse.org
Fixes #4721.
> Set tutorial preferences if undefined

- app/classifier/tutorial.jsx
- app/classifier/tutorial.spec.jsx
Follow-up to #4722.
Check if tutorials_completed_at is an array, and convert arrays to an object.
Update project preferences with the entire object.
Add tests for a case where tutorials_completed_at was created as an array.
Staging branch URL: https://tutorial_preferences.pfe-preview.zooniverse.org
> Make sure tutorials_completed_at is an object

- css/home-page-for-user.styl
Set a max height of 1000px for the home page recent projects list. Allow the container to scroll if the height of the project card list is larger than that.
Staging branch URL: https://home-projects.pfe-preview.zooniverse.org
Fixes an issue where you can't scroll down to your oldest projects, if you have contributed to a larger number of projects than is allowed by the current max-height.
> Allow home page project card list to scroll if necessary

- app/layout/expandable-menu.jsx
React Portals bubble events up through the React tree, so we don't need two keydown handlers on the user menu any more.
Staging branch URL: https://user-menu.pfe-preview.zooniverse.org
Fixes #4730.
> User account menu: Remove redundant keydown handler

- app/classifier/components/TaskNavButtons/components/BackButton/BackButton.jsx
- app/classifier/tasks/components/TaskInputField/TaskInputField.jsx
- app/classifier/tasks/drawing/components/DrawingToolInputIcon/DrawingToolInputIcon.jsx
- app/classifier/tasks/generic.jsx
- app/classifier/tasks/generic.spec.js
- app/classifier/tasks/slider/slider.spec.js
- app/classifier/translations.jsx
- app/classifier/tutorial.jsx
- app/locales/ar.js
- app/locales/he.js
- app/pages/project/components/ProjectNavbar/components/ProjectNavbarWide/ProjectNavbarWide.jsx
- app/pages/project/components/ProjectNavbar/components/ProjectTitle/ProjectTitle.jsx
- app/pages/project/field-guide.cjsx
- app/pages/project/project-page.jsx
- app/redux/ducks/translations.js
- app/talk/index.cjsx
- css/app.styl
- css/talk.styl
Add lang attribute to project page container.
Add RTL styles for Hebrew and Arabic.
Add language files for Hebrew and Arabic
Staging branch URL: https://project-language.pfe-preview.zooniverse.org/projects/judaicadh/scribes-of-the-cairo-geniza?env=production&language=he
Fixes #4621.
> Add RTL language display to projects

- app/pages/admin/project-status/experimental-features.jsx
- app/pages/lab/workflow.cjsx
Remove it from experimental tools, and remove the experimental flag on it in the workflows lab page.
Staging branch URL: https://persist-annotations.pfe-preview.zooniverse.org
> Make 'persist annotations' public

- app/classifier/classifier.jsx
- app/classifier/classifier.spec.js
Adds tests to check that feedback is updated when feedback is checked, and that the correct annotation is used.
> Add feedback tests to the classifier

- app/talk/moderation/comment.cjsx
Moderation comments require in the CommentLink component from the user profile, which is now ES6.
Staging branch URL: https://moderation-comments.pfe-preview.zooniverse.org
Fixes #4741.
> Fix comment link import

- app/classifier/tasks/drawing/summary-answer.jsx
- app/classifier/tasks/drawing/summary.jsx
Add the toggle button back to the drawing task summary.
Hide the full mark details for each mark type unless the summary is expanded by clicking More.
Staging branch URL: https://drawing-summary.pfe-preview.zooniverse.org
> Restore the drawing summary More/Less button

- app/classifier/tasks/text/index.jsx
Staging branch URL: https://text-task-es6-refactor.pfe-preview.zooniverse.org/
Tries to avoid any timing bugs (eg. the task annotation being updated after the task has unmounted) by flushing updates on unmount, and explicitly passing the current text value to `updateAnnotation` rather than getting it from the DOM. Removes some function binding that broke `_.debounce`.
> Text task: flush annotation updates on unmount

- app/pages/project/index.jsx
Staging branch URL: https://fix-get-all-linked.pfe-preview.zooniverse.org/
- staged branch, project no Field Guide: https://fix-get-all-linked.pfe-preview.zooniverse.org/projects/markb-panoptes/calbug
- same project no Field Guide: https://master.pfe-preview.zooniverse.org/projects/markb-panoptes/calbug
Fixes annoying console error `Uncaught (in promise) Error: getAllLinked: resource and link not specified` in any project without a Field Guide.
Check if `guide` is defined before requesting all linked `attached_images`.
> Prevent field guide related requests if no field guide

- app/classifier/tasks/text/index.jsx
Staging branch URL: https://fix-text-rows.pfe-preview.zooniverse.org/
Fixes https://www.zooniverse.org/talk/17/692672
- add `.length` to comparison of `value` strings before reseting rows to 1
- add Math.min and Math.max so rows never below 1 or above 10 (per `MAX_ROWS` constant)
- add `overflow: hidden` to fix issue on Windows 7, Firefox 61 where scrollHeight included scrollbar, creating row resizing loop and inconsistency with other browsers
Used BrowswerStack to test, see Passbolt for login info.
> Fix text task row issues in Windows/Firefox

- app/classifier/tasks/text/index.jsx
Staging branch URL: https://fix-text-task-rows-2.pfe-preview.zooniverse.org/
- test project: https://fix-text-task-rows-2.pfe-preview.zooniverse.org/projects/markb-panoptes/focus-testing-project/classify?reload=0&workflow=2955 
Iteration on #4754, which added a max textarea rows restriction of 10 and hid scroll bars, however, a classifier reported an issue with longer (over 10 rows) transcriptions [in Talk here](https://www.zooniverse.org/talk/17/692672?comment=1155851), so this PR removes the max row restriction.
Although it's unclear and unfortunate why `overflow: hidden` fixes the Windows/Firefox issue detailed in #4754, since it does address the large textarea (and related classifier freeze from infinite loop resizing) I think the max restriction can be safely removed.
> Remove text task max rows

- app/classifier/drawing-tools/root.jsx
- app/classifier/tasks/generic.jsx
- app/classifier/tasks/text/index.jsx
- app/classifier/tasks/text/index.spec.js
Staging branch URL: https://drawing-subtasks.pfe-preview.zooniverse.org
Fixes #4095 
Fixes #4666
Fixes a typo in a prop name for drawing subtasks.
The `ModalForm` components mount their children before adding them to the DOM, firing `componentDidMount` in the children before the DOM is ready. This PR adds a timer to `componentDidMount` for text tasks and the generic task to give a delay before trying to access their DOM nodes in order to handle focus etc.
> Drawing subtasks

- package-lock.json
- package.json
- webpack.build.js
Updates markdownz to  fix a security warning.
markdown-it-table-of-contents is now written in ES6, so update webpack to pass it through babel.
Staging branch URL: https://markdownz.pfe-preview.zooniverse.org
> Update markdownz to 7.6.3

- package-lock.json
- package.json
Updates modal-form to fix issues where the autofocus attribute was ignored in modal form content.
Staging branch URL: https://modal-autofocus.pfe-preview.zooniverse.org
Depends on zooniverse/modal-form#39
> Update modal form to 2.6.1

- app/talk/inbox.cjsx
Always pass a page param when requesting conversations from the API.
Add the onPageChange handler to the paginator.
Staging branch URL: https://inbox.pfe-preview.zooniverse.org
Fixes #3627.
> Fix inbox pagination

- app/classifier/tasks/drawing-task-details-editor.cjsx
Staging branch URL: https://dropdown-subtask.pfe-preview.zooniverse.org/
Fixes inability to add dropdown task as drawing subtask, as mentioned in #4761, similar to #4757.
> Fix broken require for dropdown subtasks

- app/talk/inbox.cjsx
Check user ID against conversation.participant_ids when rendering the link to the sender.
Staging branch URL: https://inbox-conversation.pfe-preview.zooniverse.org
Fixes #4762.
Fixes #3934.
> Fix inbox conversation participants

- app/components/subject-viewer.cjsx
Rewrite any value in subject metadata that begins with 'http' as a markdown link that opens in a new tab.
Staging branch URL: https://subject-metadata-links.pfe-preview.zooniverse.org
Fixes #3555.
Fixes #2962.
> Rewrite URLs in subject metadata as links

- app/components/subject-viewer.cjsx
Check that value.startsWith exists before calling it.
Followup to #4769, which breaks the subject metadata popup if any of the metadata values are numbers.
Reported in Talk here: https://www.zooniverse.org/talk/17/698605?comment=1165455
Staging branch URL: https://subject-metadata-links.pfe-preview.zooniverse.org/
> Fix subject metadata popup when metadata contains numbers

- app/pages/lab/field-guide/actions.js
Add a query argument to all resource.get() calls in the field guide editor actions. This forces the API client to bypass its internal cache and request the latest version of the field guide from Panoptes.
Staging branch URL: https://field-guide-editor.pfe-preview.zooniverse.org/
Fixes #4772
> Bypass API client cache in the field guide editor

- app/classifier/drawing-tools/components/DetailsSubTaskForm/DetailsSubTaskForm.jsx
- app/classifier/drawing-tools/components/DetailsSubTaskForm/DetailsSubTaskForm.spec.js
- app/classifier/tasks/crop/index.cjsx
- app/classifier/tasks/drawing/index.cjsx
- app/classifier/tasks/dropdown/index.jsx
- app/classifier/tasks/dropdown/index.spec.js
- app/classifier/tasks/highlighter/index.jsx
- app/classifier/tasks/slider/index.jsx
- app/classifier/tasks/slider/slider.spec.js
- app/classifier/tasks/text/index.jsx
- app/classifier/tasks/translations.jsx
Updates all workflow tasks so that we use `props.translation` for task instructions and task help.
Updates drawing tasks to get labels from translations too.
Staging branch URL: https://task-translations.pfe-preview.zooniverse.org
TODO:
> Add missing task translations

- app/classifier/tasks/drawing-task-details-editor.cjsx
Staging branch URL: https://fix-dropdown-subtask.pfe-preview.zooniverse.org/
Fixes issue if attempt to add dropdown task as drawing subtask.
Properly imports ES6 DropdownEditor component.
> Fix dropdown subtask editor import

- app/classifier/classification-summary.jsx
- app/classifier/world-wide-telescope.jsx
- app/classifier/world-wide-telescope.spec.js
- css/world-wide-telescope.styl
Staging branch URL: https://wwt-button-text.pfe-preview.zooniverse.org/
Fixes # .
This PR adds additional text beneath the WWT button containing instructions for misaligned images.
> Add Text to WWT Button

- app/classifier/drawing-tools/freehand-segment-line.cjsx
- app/classifier/drawing-tools/freehand-segment-shape.cjsx
Allow drawing inside freehand segment lines and freehand segment shapes by ignoring pointer events completely when the tool is disabled, and ignoring pointer events on transparent areas when drawing.
Staging branch URL: https://concave-freehand-shapes.pfe-preview.zooniverse.org
Fixes #4770 .
> Allow concave freehand drawing shapes

- app/components/workflow-assignment-dialog.jsx
- app/locales/ar.js
- app/locales/de.js
- app/locales/en.js
- app/locales/es.js
- app/locales/fr.js
- app/locales/he.js
- app/locales/it.js
- app/locales/nl.js
- app/pages/project/home/home-workflow-buttons.jsx
- app/pages/project/home/home-workflow-buttons.spec.js
- app/pages/project/home/project-home.jsx
- app/pages/project/home/project-home.spec.js
- app/pages/project/index.jsx
Staging branch URL: https://sw-split-setup.pfe-preview.zooniverse.org/
For an upcoming split for Snapshot Wisconsin at the start of their new season. This is similar to a previous split run by Gravity Spy (#3254 and #3286) where depending on the split cohort, users will be assigned a workflow.
For SW's experiment, I tried to generalize this process a bit more than the GS experiment. The client is still calling the update to the UPP to set the workflow id, but the ids aren't hardcoded in PFE, but instead stored in the Seven-Ten split variants. 
This experiment also implies a visibility split for the home page workflow buttons. Users who will not be promoted should not see the workflow buttons and see instead the 'Get Started' link to the classify page. Users who will promote should see the …
> Snapshot WI split setup

- app/pages/project/index.jsx
Staging branch URL: https://sw-split-setup.pfe-preview.zooniverse.org/projects/srallen086/workflow-assignment-testing
Follow up from #4784. I realized that the code as is could demote someone who had been promoted when they revisit the project later. This adds in a check to make sure that the `settings.workflow_id` hasn't already been set.
> Only set the workflow if the settings.workflow_id is falsey.

- app/pages/lab/export-workflows-dialog.jsx
- app/pages/lab/workflows-table.jsx
- app/pages/lab/workflows.jsx
Staging branch URL: https://add-workflow-id-lab.pfe-preview.zooniverse.org/
Fixes #4785.
Adds workflow ID to list item already displaying workflow display name, in similar way to how subject sets are listed within workflow editor.
> Add workflow ID to lists and data export

- app/pages/lab/workflows-container.jsx
Staging branch URL: https://fix-4789.pfe-preview.zooniverse.org/
Fixes #4789 and #4431.
I was wrong about what was going wrong here. I thought the lab code was still written to only remove a workflow from being default if the project was live. That got changed a while ago. The issue was in the checkbox click event handler. `defaultWorkflow` was always null because `props.projectConfiguration` isn't a prop that is being passed down, but there was a ternary conditional checking for it being defined, so it never threw since the variable was just always set as null. Not sure how that got through PR review 🤦‍♀️. Anyway, the conditional to check to see whether or not the default workflow should be unset was always false until now.
> Actually remove workflow default setting if active status is toggled to inactive

- package-lock.json
- package.json
Staging branch URL: https://update-seven-ten-client.pfe-preview.zooniverse.org/
Updates to the latest version of the seven-ten client which includes updated dependencies to resolve a TypeError being thrown by the client. 
This project had a TypeError thrown, but is now resolved: 
https://update-seven-ten-client.pfe-preview.zooniverse.org/projects/srallen086/srallen-testing
compared to master:
https://master.pfe-preview.zooniverse.org/projects/srallen086/srallen-testing
> Update to latest Seven-Ten-Client

- app/classifier/classifier.jsx
- app/classifier/drawing-tools/components/DetailsSubTaskForm/DetailsSubTaskForm.jsx
- app/classifier/tasks/dropdown/index.jsx
- app/classifier/tasks/highlighter/index.jsx
- app/classifier/tasks/text/index.jsx
- app/collections/manager-icon.spec.js
- app/collections/settings.spec.js
- app/components/svg-image.jsx
- app/lib/classification-queue.js
- app/lib/preload-subject.coffee
- app/pages/admin/project-status.jsx
- app/pages/admin/project-status.spec.js
- app/pages/admin/user-settings.jsx
- app/pages/admin/user-settings.spec.js
- app/pages/notifications/notification-section.spec.js
- app/pages/project/about/index.jsx
- app/pages/project/classify.jsx
- app/pages/project/project-page.spec.js
- app/talk/active-users.spec.js
- test/enzyme-configuration.js
- test/fake-api-client.js
Staging branch URL: https://enzyme-lifecycle-tests.pfe-preview.zooniverse.org
Fixes #4794 
Turns on lifecycle method testing and fixes broken tests.
With this PR, `shallow()` in Enzyme 3 runs `componentDidMount`. This broke some tests that ran `componentDidMount()` manually. It also means any spies that spy on method calls during mount must be defined before running `shallow()`, not after. There were also some components where `componentDidMount` broke if called with the default component props.
> Enable lifecycle method testing in enzyme

- app/classifier/tasks/survey/index.cjsx
Compare the length of annotation.value with the minimum number of required answers.
Staging branch URL: https://survey-required.pfe-preview.zooniverse.org/projects/thegalaxyonorionsbelt/are-we-alone-in-the-zooniverse/classify?env=production&reload=0&workflow=75
Fixes #4822.
> Fix required survey task answers

- app/classifier/tasks/drawing/markings-renderer.cjsx
Disable drawing mark selection, except for the selected tool, when the selected tool is in progress.
Staging branch URL: https://overlap-drawings.pfe-preview.zooniverse.org/
Fixes #4786.
> Disable mark selection for drawing in progress

- app/classifier/tasks/survey/chooser/Choices.jsx
Link thumbnail size to number of columns: 1 = large, 2 = medium, 3 = small.
Don't show thumbnails for more than 30 choices.
Always show small thumbnails if task.alwaysShowThumbnails is set.
Staging branch URL: https://survey-thumbnails.pfe-preview.zooniverse.org/projects/meredithspalmer/snapshot-grumeti/classify?env=production
> Link survey thumbnail size to number of choice columns

- app/classifier/classifier.jsx
- app/pages/project/classify.jsx
- app/pages/project/classify.spec.js
- app/pages/project/workflow-selection.jsx
- app/pages/project/workflow-selection.spec.js
- app/redux/ducks/classify.js
Builds on #4781.
Remove upcomingSubjects.forWorkflow and currentClassifications.forWorkflow.
Simplify redux actions to work with a single classification and queue.
Update ProjectClassifyPage to use props.classification and props.upcomingSubjects.
Modify WorkflowSelection so that its children don't render unless there is a workflow loaded.
Staging branch URL: https://subject-queue-workflow.pfe-preview.zooniverse.org
> Store a single subject queue and classification

- app/classifier/classifier.jsx
- app/classifier/index.cjsx
- app/classifier/task.jsx
- app/main.cjsx
- app/pages/dev-classifier/index.jsx
- app/pages/project/classify.jsx
- app/pages/project/classify.spec.js
- app/pages/project/workflow-selection.jsx
- app/pages/project/workflow-selection.spec.js
- app/redux/ducks/classify.js
- app/redux/reducers.js
Extract the subject queue code from the classifier and into redux actions for filling the queues, emptying them and getting the next subject to classify.
Removes the `currentClassifications` and `upcomingSubjects` global variables and stores those variables in the redux store instead.
Fixes a bug where the classifier state could preserve old annotations after a new classification had been created.
Fixes a small bug where the classifier annotations array could be accidentally updated at index -1.
Staging branch URL: https://subject-queue.pfe-preview.zooniverse.org/
> Extract the classifier subject queue to the redux store

- package-lock.json
- package.json
Bumps seven ten client to 3.3.2 to get the patch described and tested in https://github.com/zooniverse/Seven-Ten-Client/pull/5
> Bump seven ten client to 3.3.2

- webpack.build.js
This will allow us to deploy our website again, which I broke when I upgraded striptags yesterday.
> Add striptags to the list of ES6 dependencies

- package-lock.json
- package.json
- webpack.build.js
- webpack.dev.js
Staging branch URL: https://css-loader.pfe-preview.zooniverse.org/
Bumps the css-loader dependency, and removes some unused options from the webpack config.
Replaces #4860, since I wasn't sure how dependabot handles manual commits to one of its branches.
> Bump css-loader from 0.28.4 to 1.0.0

- package-lock.json
- package.json
Follow up to #4850. The eslint config isn't configured to even use this plugin, so I'm removing it.
> Remove eslint-plugin-promise

- app/components/thumbnail.jsx
Staging branch URL: https://fix-4821.pfe-preview.zooniverse.org/projects/zooniverse/gravity-spy/classify?env=production
Fixes #4821. This modifies the Thumbnail component to just ignore gifs. You can test by selecting a glitch type in the Gravity Spy survey and check the second example image. These are gifs that slowly loop.
> Do not compress gifs in Thumbnail component

- app/locales/ar.js
- app/locales/de.js
- app/locales/en.js
- app/locales/es.js
- app/locales/fr.js
- app/locales/he.js
- app/locales/nl.js
Staging branch URL: https://remove-word-level.pfe-preview.zooniverse.org/projects/zooniverse/gravity-spy?env=production
The last minor update prior to the Snapshot Wisconsin implementation of workflow promotion. We had hardcoded the word 'level' on the home page workflow buttons for Gravity Spy, but this doesn't make sense for SW's use case. Gravity Spy can add the word back in their workflow name if they want it. (cc @trouille )
> Remove the word level from the workflow buttons

- app/pages/lab/mobile/mobile-section-container.jsx
- app/pages/lab/mobile/mobile-section-container.spec.js
- app/pages/lab/mobile/mobile-section.jsx
- app/pages/lab/mobile/mobile-validations.js
Staging branch URL: https://addimageruleformobile.pfe-preview.zooniverse.org/
Having to do with https://github.com/zooniverse/mobile/pull/203 . We are only allowing one image in a question to show in a mobile task. However, we didn't want this to be a hard line requirement for project builders, so I made this a check, but it's just a warning instead of a failed checl.
In this PR:
- Add Mobile Validation Enum `ValidationValue` so validations can pass, fail or just be a warning
- Add validation rule for number of images in questions (max 1 allowed)
- Some changes to appease the linter
> Add image rule for mobile

- app/redux/ducks/classify.js
On next subject, destroy the old classification if the queue is empty. This should fix a bug where classification subjects persisted after visiting Talk and then remounting the Classifier (which runs the RESUME_CLASSIFICATION action.)
Staging branch URL: https://duplicate-subjects.pfe-preview.zooniverse.org
> Handle empty subject queue on next subject

- app/pages/project/classify.jsx
- app/pages/project/index.jsx
- app/pages/project/workflow-selection.jsx
Move the 'Loading workflow' check from workflow selection down to the project classify page, so that it doesn't block other project pages from loading.
Check the stored classification, and possibly reset it, if the workflow state changes while the classify page is mounted.
Staging branch URL: https://workflow-selection.pfe-preview.zooniverse.org
Fixes #4892.
> Allow project pages to render without a workflow

- .gitignore
- .travis.yml
- README.md
- package-lock.json
- package.json
This should add a coverage report to `npm test` and update Travis to pipe coverage reports to coveralls.
https://coveralls.io/github/zooniverse/Panoptes-Front-End
There's probably a badge we can add to the repo too.
[![Coverage Status](https://coveralls.io/repos/github/zooniverse/Panoptes-Front-End/badge.svg?branch=coveralls)](https://coveralls.io/github/zooniverse/Panoptes-Front-End?branch=coveralls)
> Install nyc and coveralls to measure test coverage

- app/main.cjsx
- views/index.ejs
Staging branch URL: https://fixhashfragmentredirects.pfe-preview.zooniverse.org/
Fixes #4903.
respect the location path when redirecting from old hash fragment paths style url's, e.g. http://www.penguinwatch.org/#/classify
> Fix hash fragment redirects

- package.json
Add nyc to the test-one script, so that you can quickly see which lines are covered when writing unit tests.
> Add a coverage report to the test-one script

- package-lock.json
- package.json
The only PR that references this package is #3928, and those files don't exist any more.
Staging branch URL: https://remove-he.pfe-preview.zooniverse.org
Supersedes #4938.
> Uninstall he

- webpack.dev.js
Staging branch URL: https://fix-express-routing.pfe-preview.zooniverse.org/
Follow up from the Webpack v4 update. I added another dev server config to reroute express server 404s back to index.html. This enables us to edit query params in the url and reload the page correctly. I ran into this when trying to add a search query param to the project admin page.
> Add config to fallback to index.html

- app/classifier/classifier.jsx
- app/classifier/classifier.spec.js
- app/redux/ducks/classify.js
- app/redux/ducks/classify.spec.js
Replace `classification.update` with a saveAnnotations action in the classifier, to make it explicit that annotations are saved when the Classifier component unmounts.
Update the wording on a couple of the Classifier tests to make it less confusing.
Staging branch URL: https://save-annotations.pfe-preview.zooniverse.org/
> Add a saveAnnotations action to the classifier

- app/classifier/drawing-tools/components/Fan/fan.jsx
- app/classifier/drawing-tools/components/Fan/fan.spec.jsx
Add a test for #4925 and fix it by subtracting the spread angle from 360 at large angles.
Staging branch URL: https://fan-tool-spreads.pfe-preview.zooniverse.org/dev/classifier
Fixes #4925 .
> Fix fan tool spread angles

- app/lib/classification-queue.js
- app/lib/classification-queue.spec.js
- app/pages/project/classify.jsx
- test/fake-api-client.js
Add a test for the case where the API save request is not resolved between calls to ClassificationQueue.add().
Fix a bug where pending classifications persisted in the queue, resulting in them being sent again each time a new classification was added to the queue.
Fixes some bugs in the fake API classes that break the tests.
Todo:
Staging branch URL: https://classification-queue.pfe-preview.zooniverse.org
Fixes #4911.
> Classification queue: save each queued classification once only

- app/classifier/classifier.jsx
- app/classifier/classifier.spec.js
- app/classifier/components/Intervention/Intervention.jsx
- app/classifier/components/Intervention/Intervention.spec.js
- app/classifier/tasks/dropdown/editor.spec.js
- app/classifier/tasks/shortcut/editor.spec.js
- app/classifier/tutorial.spec.jsx
- app/lib/session.coffee
- app/locales/en.js
- app/pages/lab/social-links-editor.spec.js
- app/pages/organization/organization-container.spec.js
- app/pages/project/workflow-selection.spec.js
- app/pages/settings/AccountInformationPage.jsx
- app/pages/settings/email.spec.js
- app/redux/ducks/classify.js
- app/redux/ducks/classify.spec.js
- app/redux/ducks/interventions.spec.js
- test/mock-panoptes-resource.js
Staging branch URL: https://interventions.pfe-preview.zooniverse.org/
Fixes #4810.
Allow users to set `user.intervention_notifications` from their account settings page.
Add an opt-out checkbox to the Interventions component.
Track intervention messages and opt in as `classification.metadata.interventions.message` and `classification.metadata.interventions.opt_in`.
Adds tests for the Intervention component and intervention actions.
> Allow volunteers to turn off intervention messages

- app/classifier/classifier.jsx
- app/classifier/classifier.spec.js
Staging branch URL: https://reset-annotations.pfe-preview.zooniverse.org/
Fixes #4968.
Don't save annotations on component unmount. Instead, save annotations to the Redux store whenever the annotations array is updated. Fixes a bug where old annotations could be added to a new classification if the classifier unmounts during the summary step.
> Classifier: don't persist annotations on unmount

- app/classifier/classifier.jsx
- app/classifier/classifier.spec.js
Staging branch URL: https://update-classification.pfe-preview.zooniverse.org/
Replaces `classification.update()` with `updateClassification()` to update classification metadata in the classifier.
Adds a test for classification update on subject image load.
I couldn't see how to stub the feedback modal in tests, so the feedback changes are untested.
> Classifier: use the updateClassification action to update classification metadata

- app/components/subject-viewer.cjsx
Staging branch URL: https://github.com/zooniverse/Panoptes-Front-End/pull/new/ignore-metadata-whitespace
Fixes #4967.
> Trim metadata keys before checking for metadataFilters

- app/features/feedback/shared/strategies/single-answer-question/reducer.js
- app/features/feedback/shared/strategies/single-answer-question/reducer.spec.js
Change the correct answer test to test for the case where the answer is 0 (ie. falsy) but correct.
Update the incorrect answer test to make sure we aren't being tripped up by 0 values.
Fix the reducer to return the correct value when the supplied answer is 0.
Staging branch URL: https://single-answer-feedback.pfe-preview.zooniverse.org
Fixes #4891.
> Fix single answer feedback when the answer is 0

- app/pages/project/stats/stats.jsx
Staging branch URL: https://workflow-progress-completeness.pfe-preview.zooniverse.org/
Compare workflow "Herbarium_WeDigFLPlants’ Lilies, Wakerobins, and Relatives of Florida," which has a `completed` attribute of `1` and therefore is a completed workflow, between:
- current: https://www.zooniverse.org/projects/zooniverse/notes-from-nature/stats
and
- change: https://workflow-progress-completeness.pfe-preview.zooniverse.org/projects/zooniverse/notes-from-nature/stats?env=production
Fixes #4979.
If from a project's Project Builder/Workflows list a workflow is set to show its completeness statistic on the project's stats page based on classification count and the workflow is complete the stats page still calculates a custom percentage which may be different than 100%. The calculated …
> Show workflow stats card as 100% if complete

- app/classifier/classifier.jsx
- app/classifier/expert-options.jsx
- app/redux/ducks/classify.js
- app/redux/ducks/classify.spec.js
Staging branch URL: https://gold-standard.pfe-preview.zooniverse.org/
Fixes #4984.
Fixes #4564.
Adds an action to toggle `classification.gold_standard` and binds the gold standard checkbox to that action.
> Fix the gold standard checkbox

- app/pages/project/index.jsx
Staging branch URL: https://check-for-experimental-tool.pfe-preview.zooniverse.org/
The Snapshot WI split experiment is delayed a week, but in the meantime I double checked the code I added and noticed that the class method that handles the split data to update user's project preferences didn't check to make sure that workflow assignment is enabled for the project. This PR adds a check before the method is called.
> Only use workflow assignment split if workflow assignment is enabled

- Dockerfile
- Jenkinsfile
- package.json
Adds a Jenkinsfile to stage branches at {BRANCH_NAME}.pfe-preview.zooniverse.org.
NB. `BRANCH_NAME` will be something like `PR-4753` for a PR branch.
> Add Jenkinsfile to automatically stage branches

- app/talk/discussion-new-form.cjsx
Fixes #5003 - allow more than 10 discussion radio buttons. I don't think this is great UX but it's a quick fix for a reported issue.
> increase new discussion board request page_size past 10

- app/classifier/drawing-tools/root.jsx
Only try to scroll the window in browsers that support focus() on SVG elements (currently webkit, blink and Firefox.) This should fix an annoying jump to the top of the page that some volunteers are encountering when they try to draw.
Staging branch URL: https://fix-drawing-scroll.pfe-preview.zooniverse.org
Fixes #5007 .
> Fix page scroll when drawing

- app/pages/lab/data-dumps.cjsx
This link has been added to the data exports page along side the Data-digging link.
Staging branch URL: https://add-aggregation-link.pfe-preview.zooniverse.org/
Fixes # .
> Add link to panoptes aggregation code

- app/classifier/classifier.spec.js
- app/pages/project/classify.jsx
- app/redux/ducks/classify.js
- app/redux/ducks/classify.spec.js
Call seenThisSession when the redux completeClassification() action is called.
Remove seenThisSession from the project classify page.
Update tests.
Pure functions can't be stubbed or spied on with Sinon, so this change isn't testable at the moment.
Staging branch URL: https://pr-5030.pfe-preview.zooniverse.org/
> Update seenThisSession on classification complete

- app/redux/ducks/classify.spec.js
Test that subjects are marked as seen, for a workflow, when a classification completes.
> Add a test for seenThisSession on classification complete

- app/pages/admin/project-status.jsx
Add an image layout section to the workflow settings on the project admin page, with a checkbox for the no-max-height setting.
Staging branch URL: https://no-max-height.pfe-preview.zooniverse.org
> Add workflow image layout to project admin form

- app/lib/classification-queue.js
- app/lib/classification-queue.spec.js
Add a timer to flush the failed classification queue five minutes after the current run. Flush should either run the next time that it's called manually, or in five minutes time if it hasn't been invoked yet.
Staging branch URL: https://classification-queue.pfe-preview.zooniverse.org/
> Add a timer to the classification queue

- app/components/wrapped-markdown.jsx
Internal links in markdown are overridden with history.push, so that we don't reload the site and reset classification state. Don't do this if the link has a target attribute, as this means it is probably opening in a new tab or window.
Staging branch URL: https://target-blank.pfe-preview.zooniverse.org
Fixes: #5044
> Don't override markdown links to new tabs

- app/classifier/tasks/text/index.jsx
- app/classifier/tasks/text/index.spec.js
Expect handleResize to be called once when the text value changes.
Fix code that was calling handleResize twice on change.
Use PureComponent, so that unchanged props and state don't trigger a render.
Staging branch URL: https://text-task.pfe-preview.zooniverse.org/
> Text task performance fixes

- app/classifier/tasks/drawing/marking-initializer.cjsx
- app/pages/project/classify.jsx
- app/pages/project/home/home-workflow-button.jsx
- app/pages/project/home/home-workflow-button.spec.js
- app/pages/project/home/home-workflow-buttons.jsx
- app/pages/project/home/home-workflow-buttons.spec.js
- app/pages/project/home/index.jsx
- app/pages/project/home/project-home.jsx
- app/pages/project/index.jsx
- app/pages/project/workflow-selection.jsx
Staging branch URL: https://pr-5035.pfe-preview.zooniverse.org
Removes `listenToProjectPreferences` from the top-level project page component and the `onChangePreferences` callback from its children. Instead, the project workflow buttons are connected to the redux store and set a new workflow when clicked.
Selecting a new workflow clears the current workflow, loads the new workflow from Panoptes, then stores it.
User preferences are still updated on workflow change, but only so as to persist workflow selection across browser sessions. Updating user project preferences does not trigger a re-render of the project components and the fake preferences for anonymous users can be completely removed too.
> Remove preferences change listener from workflow selection

- app/classifier/drawing-tools/freehand-helpers.coffee
- app/classifier/drawing-tools/freehand-line.cjsx
- app/classifier/drawing-tools/freehand-segment-line.cjsx
- app/classifier/drawing-tools/generic-tests.spec.js
Updates the generic drawing tool tests to expect initMove to return an object.
Applies changes to the mock mark before rendering the tool component.
Fixes the freehand line tools to conform with the behaviour expected by the marking initialiser in the drawing task.
Staging branch URL: https://test-drawing-tools.pfe-preview.zooniverse.org/
> Fix freehand line static methods and tests

- app/pages/project/classify.jsx
- app/pages/project/home/home-workflow-button.jsx
- app/pages/project/home/home-workflow-button.spec.js
When we change workflow from the home workflow buttons, or the workflow assignment popup, load the associated translation strings.
Staging branch URL: https://pr-5066.pfe-preview.zooniverse.org
Fixes #5066 .
> Load translation strings on workflow change

- app/features/feedback/shared/helpers/generate-rules.js
- app/features/feedback/shared/helpers/generate-rules.spec.js
- app/features/feedback/shared/helpers/get-feedback-from-tasks.spec.js
- app/features/feedback/shared/helpers/rule-checker.js
Add some quick tests for the shared feedback helper functions. Test that rules are correctly extracted from workflow tasks, and that gold standard subject rules are correctly merged with workflow rules when feedback is enabled.
Includes a test to reproduce #5058, and a fix.
Staging branch URL: https://pr-5068.pfe-preview.zooniverse.org
Fixes #5058.
> Test feedback helpers

- app/lib/nav-helpers/getProjectLinks.js
- app/lib/nav-helpers/getProjectLinks.spec.js
- app/pages/notifications/notification-section.jsx
- app/pages/project/classify.jsx
- app/pages/project/components/ProjectNavbar/ProjectNavbarContainer.jsx
- app/pages/project/components/ProjectNavbar/components/NavLink/NavLink.spec.js
- app/pages/project/home/project-home.jsx
- app/pages/project/home/project-home.spec.js
- app/pages/project/index.jsx
- app/pages/project/project-page.jsx
- app/pages/project/project-page.spec.js
- app/pages/project/workflow-selection.jsx
- test/mockObjects.js
Staging branch URL: https://pr-5078.pfe-preview.zooniverse.org
Check for `project.links.active_workflows` before rendering classify links on the home page or in the project navigation. Move workflow selection down to the project classify page, rather than wrapping the whole project.
> Disable classify links on projects with no active workflows

- app/pages/notifications/notification-section.jsx
Get project avatars when requesting projects and display them instead of the default blue avatar.
Fixes a small problem mentioned on Talk. https://www.zooniverse.org/talk/17/796253?comment=1317721&page=1
Staging branch URL: https://pr-5088.pfe-preview.zooniverse.org
> Notifications: fix project avatars

- app/classifier/classifier.jsx
- app/classifier/classifier.spec.js
- app/classifier/components/Intervention/Intervention.jsx
- app/classifier/components/Intervention/Intervention.spec.js
- app/redux/ducks/classify.js
- app/redux/ducks/classify.spec.js
- app/redux/ducks/interventions.js
- app/redux/ducks/interventions.spec.js
Intervention messages are shown when we classify, so store them in the classifier store. Clear any current intervention message when we start a new classification.
Replace notifications array with a single intervention object. Update the classifier to show interventions if a stored intervention exists.
Add simple validation of the message project ID against classification.links.project.
Staging branch URL: https://pr-5089.pfe-preview.zooniverse.org
> Validate message interventions against classifications

- app/classifier/tasks/components/TaskInputField/TaskInputField.jsx
- app/classifier/tasks/components/TaskInputField/TaskInputField.spec.jsx
- app/classifier/tasks/components/TaskInputField/index.js
- app/classifier/tasks/drawing/index.cjsx
- app/classifier/tasks/highlighter/components/HighlighterButton.jsx
- app/classifier/tasks/multiple/index.jsx
- app/classifier/tasks/multiple/index.spec.js
- app/classifier/tasks/single/index.jsx
- app/classifier/tasks/single/index.spec.js
Use checkbox/radio button state (active, checked or focussed) to control the style of adjacent task labels.
Remove onFocus(), onBlur(), unfocus() and associated tests from TaskInputField.
Convert TaskInputField to a function and add React.memo() for speed.
Works around some problems with the multiple choice and single answer task tests by rewriting them to use shallow rendering. Full mounting of those components won't work until enzyme supports `React.memo()`.
Fixes #5096.
This PR should fix slow/laggy behaviour on phones, where there could be a noticeable delay between tapping an answer and seeing it change colour.
Staging branch URL: https://pr-5091.pfe-preview.zooniverse.org
> Use input widget state to style task inputs

- app/pages/home-not-logged-in.jsx
Fetch the featured project when the not-logged-in home page mounts, and pass it to the featured project component.
Staging branch URL: https://pr-5101.pfe-preview.zooniverse.org
Fixes #5098.
> Fetch featured project when not logged in

- app/layout/site-footer.jsx
- app/pages/lab/index.cjsx
Policies page is now at https://help.zooniverse.org/getting-started/lab-policies
Staging branch URL: https://pr-5105.pfe-preview.zooniverse.org
> Fix broken policies page links

- app/pages/project/classify.jsx
- app/pages/project/home/home-workflow-button.jsx
- app/pages/project/home/home-workflow-button.spec.js
- app/pages/project/workflow-selection.jsx
Staging branch URL: https://pr-5107.pfe-preview.zooniverse.org
- Changes the project home page workflow links so that they defer loading the classify page until the new workflow has loaded.
- Changes workflow selection so that a new workflow is not loaded if there is already an active workflow for the project on mount.
- Updates components that load workflows so that translations are loaded in parallel with workflows, rather than after workflows load.
> Improve workflow selection for anonymous users

- app/classifier/tasks/drawing/index.cjsx
- app/classifier/tasks/multiple/index.jsx
- app/classifier/tasks/single/index.jsx
Staging branch URL: https://pr-5104.pfe-preview.zooniverse.org
#5091 removed the annotation prop from TaskInputField but I forgot to remove it from the instances of the component itself. This removes that prop from the input field in multiple choice, single answer and drawing tasks. It also tidies up the drawing task render method to make the tool choices easier to understand.
> Remove unused annotation prop from task inputs

- app/pages/project/home/home-workflow-button.spec.js
Staging branch URL: https://pr-5115.pfe-preview.zooniverse.org
Updates project home workflow button tests to convert them from `assert` to `expect` and test for changes that were made in #5107.
> Update project workflow link tests

- app/components/ExternalLinksBlock/ExternalLinksBlockContainer.jsx
Staging branch URL: https://dont-render-invalid-urls.pfe-preview.zooniverse.org/
Related to #5140, prevents a suspicious URL from being rendered on the project home page.
> Dont render invalid urls on Project home page

- app/components/ExternalLinksBlock/ExternalLinksBlock.jsx
- app/components/ExternalLinksBlock/components/ExternalLink/ExternalLink.jsx
- app/components/ExternalLinksBlock/components/ExternalLink/ExternalLink.spec.jsx
This PR fixes an XSS vulnerability on External links of the Project pages, by rendering the External links in Markdown (which auto-sanitises the URLs)
Fixes #5138
Staging branch: https://fix-xss.pfe-preview.zooniverse.org
_Screenshot shows an example project with an External Link that has JavaScript code as its URL. The <Markdown> element prevents the code from rendering properly._
_The external links on the example project, without the new fixes in this PR._
Minor side effects of this PR:
- Invalid URLs are no longer rendered as hyperlinks - it looks terrible when this happens, but it's safer than the current behaviour.
- Small style changes - note that the icons are no longer clickable.
Baseline comparison (without fixes in branch):
- go to …
> Implement XSS safety - External links on Project pages are now rendered in Markdown

- app/pages/lab/external-links-editor.jsx
Make both text inputs required.
Use input[type=url] for URLs and add simple pattern matching for http[s]:// URLs.
Add some string validation on change for both inputs.
Staging branch URL: https://pr-5140.pfe-preview.zooniverse.org
> Add simple URL checks to the external URL editor

- app/components/ExternalLinksBlock/ExternalLinksBlockContainer.jsx
- app/components/ExternalLinksBlock/components/ExternalLink/ExternalLink.jsx
- app/components/ExternalLinksBlock/components/ExternalLink/ExternalLink.spec.jsx
Restore social media link rendering that was removed in #5142, so that the social media icons have accessible labels again.
https://pr-5146.pfe-preview.zooniverse.org
> Restore social link ARIA labels

- app/redux/ducks/translations.js
- app/redux/ducks/translations.spec.js
Add tests for translations load, listLanguages and setLocale.
Update listLanguages action to be testable and consistent with load action.
Staging branch URL: https://pr-5154.pfe-preview.zooniverse.org
> Add translations actions tests

- app/classifier/index.cjsx
- app/classifier/mini-course.cjsx
We now store translations by translated type and translated ID, so we can store more than one tutorial translation at a time. Replace the old minicourse translation type with tutorial.
Staging branch URL: https://pr-5166.pfe-preview.zooniverse.org
> Fix mini-course translation API errors

- app/pages/project/classify.jsx
- app/pages/project/home/home-workflow-button.jsx
- app/pages/project/home/home-workflow-button.spec.js
- app/pages/project/workflow-selection.jsx
- app/pages/project/workflow-selection.spec.js
- app/redux/ducks/classify.js
- app/redux/ducks/classify.spec.js
Staging branch URL: https://pr-5124.pfe-preview.zooniverse.org
Add a `loadWorkflows` action creator to the classifier. Given a workflow ID, locale and optional preferences, it clears the current workflow, empties the subject queue, loads the workflow translations, loads the workflow and updates preferences to store the workflow ID. If the API request errors, the stored workflow is set to null and the preference changes are rolled back.
Classifier state is reset before loading a new workflow, which fixes #5149.
> Add a load workflows action to the redux classify store

- app/pages/project/classify.jsx
Check that project assigned workflows are active before showing the workflow assignment popup. If they are not active, clear `preferences.settings.workflow_id`. Update workflow assignment to use `componentDidUpdate` rather than `componentWillReceiveProps`.
Staging branch URL: https://pr-5171.pfe-preview.zooniverse.org
> Validate project assigned workflows

- app/pages/project/workflow-selection.jsx
- app/pages/project/workflow-selection.spec.js
- app/redux/ducks/classify.js
Spec out how loading a workflow from the API should work in the Workflow Selection component, based on the workflow tests in #5124. Adds some tests for successful workflow requests and a couple of failing tests for API errors, reproducing #5173 and #5165.
Update workflow error handling so that it only runs if the workflow ID is invalid, rather than for all workflow IDs.
Fixes #5173.
Fixes #5165.
Staging branch URL: https://pr-5187.pfe-preview.zooniverse.org
> Add spec tests for workflow selection

- app/classifier/classifier.jsx
Add subject selection state flags to the classification metadata. This should help debug issues with already seen subjects.
Staging branch URL: https://pr-5197.pfe-preview.zooniverse.org
Fixes #4949.
> Add subject flags to classifications

- app/main.cjsx
- app/pages/project/classify.jsx
- app/pages/project/workflow-selection.jsx
- app/pages/project/workflow-selection.spec.js
- app/redux/ducks/classify.js
- app/redux/ducks/classify.spec.js
Reset the classifier store to its initial state on log in or log out. This should clear the stored workflow, empty the subject queue and destroy any incomplete classifications.
Key workflow selection by workflow ID, so that workflow selection mounts and runs again when the stored workflow is reset to null.
Staging branch URL: https://pr-5186.pfe-preview.zooniverse.org
Fixes #5184.
> Reset the classifier on auth change

- app/pages/project/components/ProjectNavbar/components/ProjectTitle/ProjectTitle.jsx
Fixes #4529.
@beckyrother mentioned that the icon in the project title shouldn't be underlined on rollover. Here's her screenshot: 
Here's the updated title on rollover. 
On `ProjectNavbarWide`: 
And `ProjectNavbarNarrow`:
> Remove underline from Project Title icon

- app/classifier/tasks/survey/editor.cjsx
Staging branch URL: https://pr-5227.pfe-preview.zooniverse.org
Fixes #5208 by specifying the delimiter to use. Papaparse patched their auto-detection of delimiters and now is detecting both the comma and the semi-colon as delimiters in the survey task csvs. We still only want it to parse the comma separated values and manually handle the separation of the semi-colon separated values (answer options for a single question for instance).
> Specify the delimiter to use when parsing survey task csvs

- app/components/subject-viewer.cjsx
Avoid 'cannot read property x of null' errors on subject metadata by checking values exist before manipulating them as strings.
Staging branch URL: https://pr-5234.pfe-preview.zooniverse.org
> Check for subject metadata values

- app/pages/project/components/ProjectNavbar/ProjectNavbar.jsx
Removes componentDidUpdate from the project nav, since calling setBreakpoint without an argument does nothing.
Staging branch URL: https://pr-5240.pfe-preview.zooniverse.org
> Remove componentDidUpdate from ProjectNavbar

- app/pages/project/index.jsx
- app/pages/project/workflow-selection.jsx
Set preferences to null by default, otherwise the loadWorkflows action will fail with 'preferences.update is not a function'.
Staging branch URL: https://pr-5236.pfe-preview.zooniverse.org
> Workflow selection: default preferences to null

- css/home-page.styl
I noticed a handful of issues with homepage text when viewing on mobile. I've annotated the changes in comments within the code so it's easier to see what changes go with what.
Here are the monster before and after screenshots: 
Required Manual Testing
Review Checklist
Optional
> Mobile-friendly homepage text

- app/pages/project/classify.jsx
- app/pages/project/workflow-selection-classroom.jsx
- app/pages/project/workflow-selection-classroom.spec.js
Add a new workflow strategy for classrooms, which always loads the workflow from a workflow query parameter.
ToDo:
Staging branch URL: https://pr-5259.pfe-preview.zooniverse.org
Fixes #5256.
> Add a workflow selection strategy for classrooms

- app/components/thumbnail.jsx
- app/lib/get-subject-location.coffee
- app/lib/get-subject-locations.js
- app/pages/project/home/project-home.jsx
- app/talk/discussion-preview.cjsx
- app/talk/search-result.jsx
- app/talk/tags.cjsx
Staging branch URL: https://pr-5270.pfe-preview.zooniverse.org
Fixes #5269 
Remove explicit  references to `.mp4` files from the code.
Pass a type prop to thumbnail previews, with value `image|audio|video`.
Add `x-m4v` to the list of allowed subject video formats when rendering subjects.
> Preview video formats other than mp4

- app/pages/lab/data-exports.jsx
- app/pages/lab/data-exports.spec.js
- app/partials/data-export-button.cjsx
- app/partials/data-export-download-link.jsx
- app/partials/data-export-download-link.spec.js
Panoptes is going to remove the API to get a distinct workflow_contents export, because that resource itself is going away. This removes the button from the exports page.
I've split up the existing DataExportButton component and extracted a DataExportDownloadLink. This allowed me to keep the link for the workflow_contents export, while not letting people request new ones.
The logic was easy to pick apart, it was already neatly packaged into different functions. However, I've had to go from Coffee to ES, so someone having a look at that conversion would be appreciated.
> Remove workflow contents export button

- app/pages/lab/workflow.cjsx
Toward #5279.
This disables the test workflow button if no tasks are defined. The drawing task and survey task still break the classifier if no drawing tools or none of the survey task items are defined, but doing validations/default values for those are a bit more involved and should be fixed individually.
> Disable test workflow button if no tasks are defined

- app/components/subject-viewer.cjsx
- css/classify.styl
Staging branch URL: https://pr-5274.pfe-preview.zooniverse.org/projects/markb-panoptes/backyard-worlds-test-project-mb/classify
Closes #5092.
- adds slider to control multi-image frame rate duration
> Add subject frame duration slider

- app/components/subject-viewer.cjsx
- app/subjects/subject-page.jsx
- app/talk/comment.cjsx
- css/subject-viewer.styl
Staging branch URL: https://pr-5284.pfe-preview.zooniverse.org/projects/markb-panoptes/backyard-worlds-test-project-mb/talk/187/319
Closes #5094.
- adds invert button to Talk subject page and Talk comment page subject viewer
- inverts subject image or video using CSS `filter: invert(100%)`, does not work with IE
- keeps classification invert button functionality as is (supporting IE)
> Add invert subject to talk

- app/locales/ar.js
- app/locales/en.js
- app/locales/es.js
- app/locales/fr.js
- app/locales/he.js
- app/locales/it.js
- app/locales/nl.js
- app/pages/about/publications-page.jsx
This PR adds a small bit of text to the [Publications](https://www.zooniverse.org/about/publications) page, providing a small bit of extra info to users. 
As described in the original PR, the intention of this update is:
> Short text & form link to the top of publications page for easy access.
Replaces #5285, by fixing the layout and hooking up the intended text to our language translatomatics.
_The "Submit New Publication" text appears above the list of publications._
_Note: the tops of the sidebar and main section don't align no more because the new text is in a Markdown block that adds unnecessary margins. I am ashamed_
**Collateral Updates:**
- All the locale files were updated so the structure of the `pages.about.publications` section of every language matches that of the English's. …
> Add form link to publications page (Mk II)

- app/redux/ducks/classify.js
- app/redux/ducks/classify.spec.js
- app/redux/ducks/interventions.js
avoid showing the intervention state of a subject in the UI
Staging branch URL: https://pr-5278.pfe-preview.zooniverse.org
Fixes #5277.
> hide subject intervention metadata

- app/pages/admin/project-status.jsx
Staging branch URL: https://pr-5292.pfe-preview.zooniverse.org/admin/project_status/markb-panoptes/nfnorgtest-moths
Fixes on project admin page, Project state section, if project is "Active" the radio input won't show as checked. This is due to how this Active state is updated (as `state: ''`) and returned (as '`state: 'live'`), see [this comment](https://github.com/zooniverse/Panoptes-Front-End/pull/4204#pullrequestreview-81558681).
This is the lowest of priorities.
> Fix project admin state active radio

- app/classifier/tasks/next-task-selector.cjsx
- app/pages/lab/workflow.cjsx
This adds a fallback UI for tasks that do not have editors like the annotation task for the light curve viewer. This is to make it easier to do other workflow editor actions by preventing the app from crashing like linking subject sets, tutorials, etc in the UI. 
Try on staging at: https://pr-5295.pfe-preview.zooniverse.org/lab/1862/workflows/3280
> Fallback for task that is missing an editor in the lab

- app/features/feedback/shared/strategies/single-answer-question/reducer.js
- app/features/feedback/shared/strategies/single-answer-question/reducer.spec.js
Staging branch URL: https://pr-5297.pfe-preview.zoonvierse.org/projects/markb-panoptes/feedback-testing-mb/classify?workflow=3313
Fixes: [don't select an answer, click Next/Done](https://master.pfe-preview.zooniverse.org/projects/markb-panoptes/feedback-testing-mb/classify?workflow=3313)
- adds check for null answer
- updates tests for null answer
> Fix feedback single-answer-question left null

- app/classifier/classifier.jsx
- app/components/subject-viewer.cjsx
- app/features/feedback/classifier/components/feedback-modal.jsx
- css/feedback.styl
- demo with current PFE: https://master.pfe-preview.zooniverse.org/projects/markb-panoptes/backyard-worlds-test-project-mb/classify?reload=0&workflow=3312
- demo with changes to PFE feedback: https://add-subject-viewer-feedback-modal.pfe-preview.zooniverse.org/projects/markb-panoptes/backyard-worlds-test-project-mb/classify?reload=0&workflow=3312
Uses SubjectViewer instead of FrameViewer in the feedback modal. Provides multi-image subject image buttons and other related controls. Hides Collection button, as I think issues with modal on top of modal, but allows favoriting, which might be handy if user wants to follow-up on why they got feedback right or wrong.
> Add subject viewer to feedback modal

- app/pages/notifications/comment.cjsx
- app/pages/notifications/data-request.cjsx
- app/pages/notifications/message.cjsx
- app/pages/notifications/moderation.cjsx
- app/pages/notifications/notification-section.jsx
- app/pages/notifications/started-discussion.cjsx
Staging branch URL: https://pr-5301.pfe-preview.zooniverse.org
Fixes issue noted in Talk/Troubleshooting - https://www.zooniverse.org/talk/17/735435?comment=1555431.
Updates notification delivered attribute to true when click link to related resource.
> Update notification to delivered onClick

- app/constants/languageMenu.js
> Fix the language code for Portugese

- app/pages/lab/translations/index.jsx
Update the wording of the lab translations page to make it clear that ticking a language checkbox publishes that language for your project.
Staging branch URL: https://pr-5315.pfe-preview.zooniverse.org
> Change Live to Published for translations

- app/classifier/drawing-tools/components/DetailsSubTaskForm/DetailsSubTaskForm.jsx
- app/classifier/drawing-tools/components/DetailsSubTaskForm/DetailsSubTaskForm.spec.js
Translations are now keyed by resource ID, so get workflow translations by workflow ID before getting the strings for individual detail tasks.
Staging branch URL: https://pr-5310.pfe-preview.zooniverse.org
Fixes #5309.
> Get detail task translations by workflow ID

- app/pages/notifications/notification-section.jsx
- app/pages/notifications/notification-section.spec.js
I hope fixes #5301, as currently notifications still not marked as "read" (`delivered: true`) after clicking to related source.
- binds `markAsRead`
- refactor `markAsRead`, including filtering on `subscription_id`, though imperfect, I think best option that applies to all sources (i.e. comment, moderation, data request, etc.)
> Fix notification-section markAsRead

- app/collections/collection-search.cjsx
- app/collections/collections-manager.jsx
- app/collections/manager-icon.jsx
Staging branch URL: https://pr-5313.pfe-preview.zooniverse.org
Add an autoFocus prop to the collections manager popup and focus the search input when it opens.
Also fixes a bug where the Add button would remain active if you delete the selected collection.
> Autofocus collection manager modal

- app/router.cjsx
Required for allowing the LCV app to be reverse proxied to PFE. This will need us to add the actual route using it once we're ready to go live.
cc @adammcmaster @camallen
> Add a component to force a full refresh on entering a given route

- app/classifier/classifier.jsx
Linked to https://github.com/zooniverse/Panoptes/pull/3112/files
Tie the selection event timing to the classification metadata for debugging
> add subject selected_at metadata to classification

- app/pages/lab/mobile/mobile-section-container.fixtures.js
- app/pages/lab/mobile/mobile-section-container.jsx
- app/pages/lab/mobile/mobile-section-container.spec.js
- app/pages/lab/mobile/mobile-section.jsx
Staging branch URL: https://pr-5326.pfe-preview.zooniverse.org
Previously, only question tasks with two choices could be marked as `mobile_friendly`. This PR allows project owners to add a workflow to the mobile app if there are more than two questions.
Additional changes:
- Improve tests to cover warning state when a workflow question contains more than one image
- There's a minor bug where a markdown image tag counts against a task question's 200 character max count. I added code to fix the bug but some changes are also needed in the app to reflect this. For now, the code is commented out, but I don't mind removing if it's unnecessary.
> Allow Tasks with Two Plus Options to be Mobile Friendly

- css/organization-page.styl
Edits the organization links section heading styling closer to the [project external links section heading](https://github.com/zooniverse/Panoptes-Front-End/blob/master/css/project-page.styl#L157). Purposefully not editing content.
> Edit org links heading style

- app/classifier/classifier.jsx
- app/classifier/components/Intervention/Intervention.jsx
- app/classifier/components/Intervention/Intervention.spec.js
- app/redux/ducks/classify.js
- app/redux/ducks/classify.spec.js
Staging branch URL: https://pr-5341.pfe-preview.zooniverse.org
Fixes #5337.
Adds a `clearIntervention` action to the classifier and calls it from the `Intervention` component on component cleanup. Changes the `nextSubject` action so that it doesn't clear any stored interventions by default.
> Clear interventions after they've been displayed

- app/classifier/components/Intervention/Intervention.jsx
- app/classifier/components/Intervention/Intervention.spec.js
- app/locales/en.js
use markdown to render the optOut string correctly with a link to study. ~Also test the default translation fall back works~
Fixes # .
> add links to the opt out message

- app/redux/ducks/classify.js
- app/redux/ducks/classify.spec.js
Ensure we only show intervention messages for specified project, workflow combinations, if the intervention payload has a `workflow_id`. If there is no specified payload `workflow_id` default to project wide messages but still check the `project_id` matches the current store state.
Also ensure we compare project and workflow ids as strings as as sugar messages have int link ID values.
Fixes # .
> Only show intervention messages if workflow matches payload

- app/router.cjsx
The RELOAD component will now redirect to a new URL (passed as the `newUrl` prop). This means that in staging, going to a route which returns this component will redirect to `newUrl`, rather than getting trapped in a refresh loop.
> Change `RELOAD` component to redirect when not in production

- app/redux/ducks/classify.js
- app/redux/ducks/classify.spec.js
Track the intervention payload UUID in the next classification metadata, this links the any classification after an intervention message was seen.
linked to https://github.com/zooniverse/interventions-gateway/issues/28
Fixes # .
> Track intervention UUID in classification metadata for downstream clients

- app/classifier/components/Intervention/Intervention.jsx
- app/classifier/components/Intervention/Intervention.spec.js
Staging branch URL: https://pr-5349.pfe-preview.zooniverse.org
Expect that the Intervention component will not call `props.unMount` on props change. Update `useEffect` to pass that test.
> Only clear interventions on Intervention unmount

- app/classifier/components/Intervention/Intervention.jsx
- app/classifier/components/Intervention/Intervention.spec.js
- app/locales/en.js
- css/default-classification-summary.styl
Ensure the intervention opt-out is valid HTML and ensure the UI is visually distinct from the researcher messaging.
Fixes # .
> Fix intervention message html and add styling

- app/redux/ducks/classify.js
- app/redux/ducks/classify.spec.js
drop incoming intervention messages if one is already stored in state to avoid the clobbering existing intervention data.
If we don't clobber the stored incoming intervention state we avoid potential UI updates while i'm looking at a message and we avoid the need to track with UUID should be cleared. 
Alternative implementation to #5351
Fixes # .
> do not clobber intervention state on incoming data

- app/talk/board.cjsx
- app/talk/discussion-new-form.cjsx
Staging branch URL:  https://pr-5358.pfe-preview.zooniverse.org/
- please see linked issue below, then relatedly - https://pr-5358.pfe-preview.zooniverse.org/projects/pangorilla/wild-gabon/talk/subjects/12048508?env=production
Fixes #5357.
- checks for project prop, if exists, requests related boards, if project prop doesn't exist, requests project from subject resource then requests related boards
> Request Talk boards with project prop

- app/collections/show-list.cjsx
Fixes #5368 - determine the project talk context via the following:
1. use known project context if it exists
2. use the first collection projects link if there is only 1
3. fall back to the originating subject project
Staging branch URL: https://pr-5369.pfe-preview.zooniverse.org/
Test by visiting a subject collection page like 
https://www.zooniverse.org/projects/pangorilla/wild-gabon/collections/dj-59/babies
vs 
https://pr-5369.pfe-preview.zooniverse.org/projects/pangorilla/wild-gabon/collections/dj-59/babies
> wire subject talk links to correct project

- app/classifier/tasks/dropdown/index.jsx
- app/classifier/tasks/dropdown/index.spec.js
Staging branch URL: https://pr-5373.pfe-preview.zooniverse.org
Fixes #5370.
Use the `translations` object, instead of the `task` object, to get dropdown menu options.
Update tests.
> Show translated options in dropdown tasks

- app/pages/admin/project-status.jsx
- app/pages/admin/project-status.spec.js
Fixes #5367 - allow admins to change a workflow's retirement config between `classification_count` and `never_retire`
Staging branch URL: http://pr-5377.pfe-preview.zooniverse.org
> add retirement config selectors to admin page

- app/classifier/classifier.jsx
- app/classifier/classifier.spec.js
- app/redux/ducks/classify.js
- app/redux/ducks/classify.spec.js
Avoid storing intervention metadata in different places instead consolidate all interventions metadata to the one object store.
Fixes # .
> record the last intervention UUID on the interventions metadata object

- app/pages/project/home/index.jsx
Staging branch URL: https://pr-5394.pfe-preview.zooniverse.org
- [staging project with some complete workflows](https://pr-5394.pfe-preview.zooniverse.org/projects/markb-panoptes/some-completed-workflows)
- [staging project with all complete workflows](https://pr-5394.pfe-preview.zooniverse.org/projects/markb-panoptes/all-completed-workflows)
See #5338.
Based on new API workflow request functionality allowing [filter on workflow completeness](https://github.com/zooniverse/Panoptes/pull/3138), this PR refactors the project home page workflow request to initially request incomplete workflows, but if response empty request all active workflows.
> Edit project home workflows request to initially filter on completeness

- app/pages/organization/organization-container.spec.js
- app/pages/organization/organization-page.jsx
- app/pages/organization/organization-page.spec.js
Staging branch URL: https://pr-5395.pfe-preview.zooniverse.org
- staging example: https://pr-5395.pfe-preview.zooniverse.org/organizations/markb-panoptes/test-urls
Fixes if organization has no external or social links, then organization page won't render.
> Conditionally render organization link section

- app/lib/get-social-data.js
Staging branch URL: https://pr-5376.pfe-preview.zooniverse.org
This is trivial, but noticed the other day if a project is launched, then set back to development for a quick fix (oh no forgot something), it'll still show on zooniverse.org's Latest Project or Project Updates. This PR edits those queries to mirror [zooniverse.org/projects's queries](https://github.com/zooniverse/Panoptes-Front-End/blob/master/app/pages/projects/index.jsx#L95-L100).
If testing watch out for admin mode, which changes response, and if testing on staging the Latest Project doesn't make sense, I think old staging projects are causing a strange response. Also [status and state are equivalent](https://github.com/zooniverse/Panoptes-Front-End/blob/master/app/pages/projects/project-filtering-interface.jsx#L60) for …
> Add state: live to project queries on home

- app/talk/lib/roles.coffee
Staging branch URL: https://pr-5416.pfe-preview.zooniverse.org
This should allow Talk owners/admins to set up boards that can only be accessed by translators. Translators are added at the bottom of the permissions tree, so don't have access to any other restricted boards.
> Add translator as a Talk role

- app/pages/project/index.jsx
Use a project's primary language to set the locale on initial load, unless a language query param is present.
Staging branch URL: https://pr-5414.pfe-preview.zooniverse.org
Fixes #5333.
> Set locale from project primary language

- app/pages/lab/translations/index.jsx
- app/pages/lab/translations/translation-tools.jsx
Staging branch URL: https://pr-5407.pfe-preview.zooniverse.org
Updates the translation pages in the project builder to link to https://translations.zooniverse.org
~~Waiting on zooniverse/pandora#116 and the Panoptes translations editor being deployed.~~
> Project Builder: Link to the production translation editor

- .github/PULL_REQUEST_TEMPLATE.md
I got tired of typing out the staging URL by hand on each PR. With this, you should just have to update the number.
> Add a template URL for staged PRs

- app/partials/register-form.cjsx
Staging branch URL: https://pr-5412.pfe-preview.zooniverse.org/
Fixes #4553 
Adds a regex browser validation to prevent users from submitting email addresses in the real name field.
> Add browser based validation for the real name field

- app/pages/project/components/ProjectNavbar/ProjectNavbar.jsx
Render a wide navbar initially, until we can calculate a breakpoint, then render the appropriate navbar component, depending on the viewport size. This ensures that the page width will not overflow the viewport on small screens, which allows us to draw without scrolling the page sideways.
Staging branch URL: https://pr-5400.pfe-preview.zooniverse.org
Fixes #5399.
> Fit project nav into the browser viewport

- app/classifier/tasks/multiple/index.jsx
- app/classifier/tasks/multiple/index.spec.js
- app/classifier/tasks/single/index.jsx
- app/classifier/tasks/single/index.spec.js
Adds tests to the question task to check autofocus in the cases where autoFocus is true or false, and where the task has a selected answer or not.
Staging branch URL: https://pr-5422.pfe-preview.zooniverse.org
> Question tasks: test the autofocus prop

- app/partials/data-export-download-link.jsx
clarify the link wording to make it explicit so users know they can download their file
Staging branch URL: https://pr-5427.pfe-preview.zooniverse.org
> change download export link wording

- app/collections/show-list.cjsx
if we can't determine the URL context for a talk board, then fallback to the subjects' uploading project context, do not use the collection context as it is missing project links for collections originally created in a project talk context but then used to collect subjects across the zooniverse. I.e. the collection project link was only set on create and not when adding subjects in other project contexts
Staging branch URL: https://pr-5440.pfe-preview.zooniverse.org
> use subject's uploading project as fallback for talk

- app/features/feedback/shared/helpers/generate-rules.spec.js
- app/features/feedback/shared/helpers/metadata-to-rules.js
- app/features/feedback/shared/helpers/metadata-to-rules.spec.js
Add a feedback test for the case where the subject rule doesn't match a workflow task rule.
Convert metadata values to strings before checking their existence.
Spec the function that converts subject metadata to feedback rules.
Staging branch URL: https://pr-5445.pfe-preview.zooniverse.org
Fixes #5444.
> Fix undefined rule error for feedback

- app/pages/project/home/home-workflow-buttons.jsx
- app/pages/project/home/project-home.jsx
Pass the project translation down to the HomeWorkflowButtons component and use that to display the workflow description.
Staging branch URL: https://pr-5456.pfe-preview.zooniverse.org
Towards #5451.
> Use translated workflow description on project home page

- app/pages/home-for-user/recent-messages.jsx
- app/talk/inbox.cjsx
Staging branch URL: https://skip-deleted-user-messages.pfe-preview.zooniverse.org/
Messages from deleted users are broken, and often this comes up with spam messages that we don't want cluttering up the message list.
This PR simply doesn't display those messages in the inbox – this is obviously not ideal (this results in less than 10 messages being listed on the page, and the empty `div` is ugly) but it's the quickest workaround I can think of and imho it'll do for now.
> Don't display private messages from deleted users

- app/classifier/tasks/drawing/hide-previous-marks-toggle.jsx
- app/locales/cs.js
- app/locales/en.js
- Add an EN and CS translation for `hide previous marks`, with count interpolation
- Remove text string from tool and use `Translate` component instead
Fixes #5484
> Translate `hide previous marks` tool

- app/locales/fr.js
Here I've translated from line 0 to 258. I have another commit here https://github.com/zooniverse/Panoptes-Front-End/compare/master...gabocks:patch-2
but I do not understand how to put them together.
Staging branch URL: https://pr-5481.pfe-preview.zooniverse.org
Fixes # .
> Add french translation to PFE

- app/locales/index.js
- app/main.cjsx
- app/pages/project/index.jsx
- app/partials/app.cjsx
Add a locales object which stores all registered locales, then dynamically load this into counterpart. Contributors then don't have to remember to edit the code in two places in order to add a new language.
Check the URL for a language on first load, so that we can display translated pages such as:
https://pr-5493.pfe-preview.zooniverse.org/about/faq?language=cs
Staging branch URL: https://pr-5493.pfe-preview.zooniverse.org
> Register new locales in one place

- app/lib/draggable.jsx
- app/lib/draggable.spec.js
Staging branch URL: https://pr-5489.pfe-preview.zooniverse.org
Fixes #5462.
Adds tests for multitouch gestures to the Draggable component.
Wraps each of Draggable's event handlers inside a test that checks if `event.touches` only contains one touch.
> Disable drawing for multi-touch events

- package-lock.json
- package.json
Updates some outdated dependencies, which dependabot can't update automatically. Should fix the security warning about an outdated version of `mem` by removing version 1.1.0 from the package lock file.
Staging branch URL: https://pr-5506.pfe-preview.zooniverse.org
> [Security] upgrade webpack-dashboard

- README.md
- docker-compose.yml
Add `npm start` as the default entrypoint for docker-compose. Update the README instructions for local development with docker.
Staging branch URL: https://pr-5502.pfe-preview.zooniverse.org
> Add a default entrypoint for local development

- app/pages/home-not-logged-in.jsx
- app/pages/home-not-logged-in/research.jsx
Staging branch URL: https://pr-5518.pfe-preview.zooniverse.org
Fixes #4043 following style of #4511 solution.
Offset between true DB user count and the current/old displayed value is because the old count excluded Ouroboros users (where `USERS.OUROBOROS_CREATED` is true).  That population is currently 124921, so that is the offset used in this fix.  I'll note that this number appears to fluctuate with time (?): it was 126571 on 17 May 2019 and ~118600 in Sep 2017.
Edit to initialize counter to 0 in app/pages/home-not-logged-in.jsx follows fix in #4526.
> Fix volunteer count via constant offset

- app/pages/notifications/comment.cjsx
- app/pages/notifications/moderation.cjsx
- app/pages/notifications/notification-section.jsx
Pass a notification section's project down as a prop to children.
Add the project prop to Talk comments and moderation reports, so that link URLs point to the parent project.
Staging branch URL: https://pr-5525.pfe-preview.zooniverse.org
Fixes #5524.
> Fix notification project links

- app/lib/draggable.jsx
- app/lib/draggable.spec.js
Fixes #5527 
Staging branch URL: https://pr-5528.pfe-preview.zooniverse.org
Currently, if we attempt to perform a marking task on a touchscreen device, _two_ annotation marks are created instead of one. This is caused by the `onPointerDown` and `onTouchStart` handlers (in the `Draggable` class) firing simultaneously when a touchscreen device detects touch input.
This PR fixes that issue by checking if Pointer Events exist on the browser, and if available, using it instead of Mouse Events or Touch Events. This prevents redundant events from firing.
(Note: we shouldn't remove Mouse Events or Touch Events altogether, since they're good fallbacks for less modern browsers.)
Ready for review, and this might be of interest to @eatyourgreens and @simensta
> Fix 5527: prevent double annotations on touchscreen marking tasks

- app/classifier/drawing-tools/drag-handle.cjsx
Multiply the drawing tool drag handle size by 2.5 on screens smaller than 900px.
Staging branch URL: https://pr-5537.pfe-preview.zooniverse.org
Fixes #5536.
> Adjust drawing tool drag handle size

- app/classifier/tasks/survey/choice.jsx
- app/classifier/tasks/survey/chooser/Choices.jsx
- app/classifier/tasks/survey/chooser/Chooser.jsx
- app/classifier/tasks/survey/image-flipper.jsx
- app/classifier/tasks/survey/index.jsx
Staging branch URL: https://pr-5533.pfe-preview.zooniverse.org
Towards #5531.
Add more descriptive labels to the controls for example images.
Make the example image a live region.
Lint survey task components.
> Improve accessibility of survey task example photos

- app/pages/lab/subject-set.cjsx
Remove the admin restriction for video and audio uploads.
Add `text/*` and `application/json` to the list of allowed MIME types.
Add `.txt` and `.json` to the list of allowed file extensions.
Staging branch URL: https://pr-5532.pfe-preview.zooniverse.org
> Expand the allowed subject upload list

- app/pages/lab/mobile/mobile-section-container.jsx
- app/pages/lab/mobile/mobile-section-container.spec.js
- app/pages/lab/mobile/mobile-section.jsx
- package-lock.json
Staging branch URL: https://pr-5476.pfe-preview.zooniverse.org
Fixes # .
DO NOT MERGE until https://github.com/zooniverse/mobile/pull/279 is merged **and** deployed to the app store
This PR allows a workflow with the flipbook to be tagged mobile friendly. See more at the linked PR above. There is really no reason the mobile app shouldn't allow a flipbook in the app since multi-image subjects are now supported.
> Remove mobile flipbook check

- app/pages/admin/project-status/experimental-features.jsx
Disables the grid experimental tool by removing it from the list of available experimental features.
I haven't removed the code yet, as there are two projects still using it - the prototype OCR project for Old Weather it was originally built for, and a test project owned by @snblickhan. My plan for this is to:
- Inform the OW team
- Remove the tool from the OCR project workflow
- Delete the code from PFE
> Remove grid tool from list of experimental features

- webpack.dev.js
I've been seeing https://github.com/webpack/webpack-dev-server/issues/2313, so I'm removing the https dev server config for now until it is fixed. I'm also removing the auto open config because it'll open to `localhost` which is not useful (since you should be using `local.zooniverse.org` or one of the other allowed sub-domains)
> Remove https and open config options

- css/secondary-page.styl
- css/typography.styl
- views/index.ejs
- Removes the link to Open Sans in the base html
- Removes references to Open Sans in the styling
- Removes references to Gill Sans in the styling
Fixes #5237.
(BTW, the CSS font spec only requires quotes in certain cases - in ours, it's perfectly fine to use font names unquoted.)
> Remove unused fonts

- app/router.cjsx
Forces links to the Planet Hunters TESS homepage to trigger a full-page refresh, picking up the new home page.
Found by @camallen - https://zooniverse.slack.com/archives/CANKLB50E/p1575643088080700
> Add refresh for PHT home page

- app/components/ExternalLinksBlock/ExternalLinksBlock.jsx
- app/components/ExternalLinksBlock/ExternalLinksBlockContainer.jsx
- app/components/ExternalLinksBlock/components/ExternalLink/ExternalLink.jsx
- app/components/ExternalLinksBlock/components/ExternalLink/ExternalLink.spec.jsx
- app/locales/en.js
- app/pages/organization/organization-container.jsx
- app/pages/organization/organization-container.spec.js
- app/pages/organization/organization-metadata.jsx
- app/pages/organization/organization-metadata.spec.js
- app/pages/organization/organization-page.jsx
- app/pages/organization/organization-page.spec.js
- app/pages/organization/organization-project-cards.jsx
- app/pages/organization/organization-project-cards.spec.js
- css/organization-page.styl
HOLD: until Notes from Nature and Snapshot Safari can update their organization content for new design, most notably about section.
Staging branch URL: https://pr-5554.pfe-preview.zooniverse.org
Helpful links:
- staging test organization: https://pr-5554.pfe-preview.zooniverse.org/organizations/markb-panoptes/urban-wildlife-org-test
- Snapshot Serengeti: https://pr-5554.pfe-preview.zooniverse.org/organizations/meredithspalmer/snapshot-safari?env=production
- Notes from Nature: https://pr-5554.pfe-preview.zooniverse.org/organizations/md68135/notes-from-nature?env=production
[InVision organization landing page redesign](https://projects.invisionapp.com/d/main/default/#/console/12924056/391430827/preview)
I've separated the organization landing page redesign work into several small PRs. …
> Organization landing page redesign - base

- app/pages/organization/organization-container.jsx
Staging branch URL: https://pr-5598.pfe-preview.zooniverse.org
Note projects count on...
- master Snapshot Safari Organization (20): https://www.zooniverse.org/organizations/meredithspalmer/snapshot-safari
- this PR Snapshot Safari Organization (23): https://pr-5598.pfe-preview.zooniverse.org/organizations/meredithspalmer/snapshot-safari?env=production
Adds `getAllLinked` to request all projects linked to an organization.
Using `getAllLinked` is not ideal, however, currently avoiding pagination or requesting projects with `cards: true` because all of the projects and each full project resource is used for the "organization stats" section which consists of project stats aggregated. The full project resource includes properties like `classifications_count`, `subjects_count`, and …
> Use getAllLinked to get all projects linked to an organization

- app/pages/project/home/home-workflow-button.jsx
- app/pages/project/home/home-workflow-button.spec.js
- app/pages/project/home/home-workflow-buttons.jsx
- app/pages/project/home/index.jsx
Staging branch URL: https://pr-5626.pfe-preview.zooniverse.org
Fixes #5451.
Connect up the project homepage workflow buttons to the redux store. Display translations for the workflow display names.
https://pr-5626.pfe-preview.zooniverse.org/projects/sassydumbledore/chimp-and-see?env=production
https://pr-5626.pfe-preview.zooniverse.org/projects/sassydumbledore/chimp-and-see?env=production&language=de
> Project home page: translate workflows

- app/pages/admin/project-status/experimental-features.jsx
- app/pages/lab/collaborators.cjsx
Fixes #5607
Staging branch URL: https://pr-5608.pfe-preview.zooniverse.org
This PR adds 'museum' role option, to the PFE Lab's Collaborators page.
- The new `museum` role is designed, presumably, for use with museum exhibits or similar events. (See #5607)
- ❗️ To see the `museum` role on the PFE Lab's Collaborators page, EITHER the `experimental_tools: ['museum-role']` value must be enabled for the project, OR the user viewing the page must be in admin mode.
- ❗️ To actually add/remove museum roles to certain users, the Panoptes API needs to have a `museum` role first.
I'm actually not aware if there was ever any discussion whether there _should_ be a `museum` role or not, but AFAIC that's irrelevant to this PR and the requirements set out by 5607. Any discussion on whether there should …
> Add "Museum" role to PFE Lab Collaborators (experimental tool)

- app/classifier/drawing-tools/components/Fan/fan.jsx
Change the default fan tool spread angle to 10º.
Staging branch URL: https://pr-5605.pfe-preview.zooniverse.org
Fixes #5604.
> Fan tool: make default spread 10º

- app/components/ExternalLinksBlock/ExternalLinksBlock.jsx
Staging branch URL: https://pr-5627.pfe-preview.zooniverse.org
Fixes an issue appearing [on Talk](https://www.zooniverse.org/talk/17/1232948) 
Gives a background to an otherwise transparent div that was not receiving styling from the theme. I think this issue was only appearing on Windows in particular browsers? It appears to only appear when images are quite tall. However, I went ahead and made the change as I can see this occurring for any project with tall subjects.
> Show Background Color Over External Links

- app/lib/ga-log-adapter.js
- app/lib/ga-log-adapter.spec.js
Staging branch URL: https://pr-5639.pfe-preview.zooniverse.org
Fixes #5638.
Add a test for the case where Google Analytics is not available.
Check for the existence of the Google tracker before getting a code and logging an event.
> Fail gracefully when Google Analytics is not available

- app/classifier/drawing-tools/index.coffee
- app/classifier/tasks/generic-editor.cjsx
Add transcriptionLine to the list of drawing tools.
Show it in the lab options in admin mode.
Staging branch URL: https://pr-5640.pfe-preview.zooniverse.org
> Add the transcription line for admins

- app/components/file-viewer/video-player.jsx
Bind the video player event handlers so that `this` is defined. Refactor `playVideo` so that it is only bound once.
Staging branch URL: https://pr-5661.pfe-preview.zooniverse.org
Fixes #5570.
> Bind video event handlers properly

- app/pages/admin/project-status-list.jsx
- app/pages/projects/projects-search-selector.jsx
- css/admin-page.styl
Staging branch URL: https://pr-5669.pfe-preview.zooniverse.org
This PR adds a search box to the admin "set project status" page as it's always a bit tricky to find a project on that view. Clicking on a project from the search box navigates directly to the status page.
> Allow Admin to Search Project on Status Page

- app/redux/ducks/classify.js
- app/redux/ducks/classify.spec.js
- Add a test to check that existing subjects are not added to the subject queue on append.
- Update the `append` action to pass the test by deduping the upcoming subjects array.
Staging branch URL: https://pr-5671.pfe-preview.zooniverse.org
> Remove duplicates from the upcoming queue on append

- app/pages/admin/project-status-list.jsx
- app/pages/projects/featured-project-editor.jsx
- app/pages/projects/project-filtering-interface.jsx
- app/pages/projects/projects-search-selector.jsx
- app/pages/projects/projects-welcome.jsx
- css/project-card.styl
- Adds a FeaturedProjectEditor, which wraps a featured project card and allows admins to edit it with the project search selector.
- adds an optional onChange prop to the project search selector, so that we can override the default link navigation behaviour.
- adds an options prop to the project search selector, which can be used to pass query options for filtered searches.
- updates the admin project search to use the new search selector.
Staging branch URL: https://pr-5667.pfe-preview.zooniverse.org/projects
> Add a featured project editor to the Projects page

- app/router.cjsx
fix the home redirect route by using the v3 version of router history manipulation, https://github.com/ReactTraining/react-router/blob/v3/docs/API.md#router-1
Staging branch URL: https://pr-5685.pfe-preview.zooniverse.org
Fixes a bug report from twitter https://twitter.com/clmcavaney/status/1250575570850603009.
> use new router api for history navigation

- app/locales/ar.js
- app/locales/he.js
Staging branch URL: https://pr-5702.pfe-preview.zooniverse.org
The project home page talk section (`project.home.talk` strings) has an issue with `<strong>` when translated right-to-left: https://www.zooniverse.org/projects/markbouslog/test-project-mb?language=he
- replaced `<strong>` with `**`, see: https://pr-5702.pfe-preview.zooniverse.org/projects/markbouslog/test-project-mb?language=he
> Edit project home talk rtl translations

- app/locales/en.js
Reorganized the Brand repo and the original pdf got moved.
> Fixing broken link to Zooniverse book pdf

- app/locales/ar.js
- app/locales/cs.js
- app/locales/de.js
- app/locales/en.js
- app/locales/es.js
- app/locales/fr.js
- app/locales/he.js
- app/locales/hi.js
- app/locales/it.js
- app/locales/ja.js
- app/locales/kn.js
- app/locales/ko.js
- app/locales/nl.js
- app/locales/pl.js
- app/locales/pt.js
- app/locales/sv.js
- app/locales/zh-cn.js
- app/locales/zh-tw.js
- app/pages/project/field-guide-container.jsx
Staging branch URL: https://pr-5706.pfe-preview.zooniverse.org
- https://pr-5706.pfe-preview.zooniverse.org/projects/markbouslog/test-project-mb/classify?env=production
- update Field Guide toggle button content so translatable
> Add translation for Field Guide toggle

- app/main.cjsx
Staging branch URL: https://pr-5714.pfe-preview.zooniverse.org
Closes https://github.com/zooniverse/how-to-zooniverse/issues/60
This PR remove zooAPI and talkAPI from the global window. More info found on the issue.
> Remove zooAPI from Window

- app/pages/project/index.jsx
Temporarily disables splits in case of 7-10 timeout keeping project page from loading.
> Temp Disable Splits

- app/pages/project/about/team.jsx
Staging branch URL: https://pr-5739.pfe-preview.zooniverse.org
Fixes #5738, similar to #338
Adds "Museum" role to list of registered list of role translations.
> Add museum role translation

- app/pages/home-for-user/index.jsx
Check activePreferences before making a request for associated projects. If activePreferences is empty, getProjectsForPreferences would make an API request with page size 0.
Staging branch URL: https://pr-5748.pfe-preview.zooniverse.org
> Home page: Fix page_size=0 bug for classifications ribbon

- app/constants/languageMenu.js
- app/locales/de.js
- app/locales/es.js
- app/locales/fr.js
- app/locales/it.js
Staging branch URL: https://pr-5769.pfe-preview.zooniverse.org
Adds platform translation in Spanish, Italian, French, and German of "Field Guide" UI label.  Also edits French language label in dropdown from "Francais" to "Français".
> Edit Translation: Field Guide + French lang label

- app/locales/ar.js
- app/locales/cs.js
- app/locales/de.js
- app/locales/en.js
- app/locales/es.js
- app/locales/fr.js
- app/locales/he.js
- app/locales/hi.js
- app/locales/hr.js
- app/locales/it.js
- app/locales/ja.js
- app/locales/kn.js
- app/locales/ko.js
- app/locales/nl.js
- app/locales/pl.js
- app/locales/pt.js
- app/locales/sv.js
- app/locales/zh-cn.js
- app/locales/zh-tw.js
- app/pages/settings/email.jsx
- app/pages/settings/email.spec.js
- css/settings.styl
Staging branch URL: https://pr-5747.pfe-preview.zooniverse.org
Closes #5746.
Why DRAFT:
- adds user email preference toggle with note
> Add user email preference toggle for NASA email list

- css/classify.styl
- webpack.dev.js
Staging branch URL: https://pr-5784.pfe-preview.zooniverse.org
Fixes #5781 
The underlying scroll anchor behavior has changed with Chrome since v84. We're disabling scroll anchoring on the task nav container by adding `overflow-anchor: none` style to it. This seems to fix the unusual scroll behavior originally reported on Talk: https://www.zooniverse.org/talk/17/1533848
No changelog report exist for this change, so this is still a guess, but #5781 got us on the right track.
This PR also adds back in `https: true` to the webpack dev server configuration. It was removed a few months ago because of a bug in webpack, but webpack has been updated since then. We need this to be able to run the site locally.
> Add overflow-anchor style to task nav container

- app/classifier/drawing-tools/full-height-line.cjsx
- app/classifier/drawing-tools/full-width-line.cjsx
Use the subject's naturalHeight and naturalWidth to set the dimensions of the full height and full width line tools.
Staging branch URL: https://pr-5801.pfe-preview.zooniverse.org
Fixes #5800.
> Full-size drawing tools: use subject dimensions

- app/classifier/tasks/survey/editor.cjsx
Staging branch URL: https://pr-5765.pfe-preview.zooniverse.org
Fixes issue where UI shows there are no survey task questions when there are questions. This issue is because the existence of questions is being determined by `questionsOrder` length, when if no questions are applied to all choices, or if questions have `included` defined with all choices (not suggested usage, but happens), then `questionsOrder` will have no length and the UI (button text, warning) will appear as if there are no questions.
- changes questions existence check from `questionsOrder.length` to `questions.keys?.length`
> Refactor survey questions existence check

- app/pages/admin/project-status.jsx
Add workflow.grouped to the project admin, and allow it to be set for project workflows.
Staging branch URL: https://pr-5803.pfe-preview.zooniverse.org
Fixes #5783.
> Project admin: add workflow.grouped

- app/locales/ja.js
Staging branch URL: https://pr-5819.pfe-preview.zooniverse.org
Adds Japanese translation to ja.js locale file.  Warm thanks and acknowledgements to Michiharu Hyogo for this contribution.
Closes #5802
> Add Japanese locale file translations

- css/field-guide.styl
Fixes #5811 
Fix for transparency issue within the Field Guide. Background color is now using ‘BACKGROUND’ from the `common.styl` file which is white and opacity at 100%.
> Updated Field Guide background

- app/classifier/tasks/text/index.jsx
Remove `componentDidUpdate` and, instead, call `handleResize` only after updates to the text value. This should make it impossible for `handleResize` to invoke itself via `componentDidUpdate`.
Staging branch URL: https://pr-5795.pfe-preview.zooniverse.org
Fixes #5767.
> Text task: fix potential infinite loop

- app/router.cjsx
Staging branch URL: https://pr-5824.pfe-preview.zooniverse.org
This is in preparation of the beta test next Tuesday so that zooniverse.org URLs routes to the new app.
> Add redirect for stellar sleuths

- app/pages/admin/project-status.jsx
- app/pages/admin/project-status.spec.js
- css/admin-page.styl
Staging branch URL: https://pr-5830.pfe-preview.zooniverse.org
I added a select dropdown to the admin interface for projects to set the subject viewer to use per workflow. I also reorganized the layout because it was really inconsistent and didn't clearly label what different settings were for.
Here we see the staging Anti-Slavery Test project with its default workflow setup for the new classifier using the `multiFrame` viewer. Most workflows won't have this set yet because they haven't migrated over to the new classifier.
Specs are updated.
> Admin interface for subject viewer settings

- app/subjects/comment-form.cjsx
- app/talk/discussion-comment.jsx
- app/talk/discussion-comment.spec.js
Require a valid email address before showing the Talk comment form. Otherwise, link them to the settings page to update their details.
Require a valid email address for the subject comment form too.
Staging branch URL: https://pr-5799.pfe-preview.zooniverse.org
> Talk: require a valid email address

- app/subjects/comment-form.cjsx
- app/talk/discussion-comment.jsx
- app/talk/discussion-comment.spec.js
Reverts zooniverse/Panoptes-Front-End#5799
Volunteers with real email addresses are flagged as invalid in the `users` table, which has locked them out of Talk.
> Revert "Talk: require a valid email address"

- app/pages/admin/project-status.jsx
- css/admin-page.styl
Staging branch URL: https://pr-5835.pfe-preview.zooniverse.org
Allow admins to enable sequential subject selection for a workflow.
> Add workflow.prioritized to project admin

- app/pages/lab/workflow.cjsx
Fixes misspelling of "workflow" on workflow editing page of lab, in banner when workflow is frozen to editing when active.
> Fixed typo on lab workflow page

- app/pages/lab/workflows-table.jsx
- css/lab.styl
Align the workflow completeness radio buttons, in the lab, so that they are above one another.
Staging branch URL: https://pr-5834.pfe-preview.zooniverse.org
**before**
**after**
> Project Builder: Align workflow completeness radio buttons

- app/pages/lab/project.cjsx
- app/partials/data-export-download-link.jsx
Staging branch URL: https://pr-5847.pfe-preview.zooniverse.org
Closes: #5848. 
Fixes an error where the project builder crashes with `exported.metadata is null` if you try to view data exports on a project that has no exports, like I Fancy Cats (staging project 335.)
This PR adds an error boundary to lab projects, which prints out the error message and stack trace for page crashes.
The bug is fixed by adding an existence check to `exported.metadata` in the data download link component.
> Lab data export error

- app/router.cjsx
Staging branch URL: https://pr-5862.pfe-preview.zooniverse.org
Getting HMS NHS ready for beta. You can test this PR by navigating to the project home, or classify, pages from 
- this PR: https://pr-5862.pfe-preview.zooniverse.org/projects/msalmon/hms-nhs-the-nautical-health-service/talk?env=production
- without the redirect: https://www.zooniverse.org/projects/msalmon/hms-nhs-the-nautical-health-service/talk
Closes #5861.
> Add router redirects for HMS NHS

- app/partials/project-card.cjsx
Linked to #5864 
This PR allows the `project.avatar_src` attribute to be in full URL or path only formats (currently the difference between staging and prod APIs). Once this is in we can safely deploy to production www.zooniverse.org site.
When the API changes in https://github.com/zooniverse/panoptes/pull/3532 are deployed we can merge #5864 to replace this fallback behaviour PR.
Staging branch URL: https://pr-5865.pfe-preview.zooniverse.org/projects
Prod version branch URL: https://pr-5865.pfe-preview.zooniverse.org/projects?env=production
> handle valid URLs and path only avatar_src values

- app/partials/project-card.cjsx
Linked to #5865 - it appears that #5865 broke the www.zooniverse.org project cards for IE11 users. This PR fixes the issue for all supported browsers.
Another attempt to fix the broken project avatars, this time use regex instead to determine if the `avatar_src` is a full URL or a path suffix. MDN shows support for `new RegExp` and the `test` method in use here, https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp#Browser_compatibility
I think this will work to bridge the difference in API behaviour.
Staging branch URL: https://pr-5866.pfe-preview.zooniverse.org/projects
Prod version branch URL: https://pr-5866.pfe-preview.zooniverse.org/projects?env=production
> use regexes to detect valid avatar_src urls vs paths

- views/index.ejs
Staging branch URL: https://pr-5877.pfe-preview.zooniverse.org
Minor change to the Zooniverse social header info (Facebook OG and Twitter tags): change logo URL from S3-specific to cloud-agnostic version -- specifically, change domain from zooniverse-static.s3.amazonaws.com to static.zooniverse.org.  This will ensure the logo PNG URL resolves to the correct location once zooniverse-static content starts to be hosted out of Azure.
Note to @srallen: This was the only s3-specific URL I identified in PFE that required a change.  In contrast to what I said during our conversation on Tuesday, the app status messages already use the cloud-agnostic version of the URL, so no PFE changes are needed for that feature.  The only change needed for that feature applies to the Jenkins jobs (I created …
> Update static asset URL

- app/lib/init-sentry.js
- app/main.cjsx
- app/pages/project/index.jsx
- package-lock.json
- package.json
Staging branch URL: https://pr-5885.pfe-preview.zooniverse.org
Install Sentry browser error logging and performance tracing packages. Initialise Sentry before the App component mounts in the browser. Add Sentry logging to the project error boundary.
> Add Sentry logging for project errors

- app/pages/project/field-guide.cjsx
Use the Translate component to render the field guide title in the current locale.
Staging branch URL: https://pr-5888.pfe-preview.zooniverse.org
Fixes #5886.
> Localise the field guide title

- views/index.ejs
**DO NOT MERGE UNTIL CLEARED BY @nciemniak ON THURSDAY Feb 11!**
Add maintenance page placeholder for Feb 2021 DB upgrade downtime.  Follows example from July 2020 via Apply PR (https://github.com/zooniverse/Panoptes-Front-End/pull/5773) and Revert PR (https://github.com/zooniverse/Panoptes-Front-End/pull/5774).
Staging branch URL: https://pr-5889.pfe-preview.zooniverse.org
> Maintenance Mode - Feb 2021

- app/pages/admin/project-status.jsx
- app/pages/admin/project-status.spec.js
Context (Why): a Workflow's Training data can currently only be edited by manually editing the Workflow config object, e.g. by the Rails console. It would be much easier to make these minor changes via a UI. As a Hackday project, @nciemniak wants to add such a functionality to the Admin page.
Details (What): This PR allows admins to edit the Training data values in a Workflow's configuration.
- This can be accessed by going to the Admin page, "Set Project Status", selecting a Project, then scrolling down to the individual workflows.
- The Training data fields are: `training_chances`, `training_default_chance`, `training_set_ids`
- Example:
```
workflow.configuration = {
training_chances: [1, 0.5, 0.3],
training_default_chance: 5,
training_set_ids: [4808,4807],
}
```
_Example of the …
> Allow admins to edit Training data in Workflow config

- app/router.cjsx
Staging branch URL: https://pr-5894.pfe-preview.zooniverse.org
Since the retirement of the Ouroboros P4 and redirect of the www domain to the PFE version of it, old links to the original authors page get directed to `/projects/mschwamb/planet-four/authors` which doesn't exist. This PR adds a redirect for `/projects/mschwamb/planet-four/authors` to `https://authors.planetfour.org/`.
There are other solutions we could consider, especially for future projects that may want to have author pages, but this should work for now and is the simplest solution.
> Add redirect to P4's authors page

- app/router.cjsx
Reverts zooniverse/Panoptes-Front-End#5894
In production, this is looping in redirects, so I need to have another look at this.
> Revert "Add redirect to P4's authors page"

- app/router.cjsx
Retrying what I meant to do in #5894. I reused `RELOAD` when I shouldn't have. It does what we expect when the hostname is not `www.zooniverse.org`, but not when it is (aka production) because what its intended behavior is to reload the page to then proxy redirect to the new apps. All we want here is a simple redirect, so I added code to do just that.
Can test with:  https://pr-5897.pfe-preview.zooniverse.org/projects/mschwamb/planet-four/authors?env=production
> Redirect for P4

- app/pages/lab/actions/media.js
- app/pages/lab/media-area/index.jsx
This PR adds a basic pagination system to the Media page. (e.g. https://www.zooniverse.org/lab/1292/media) This fixes an issue where projects owners with more than 200 media files either 1. think they've "lost" images, or 2. can't see when they've successfully uploaded new images.
Context:
- We had a [Freshdesk report](https://zooniverse.freshdesk.com/a/tickets/7034) from project owners detailing the issue.
- Our investigation uncovered that the Media page in the lab has a hard limit of _showing_ 200 images, but a small number of projects having far, far more than 200 images.
- The backend is fine, this is purely a UI issue causing user confusion.
This update consists of 3 parts
- the `<MediaArea>` component now tracks …
> Add paging for Media lab page

- app/router.cjsx
Staging branch URL: https://pr-5900.pfe-preview.zooniverse.org
We're beta testing the transcription task tools and would like to send out this test project to a group of testers. This sets up the client side routing reload. After this merges and deploys, I'll update the Azure Frontdoor rules.
> Add the routes for the transcription task test project

- app/pages/lab/workflow.cjsx
Staging branch URL: https://pr-5899.pfe-preview.zooniverse.org
This adds a button in the list of tasks when you click "Add Task" for transcription task, if the project has the `transcription-task` experimental tool enabled. This can be setup in the admin pages for a project. Once it is, you'll see it in the list:
For existing projects setup with the transcription task, it also adds the icon to the task in the task list:
Both of these can be demoed by checking out https://pr-5899.pfe-preview.zooniverse.org/lab/1764/workflows/3392
Right now the button doesn't do anything other than console log. Functionality will come in a future PR.
> Add UI button for transcription task to lab

- app/classifier/tasks/transcription/SubtaskEditor.jsx
- app/classifier/tasks/transcription/editor.jsx
Staging branch URL: https://pr-5904.pfe-preview.zooniverse.org
This adds a basic editor for the text subtask portion of the transcription task. You should be able to edit the instruction and which text tags are allowed for an already existing transcription task. Try it out at: https://pr-5904.pfe-preview.zooniverse.org/lab/1764/workflows/3392
I also added a basic explanatory message about what the transcription task is at the top:
> Add subtask editor

- app/classifier/tasks/transcription/SubtaskEditor.jsx
- app/classifier/tasks/transcription/editor.jsx
Staging branch URL: https://pr-5905.pfe-preview.zooniverse.org
This add explanatory text a bout the transcription line:
Previewed at: https://pr-5905.pfe-preview.zooniverse.org/lab/1764/workflows/3392
@snblickhan and @beckyrother is this text ok for the editor?
> Add transcription line tool explanation

- app/pages/admin/project-status.jsx
Staging branch URL: https://pr-5898.pfe-preview.zooniverse.org
This adds `scatterPlot` as a subject viewer option for the new classifier in the admin tools.
> Add scatterPlot to the list in the admin pages

- app/pages/collections/collection-card.jsx
Staging branch URL: https://pr-5916.pfe-preview.zooniverse.org
For https://zooniverse.freshdesk.com/a/tickets/7356
Let's use the thumbnail service for the collection previews. Hopefully this will make this component a bit faster. The actual subject views use the subject viewer, so unfortunately I don't think we can use the thumbnail service here. Thoughts for a new version of the page in the app:  Maybe default to an optimized preview and let the volunteer view it in the subject viewer only per subject, not on the paginated version.
> Use the thumbnail service for collections previews

- app/pages/lab/workflow.cjsx
Staging branch URL: https://pr-5906.pfe-preview.zooniverse.org
For the upcoming NEH workshop and Davy Notebooks use, the lab now has the ability to add and remove the transcription task and the associated question task for caesar retirement grouped together in a single step. If transcription task is enabled, any task that is added or removed will be also added or removed in the workflow steps. This is because some of the projects may want additional tasks. The order of the steps determines the order of the workflow, so the first task designation and setting what comes next does not matter.
Here's what you should be able to do (recommend inspecting the network response for workflow PUTs):
- Add `transcription-task` as an experimental tool for a project in the admin pages
- Then add any …
> Add functionality to add or delete transcription task and steps

- app/classifier/tasks/transcription/SubtaskEditor.jsx
The _Davey Notebooks_ project wants to add three new tags to the Transcription task's Text subtask. This PR makes those tags available to any Transcription-type project.
- Added new tags to the Transcription -> Text subtask: `underline`, `superscript`, `&`
- These tags are fairly generic ; I see no issue if other transcription projects want to use them.
Go ahead and play with the workflow settings:
- Project builder: https://local.zooniverse.org:3735/lab/1929/workflows/3459
- Classifier: https://fe-project.preview.zooniverse.org/projects/darkeshard/davy-notebooks-2021/classify/workflow/3459?env=staging
Ready for review
> Transcription Task: add 3 new text tags for subtask

- app/pages/collections/collection-card.jsx
Staging branch URL: https://pr-5921.pfe-preview.zooniverse.org
Follow up to #5916 and in response to https://www.zooniverse.org/talk/17/1904019
Changes the background-size CSS for the collections card to use contain.
> Change background-size to contain

- app/pages/lab/workflow.cjsx
Staging branch URL: https://pr-5919.pfe-preview.zooniverse.org
Another enhancement to make using the transcription task in the lab a little easier. If a project has the transcription task experimental tool enabled and if the workflow being edited is using one, then the "Test Workflow" link goes to `fe-project` rather than PFE. 
Try this out with Anti-Slavery Testing: https://pr-5919.pfe-preview.zooniverse.org/lab/1764/workflows
Workflow 3392 goes to fe-project, but all the others go to staging PFE. 
Note for projects/workflows intending to use this, the workflow must be active and the project public. The new project app isn't setup to support private projects or user roles that can load inactive workflows yet.
It'd be really helpful to have this reviewed and merged before this Friday (NEH …
> Use link to fe-project for transcription task workflows

- .github/workflows/ci-tests.yml
- .travis.yml
- package.json
Remove travis.yml. Add a GH workflow which runs the CI tests, generates a coverage report and posts the results to Coveralls.
Staging branch URL: https://pr-5918.pfe-preview.zooniverse.org
> Replace Travis CI with GitHub Actions

- app/classifier/tasks/combo/editor.cjsx
- app/classifier/tasks/dropdown/editor.jsx
- app/classifier/tasks/generic-editor.cjsx
- app/classifier/tasks/next-task-selector.cjsx
- app/classifier/tasks/slider/editor.jsx
- app/classifier/tasks/survey/editor.cjsx
- app/classifier/tasks/text/editor.cjsx
Add a task prop to the `NextTaskSelector` in the lab and pass down the current task. Filter the current task out of the list of next task options.
This turned out to be more complicated than I thought because each task (`app/classifier/tasks`) implements its own 'Next task' menu in its editor component. I think I got them all. You can check it by editing tasks in the project builder. You shouldn't be able to link any task back to itself any more.
Staging branch URL: https://pr-5925.pfe-preview.zooniverse.org
Fixes #2512.
> Prevent tasks linking to themselves

- app/pages/admin/project-status/experimental-features.jsx
Related to: classroom.zooniverse.org
This PR adds the `wildcam classroom` to the list of available Experimental Tools at the project admin. (e.g. https://www.zooniverse.org/admin/project_status/sandiegozooglobal/wildwatch-kenya)
- The 'wildcam classroom' flag indicates that a Project is part of "WildCam Lab"-type Zooniverse Classroom. This in turn means that the PFE classifier allows the user to select specific workflows (i.e. Classroom assignments) by their ID. 
- The 'wildcam classroom' flag has already been extant in WildCam Gorongosa and WildCam Darién's configuration since 2019, but we never noticed there wasn't a way to easily add this flag for new projects. (e.g. for the upcoming Wildwatch Kenya Lab)
Ready for …
> Add 'wildcam classroom' to Experimental Tools admin

- app/router.cjsx
This PR adds a new Front End Monorepo project (re-)route for the Davy Notebooks, which is going into Beta on Thu 29 Apr 2021.
- The URL https://www.zooniverse.org/projects/humphrydavy/davy-notebooks-project will functionally take users to the FEM equivalent, https://fe-project.zooniverse.org/projects/humphrydavy/davy-notebooks-project
- Ditto for the /classify page and its child pages.
Ready for review. Next up: Front Door modifications.
> Add Davy Notebooks project to list of FEM routes

- app/router.cjsx
Staging branch URL: https://pr-5933.pfe-preview.zooniverse.org
Fixes # .
Force a page redirect / reload for the zooniverse team page to the content pages app. This replicates the setup for the publications page and mirrors the production setup via the CDN for these URLs in production (sadly missed when navigating by router links).
> ensure team page is reloaded to content pages app

- package-lock.json
- package.json
Reverts zooniverse/Panoptes-Front-End#5936 - sugar integration is broken with this version
> Revert "Upgrade Panoptes API client to 3.3.1"

- package-lock.json
- package.json
This fixes a Sugar problem that was introduced in 3.3.0, and installs a security patch for lodash. The window for refreshing expired tokens is increased to 5 minutes, which might help resolve issues where classifications from logged-in volunteers are being recorded as anonymous. 3.3 also included changes to store  the auth bearer token more securely in the client.
Staging branch URL: https://pr-5939.pfe-preview.zooniverse.org
> [Security] Upgrade panoptes-client to 3.3.2

- app/classifier/tasks/generic-editor.cjsx
- app/classifier/tasks/index.jsx
- app/classifier/tasks/subjectGroupComparison/README.md
- app/classifier/tasks/subjectGroupComparison/editor.jsx
- app/classifier/tasks/subjectGroupComparison/index.jsx
- app/classifier/tasks/subjectGroupComparison/index.spec.js
- app/classifier/tasks/subjectGroupComparison/summary.jsx
- app/pages/admin/project-status/experimental-features.jsx
- app/pages/lab/workflow-components/subject-group-viewer-editor.jsx
- app/pages/lab/workflow.cjsx
This PR allows the "Subject Group" set of viewers and tasks to be edited on the PFE project builder. The "Subject Group" set refers to the Subject Group _Viewer_ (a grid-like subject viewer + "drawing" interface) and the Subject Group Comparison _Task_ (similar to a multi-answer task, except instead of checkboxes in the Task area, the 'selectable checkboxes' are cells on the grid. The Task Area itself just has a single question) that's built for the Front End Monorepo.
Please see the [FEM](https://github.com/zooniverse/front-end-monorepo) for the SubjectGroupViewer and SubjectGroupComparisonTask components.
Intended features of this PR:
Staging branch URL: https://pr-5946.pfe-preview.zooniverse.org/
View the SURVOS Testing 2020 project from the user's perspective on the FEM Classifier: …
> Subject Group project builder controls

- app/pages/home-for-user/index.jsx
filter any user project preferences that have the settings object marked as `preference.hidden=true`
Currently relies on manually setting the value in the API db manually, however changes in https://github.com/zooniverse/panoptes/pull/3583 will expose this `hidden` attribute for update via the API.
I'm happy to modify any testing user project preferences to have this value. 
Staging branch URL: https://pr-5908.pfe-preview.zooniverse.org
> remove hidden project prefs from the logged in user ribbon

- package-lock.json
- package.json
Upgrade `chart.js` to fix a security vulnerability in version 2.7.
Staging branch URL: https://pr-5943.pfe-preview.zooniverse.org
I think `chart.js` is only used on project stats pages
eg. https://pr-5943.pfe-preview.zooniverse.org/projects/stephenresearch/beluga-bits/stats?env=production
> [Security] Upgrade chart.js to version 3

- app/classifier/tasks/survey/annotation-view.jsx
- app/classifier/tasks/survey/annotation-view.spec.jsx
Staging branch URL: https://pr-5950.pfe-preview.zooniverse.org
Fixes #5949.
I've refactored the `AnnotationView` component to wrap it in `TaskTranslations`, which passes a `translation` object containing localised strings for the current task.
I've also removed the `title` attribute, which isn't accessible to volunteers who use screen readers or who rely on the keyboard or voice control. Buttons are labelled with `aria-label` and I've added answers to the displayed text.
https://localhost.pfe-preview.zooniverse.org:3735/projects/aicensusuhu/iberian-camera-trap-project/classify?env=production&language=cs
> Survey task: localise the AnnotationsView component

- .github/workflows/deploy_production.yml
- .github/workflows/deploy_staging.yml
Add HEAD_COMMIT to the build environment (it's referenced in `package.json` in a couple of places.) Publish HEAD_COMMIT as `dist/commit_id.txt` and upload that to Azure with a cache lifetime of 60s.
Staging branch URL: https://pr-5951.pfe-preview.zooniverse.org/commit_id.txt
This is https://github.com/zooniverse/pandora/pull/189 adapted for PFE.
> Publish commit_id.txt on deploy

- app/pages/lab/workflow-create-form.cjsx
Copy workflow steps, prioritized and grouped (if defined) when cloning a workflow. Set the new workflow's primary language to the same language as the original.
This is a quick patch so that we can continue to copy workflows for transcription projects and for Engaging Crowds.
Staging branch URL: https://pr-5961.pfe-preview.zooniverse.org
Fixes #5960.
> Bugfix: Update the Copy Workflow button

- app/pages/lab/workflow-create-form.cjsx
- app/pages/lab/workflow.cjsx
- app/pages/lab/workflows.jsx
Staging branch URL: https://pr-5962.pfe-preview.zooniverse.org
Ensure we have a primary language specified on workflow creation. Use the workflow to clone by default and fallback to the current locale.
> ensure the workflow has a pimary language set

- app/components/wrapped-markdown.jsx
Add [relNofollow](https://github.com/zooniverse/markdownz/blob/af0338244a3bd8cdf2ea6cf138393eab87fa31cb/test/markdown-test.jsx#L61-L64) to `WrappedMarkdown`, which is used to render Talk comments. This should add "nofollow noreferrer" to all links posted on Talk, not just those that open new tabs/windows.
Staging branch URL: https://pr-5972.pfe-preview.zooniverse.org
> Add relNoFollow to Talk comments

- app/classifier/components/TaskNavButtons/components/DoneButton/DoneButton.spec.jsx
- package-lock.json
- package.json
Upgrade enzyme to 3.11 and html-webpack-plugin to 4.5. Upgrading html-webpack-plugin any further would require webpack 5 (see #5953.)
Staging branch URL: https://pr-5969.pfe-preview.zooniverse.org
> [Security] Upgrade enzyme and html-webpack-plugin

- app/router.cjsx
Staging branch URL: https://pr-5974.pfe-preview.zooniverse.org
Adds the relevant reload component routs for the gridtool project to launch via the fe-project app on www.zooniverse.org
> add gridtool project redirects

- package-lock.json
- package.json
Staging branch URL: https://pr-5976.pfe-preview.zooniverse.org/
Fixes security alert: https://github.com/zooniverse/how-to-zooniverse/issues/160.
Manually update `striptags` package to 3.2.0.  I found this package used in only one location on the website (on the homepage):
> [Security] Update striptags to 3.2.0

- app/talk/active-users.jsx
- app/talk/active-users.spec.js
Staging branch URL: https://pr-5981.pfe-preview.zooniverse.org
CI tests are failing with `this.restartTimer is not a function` so this explicitly binds `restartTimer` in the `ActiveUsers` component and stubs it in tests.
> ActiveUsers: explicitly bind this.restartTimer

- app/classifier/drawing-tools/components/DetailsSubTaskForm/DetailsSubTaskForm.jsx
- app/talk/active-users.jsx
Merge subtask translation strings into the original task, so that the passed translation has the same shape as the task, including option values.
Staging branch URL: https://pr-5980.pfe-preview.zooniverse.org
Fixes #5979.
> Subtasks: merge translations into the original task

- app/components/subject-viewer.cjsx
- css/subject-viewer.styl
When the subject viewer mounts, check subjects for `subject.metadata.#subject_group_id`. If that's present, turn off flipbook mode so that all the subject images are shown in a grid. Also set a new viewer class, `subject-viewer--layout-grid4`, when that metadata key is present.
Staging branch URL: https://pr-5983.pfe-preview.zooniverse.org/projects/zookeeper/galaxy-zoo-weird-and-wonderful/talk/subjects/63395872?env=production
I've styled images with `max-width: 100px` so they fill the available width without appearing too large.
https://pr-5983.pfe-preview.zooniverse.org/projects/darkeshard/survos-testing-2020-subject-group-viewer/talk/228/345
> Talk: turn off flipbook mode for group subjects

- css/subject-viewer.styl
Remove the `:only-child` selector so that the invert filter can be applied to multiple images in the subject viewer. Enables the 'invert' button in Talk for group subjects.
Staging branch URL: https://pr-5985.pfe-preview.zooniverse.org/projects/zookeeper/galaxy-zoo-weird-and-wonderful/talk/subjects/63395872?env=production
> Talk: Add invert filter for multiple images

- app/components/subject-viewer.cjsx
Add `isGroupSubject` to the subject viewer, which checks for undefined subject metadata and only displays group subjects if `subject.metadata` exists.
Staging branch URL: https://pr-5987.pfe-preview.zooniverse.org
Fixes #5986.
> Subject viewer: add isGroupSubject

- css/subject-viewer.styl
#5985 has broken the invert filter for the classifier on projects like Plankton Portal. This redoes the CSS change, but scopes it only to group subjects (`subject-viewer--layout-grid4`.) Images in the classifier shouldn't be accidentally styled by this change, like they were in the previous PR.
Staging branch URL: https://pr-5990.pfe-preview.zooniverse.org
Test URLs:
Plankton Portal
https://pr-5990.pfe-preview.zooniverse.org:3735/projects/kelseyswieca/plankton-portal/classify?env=production
GZ: Weird and Wonderful
https://pr-5990.pfe-preview.zooniverse.org:3735/projects/zookeeper/galaxy-zoo-weird-and-wonderful/talk/subjects/63395872?env=production
Fixes #5813.
> Add Talk invert filters for group subjects

- app/components/frame-viewer.jsx
- app/components/subject-viewer.cjsx
- app/subjects/index.jsx
- css/subject-viewer.styl
Alternative to: #5984 
Follows #5983 (allows Subject Talk pages to display SubjectGroup images) and #5987
Context: for projects using the new "Subject Group" subject type (e.g. Galaxy Zoo: Weird and Wonderful, 2021), we want users on Talk to be able to go to the the individual Subjects that form the group.
This PR makes individual "frames" (i.e. component Subjects) of a SubjectGroup-type subject clickable, and link to their respective component subject's Talk pages.
- ⚠️ This adds new behaviour to the very widely used `subject-viewer.cjsx` component
- While this behaviour is exclusive to only a specific type of subject (i.e. SubjectGroups), we need to confirm the functionality of the SubjectViewer component in multiple cases.
- Known use cases: Subject Talk page, a project's Recents list, …
> Talk + SubjectViewer: make Subject Group's images link to component Subjects

- app/components/subject-viewer.cjsx
Check `props.allowFlipbook` and `isGroupSubject` before enabling flipbook mode in the subject viewer.
Staging branch URL: 
https://pr-5993.pfe-preview.zooniverse.org/projects/zookeeper/galaxy-zoo-weird-and-wonderful/talk/subjects/63395872?env=production
https://pr-5993.pfe-preview.zooniverse.org/projects/dwright04/supernova-hunters/classify?env=production
> Subject Viewer: fix inFlipbookMode

- app/pages/lab/workflow-components/subject-group-viewer-editor.jsx
Extension of: #5946 (adds ability to change workflow configuration values for Subject Group Viewer.)
Related PR: https://github.com/zooniverse/front-end-monorepo/pull/2231 (allows Subject Group Viewer to have an optional maximum grid height/width)
This PR allows project owners to edit the optional `grid_max_width` and `grid_max_height` workflow configuration values, for their workflows that use the Subject Group Viewer. These optional values are useful to restrict the the grid component to only appear on the visible browser space, instead of, e.g. growing so tall (due to "fit-to-width" behaviour) that the grid's bottom half gets cut off.
- Please note that this functionality is only relevant to Projects that 1. have the "subject group viewer" experimental tool enabled, and 2. have the …
> Subject Group project builder controls pt 2

- app/router.cjsx
Redirect `hughdickinson/superwasp-black-hole-hunters` so that it's served from fe-project.zooniverse.org
Staging branch URL: https://pr-5997.pfe-preview.zooniverse.org/projects/hughdickinson/superwasp-black-hole-hunters/talk?env=production
Fixes #5996.
> Add redirects for Black Hole Hunters

- app/components/file-viewer/index.jsx
- app/components/file-viewer/text-viewer.jsx
Staging branch URL: https://pr-5999.pfe-preview.zooniverse.org
Fixes #5995 
Use the text viewer as a fallback for subject locations that are json to render something. This can be previewed at https://pr-5999.pfe-preview.zooniverse.org/projects/adamamiller/zwickys-stellar-sleuths/talk/subjects/50787258?env=production
The second frame is the JSON, so should just display it now rather not anything at all.
> Allow the text viewer to render json

- app/router.cjsx
Redirect `bogden/scarlets-and-blues` to fe-project.zooniverse.org.
Staging branch URL: https://pr-6001.pfe-preview.zooniverse.org
> Redirect Scarlets and Blues to fe-project

- views/index.ejs
`npm run _build-production` strips whitespace and comments from the output HTML. This PR moves the build info (commit, environment and date) into meta tags in the document head.
Staging branch URL: https://pr-6003.pfe-preview.zooniverse.org
> Publish build info in meta tags

- app/router.cjsx
Staging branch URL: https://pr-6014.pfe-preview.zooniverse.org
Also adds Peoples Contest Digital Archive project to the set of FEM projects with redirect. 
**This should not merge until zooniverse/operations#523, zooniverse/operations#528, and zooniverse/operations#529 are done and the about pages are included there for each project. Then this should merge shortly after we confirm the existing routes work with the NGINX http frontend and the about page routes are added**
> Add about pages for FEM redirect routes.

- app/MonorepoRoute.jsx
- app/router.cjsx
Redirects to the NextJS apps should use `location.replace(url)`, so that the redirected PFE route is not remembered in browser history. This PR uses `location.replace` for pages hosted on both the `fe-project` and `fe-content-pages` apps.
Staging branch URL: https://pr-6027.pfe-preview.zooniverse.org/projects/nora-dot-eisner/planet-hunters-tess/talk?env=production
- Go to any of the project pages that are served from NextJS, then back with the Back button.
- Go to the Projects page, then through to HMS NHS, then back with the Back button.
- Go to the About page, then Publications or Our Team, then back with the Back button.
Fixes #6026.
Fixes https://github.com/zooniverse/front-end-monorepo/issues/1054.
> Fix FEM redirects

- app/pages/lab/project-details.cjsx
- app/pages/lab/social-links-editor.jsx
- app/pages/lab/workflow.cjsx
- app/partials/display-name-slug-editor.jsx
Add labels to some of the unlabelled text inputs and textareas in the project editor and workflow editor.
Staging branch URL: https://pr-6040.pfe-preview.zooniverse.org
There are still lots of accessibility errors in the lab, but this catches unlabelled inputs that were a quick fix in the project and workflow pages.
On master, this WAVE check shows around 49 errors. On this branch, it’s down to 32.
> Lab: Label unlabelled text inputs

- app/pages/lab/workflow-components/subject-set-linker.jsx
- app/pages/lab/workflow.cjsx
TODO:
UPDATE: Alphabetical sorting, by name, is preserved while still showing the 2021 sets for Radio Meteor Zoo.
The motivation for this is that [Radio Meteor Zoo](https://www.zooniverse.org/lab/2471) has hit a hard limit for the number of sets displayed for a workflow, so can't link up new sets to new workflows.
Try it out on Radio Meteor Zoo, where you should see the latest 2021 subject sets listed for a workflow:
https://pr-6042.pfe-preview.zooniverse.org/lab/2471/workflows/19930?env=production
Staging branch URL: https://pr-6042.pfe-preview.zooniverse.org
> Lab: Refactor workflow subject sets

- css/subject-viewer.styl
Staging branch URL: https://pr-6046.pfe-preview.zooniverse.org
Closes #5041 
Fixes issue with video subjects and survey task identifications, where video speed controls are overlapped by survey task identifications.
See - https://www.zooniverse.org/projects/victorav/spyfish-aotearoa/talk/4189/2148047?comment=3586444
Testing
- WARNING production project, video subjects, survey task - https://pr-6046.pfe-preview.zooniverse.org/projects/victorav/spyfish-aotearoa/classify?env=production
- staging project, image subjects, survey task - https://pr-6046.pfe-preview.zooniverse.org/projects/markb-panoptes/survey-task-test-project/classify (for reference)
Issue #3765 and PR #3781 fixed an IE bug, but added the styling issue noted above. We no longer support IE, so I think it's ok to remove this …
> Fix styling for video subject controls and survey task identifications

- app/classifier/tasks/survey/editor.cjsx
Staging branch URL: https://pr-6052.pfe-preview.zooniverse.org
Fixes currently broken link to Google Docs folder with survey task templates.
- created new bitly link
> Update survey task editor link to templates

- app/monorepoUtils.js
Use the new project app for all projects on frontend.preview.zooniverse.org.
Related to #6053, this ensures that all projects link to the correct Home, About and Classify pages when previewed on `frontend.preview.zooniverse.org`.
Staging branch URL: https://pr-6054.pfe-preview.zooniverse.org
> Update monorepoUtils for staging

- app/pages/admin/project-status.jsx
Staging branch URL: https://pr-6063.pfe-preview.zooniverse.org
Linked to https://github.com/zooniverse/panoptes/pull/3737 - this PR adds the ability for admins to opt into API features like the "Run SubjectSet completion events" as outlined the the linked PR.
> add opt in API feature toggles for project admin attributes

- .github/workflows/deploy_branch.yml
- .github/workflows/deploy_production.yml
- .github/workflows/deploy_staging.yml
Staging branch URL: https://pr-6065.pfe-preview.zooniverse.org
The deployment scripts are still pointing to the `reusable-workflows` branch. This points them to the `production-release` tag. 
In the meantime, I’ve restored the `reusable-workflows` branch so that actions still run.
> Fix deploy scripts

- app/classifier/tasks/survey/annotation-view.jsx
- app/classifier/tasks/survey/annotation-view.spec.jsx
The delete button for survey task annotations is passing the click event as the annotation index, `i`. This PR stores the index on each tag as `data-index` then uses that to get the selected annotation from the click event target.
See this Talk thread for a description of the bug:
https://www.zooniverse.org/talk/17/2251137?comment=3691589
Staging branch URL: https://pr-6068.pfe-preview.zooniverse.org/projects/zooniverse/snapshot-serengeti/classify?env=production
> Fix broken delete for survey annotations

- app/classifier/classifier.jsx
- app/classifier/classifier.spec.js
Throw `First task has not been set for workflow`, when `workflow.first_task` is undefined or empty.
There's a project that's broken because `workflow.first_task` is an empty string. This PR would show them a meaningful error, although it's not clear how they created a workflow with no first task.
https://www.zooniverse.org/projects/matildagrahn/korrekturlas-svenska-skillingtryck/classify?reload=0&workflow=20341
See also this Talk post:
https://www.zooniverse.org/talk/17/2244862?comment=3681061&page=1
TODO: is there a bug in the project builder that allows you to create invalid workflows?
Staging branch URL: https://pr-6067.pfe-preview.zooniverse.org/projects/matildagrahn/korrekturlas-svenska-skillingtryck/classify?reload=0&workflow=20341&env=production
> Throw a meaningful error when workflow.first_task is missing

- .github/workflows/ci-tests.yml
- .github/workflows/deploy_branch.yml
- .github/workflows/npm_build.yml
Bump `actions/setup-node` and use [built-in package caching](https://github.com/actions/setup-node#caching-packages-dependencies) instead of `actions/cache`.
> CI: use built-in package caching

- .github/workflows/deploy_staging.yml
Staging deploys are failing at the moment (check under the Actions tab), because I forgot to remove the Slack webhook URL from the `deploy_staging` job.
> Fix broken staging deploys

- app/layout/site-footer.jsx
Add missing link text to the Twitter and Facebook links in the footer. Add `rel="noopener noreferrer"` to guard against the target tab/window having access to the original page.
Staging branch URL: https://pr-6076.pfe-preview.zooniverse.org
> [Security] Fix footer Twitter and Facebook links

- app/pages/admin/user-settings.jsx
- app/pages/admin/user-settings/ClassificationData.jsx
- app/pages/admin/user-settings/stats.js
Add the 20 most recent classifications to the admin page for a user account.
Tidy up the mark-up to use summary/details for classification history.
Staging branch URL: https://pr-6077.pfe-preview.zooniverse.org
> Admin pages: show recent user classification history

- app/redux/ducks/translations.js
Translations can be accidentally saved, from the project builder, with extra whitespace, which then causes display bugs. This trims all language strings after loading them from Panoptes.
Staging branch URL: https://pr-6075.pfe-preview.zooniverse.org/projects/eatyourgreens/text-highlighter-demo
Test project with the whitespace bug: https://master.pfe-preview.zooniverse.org/projects/eatyourgreens/text-highlighter-demo
> Trim translation strings

- package-lock.json
- package.json
Upgrades `markdown-it` by four major versions, from 8 to 12, including a security patch.
Staging branch URL: https://pr-6082.pfe-preview.zooniverse.org
> [Security] Bump markdownz to 7.8.1

- app/router.jsx
This PR adds a redirect for a misprinted Bursts from Space URL
- A recent publication of "Sky and Telescope" misprinted the URL for @mwalmsley 's Bursts from Space project
- Incorrect URL: https://www.zooniverse.org/projects/mike-walmsley/bursts-from-space
- Correct URL: https://www.zooniverse.org/projects/mikewalmsley/bursts-from-space
Test URL: https://pr-6088.pfe-preview.zooniverse.org/projects/mike-walmsley/bursts-from-space?env=production
Ready for review
This workaround should be deleted after, say, _6 months_ to keep the code clean.
> Temporary workaround: Bursts from Space redirect

- app/classifier/tasks/survey/choice.jsx
Survey task translations crash the project page if a choice is missing. This updates the survey task to fall back to show the original dictionary key for missing choices, questions and answers.
Staging branch URL: https://pr-6102.pfe-preview.zooniverse.org/projects/shuebner729/snapshot-tswalu/classify?env=production
(select honey badger, black-footed cat or meerkat to trigger the original bug.)
Fixes #6101.
> Survey task translations: fallback to showing keys

- package-lock.json
- package.json
- webpack.dev.js
Upgrade `webpack-dev-server` and `webpack-cli` to the latest versions, which should fix a bunch of dependabot security alerts for outdated dependencies.
Staging branch URL: https://pr-6104.pfe-preview.zooniverse.org
> [Security] Upgrade webpack-dev-server to v4

- package-lock.json
update the PJC to v3.3.5 which includes the sugar client v2.0.0 update (primus client updates)
Staging branch URL: https://pr-6107.pfe-preview.zooniverse.org
> update panoptes-client to v3.3.5

- app/monorepoUtils.js
Add the PRINT project to the list of monorepo projects.
Staging branch URL: https://pr-6108.pfe-preview.zooniverse.org/projects/printmigrationnetwork/print?env=production
> Add PRINT project to monorepo slugs

- .github/PULL_REQUEST_TEMPLATE.md
Replace `npm install` with `npm ci` in the PR checklist. `npm ci` removes `node_modules` and does a clean install with a frozen lock file, whereas `npm install` is allowed to change the lock file.
Also update the template to reflect that tests run on GitHub Actions now.
> Add `npm ci` to the PR checklist

- app/pages/lab/iiif/Readme.md
A short Readme for IIIF manifests in the project builder.
Staging branch URL: https://pr-6118.pfe-preview.zooniverse.org
> Project builder: Add a readme for IIIF manifests

- app/pages/lab/iiif/components/IIIFSubjectSet.jsx
- app/pages/lab/iiif/components/MetadataEditor.jsx
- app/pages/lab/iiif/components/helpers/parseManifestV2.js
Fix a couple of small errors in the `IIIFSubjectSet` component and its children.
- Fix invalid DOM nesting in the metadata table by wrapping the table body in `<tbody>`.
- Fix missing keys for preview thumbnails by using the canvas identifier as a key for each image.
Staging branch URL: https://pr-6119.pfe-preview.zooniverse.org
> Project Builder: IIIF: fix React errors

- app/pages/lab/iiif/components/IIIFSubjectSet.jsx
- app/pages/lab/iiif/components/helpers/parseManifestV2.js
- app/pages/lab/iiif/components/helpers/parseManifestV2.spec.js
- show an error when the manifest context does not match IIIF Presentation version 2.
- Update metadata when the manifest URL changes (bug fix.)
- Submit the manifest URL by pressing Enter.
- Improved metadata parsing: handle complex metadata values, including arrays of items in multiple languages.
Some manifests that should work with this version:
- BL Siberian Photographs: https://eap.bl.uk/archive-file/EAP016-1-1/manifest
- BL In The Spotlight playbills: https://api.bl.uk/metadata/iiif/ark:/81055/vdc_100022589176.0x000002/manifest.json
- Getty images: https://media.getty.edu/iiif/manifest/db379bba-801c-4650-bc31-3ff2f712eb21
Staging branch URL: https://pr-6117.pfe-preview.zooniverse.org
> Project Builder: Improved IIIF manifest parser

- package-lock.json
Update minimist from 1.2.5 to 1.2.6.
Staging branch URL: https://pr-6113.pfe-preview.zooniverse.org
> [Security] Bump minimist to 1.2.6

- app/pages/lab/iiif/components/UploadButton.jsx
- app/pages/lab/iiif/components/hooks/useSubjectUploads.js
Improved error handling for subject uploads from an IIIF manifest.
- add an error state to the `useSubjectUploads` hook.
- report error status when `UploadButton` fails.
- don't retry if the API error has a status code. A status code either indicates that you aren't authorised to upload, or something is wrong with the API. In either case, retrying probably won't help.
Staging branch URL: https://pr-6121.pfe-preview.zooniverse.org
> Project Builder: IIIF: handle subject upload errors

- app/pages/lab/iiif/components/IIIFSubjectSet.jsx
- app/pages/lab/iiif/components/UploadButton.jsx
- app/pages/lab/iiif/components/UploadButton.spec.jsx
- app/pages/lab/subject-sets-container.jsx
- add an `onSubjectSetChange` hook to lab subject set pages, which can be run after we create a new set.
- pass down `getSubjectSets` to the upload button, so that the list of project subject sets is refreshed after uploading a new set.
Staging branch URL: https://pr-6122.pfe-preview.zooniverse.org
Fixes this issue, from https://github.com/zooniverse/Panoptes-Front-End/pull/6095#pullrequestreview-922206590
>[minor][UI/UX][quirk] if the user then clicks on the Subject Sets link in the Project Builder from the IIIF Uploader page or the created Subject Set page, then the newly created SSet will NOT be listed. This is because the "fetch list of SSets" doesn't trigger when you move from the /subject-sets/iiif (or /subject-sets/1234) route to /subject-sets. Just a quirk worth noting in case …
> Project Builder: IIIF: update project subject sets

- app/pages/lab/iiif/components/helpers/parseManifestV2.js
- app/pages/lab/iiif/components/helpers/parseManifestV2.spec.js
Support for bi-lingual IIIF manifests, as published by the National Library of Wales.
Try it out with this manifest:
https://damsssl.llgc.org.uk/iiif/2.0/4389767/manifest.json
Staging branch URL: https://pr-6120.pfe-preview.zooniverse.org
> Project Builder: IIIF: improved language support

- app/components/frame-viewer.jsx
- app/components/pan-zoom.jsx
- app/components/pan-zoom.spec.js
- app/pages/admin/project-status/experimental-features.jsx
- css/subject-viewer.styl
Affects: Subject Viewer
This PR adds an experimental feature to the Subject Viewer, which allows the Subject image to be rotated freely (instead of being locked into 90-degree rotations).
_In the image above, there's a new vertical slider/range input (below the old "Rotate" button and above the "Reset" button) on the image toolbar, which allows users to set an arbitrary rotation for the Subject images._
Preview: https://pr-6127.pfe-preview.zooniverse.org/projects/ellenjj/rosetta-zoo/classify?env=production
Experimental.
- To be properly reviewed on a hackday.
- Feature needs to be hidden behind an experimental flag
> Experiment: Free Rotation for Subject Viewer

- app/classifier/tasks/index.jsx
- app/classifier/tasks/textFromSubject/editor.jsx
- app/classifier/tasks/textFromSubject/editor.spec.js
- app/classifier/tasks/textFromSubject/index.jsx
- app/classifier/tasks/textFromSubject/index.spec.js
- app/pages/admin/project-status/experimental-features.jsx
- app/pages/lab-fem/workflow.cjsx
Staging branch URL: https://pr-6131.pfe-preview.zooniverse.org
- https://pr-6131.pfe-preview.zooniverse.org/lab/1952/workflows/3602
See related [FEM DigiLeap project](https://github.com/zooniverse/front-end-monorepo/projects/17) and specifically documentation related https://github.com/zooniverse/front-end-monorepo/pull/3008.
- add `textFromSubject` task to admin project experimental features
- add `Text from Subject` option to FEM lab task options
- add `textFromSubject` task with placeholder component
- add `textFromSubject` task editor
> Add TextFromSubject task to FEM lab

- package-lock.json
- package.json
Upgrade `moment` to the latest version.
Staging branch URL: https://pr-6134.pfe-preview.zooniverse.org
Closes https://github.com/zooniverse/how-to-zooniverse/issues/274
> [Security] bump moment to 2.29.3

- app/MonorepoRoutes.jsx
- app/pages/project/index.jsx
- app/router.jsx
Add support for routes like `/projects/:locale/:owner/:name/talk`, which will allow us to support links to PFE project pages from FEM projects.
Try it out with Planet Hunters TESS:
- Talk in Spanish: https://pr-6145.pfe-preview.zooniverse.org/projects/es/nora-dot-eisner/planet-hunters-tess/talk?env=production
- The home page in the test locale:  https://pr-6145.pfe-preview.zooniverse.org/projects/test/nora-dot-eisner/planet-hunters-tess?env=production
Staging branch URL: https://pr-6145.pfe-preview.zooniverse.org
> Add an optional locale to project page routes

- app/MonorepoRoute.jsx
Fix the host name for the NextJS project app on staging.
Staging branch URL: https://pr-6148.pfe-preview.zooniverse.org
> Fix FEM staging host

- app/pages/project/components/LanguagePicker/LanguagePicker.jsx
- app/pages/project/components/LanguagePicker/LanguagePicker.spec.js
Set the `language` query parameter and update the page URL after selecting a new language.
Try it out on a project that's available in multiple languages:
https://pr-6147.pfe-preview.zooniverse.org/projects/arolsen-archives/every-name-counts?env=production
Staging branch URL: https://pr-6147.pfe-preview.zooniverse.org
> Update page URL after changing language

- app/monorepoUtils.js
Add a redirect for `bldigital/in-the-spotlight`.
See also https://github.com/zooniverse/static/pull/286
Staging branch URL: https://pr-6151.pfe-preview.zooniverse.org
> Add In The Spotlight to monorepo projects

- app/classifier/tasks/survey/editor.cjsx
Staging branch URL: https://pr-6143.pfe-preview.zooniverse.org
- review here: https://pr-6143.pfe-preview.zooniverse.org/lab/4312/workflows/20254?env=production
Clarifies survey task setting `alwaysShowThumbnails` consequences.
- add description for `alwaysShowThumbnails` setting, noting fluctuating choices thumbnails sizing
> Add description for survey task alwaysShowThumbnails

- .github/workflows/deploy_production.yml
Staging branch URL: https://pr-6156.pfe-preview.zooniverse.org
Fixes https://github.com/zooniverse/Panoptes-Front-End/runs/7098696366?check_suite_focus=true.
- updates script in production action to `build_production` , continuation of #6154
> Update script for production deploy action

- app/components/pan-zoom.jsx
- css/subject-viewer.styl
Staging branch URL: https://pr-6140.pfe-preview.zooniverse.org
The experimental rotation slider in use at https://www.zooniverse.org/projects/ellenjj/rosetta-zoo/classify was quite short. This was also a frequent item mentioned in the beta review comments: due to it's small size, it was harder to set the angle than it needed to be.
I've switched the CSS over to use vendor prefixes rather than the commonly used rotation trick, because setting an element to full but dynamic "height" after rotation cannot really be done with CSS alone. I hope that this is okay, especially for a tool that's behind an experimental flag. If it cannot be accepted because of this, let me know and I'll rework it to just make it a bit bigger but still statically sized.
Manually tested in Chrome, EdgeChrome, …
> Make rotate slider use all remaining space in the pan/zoom controls area

- app/lib/nav-helpers/getProjectLinks.js
- app/pages/project/components/ProjectNavbar/ProjectNavbarContainer.jsx
Add the current location's `env` and `language` query parameters to project navigation links, so that query parameters are preserved when you change pages, or reload a page.
Prepend the locale to page URLs when we're linking to pages in the NextJS project app.
Try it out on:
- PH TESS in Spanish: https://pr-6146.pfe-preview.zooniverse.org/projects/nora-dot-eisner/planet-hunters-tess/talk?language=es
- PH-TESS in Spanish, without query parameters: https://pr-6146.pfe-preview.zooniverse.org/projects/es/nora-dot-eisner/planet-hunters-tess/talk
- or with the test locale: https://pr-6146.pfe-preview.zooniverse.org/projects/nora-dot-eisner/planet-hunters-tess/talk?language=test
- I Fancy Cats without any query parameters: https://pr-6146.pfe-preview.zooniverse.org/projects/brooke/i-fancy-cats?en …
> Preserve language codes in project navigation

- app/lib/nav-helpers/getProjectLinks.js
- app/pages/project/components/ProjectNavbar/ProjectNavbarContainer.jsx
Reverts zooniverse/Panoptes-Front-End#6146
Seeing some odd behavior due to this PR: an env=null query param is getting appended in cases where no param was originally included.
Example:
- Visit https://www.zooniverse.org/projects/reinforce/deep-sea-explorers
- Click link to visit stats page
- Click banner to return to project landing page
landing page URL is now https://www.zooniverse.org/projects/reinforce/deep-sea-explorers?env=null
Reloading the page (i.e., explicitly loading the URL with query param included) causes an error and page fails to load: `Uncaught Error: Panoptes Javascript Client Error: Invalid Environment; try setting NODE_ENV to "staging" instead of "production".`
The other failure mode: right click to "open in new tab" of any link with env=null will fail to load
> Revert "Preserve language codes in project navigation"

- app/lib/nav-helpers/getProjectLinks.js
- app/pages/project/components/ProjectNavbar/ProjectNavbarContainer.jsx
Staging branch URL: https://pr-6164.pfe-preview.zooniverse.org
Fixes previous PR revert: https://github.com/zooniverse/Panoptes-Front-End/pull/6163
Adds the current location's `env` and `language` query parameters to project navigation links, so that query parameters are preserved when you change pages, or reload a page.
Prepends the locale prefix to URLs when we link to pages in the FEM project app.
PFE Project
- Visit this branch URL and go to a PFE project such as [Galaxy Zoo](https://pr-6164.pfe-preview.zooniverse.org/projects/zookeeper/galaxy-zoo).
- If an env query param such as `?env=production` is added to the url, it will be preserved while using the project header navigation links.
- Use the language dropdown to choose a language other than English.
- The dropdown should add …
> Handle locale in nav query parameters

- app/partials/app.cjsx
Pass down `user` and `initialLoadComplete` as props from the root app to its children. This fixes a bug where project pages won't load if you aren't logged in.
Staging branch URL: https://pr-6169.pfe-preview.zooniverse.org
Fixes #6170.
> Pass initial loading state with the current user

- app/monorepoUtils.js
Related to https://github.com/zooniverse/static/pull/315 
Staging branch URL:  https://pr-6174.pfe-preview.zooniverse.org/
> Add redirect url for Notes from Nature - Labs

- README.md
This PR updates the README with additional information on how to run PFE. There were some deficiencies in information that weren't uncovered until I walked our new intern through the process of setting PFE up.
- New: added explicit instructions on how to view the website (i.e. open local.zooniverse.org:3735)
- New: added important installation notes from #6155
Ready for review. Assigning to MaysaB, but everyone is free to jump in.
> README: update installation & running details

- app/monorepoUtils.js
Related PR: https://github.com/zooniverse/static/pull/317
This PR puts the **Planet Hunters TESSting** project on the FEM codebase.
- Affected URL: https://www.zooniverse.org/projects/zookeeper/planet-hunters-tessting and subpages
- Planet Hunters TESSting is the "test copy" of Planet Hunters TESS
- Note that the owner is zookeeper, not nora-dot-eisner
- In Sep 2022, we want to use this "test copy" to ask users to try out the new Quick Talk feature.
DO NOT MERGE YET.
- We are currently waiting for the project to change its name from ["Planet Hunters TESS"](https://frontend.preview.zooniverse.org/projects/zookeeper/planet-hunters-tess) to "Planet Hunters TESSting".
- (As of 13 Sep 15:00 BST, the "test copy" shares the exact same slug as the original, which is why we're renaming - to avoid …
> Add FEM redirect for Planet Hunters TESSting

- app/pages/home-common/social.jsx
Publications is an external page now, so link to it with a HTML link, not React Router.
Staging branch URL: https://pr-6195.pfe-preview.zooniverse.org
Fixes #6187.
> Home page: Fix ‘Show all publications link’

- app/features/modelling/line-plot/index.js
- package-lock.json
- package.json
Follows #5943
❗ Affects experimental / no-longer-supported feature
This PR updates the LinePlotModel (for the canvas viewer, and it's actually a _scatter plot model,_ because why not) to properly use Chart.js v3
- Previously, the scatter plots on the LinePlotModel wouldn't render, since PR 5943 bumped the `chart.js` dependency to v3
- This is because chart.js v3 introduces tree-shaking, so the way the library is imported has to change. (See: [migration guide](https://www.chartjs.org/docs/latest/getting-started/v3-migration.html), [v3 integration guide](https://www.chartjs.org/docs/3.9.1/getting-started/integration.html))
For info on how the data should look like, see https://www.chartjs.org/docs/3.9.1/charts/scatter.html
Example [JSON](https://panoptes-uploads.zooniverse.org/subject_locati …
> Update LinePlotModel (for canvas viewer) to use Chart.js v3

- package-lock.json
- package.json
Upgrade `panoptes-client` to the latest version, which upgrades Superagent to 8.
Staging branch URL: https://pr-6201.pfe-preview.zooniverse.org
> Bump Panoptes client to v4

- app/pages/home-for-user/index.jsx
This PR change uses the user's project preferences activity counts to calculate their total classification contributions. It  avoids the situation where a project set's their previously accessible project to 'private' and the user's total classification count decreases as it won't include the private projects. 
This change means all classifications contributions a user makes will count in their total. However this change won't impact the ribbon wheel image as that is created by accessing only public projects, hence there can be discrepancies between the total count displayed and the values in the ribbon wheel. 
Staging branch URL: https://pr-6208.pfe-preview.zooniverse.org
Fixes bug reports where users 'lose' classifications on their logged in home page.
> collate logged in home page total classifications count from user's project preferences

- package-lock.json
- package.json
4.2.0 includes improved error handling for response errors.
Staging branch URL: https://pr-6213.pfe-preview.zooniverse.org
> Bump panoptes-client from 4.1.1 to 4.2.0

- app/classifier/tasks/dropdown/index.jsx
- app/classifier/tasks/multiple/index.jsx
- app/classifier/tasks/single/index.jsx
- app/classifier/tasks/subjectGroupComparison/index.jsx
- app/classifier/tasks/survey/index.jsx
- app/classifier/tasks/textFromSubject/index.jsx
- app/pages/lab/workflow.cjsx
- Set a default for `task.required` in the workflow editor.
- Convert string values to booleans in the workflow editor.
- Add `required: false` to default tasks when new tasks are created.
Staging branch URL: https://pr-6215.pfe-preview.zooniverse.org
SquirrelMapper workflow from the original bug report: https://pr-6215.pfe-preview.zooniverse.org/lab/8149/workflows/20808
- Fixes #6214.
- This should fix the project builder showing tasks as required when `task.required` is undefined ~~but won't fix any tasks with `required: 'false'`, since it doesn't overwrite existing values~~. I'll add a couple of lines to convert string values to booleans.
> Project builder: Fix undefined required tasks

- app/pages/lab-fem/workflow.cjsx
Follows #6215 , which applies the same changes for PFE Lab's Workflow Editor.
Also fixes #6214, for FEM projects
This PR updates the FEM Lab's Workflow Editor so that "Required" checkbox for Tasks is checked when task.required is _true or "true",_ and un-checked when task.required is _false, "false", or undefined_
Please see #6215 for testing procedures. Note that the "Shortcut Editor" that exists on PFE Lab does not exist on FEM Lab.
> Project builder: Fix undefined required tasks (FEM Lab ver)

- app/pages/lab/actions/workflow.js
- app/pages/lab/workflow-create-form.cjsx
- app/pages/lab/workflow.cjsx
- Copy workflows via the [`/project/{projectID}/links/workflows`](https://panoptes.docs.apiary.io/#reference/projects/project-create-links/add-a-link) API endpoint.
- Get the new workflow ID from the updated project links.
- Update the new workflow with the new title, then redirect.
Staging branch URL: https://pr-6212.pfe-preview.zooniverse.org
> Copy workflows via the Panoptes API

- app/pages/lab/workflow-create-form.cjsx
Staging branch URL: https://pr-6217.pfe-preview.zooniverse.org
Iteration on #6212 .
Local project for testing - https://local.zooniverse.org:3735/lab/1779/workflows
Production test project on preview for testing - https://pr-6217.pfe-preview.zooniverse.org/lab/4312/workflows
- per [panoptes create workflow schema](https://github.com/zooniverse/panoptes/blob/master/app/schemas/workflow_create_schema.rb#L5) adds `primary_language` to new workflow creation object
- per workflow_versions not null violations add `first_task` empty string and `tasks` empty object
> Add required or not null properties for new workflow creation

- app/classifier/tasks/survey/editor.cjsx
Replace `workflow.update('tasks').save()` with `@props.onChange(@props.task)` throughout.
Since #6215, the `task` prop that is passed into task editors is a shallow copy of the original task, so the workflow won't be updated when the editor makes changes to the task. A consequence of this is that survey tasks no longer update when you edit them in the project builder.
This PR changes the survey task editor to call `@props.onChange(task)` which is a wrapper for 
```js
workflow.update({ [`tasks.${taskKey}`]: task }).save()
```
Staging branch URL: https://pr-6221.pfe-preview.zooniverse.org
> Fix broken survey task editor

- app/pages/lab-fem/workflow.jsx
React no longer automatically binds event handlers to a component, so this binds the workflow editor's event handlers to the component when it is instantiated. This is a direct replacement for `@eventHandler` in the old CoffeeScript version.
Staging branch URL: https://pr-6225.pfe-preview.zooniverse.org
> Workflow editor: bind event handlers on mount

- app/pages/lab-fem/workflow.jsx
Replace `PromiseRenderer` with a data-fetching hook, when the workflow editor loads.
Staging branch URL: https://pr-6226.pfe-preview.zooniverse.org
> Workflow Editor: fetch data with hooks

- app/classifier/classifier.jsx
Check that `subject.expert_classification_data` exists before reading an expert classification.
Staging branch URL: https://pr-6200.pfe-preview.zooniverse.org/projects/povich/milky-way-project/classify
Should fix #6194.
> Fix expert classification data

- app/pages/project/home/index.jsx
Catch errors when fetching the researcher for a project home page. Use `researcher?.avatar_src` as the researcher avatar.
Staging branch URL: https://pr-6199.pfe-preview.zooniverse.org/projects/zooniverse/astronomy-rewind?env=production
Should fix #6189.
> Catch missing researcher avatars

- app/pages/lab/project.jsx
Affects: Project Editor
Small follow up to #6250
This PR is a minor code refactor. We now use ternary operators when deciding to render React components in the Project Editor, instead of `&&` shortcuts. No behaviour change expected.
Running some quick tests before flagging this ready for review.
> Minor refactor: improve Project Editor with ternaries

- app/partials/app.cjsx
Use `getSessionID()`, instead of `generateSessionID()`, to preserve any existing session ID when the page first loads.
Staging branch URL: https://pr-6254.pfe-preview.zooniverse.org
Fixes #6253.
> Preserve session ID on page load

- package-lock.json
- package.json
- webpack.build.js
- webpack.dev.js
- webpack/cjsx-loader.js
Replace cjsx-loader with a custom loader that doesn't depend on `loader-utils@0.2`.
Run `npm audit fix` to bump outdated packages, including `loader-utils`.
Staging branch URL: https://pr-6262.pfe-preview.zooniverse.org
> [Security] Replace outdated cjsx-loader

- package-lock.json
- package.json
Bump `markdownz` from 7.8.6 to [7.9.0](https://github.com/zooniverse/markdownz/releases/tag/v7.9.0).
Staging branch URL: https://pr-6266.pfe-preview.zooniverse.org
> Bump markdownz to 7.9.0

- app/locales/zh-cn.js
Closes #6218
This PR updates our zh-cn translations. Credit goes to @SiminTong, thank you!
- I changed Simin's recommendation of "通过星系动物园账号登录" to "通过 Zooniverse 账号登录".
- I think 星系动物园 translates to ["Galaxy Zoo"](https://www.zooniverse.org/projects/zookeeper/galaxy-zoo/?language=zh-cn), and the correct term should be "login to Zooniverse account", not "login to Galaxy Zoo account".
Staging branch URL: https://pr-{NUMBER}.pfe-preview.zooniverse.org/projects/brooke/i-fancy-cats/?env=staging&language=zh-cn
Ready for review
> Update zh-cn translations

- app/pages/lab-fem/workflow.jsx
- app/pages/lab/workflow-components/task-icon.jsx
Targets and follows #6247 
Affects: Project Builder -> Workflow Editor (PFE Lab & FEM Lab versions)
This PR fixes two issues:
- TaskIcon now has default `return null`, to ensure it doesn't crash the page when an _unaccounted-for Task_ (i.e. Light Curve Task) is rendered.
- The changes to `lab/workflow.jsx` in 6247 is now copied to `lab-fem/workflow.jsx`
**Testing:**
- You can test that _unaccounted-for Tasks_ work properly by taking a look at Planet Hunters TESSting: https://local.zooniverse.org:3735/lab/18190/workflows/20991?env=production&pfeLab=true
- You can test FEM Lab by appending `?femLab=true` to any Workflow Editor URL.
> Addendum for #6247

- Dockerfile
- Remove `apk add` since we're no longer using Alpine.
- Add `.npmrc` before installing, to install with legacy peer dependencies for old packages that are looking for React 16.
Staging branch URL: https://pr-6271.pfe-preview.zooniverse.org
> Fix broken Docker builds

- package-lock.json
- package.json
Run `npm audit fix` to bump `qs` and `formidable`.
Staging branch URL: https://pr-6273.pfe-preview.zooniverse.org
> [Security] Bump qs and formidable

- package-lock.json
- package.json
Bump markdownz from v7.9.0 to v7.10.1
- Release notes [7.10.0](https://github.com/zooniverse/markdownz/releases/tag/v7.10.0)
- Release notes [7.10.1](https://github.com/zooniverse/markdownz/releases/tag/v7.10.1)
Staging branch URL: https://pr-6276.pfe-preview.zooniverse.org
> Bump markdownz to v7.10.1

- .github/dependabot.yml
Allow dependabot to make changes to `package.json`, including major version updates for packages.
Staging branch URL: https://pr-6286.pfe-preview.zooniverse.org
> Use default dependabot versioning strategy

- app/pages/notifications/notification-section.jsx
- app/pages/organization/organization-page.jsx
- app/partials/zooniverse-logo.cjsx
Affects: header site nav, Notifications page, Organizations page
This PR changes the SVG `title` for the Zooniverse Logo component.
At the moment, the Zooniverse Logo has "Zooniverse Logo" has a generic title ("alt text") describing _what the SVG is._ This PR changes that title on a few pages, so we have context for _what the SVG is used for._
**Case 0:** by default, the Zooniverse Logo SVG has title="Zooniverse"
**Case 1:** the **header site nav**'s Zooniverse Logo SVG now has title="Zooniverse", indicating the logo is a link to the Zooniverse home page.
**Case 2:** on the **Notifications** page, for all official notifications from the Zooniverse, the Zooniverse's avatar will have title="Zooniverse Logo"
**Case 3:** on …
> Update Zooniverse Logo title with more context

- app/classifier/tasks/survey/chooser/Choices.jsx
- app/components/thumbnail.jsx
- app/pages/project/home/project-home.jsx
- Make height and width optional for thumbnails.
- Remove the maximum height from thumbnails where they should be resized to a fixed width.
- Fix CSS dimensions for thumbnail sizing.
Fixes an issue where tall portrait images are stretched to match the required width, resulting in pixelated or blurred previews.
Staging branch URL: https://pr-6351.pfe-preview.zooniverse.org
Talk thumbnails for Living With Machines:
- [Blurred on www.zooniverse.org](https://www.zooniverse.org/projects/bldigital/living-with-machines)  
- [Fixed on this branch](https://pr-6351.pfe-preview.zooniverse.org/projects/bldigital/living-with-machines)  <img width="1064" alt="Talk subject thumbnails, crisp and sharp and legible." src="https://user-images.githubusercontent.com/59547/212086437-ad142756-4eae-4349-929b-f61f …
> Thumbnails: make height and width optional

- app/pages/lab/workflow-components/task-editor.jsx
- app/pages/lab/workflow.jsx
Replace another auto-running anonymous closure, generated by decaffeinate, with functional React components:
- `TaskEditor` handles all the logic associated with finding and displaying the editor for the selected workflow task.
Staging branch URL: https://pr-6251.pfe-preview.zooniverse.org
> Workflow editor: refactor task editor

- css/landing-page.styl
- package-lock.json
- package.json
- webpack.build.js
- webpack.dev.js
- Replace `file-loader` with webpack 5 asset modules.
- Set a sensible background colour for the lab landing page.
Staging branch URL: https://pr-6375.pfe-preview.zooniverse.org
Fixes #6374.
> Fix broken lab landing page

- package-lock.json
- package.json
Staging branch URL: https://pr-6382.pfe-preview.zooniverse.org
Related to #6381
- reverts PFE to use panoptes-client (aka PJC) to v4.2.8
- PJC v5.0.0 introduced breaking change as noted in #6381 
fix:
- my test project on staging - https://local.zooniverse.org:3735/lab/1779/subject-sets
- ^ click any subject set and it should load
bug:
- same project as ^, with bug - https://master.pfe-preview.zooniverse.org/lab/1779/subject-sets?env=staging
> Set panoptes-client to 4.2

- package-lock.json
- package.json
- Bumps `json-api-client` to 7.0.2.
- Upgrades the Sugar client to Primus 8.
Staging branch URL: https://pr-6368.pfe-preview.zooniverse.org?env=staging
You can test it out by using the staging API, watching the Sugar websocket connection in browser dev tools.
> Bump panoptes-client to 5.1.0

- app/talk/discussion.cjsx
Set the default board ID from the page URL, so that it isn’t undefined when the page loads.
Staging branch URL: https://pr-6388.pfe-preview.zooniverse.org
Fixes #6278.
> Fix moderator discussion board menu

- app/pages/lab/workflow-components/tutorials.jsx
Update the workflow tutorials widget to allow for a case where Panoptes might erroneously link more than one tutorial of the same type to a single workflow.
Staging branch URL: https://pr-6405.pfe-preview.zooniverse.org/lab
Fixes #6400.
> Lab: more robust workflow-tutorial links

- app/lib/get-social-data.js
- app/pages/home-common/social.jsx
- Replace XHR with `fetch`.
- Refactor with `async/await`.
- Catch response errors and return an empty feed by default.
Staging branch URL: https://pr-6413.pfe-preview.zooniverse.org
Fixes #6412.
> Handle errors on the Zooniverse social feed

- app/pages/lab-fem/workflow.jsx
- app/pages/lab/workflow-components/task-editor.jsx
- app/pages/lab/workflow.jsx
Follows #6251, which applies similar changes for PFE Lab's Workflow Editor.
This PR updates the FEM Lab's Workflow Editor so the "Edit Task" portion of the Workflow Editor uses the new Task Editor component.
- Task Editor component has also been updated to accept a `pfeLab=true|false` value. This is due to FEM Lab not supporting the experimental Shortcuts feature any more.
Please see #6251 for testing procedures.
- Test project in PFE Lab (Shortcuts are enabled, and Shortcut Editor should be visible): [(local)](https://local.zooniverse.org:3735/lab/1966/workflows/3731?pfeLab=true)
- Test project in FEM Lab (Shortcut Editor should NOT be visible): [(local)](https://local.zooniverse.org:3735/lab/1966/workflows/3731?femLab=true)
> Workflow editor: refactor task editor (FEM Lab version)

- app/pages/admin/user-settings.jsx
- app/pages/admin/user-settings/stats.js
Add a form to the user admin page, which filters their classifications by classified subject ID. Handy if you want to debug reports of duplicate subjects for a volunteer.
Staging branch URL: https://pr-6426.pfe-preview.zooniverse.org
> Debug volunteer classifications by subjectID

- app/components/file-viewer/image-viewer.jsx
- app/main.cjsx
Capture image loading errors so that we can log any problems with timeouts from `panoptes-uploads`.
Staging branch URL: https://pr-6427.pfe-preview.zooniverse.org
> Log subject image errors to Sentry

- package-lock.json
Reinstall `webpack-dev-server`, to force an upgrade of its dependencies and fix [a crashing bug in `memfs` 3.4.1](https://github.com/streamich/memfs/issues/828) on Node 18.
Staging branch URL: https://pr-6438.pfe-preview.zooniverse.org
> Upgrade webpack-dev-server dependencies

- app/features/feedback/README.md
Edit Feedback Docs: add list of strategies to top-level feedback README page that links to strategy-specific README pages lower in the hierarchy.
> Edit Feedback Docs

- app/lib/put-file.js
Update the `putFile` helper to sanitise SVG files and remove unsafe tags, such as `script`.
Towards https://github.com/zooniverse/panoptes/security/advisories/GHSA-85fr-5pvp-fmjm
You can test this out by uploading an SVG file, containing malicious content, via any of the components that use `putFile`:
- project media uploads.
- project subject uploads.
- project avatars.
- user avatars.
- field guide icons.
Any scripts etc. in the original SVG should be stripped out before it is uploaded.
https://pr-6479.pfe-preview.zooniverse.org
> Sanitise SVG file uploads

- app/components/file-viewer/canvas-viewer.jsx
- app/components/thumbnail.jsx
- app/features/modelling/line-plot/index.js
- app/pages/profile/recents.jsx
- Refactor `Recents` as a functional component.
- add a fake subject and viewer for `application/json` URLs.
- fix a small bug where the canvas viewer crashes if you try to use it when it's already in use.
Staging branch URL: https://pr-6491.pfe-preview.zooniverse.org
Classify a few supernova candidates on this workflow, then go to Recents. Your recent classifications should show up as scatterplot charts, each of them linked through to the Talk page for that subject. There are only 6 subjects, so you should be able to get through them all very quickly.
https://pr-6491.pfe-preview.zooniverse.org/projects/eatyourgreens/-project-testing-ground/classify?reload=0&workflow=3742&env=staging
> Add JSON data subjects to recents

- .github/workflows/deploy_branch.yml
- .github/workflows/deploy_production.yml
- .github/workflows/deploy_staging.yml
Deploy notifications for this repo are now handled by the github slack app, where the #deploys channel is subscribed to the repo's workflow events.
> Remove slack notifications from deploy actions

- app/pages/lab-fem/components/fem-multi-image-subject-options-editor.jsx
Staging branch URL: https://pr-6536.pfe-preview.zooniverse.org
I added four options to the FEM lab's multi-image subject options section: "row", "grid2", and "grid3" are already established as layout options in PFE. In this PR I also added the option of "col". The layout options only appear when a workflow has "allow volunteers to switch between flipbook and separate frames" enabled:
Below are the four layouts rendered in a workflow with a subject that has five frames. The subject image becomes tiny in a "row" or "3-col grid", but we can trust project teams will choose the layout that best suits their subject type. This is just an example.
Column
Row
Grid With 2 Columns
Grid With 3 Columns
@seanmiller26 for your review in addition to the screenshots above:
- Should I add text to the lab …
> FEM lab: Add separate frames layout options

- app/classifier/tasks/generic-editor.cjsx
Staging branch URL: https://pr-6538.pfe-preview.zooniverse.org
Towards https://github.com/zooniverse/front-end-monorepo/pull/4326.
Refactors colors as defined by related [Figma design](https://www.figma.com/file/miwXeAuA8iqBOD4E8ofOXR/Digi-Leap?node-id=0-1&t=XX5H8IzWxXXEP7au-0).
Staging project builder workflow with highlighter task - https://pr-6538.pfe-preview.zooniverse.org/lab/1952/workflows/3538?env=staging
> Refactor highlighter task colors

- app/collections/show-list.jsx
Filter deleted subjects out of the displayed subjects, then display the filtered list.
Staging branch URL: https://pr-6541.pfe-preview.zooniverse.org
Fixes #6539.
> Fix subject delete buttons in collections

- app/classifier/tasks/highlighter/index.jsx
- app/classifier/tasks/highlighter/label-renderer.jsx
Staging branch URL: https://pr-6548.pfe-preview.zooniverse.org
Fixes #6537 .
- adjust highlighter annotation `end` calculation to subtract 1 from range endOffset, see issue for detailed comparison
- adjust label renderer calculation per adjustment to end calculation
- remove `extraNewLineCharacter` which is no longer applicable for IE 11 (not supported) and Edge (no longer issue with current versions of Edge), added in #3954
local testing - https://local.zooniverse.org:3735/projects/markb-panoptes/digileap-testing-staging/classify?reload=0&workflow=3538
branch testing - https://pr-6548.pfe-preview.zooniverse.org/projects/markb-panoptes/digileap-testing-staging/classify?reload=0&workflow=3538&env=staging
> Refactor highlighter annotation end calculation

- app/lib/get-social-data.js
- app/pages/home-common/social.jsx
Fetch the home page blog feeds direct from `wordpress.com`.
Staging branch URL: https://pr-6629.pfe-preview.zooniverse.org
Fixes #6613.
> Fix home page social feeds

- app/monorepoUtils.js
Staging branch URL: https://pr-6681.pfe-preview.zooniverse.org/projects/communitiesandcrowds/how-did-we-get-here
- add `'communitiesandcrowds/how-did-we-get-here'` to monorepoUtils redirect slugs
Related to https://github.com/zooniverse/static/pull/324
> Add communitiesandcrowds/how-did-we-get-here to monorepoUtils redirect slugs

- app/constants/languages.js
Labels and ISO 693-3 language codes for Tshivenḓa and Xitsonga.
Staging branch URL: https://pr-6729.pfe-preview.zooniverse.org
> Add Venda and Tsonga language codes

- app/constants/languageMenu.js
Staging branch URL: https://pr-6753.pfe-preview.zooniverse.org
To address this freshdesk [ticket](https://zooniverse.freshdesk.com/a/tickets/17617) request to enable Indonesian translations.
Should this be alphabetized into the language menu by locale code or the first letter of the label?
> Add Indonesian to language menu

- app/pages/lab/translations/index.jsx
Staging branch URL: https://pr-6755.pfe-preview.zooniverse.org
I added an additional sentence to the Translations tab in the lab instructing project owners to email Zooniverse if they've submitted translations for a language, but that language doesn't show up as a checkbox. That scenario means they're the first project to translate that language and it needs to be added to the menus on frontend apps.
> Lab: Add instructions in Translations tab for new language

- app/pages/admin/project-status.jsx
On a project's workflow admin settings, emphasise that individual data subject viewers have been deprecated by displaying that text in bold.
Staging branch URL: https://pr-6792.pfe-preview.zooniverse.org/admin/project_status/nora-dot-eisner/planet-hunters-tess
> Emphasise that JSON subject viewers are deprecated

- app/classifier/tasks/dataVisAnnotation/index.jsx
- app/classifier/tasks/generic-editor.cjsx
- app/classifier/tasks/index.js
- app/pages/lab-fem/fem-lab-utilities.js
- app/pages/lab-fem/workflow.jsx
Add the data selection task (`dataVisAnnotation`) to the list of new tasks in the workflow editor. Only one tool is available at the moment, `graph2dRangeX`, so that's hardcoded into the editor (similar to the point tool for drawing tasks.)
Data selection is available as an option if either:
- the workflow has `application/json` subjects.
- the workflow is configured to use the JSON data viewer.
Staging branch URL: https://pr-6808.pfe-preview.zooniverse.org/lab/908/workflows/3762?femLab=true&env=staging
> Add the data selection task to the project builder

- app/pages/lab-pages-editor/DataManager.jsx
- app/pages/lab-pages-editor/Tester.jsx
Follows #6787 
The aim of this PR is to allow the Pages Editor to update Workflow resources and save those changes to Panoptes.
The plan:
- The `DataManager` component should have an `update()` function 
- ⚠️ OR better yet, updates should be queued _(Shaun's note: Not sure if this needs to be a stretch goal, or if this is already handled by [PJC's "save()"](https://github.com/zooniverse/panoptes-javascript-client/blob/master/lib/json-api-client/resource.js#L40-L75) functionality)_
- For this PR the `Tester` UI component serves as a rudimentary read/write interface.
WIP
> Pages Editor: Save/Update Workflow

- app/lib/get-social-data.js
- app/pages/home-common/social.jsx
Sort recent blog posts by `created_at`, so that the most recent blog post is always first on the home page.
Staging branch URL: https://pr-6814.pfe-preview.zooniverse.org
Fixes #6813.
> Sort recent blog posts by created_at

- app/classifier/tasks/dropdown/dropdown-dialog.cjsx
- app/classifier/tasks/dropdown/editor.jsx
- app/classifier/tasks/dropdown/editor.spec.js
Bifurcates the Dropdown in PFE & FEMLab interface to implement SimpleDropdown only in FEMLab.
Toward https://github.com/zooniverse/Panoptes-Front-End/issues/6765
[PFE without FEMLab enabled for a Dropdown](https://pr-6820.pfe-preview.zooniverse.org/lab/1996/workflows/3771?env=staging):
[PFE with FEMLab enabled for a Dropdown should](https://pr-6820.pfe-preview.zooniverse.org/lab/1995/workflows/3770?env=staging):
> POC of bifurcation of SimpleDropdown for FEMLab in PFE

- app/pages/lab-pages-editor/PagesEditor.jsx
- app/pages/lab-pages-editor/components/WorkflowHeader.jsx
- app/pages/lab-pages-editor/components/WorkflowSettingsPage.jsx
- css/lab-pages-editor.styl
Follows #6822
Staging Example: https://pr-6836.pfe-preview.zooniverse.org/lab/1982/workflows/editor/3711?env=staging
Tabs Pattern: https://www.w3.org/WAI/ARIA/apg/patterns/tabs/
This PR adjusts the Workflow Header so that the navigation/paging tabs actually behaves like the ARIA-specified Tabs patten. This follows [feedback](https://github.com/zooniverse/Panoptes-Front-End/pull/6822#pullrequestreview-1630968196) from the previous PR.
- Elements should now have `tablist`, `tab`, and `tabpanel` roles
- Mouse: clicking on Task or Workflow Settings should switch to the appropriate panel (or placeholder panel)
- Keyboard:
- tab-navigation (pressing the Tab key on a keyboard) should only allow users to focus on the …
> Pages Editor: improve Workflow Header with Tabs pattern

- app/partials/project-card.cjsx
Fixes #6855  .
Provide default value for props.project. I haven't followed the testing protocol as I'm not using a staging environment.
> project-card.cjsx: provide default value for props.project

- app/classifier/tasks/dropdown/dropdown-dialog.cjsx
Staging branch URL: https://pr-6872.pfe-preview.zooniverse.org
Limit the SimpleDropdown within FEMLab to between 4-200 options. 
Toward https://github.com/zooniverse/Panoptes-Front-End/issues/6765
[PFE without FEMLab enabled for a Dropdown](https://pr-6872.pfe-preview.zooniverse.org/lab/1996/workflows/3771?env=staging):
[PFE with FEMLab enabled for a Dropdown should](https://pr-6872.pfe-preview.zooniverse.org/lab/1995/workflows/3770?env=staging):
> Limit FEMLab Dropdown to only allow between 4-200 options.

- app/pages/lab-pages-editor/components/TasksPage.jsx
- app/pages/lab-pages-editor/helpers/constants.js
- app/pages/lab-pages-editor/helpers/convertKeyToIndex.js
- app/pages/lab-pages-editor/helpers/createStep.js
- app/pages/lab-pages-editor/helpers/createTask.js
- app/pages/lab-pages-editor/helpers/getNewStepKey.js
- app/pages/lab-pages-editor/helpers/getNewTaskKey.js
- css/lab-pages-editor.styl
Follow #6868
Staging branch URL: https://pr-6888.pfe-preview.zooniverse.org/lab/1982/workflows/editor/3711?env=staging
This PR implements the functionality of the _"Add a New Task +"_ button. Clicking the button will: 1. create a new empty **(Text)** Task, 2. create a new Step/Page then add that Task to it, and 3. add the Task + Step/Page to the Workflow resource (i.e. save to Panoptes)
- Tasks are created with Task Keys like T0, T1, T2, etc.
- Steps/Pages are created with Task Keys like P0, P1, P2, etc.
- Tasks will be visible (listed) on the Tasks page.
- Temporary Debug code: "Reset" button added. 
- ⚠️ UI issue: the Steps List is actually only _listing Tasks, not Steps with Tasks._ This won't be relevant when running …
> Pages Editor: implement basic "Add Tasks" functionality

- app/pages/home-not-logged-in.jsx
Staging branch URL: https://pr-6925.pfe-preview.zooniverse.org
Updating Non-Logged In Home Page to Callout to new Stats Service for Stress Testing new stats service. (Stress testing CPU usage on managed timescale + current app resources, to see if we need to scale up)
> update non logged in home page to call out to ERAS stats service

- app/pages/lab-pages-editor/components/TasksPage/TasksPage.jsx
- app/pages/lab-pages-editor/components/TasksPage/components/NewTaskButtonAndDialog.jsx
- app/pages/lab-pages-editor/components/TasksPage/components/StepItem.jsx
- app/pages/lab-pages-editor/components/TasksPage/components/TaskItem.jsx
- app/pages/lab-pages-editor/icons/CloseIcon.jsx
- app/pages/lab-pages-editor/icons/CopyIcon.jsx
- app/pages/lab-pages-editor/icons/DeleteIcon.jsx
- app/pages/lab-pages-editor/icons/EditIcon.jsx
- app/pages/lab-pages-editor/icons/GripIcon.jsx
- app/pages/lab-pages-editor/icons/MoveDownIcon.jsx
- app/pages/lab-pages-editor/icons/MoveUpIcon.jsx
- app/pages/lab-pages-editor/icons/ReturnIcon.jsx
- app/pages/lab-pages-editor/icons/TaskIcon.jsx
- css/lab-pages-editor.styl
Follow #6898
Staging branch URL: https://pr-6915.pfe-preview.zooniverse.org/lab/1982/workflows/editor/3711?env=staging
This PR adds the "Add New Task" Dialog.
Expected behaviour:
- On the Tasks Page:
- clicking "Add a new Task" button should open the Add New Task dialog
- On the Add New Task Dialog:
- clicking on a Task type should...
- create a new Step, e.g. `P0`
- create a new Task, corresponding to the Task type, e.g. `T0`.
- add the new Task to the new Step.
- update the workflow resource with the task and steps (NOTE: most of the above has a POC with experimentalAddNewTaskWithStep())
- close the Add New Task dialog, ~~then open the Edit Step dialog with the new Step selected.~~
- pressing Esc or clicking the 'x' …
> Pages Editor: add "Add New Task" Dialog

- app/pages/lab-pages-editor/components/TasksPage/TasksPage.jsx
- app/pages/lab-pages-editor/helpers/linkStepsInWorkflow.js
Follows #6915
Staging branch URL: https://pr-6939.pfe-preview.zooniverse.org/lab/1982/workflows/editor/3711?env=staging
This PR ensures that Steps are automatically linked to each other (i.e. Page 1 goes to Page 2, etc) 
- `linkStepsInWorkflow()` added.
- This function is currently called every time a new Step is added...
- ...and _will_ also be called when a Step is rearranged or deleted. 
- The rules:
- If a Step ~~is branching~~ **can** branch OR is the last Step in the workflow, step.next = undefined
- Otherwise, that Step's step.next = next step's ID. 
Additional thoughts:
- In the future, linkStepsInWorkflow() could be part of a cleanUp() workflow function, which is called every time the WF is updated, and does the …
> Pages Editor: link Steps together

- app/pages/notifications/notification-section.jsx
- app/pages/notifications/notification-section.spec.js
Staging branch URL: https://pr-6972.pfe-preview.zooniverse.org
Fixes issue noted with recent PRs CI testing on node v20.10.0. The NotificationSection tests were providing a non-iterable value for an item that the component needs to be iterable.
This issue reminded me notifications would benefit from a refactor like #6815 or similar.
- refactor tests with props and state values such that component doesn't error when shallow rendered for tests
> Fix notification-section tests

- app/components/file-viewer/canvas-viewer.jsx
- app/components/thumbnail.jsx
Show a small `FileViewer` as the thumbnail for data subjects, with the MIME type `application/json`.
Staging branch URL: https://pr-7019.pfe-preview.zooniverse.org
You can test this out on the relaunched Black Hole Hunters, where the `Thumbnail` component is used to show subject previews for hashtags:
https://www.zooniverse.org/projects/cobalt-lensing/black-hole-hunters/talk/tags/lensing
- Closes #7020.
> Add thumbnails for application/json subjects

- app/pages/lab/subject-set.cjsx
Adds `mp4` as a supported file type to list in the Lab's drag-and-drop subject uploader (on subject set page).  File type is already supported but not included in the list displayed in the Lab.
Staging branch URL: https://pr-7025.pfe-preview.zooniverse.org
> edit extension list for lab uploader

- app/pages/lab-pages-editor/components/TasksPage/TasksPage.jsx
- app/pages/lab-pages-editor/components/TasksPage/components/StepItem.jsx
- app/pages/lab-pages-editor/components/WorkflowHeader.jsx
- app/pages/lab-pages-editor/components/WorkflowSettingsPage.jsx
- app/pages/lab-pages-editor/helpers/moveItemInArray.js
- css/lab-pages-editor.styl
Follows #6939
Staging branch URL: https://pr-6947.pfe-preview.zooniverse.org/lab/1982/workflows/editor/3711?env=staging
This PR allows Pages/Steps in the workflow.steps array to be rearranged.
- New helper: `moveItemInArray()`. This is a pretty useful general-purpose utility function, as it turns out.
- TasksPage: new `moveStep()` function can be called to rearrange Pages/Steps, _run a cleanup process that re-links the newly arranged Pages/Steps,_ and saves the changes to Panoptes.
- StepsItem:
- New action: pressing the up/down buttons will rearrange the Page/Step.
- **[TODO]** New action: Page/Step can be rearranged via dragging & dropping
WIP, I still need to do that drag & drop.
Do not merge until 6915 + 6939 are …
> Pages Editor: allow Steps to be rearranged

- app/pages/lab-pages-editor/components/TasksPage/TasksPage.jsx
- app/pages/lab-pages-editor/components/TasksPage/components/EditStepDialog/EditStepDialog.jsx
- app/pages/lab-pages-editor/components/TasksPage/components/EditStepDialog/EditTaskForm.jsx
- app/pages/lab-pages-editor/components/TasksPage/components/EditStepDialog/types/SingleQuestionTask.jsx
- app/pages/lab-pages-editor/components/TasksPage/components/EditStepDialog/types/TextTask.jsx
- app/pages/lab-pages-editor/icons/CloseIcon.jsx
- app/pages/lab-pages-editor/icons/CopyIcon.jsx
- app/pages/lab-pages-editor/icons/DeleteIcon.jsx
- app/pages/lab-pages-editor/icons/EditIcon.jsx
- app/pages/lab-pages-editor/icons/GripIcon.jsx
- app/pages/lab-pages-editor/icons/MinusIcon.jsx
- app/pages/lab-pages-editor/icons/MoveDownIcon.jsx
- app/pages/lab-pages-editor/icons/MoveUpIcon.jsx
- app/pages/lab-pages-editor/icons/PlusIcon.jsx
- app/pages/lab-pages-editor/icons/ReturnIcon.jsx
- app/pages/lab-pages-editor/icons/TaskIcon.jsx
- css/lab-pages-editor.styl
Follows #6973
Staging branch URL: https://pr-6981.pfe-preview.zooniverse.org/lab/1982/workflows/editor/3711?env=staging
This PR implements the Edit Task Form (the actual interesting bits inside the Edit Step/Page dialog).
- Currently supports editing: **Text Task** and **Single Question Task**
- Deferred for another PR: Drawing Task
- Text Task: project owners can edit main text, help text, and is required y/n.
- Single Question Task: project owners can...
- edit main text, help text and is required y/n
- add, edit, and delete choices (Answers)
- NOT choose the next Step/Page yet. That's for the next PR.
_Screenshot: user editing Page P0, Text Task T0_
_Screenshot: user editing Page P0, Single Question Task T0 with 3 …
> Pages Editor: implement Edit Task Form

- app/pages/lab-pages-editor/components/TasksPage/TasksPage.jsx
- app/pages/lab-pages-editor/components/TasksPage/components/EditStepDialog/types/SingleQuestionTask.jsx
- app/pages/lab-pages-editor/components/TasksPage/components/EditStepDialog/types/TextTask.jsx
- app/pages/lab-pages-editor/components/TasksPage/components/NewTaskDialog.jsx
- app/pages/lab-pages-editor/components/TasksPage/components/StepItem/BranchingControls.jsx
- app/pages/lab-pages-editor/components/TasksPage/components/StepItem/DropTarget.jsx
- app/pages/lab-pages-editor/components/TasksPage/components/StepItem/StepItem.jsx
- app/pages/lab-pages-editor/components/WorkflowHeader.jsx
- app/pages/lab-pages-editor/helpers/canStepBranch.js
- app/pages/lab-pages-editor/helpers/linkStepsInWorkflow.js
- app/pages/lab-pages-editor/icons/ExternalLinkIcon.jsx
- css/lab-pages-editor.styl
Follows #6981
Staging branch URL: https://pr-6991.pfe-preview.zooniverse.org/lab/1982/workflows/editor/3711?env=staging
This PR adds the ability to **choose the next Page**, for Steps with branching Tasks.
- i.e. any Step with a Single Question Task will enable branching controls.
- When branching controls are enabled, a choice of Next Step/Page is given for every answer/choice in the task
- The Next Step/Page is identified by the Tasks keys within that Step/Page. 
- The visual UI doesn't fully match Sean's design (notably, the yellow arrows aren't going beyond the Step body's container) but that's
- _(2024.02.13 EDIT: I forgot to finish this sentence earlier. It should have said "The visual UI doesn't fully match Sean's …
> Pages Editor: implement Branching Controls

- app/pages/lab-fem/components/fem-multi-image-subject-options-editor.jsx
Staging branch URL: https://pr-6996.pfe-preview.zooniverse.org
Adds the option to clone marks in FEM Lab of PFE. Work towards [issue #5493](https://github.com/zooniverse/front-end-monorepo/issues/5493)
> Add clone options for flipbook/multiframe drawing tasks.

- app/pages/admin/user-settings/details.jsx
Adds `confirmed_at` User property to admin page, helping verify email confirmation status (especially useful for troubleshooting Talk posting problems).
Staging branch URL: https://pr-7050.pfe-preview.zooniverse.org
For testing (assuming tester can enter admin mode):
- Unconfirmed user: https://pr-7050.pfe-preview.zooniverse.org/admin/users/2698362
- Confirmed User: https://pr-7050.pfe-preview.zooniverse.org/admin/users/1901126
> Add confirmed at to admin page

- app/pages/lab-pages-editor/components/TasksPage/TasksPage.jsx
- app/pages/lab-pages-editor/components/TasksPage/components/EditStepDialog/types/SingleQuestionTask.jsx
- app/pages/lab-pages-editor/components/TasksPage/components/StepItem/StepItem.jsx
- app/pages/lab-pages-editor/helpers/cleanupTasksAndSteps.js
- css/lab-pages-editor.styl
Follows #6991
Staging branch URL: https://pr-7046.pfe-preview.zooniverse.org/lab/1982/workflows/editor/3711?env=staging
This PR adds the ability to **delete a Step/Page**.
- Clicking on the "trash can" icon on a Page will prompt a confirmation dialog, before deleting a Step/Page.
- Any _Branching Task_ with answers that pointed to the now-deleted Page will be updated, so the answers now point to nothing (i.e. "Submit").
- A new `cleanupTasksAndSteps()` helper function has been added to remove orphaned references in branching tasks, (this has been implemented). This maaay be updated in the future to also remove Tasks that aren't associated with any Steps, and remove Steps that have 0 Tasks. We'll see.
Other changes:
- …
> Pages Editor: implement Delete Page action

- app/pages/lab-pages-editor/DataManager.jsx
- app/pages/lab-pages-editor/PagesEditor.jsx
- app/pages/lab-pages-editor/components/TasksPage/TasksPage.jsx
- app/pages/lab-pages-editor/components/WorkflowSettingsPage/WorkflowSettingsPage.jsx
- app/pages/lab-pages-editor/components/WorkflowSettingsPage/components/AssociatedSubjectSets.jsx
- app/pages/lab-pages-editor/components/WorkflowSettingsPage/index.jsx
- app/pages/lab-pages-editor/helpers/getPreviewEnv.js
- css/lab-pages-editor.styl
Follows #7046
Staging branch URL: https://pr-7048.pfe-preview.zooniverse.org/lab/1982/workflows/editor/3711?env=staging
This PR implements the "Associated Subject Sets" feature on the Workflow Settings sub-page.
- New component: AssociatedSubjectSets.
- New behaviour/feature: on Pages Editor (for any Workflow) -> Workflow Settings...
- The _Associated Subject Sets_ feature should list all Subject Sets available to the Project _(caveat: up to a max of 250. Paging may be a future problem to solve.)_
- The Associated Subject Sets feature _(and no, I will not shorten it to an acronym)_ should show which Subject Sets are linked to the Workflow via ticked checkboxes.
- Clicking on the checkboxes should link/unlink Subject Sets …
> Pages Editor: implement Associated Subject Sets & fetch more data

- views/index.ejs
Staging branch URL: https://pr-7057.pfe-preview.zooniverse.org
Closes #7051 . Fixes #7056 
This PR removes `polyfill.io` from our base HTML file. At the moment, Polyfill.io breaks our Markdown components for _Safari browsers._ For example, posts on Talk pages viewed on Safari  are no longer formatted.
Example of what we expect to see:
Example of what we actually see, prior to the fix in this PR:
Issue was confirmed on local with macOS + Safari 15.6.1 (yes, that old) and on Browserstack with macOS + Safari 17.3
**For the tester:** since this is a small change that may have a large effect, a second set of eyes running some very thorough checks would be very appreciated. I've listed my suggested testing method, and I've also retained the default testing checklist that comes with PFE PRs …
> Remove polyfill.io

- app/monorepoUtils.js
Add FEM redirects for Civil War: Bluejackets (Project 21982)
Staging branch URL: https://pr-7058.pfe-preview.zooniverse.org/
Staging URL for Project: https://pr-7058.pfe-preview.zooniverse.org/projects/bluejackets/civil-war-bluejackets
Target Link: https://www.zooniverse.org/projects/bluejackets/civil-war-bluejackets
Project Lab Link: https://www.zooniverse.org/lab/18285
Static PR: https://github.com/zooniverse/static/pull/342
> Add FEM redirect for Civil War Bluejackets

- app/talk/search-result.jsx
Fix an error where `project.slug` is undefined in Talk search results,
leading to raw markdown strings being passed to the HTML parser in
the `Markdown` component.
Staging branch URL: https://pr-7068.pfe-preview.zooniverse.org/talk/search?page=11&query=add&env=production
- Fixes #7067.
> fix: undefined project.slug in Talk search results

- app/pages/lab/project-details.cjsx
Staging branch URL: https://pr-7070.pfe-preview.zooniverse.org
Closes https://github.com/zooniverse/front-end-monorepo/issues/3633
Removed the phrase "These links open in a new tab when clicked." External links behave differently in PFE and FEM, so I just removed the related help text in the lab for now. FEM-hosted projects still use parts the PFE lab for the foreseeable future, so lab instructions must make sense to both.
> Lab: edit the External Links section copy

- app/pages/lab-pages-editor/components/TasksPage/TasksPage.jsx
- app/pages/lab-pages-editor/components/TasksPage/components/StepItem/BranchingNextControls.jsx
- app/pages/lab-pages-editor/components/TasksPage/components/StepItem/NextStepArrow.jsx
- app/pages/lab-pages-editor/components/TasksPage/components/StepItem/SimpleNextControls.jsx
- app/pages/lab-pages-editor/components/TasksPage/components/StepItem/StepItem.jsx
- app/pages/lab-pages-editor/components/TasksPage/components/StepItem/TaskItem.jsx
- app/pages/lab-pages-editor/helpers/cleanupTasksAndSteps.js
- css/lab-pages-editor.styl
Follows #7052
Staging branch URL: https://pr-7055.pfe-preview.zooniverse.org/lab/1982/workflows/editor/3711?env=staging
This PR rebuilds the "Next Page" logic. Plus, it adds placeholder answers (fake text input & fake buttons for tasks). All this has been done mostly for UI examining purposes.
Next Page Logic:
- Previously, the Branching Controls (the component that lets were the property of the Page/Step.
- However, this was a problem - the branching controls weren't setting `step.next`, but instead `step.task[x].answer[y].next`! This meant that if we have more than 1 Single Question Task on the Page/Step, and _especially_ if that SQT _wasn't the final Task_ on the Page/Step, the visual design would be broken.
- Now, …
> Pages Editor: rebuild "Next Page" logic. Add placeholder answers.

- app/pages/home-not-logged-in/research.jsx
Staging branch URL: https://pr-7081.pfe-preview.zooniverse.org
This PR is a very small text update to the (hardcoded) number of volunteers on the non-signed-in home page. Requested by @apreleva , since the static number of volunteers (1.6m) clashes with the dynamic number of volunteers (2,729,414 as of 23 Apr 14:40 BST).
Long term, we may want to rewrite this `researchHomePage.about` text block to be _numerically agnostic,_ since the number of volunteers is already dynamically fetched and displayed.
> Home Page: minor text update to volunteer numbers

- app/pages/lab-pages-editor/components/TasksPage/TasksPage.jsx
- app/pages/lab-pages-editor/components/TasksPage/components/EditStepDialog/EditStepDialog.jsx
- app/pages/lab-pages-editor/components/TasksPage/components/EditStepDialog/EditTaskForm.jsx
- app/pages/lab-pages-editor/components/TasksPage/components/EditStepDialog/types/SingleQuestionTask.jsx
- app/pages/lab-pages-editor/components/TasksPage/components/EditStepDialog/types/TextTask.jsx
- app/pages/lab-pages-editor/helpers/cleanupTasksAndSteps.js
- css/lab-pages-editor.styl
Follows #7065
Staging branch URL: https://pr-7075.pfe-preview.zooniverse.org/lab/1982/workflows/editor/3711?env=staging
This PR implements the "Delete Task" functionality, which deletes Tasks from an _existing_ Page. Prior to this PR, you only had the "Delete Page/Step" functionality.
New Behaviour:
- Tasks in the "Edit Page/Step" modal should now have a "Delete Task" button (trashcan icon).
- Clicking on the button will prompt users to confirm if they want to delete the task.
- If this is the only task in a page/step, additional information will be given.
- Confirming the action will result in the Task being deleted.
- Cancelling will result in no action.
- If the only task in a page/step is deleted, the page/step will …
> Pages Editor: add "Delete Task from Page" functionality

- app/monorepoUtils.js
Newly migrated project [Where's Walleye](https://www.zooniverse.org/projects/dangogh/wheres-walleye) is having issues with FEM. This migrates the project back but will require a Friday deploy to get out quickly.
static PR: https://github.com/zooniverse/static/pull/350
> Revert FEM migration for Walleye project

- app/monorepoUtils.js
Another emergency un-migration, this time for `sandiegozooglobal/wildwatch-burrowing-owl`. 
Static PR: https://github.com/zooniverse/static/pull/351
> Revert FEM migration for owl project

- app/pages/lab/mobile/mobile-section-container.fixtures.js
- app/pages/lab/mobile/mobile-section-container.jsx
- app/pages/lab/mobile/mobile-section-container.spec.js
Staging branch URL: https://pr-7092.pfe-preview.zooniverse.org
Based on addition of feedback on mobile for single or multiple answer question tasks (see https://github.com/zooniverse/mobile/pull/572), I've removed the feedback-related check for mobile compatible for workflows with that task type.  Code and tests were rewritten to only apply this check for drawing tasks.
For testing, consider this production project: https://www.zooniverse.org/lab/15140
- [Workflow 26145](https://www.zooniverse.org/lab/15140/workflows/26145): feedback check should not be applied, all checks should pass, and the workflow should be able to be enabled for mobile.
- [Workflow 18155](https://www.zooniverse.org/lab/15140/workflows/18155): feedback check should applied and the workflow should be able to be …
> Remove feedback check for mobile compatibility

- app/pages/lab-pages-editor/components/TasksPage/TasksPage.jsx
- app/pages/lab-pages-editor/components/TasksPage/components/EditStepDialog/EditStepDialog.jsx
- app/pages/lab-pages-editor/components/TasksPage/components/EditStepDialog/EditTaskForm.jsx
- app/pages/lab-pages-editor/components/TasksPage/components/EditStepDialog/types/SingleQuestionTask.jsx
- app/pages/lab-pages-editor/components/TasksPage/components/EditStepDialog/types/TextTask.jsx
- app/pages/lab-pages-editor/components/TasksPage/components/NewTaskDialog.jsx
- app/pages/lab-pages-editor/components/TasksPage/components/StepItem/SimpleNextControls.jsx
- app/pages/lab-pages-editor/components/TasksPage/components/StepItem/StepItem.jsx
- app/pages/lab-pages-editor/components/TasksPage/components/StepItem/TaskItem.jsx
- app/pages/lab-pages-editor/icons/TaskIcon.jsx
- css/lab-pages-editor.styl
Follows #7075
Staging branch URL: https://pr-7079.pfe-preview.zooniverse.org/lab/1982/workflows/editor/3711?env=staging
This PR adds special rules for the "Add Task to Page" functionality. (See #7065)
The overall rule is this: _a Step can only have 1 branching task (single answer question task)_
(New behaviour) The specific sub-rules are:
1. if a Step has a branching task, it can't have any other tasks.
_Screenshot: The "Add New Task to Page" button is disabled when (and only when) there's a branching ('Single'-type) Task._
2. if a Step already has at least one task, any added Question task must be a Multiple Answer Question Task.
_Screenshot: no visible changes, but clicking 'Question' will add a 'Multiple'-type Task, …
> Pages Editor: add rules to "Add Task to Page" functionality

- app/pages/lab-pages-editor/components/TasksPage/ExperimentalPanel.jsx
- app/pages/lab-pages-editor/components/TasksPage/TasksPage.jsx
- app/pages/lab-pages-editor/components/WorkflowHeader.jsx
- app/pages/lab-pages-editor/components/WorkflowSettingsPage/WorkflowSettingsPage.jsx
- css/lab-pages-editor.styl
Follows #7079
Staging branch URL: https://pr-7088.pfe-preview.zooniverse.org/lab/1982/workflows/editor/3711?env=staging
This PR adds the ability for project owners to set the _starting_ page/step of a workflow, by selecting the appropriate page/step in a dropdown.
NOTE: in this PR, the term **"first page/step"** means the "first item in the workflow.steps data array". The term **"starting page/step"** means the initial page/step a volunteer sees on the FEM Classifier for this workflow. _Functionally, these are the same._
New changes in this PR:
- ⭐ Added "choose starting page" dropdown
- Selecting a page/task in the "choose starting page" dropdown will now **rearrange** the target page/step so it's the _first step._ 
- …
> Pages Editor: add "Choose Starting Page" dropdown

- package-lock.json
- package.json
Staging branch URL: https://pr-7111.pfe-preview.zooniverse.org
Related: #7066 
This PR bumps PJC to [5.6.2,](https://github.com/zooniverse/panoptes-javascript-client/pull/241) which includes a [fix](https://github.com/zooniverse/panoptes-javascript-client/pull/240) to responses on Talk posts going nuts on occasion.
Turns out that, while PJC was correctly updated with the fix, PFE wasn't updated with the latest version of PJC.
Note: this is more targeted than #7109, and only intends to fix the Talk issue.
Compare: https://www.zooniverse.org/talk/search?page=3&query=depression
With: https://pr-7111.pfe-preview.zooniverse.org/talk/search?page=3&query=depression&env=production
The the second link should display all talk posts correctly.
Also, baseline tests: ensure you can login/logout, view …
> Update panoptes-client (PJC) to 5.6.2 / fix 

- app/locales/en.js
- app/pages/settings/email.jsx
- webpack.dev.js
Staging branch URL: https://pr-7083.pfe-preview.zooniverse.org
Towards #7032
This PR adds "🟢 valid / 🔴 invalid email" and "🟢 verified / 🔴 unverified email" indicators to the [Email Settings page](https://www.zooniverse.org/settings/email) (under User -> Settings -> Email)
- These indicators are based on the `user.valid_email` and `user.confirmed_at` values of the User resource.
Next steps: the "request confirmation email" functionality requires either
1. a fairly custom (and complex) fetch() function inside email.jsx to POST to panoptes.zooniverse.org/api/users/confirmation with the auth token inside the code, or
2. an update to PJC to do the same, or
3. _as a placeholder,_ a simple link to https://panoptes.zooniverse.org/users/confirmation/new
For this PR, the "request …
> Email Settings: add "valid email" and "verified email" status

- app/layout/site-footer.jsx
Preview: https://pr-7112.pfe-preview.zooniverse.org/
Closes #7110 
Adds an Instagram link to the Zooniverse footer.
Ready for review
> Add Instagram link to Zooniverse footer

- app/pages/lab-pages-editor/DataManager.jsx
- app/pages/lab-pages-editor/PagesEditor.jsx
- app/pages/lab-pages-editor/components/TasksPage/ExperimentalPanel.jsx
- app/pages/lab-pages-editor/components/TasksPage/TasksPage.jsx
- app/pages/lab-pages-editor/components/TasksPage/components/StepItem/SimpleNextControls.jsx
- app/pages/lab-pages-editor/components/TasksPage/components/StepItem/StepItem.jsx
- app/pages/lab-pages-editor/components/WorkflowSettingsPage/WorkflowSettingsPage.jsx
- app/pages/lab-pages-editor/components/WorkflowVersion.jsx
- app/pages/lab-pages-editor/icons/LoadingIcon.jsx
- app/pages/lab-pages-editor/icons/WrenchIcon.jsx
- css/lab-pages-editor.styl
Follows #7088
Staging branch URL: https://pr-7093.pfe-preview.zooniverse.org/lab/1982/workflows/editor/3711?env=staging
This PR combines a number of UI tweaks and updates to the Workflow Settings. The UI changes makes the visual presentation closer to [Sean's intended design](https://www.figma.com/file/gNOcFdlskfEXmVIFPvx7Yj/Pages-Editor?type=design&node-id=0-1&mode=design), while the Workflow Settings changes make that tab ⭐ _on par with the Project Builder FEM Lab's functionality._ [(comparative link)](https://master.pfe-preview.zooniverse.org/lab/1982/workflows/3711?femLab=true&env=staging)
**Part 1: UI changes**
- Workflow ID moved to Workflow Settings tab
- **Workflow Version** added, and also displays a spinner 🕐 to …
> Pages Editor: UI tweaks, improved Workflow Settings

- app/pages/lab-pages-editor/components/TasksPage/TasksPage.jsx
- app/pages/lab-pages-editor/components/TasksPage/components/StepItem/StepItem.jsx
Follows #7100
Staging branch URL: https://pr-7102.pfe-preview.zooniverse.org/lab/1982/workflows/editor/3711?env=staging
This PR adds the ability to copy Pages/Steps - and their related Tasks - via the "copy" button. This PR adds the ability to copy Pages/Steps - and their related Tasks - via the "copy" button.
_Screenshot: the "copy" button is the "two pieces of paper" button at the top right._
- New Feature: **Copy Page** (aka Copy Step)
- duplicating Page also duplicates its Tasks.
- each copied Page and copied Task is INDEPENDENT of the original Page/original Task. This means you can edit/delete a copied Step or Task without affecting the original.
- A copied Page is appended at the END of the sequence of Pages.
- Open …
> Pages Editor: add Copy Page feature

- app/pages/lab-pages-editor/DataManager.jsx
- app/pages/lab-pages-editor/components/TasksPage/TasksPage.jsx
- app/pages/lab-pages-editor/components/TasksPage/components/EditStepDialog/EditStepDialog.jsx
- app/pages/lab-pages-editor/components/TasksPage/components/EditStepDialog/EditTaskForm.jsx
- app/pages/lab-pages-editor/components/TasksPage/components/EditStepDialog/types/QuestionTask.jsx
- app/pages/lab-pages-editor/components/TasksPage/components/NewTaskDialog.jsx
- app/pages/lab-pages-editor/components/TasksPage/components/StepItem/BranchingNextControls.jsx
- app/pages/lab-pages-editor/components/TasksPage/components/StepItem/NextStepArrow.jsx
- app/pages/lab-pages-editor/components/TasksPage/components/StepItem/SimpleNextControls.jsx
- app/pages/lab-pages-editor/components/TasksPage/components/StepItem/StepItem.jsx
- app/pages/lab-pages-editor/components/TasksPage/components/StepItem/TaskItem.jsx
- app/pages/lab-pages-editor/components/WorkflowSettingsPage/WorkflowSettingsPage.jsx
- app/pages/lab-pages-editor/helpers/checkCanStepBranch.js
- app/pages/lab-pages-editor/helpers/checkIsPFEWorkflow.js
- app/pages/lab-pages-editor/helpers/linkStepsInWorkflow.js
- css/lab-pages-editor.styl
Follows #7102
Staging branch URL: https://pr-7105.pfe-preview.zooniverse.org/lab/1982/workflows/editor/3711?env=staging
This PR adds a number of misc updates in preparation for the internal team review, at the end of May. Here's the adapted ToDo List from [Slack, 13 May](https://zooniverse.slack.com/archives/C39AUB9UK/p1715631331033939):
Functional:
- Current implementation: a warning screen appears to block users from viewing/editing traditional PFE workflows.
- Future PR thoughts: the warning screen should have an option to perform a one-way conversion from classic PFE workflow to FEM workflow.
- Note: a "traditional PFE workflow" is a WF with tasks, but no steps.
- Fixed: due to a misunderstanding on my part, I …
> Pages Editor: misc updates for internal review

- app/monorepoUtils.js
Add FEM redirect for Newark Digital Archive (Project 23088)
Staging branch URL: https://pr-{NUMBER}.pfe-preview.zooniverse.org/
Staging URL for Project: https://pr-{NUMBER}.pfe-preview.zooniverse.org/projects/bethzc/newark-digital-archive
Target Link: https://www.zooniverse.org/projects/bethzc/newark-digital-archive
Project Lab Link: https://www.zooniverse.org/lab/23088
> Add redirect for Newark Digital Archive

- app/monorepoUtils.js
Add FEM redirect for SciScribbler Synapse Safari (Project 21429)
Staging branch URL: https://pr-7127.pfe-preview.zooniverse.org/
Staging URL for Project: https://pr-7127.pfe-preview.zooniverse.org/projects/chloezycheng/science-scribbler-synapse-safari
Target Link: https://www.zooniverse.org/projects/chloezycheng/science-scribbler-synapse-safari
Project Lab Link: https://www.zooniverse.org/lab/21429
> Add FEM redirect for SciScribbler Synapse Safari

- app/pages/settings/email.jsx
Fixes an empty description for the email address text input in the new verified email code.
- Fixes #7119.
> fix(accessibility): Fix user settings email description

- app/monorepoUtils.js
Staging branch URL: https://pr-7138.pfe-preview.zooniverse.org/
Add FEM redirect for Bradford's Industrial Heritage (Project 23454)
Staging branch URL: https://pr-7138.pfe-preview.zooniverse.org/
Staging URL for Project: https://pr-7138.pfe-preview.zooniverse.org/projects/alexfitzpatrick/bradfords-industrial-heritage-in-photographs
Target Link: https://www.zooniverse.org/projects/alexfitzpatrick/bradfords-industrial-heritage-in-photographs
Project Lab Link: https://www.zooniverse.org/lab/23454
> Add FEM redirect for Bradford Industrial Heritage

- app/collections/collection-search.cjsx
- app/collections/searchCollections.js
Panoptes full-text search requires at least 3 characters in order to return results. If your search string is longer than 3 characters, `collectionsSearch` passes it to the Panoptes full-text search API. Otherwise, it fetches as many collections as it can then filters for collections that include the search string in the collection name.
- Fixes #7121 for searches that contain 3 characters or less.
- see https://github.com/zooniverse/front-end-monorepo/pull/4867 for the collections search logic in the monorepo.
The Panoptes API returns odd results for search terms that are 4 or 5 characters (not whole words), but the API’s not something that can be fixed here.
https://github.com/zooniverse/Panoptes-Front-End/assets/59547/2307d4ff-00b3-4376-9fb5-0ecc6e60a002
> refactor(collections): refactor collection search to match monorepo

- app/pages/admin/project-status/experimental-features.jsx
- app/pages/lab-fem/workflow.jsx
Staging branch URL: https://pr-7148.pfe-preview.zooniverse.org
LInked Issue: https://github.com/zooniverse/front-end-monorepo/issues/6038
Linked FEM PR: https://github.com/zooniverse/front-end-monorepo/pull/6039
This PR does 2 things towards fetching Caesar reductions efficiently in FEM.
- First, it adds an Admin area toggle called "CaesarEnabled". This toggle, when enabled, shows part two.
- Second, it adds a small config section to the FEMLab workflow editing page - which is currently limited to a toggle - that enables this specific workflow to make requests from Caesar to fetch Reductions on Subject load in the Classifier
- The logic for using this workflow configuration in FEM is in a separate PR
The full end-to-end connection between FEM & PFE for this PR can be reviewed as follows: …
> Enable Caesar fetching through a Workflow configuration key.

- app/pages/home-not-logged-in/research.jsx
Freeze the Zoo-wide total classification count on the PFE not-logged-in homepage during ERAS backfill of Ouroboros classifications.  This change freezes the Panoptes classification count at a fixed value (as of 27 Aug 2024) and ignores the value returned by ERAS so that backfilled Ouroboros entries are not double counted (by ERAS and via pre-Panoptes fixed count totals). Keep this in place until the Ouroboros classifications are backfilled in ERAS and new offsets can be calculated and implemented here (as corrections to the ERAS total).
cc: @yuenmichelle1 
Staging branch URL: https://pr-7160.pfe-preview.zooniverse.org
> Freeze ERAS classification count

- app/pages/home-not-logged-in/research.jsx
Staging branch URL: https://pr-7167.pfe-preview.zooniverse.org
Actions Taken:
- Reverts freeze placed by #7160 so classification count is based on live total from ERAS.
- Revises classification count offset to account for ouroboros classifications that were successfully backfilled to ERAS. Details: Take the previous offsets (`GZ123_COUNT + OUROBOROS_COUNT + OTHERS_COUNT` = 250,469,827) and subtract the `NOW_IN_ERAS_COUNT` = 225,185,041 resulting in new offset -- `PREPANOPTES_COUNT` = 25,284,786
- Revises user count offset to up-to-date values. Details: Panoptes API returns a user count (via `/users` endpoint) that is less than the `users` table total. This is due to omissions of 1) deleted users (currently 2220); 2) `ouroboros_created` users (currently 114576).  In #5518 we added an …
> Unfreeze ERAS class count, update ouroboros count offsets

- app/constants/languageMenu.js
- app/locales/hu.js
- app/locales/index.js
Staging branch URL: https://pr-7169.pfe-preview.zooniverse.org
Example project url: https://pr-7169.pfe-preview.zooniverse.org/projects/benjamin-dot-richards/oceaneyes?language=hu
Follows https://github.com/zooniverse/Panoptes-Front-End/pull/7140
Add hungarian language option and dictionary
> Add hungarian language option and dictionary

- app/layout/site-nav.jsx
Staging branch URL: https://pr-7172.pfe-preview.zooniverse.org
Removes react-router Link from /about and /get-involved in router.jsx.
> Remove react-router Link from /about and /get-involved

- app/layout/site-footer.jsx
Staging branch URL: https://pr-7173.pfe-preview.zooniverse.org
Remove sreact-router Link from footer routes to FEM pages such as /about and /get-involved.
> Remove react-router Link from footer routes to FEM pages

- app/router.jsx
Per subsequent conditional I think this should use `let`.
Staging branch URL: https://pr-7174.pfe-preview.zooniverse.org
I was getting a related console warning, but I'm not getting it anymore 🤔 , so I don't think anything related is broken at the moment, but nonetheless opening this.
> Update newUrl in router.jsx

- app/pages/dev-classifier/mock-data.coffee
- app/pages/home-for-user/circle-ribbon.jsx
- app/pages/home-for-user/recent-messages.jsx
- app/pages/home-not-logged-in.jsx
- app/pages/lab/mobile/mobile-section.jsx
- app/pages/notifications/notification-section.jsx
- app/pages/organization/organization-page.jsx
- app/pages/project/components/ProjectNavbar/components/Background/Background.spec.js
- app/pages/project/home/project-home.jsx
- app/pages/project/home/project-home.spec.js
- app/partials/avatar.cjsx
- app/partials/project-card.cjsx
- app/talk/comment.cjsx
- css/collection-card.styl
- css/landing-page.styl
Staging branch URL: https://pr-7175.pfe-preview.zooniverse.org
Fixes a bug where recent changes to the `static` repo to launch new pages caused some image assets in the PFE codebase to have faulty urls.
I tested this by running locally and visiting common urls where static image assets should load such as `/talk` and `/lab` while not signed-in.
> Update image assets with absolute urls

- README.md
- app/layout/account-bar.jsx
- app/layout/site-nav.jsx
- app/pages/notifications/notification-section.jsx
- app/pages/notifications/notification-section.spec.js
- app/pages/profile/stats.cjsx
- app/pages/profile/user.jsx
- app/router.jsx
❌ Do not deploy until Sept 17
- Removed react-router Link components from links we want to hit the static proxy (and passed on to FEM)
- Added a redirect to the router for `/`.
- Noted in PFE's readme this app is no longer used for the homepage so you must have a /subpath when run locally.
Visit https://pr-7176.pfe-preview.zooniverse.org and you'll be redirected to "www".
❓ The consequence of adding a redirect like this to the router is you can't use the browser back button 🤔 The only scenario where someone might hit this redirect though is if `'/'` is used in markdown beyond our control. All other links to the homepage are hardcoded to www.
Visit subpaths that are intended to still use PFE such as [/lab](https://pr-7176.pfe-preview.zooniverse.org/lab) and[ …
> Redirect the homepage to static proxy

- app/pages/admin/project-status/experimental-features.jsx
Staging branch URL: https://pr-7171.pfe-preview.zooniverse.org
Adds a toggle in the Admin section called "VolumetricViewer". This is to be used in FEM for displaying the new VolumetricViewer subject viewer. A separate ADR is not part of this PR because it will be added to the VolumetricViewer ADR when the VolumetricViewer is added to FEM.
Go to the staging branch and see that 1) the toggle is in the admin area and 2) see that it is enabled for the project "[VV Production](https://pr-7171.pfe-preview.zooniverse.org/admin/project_status/kieftrav/vv-production)".
> Add VolumetricViewer to Admin Experimental Features flags

- package-lock.json
- package.json
- Version bump so that PFE and FEM are using the same client
> Bump engine.io-client to 6.6.0 to the same as FEM

- package-lock.json
- package.json
Reverts zooniverse/Panoptes-Front-End#7206
This bump actually breaks PFE. The website renders a blank page, with the console error message:
```
Uncaught TypeError: _browser.BrowserTracing is not a constructor
at initSentry (init-sentry.js:11:1)
at ./app/main.cjsx (main.cjsx:48:1)
at __webpack_require__ (bootstrap:22:1)
at startup:6:1
at startup:6:1
```
Follow up required:
- observe how FEM updated sentry: https://github.com/zooniverse/front-end-monorepo/pull/6387
- observe sentry 7->8 migration guide: https://docs.sentry.io/platforms/javascript/migration/v7-to-v8/
- approach all future sentry (major) bumps with a very wary eye.
(Thanks Delilah!)
> Revert "Bump @sentry/browser from 7.100.1 to 8.36.0"

- app/pages/lab-pages-editor/DataManager.jsx
- app/pages/lab-pages-editor/helpers/checkIsWorkflowPartOfProject.js
Staging branch URL: https://pr-7156.pfe-preview.zooniverse.org/lab/1982/workflows/editor/3711?env=staging
This PR fixes an issue where it's possible to view/edit a Workflow in the incorrect Project.
The Issue:
- e.g. if you have a WF 1111 that's part of project 22, you can still access that WF at the URL for project 44: `/lab/44/workflows/editor/1111` This is clearly incorrect.
- Note that this issue exists even with the PFE workflow editor, i.e. `/lab/44/workflows/1111` still allows you to edit the WF on an incorrect project. This is a separate issue to be fixed.
The Fix:
- Add `checkIsWorkflowPartOfProject()` helper that returns true if, and only if, the Workflow is linked to the Project.
- Add error message if the Workflow isn't part of the higher-level Project.
For the following …
> Pages Editor: check if workflow is part of project

- package.json
This PR modifies our package.json to specify that PFE's supposed to run with node 20+, and npm 10+.
- This brings our package.json to match our Dockerfile (node 20 alpine) and deploy files (lts/iron, aka Node.js 20)
- This is more of a preventative change for dev hygiene, instead of a fix for something that's actually broken.
This update was spurred by the [stylus dependabot bump](https://github.com/zooniverse/Panoptes-Front-End/pull/7183), as stylus 8.0.0 has a breaking change that requires node 18.12.0. In practice this isn't a problem as all our deploy & Docker files use Node.js 20, but in theory it could be a problem for local devs who think that PFE _should_ work with, say, Node 18.0.0.
Looking for comment, ready for review, but low priority, to be honest.
> Update package.json to use node 20+

- app/layout/index.jsx
Staging branch URL: https://pr-7217.pfe-preview.zooniverse.org/projects
Corresponds to: https://github.com/zooniverse/front-end-monorepo/pull/6456
Slack: https://zooniverse.slack.com/archives/C4RJRAGKA/p1731079514305719
- Add html and css for a simple `<details>` and `<summary>` at the top of each layout.
- 🗒️ Noting that I am not using the existing AppStatus component in this repo because that banner is sticky and disruptive to users who have to close it each time they visit the site.
I will likely end up just self-reviewing and merging this due to its simplicity and non-permanence.
> Add a temporary notice banner to the layout

- package-lock.json
- package.json
Staging branch URL: https://pr-7220.pfe-preview.zooniverse.org/projects
See [Dependabot notice](https://github.com/zooniverse/Panoptes-Front-End/security/dependabot/92)
This PR updates `@sentry/browser` to address some security advice provided by Dependabot.
- Dependabot previously tried to update sentry-browser to v8, but that broke PFE. #7206 
- We reverted that change. #7209 
- This PR updates `@sentry/browser` to the latest v7 iteration instead, which seems to work on local and I _think_ will address Dependabot's concerns.
- There's a longer [v7 to v8 migration guide,](https://docs.sentry.io/platforms/javascript/migration/v7-to-v8/) but we won't invest dev time into that until it's necessary.
Open the Projects Page in the staging branch. If the page loads & renders properly, this …
> [Security] Update @sentry/browser to 7.120.0

- app/lib/session.coffee
Staging branch URL: https://pr-7233.pfe-preview.zooniverse.org
Paired with https://github.com/zooniverse/front-end-monorepo/pull/6499
- While investigating https://github.com/zooniverse/front-end-monorepo/issues/6493, I found that the "generate a new session id after 5 minutes of inactivity" logic does not work in the classifier. As mentioned in that Issue, session id is attached to classification metadata and can be used for analysis of anonymous users contributing classifications.
- In this PR I removed the "5 minutes" logic because its original condition of comparing a Date() string to a Date.now() number was never met, and therefore the code never worked as intended.
> Classifier: Remove the faulty session id code

- app/classifier/tasks/generic-editor.cjsx
- app/classifier/tasks/index.js
- app/classifier/tasks/volumetric/index.jsx
- app/pages/admin/project-status/experimental-features.jsx
- app/pages/lab-fem/workflow.jsx
Staging branch URL: https://pr-7227.pfe-preview.zooniverse.org
- Rename experimental flag for the Volumetric Viewer to "volumetricProject" from "volumetricViewer"
- Create Volumetric task that it can be added to any project with the "volumetricProject" and "FemLab" flags enabled
- Open the [Admin Page](https://local.zooniverse.org:3735/admin/project_status/kieftrav/volumetric-viewer) and the [Workflow Editor](https://local.zooniverse.org:3735/lab/2015/workflows/3831) in separate tabs for my test/staging Volumetric Viewer project [Volumetric Viewer]() project for testing
- As of this writing, "FemLab" and "volumetricViewer" are enabled and you should see a Volumetric task existing on workflow 3831
- The Volumetric task was _heavily_ inspired by the Highlighter task. …
> Create Volumetric Task

- app/monorepoUtils.js
FEM redirect for cmcbrain/axonal-pathfinders (Project 25108)
Staging branch URL: https://pr-7260.pfe-preview.zooniverse.org/
Staging URL for Project: https://pr-7260.pfe-preview.zooniverse.org/projects/cmcbrain/axonal-pathfinders
Target Link: https://www.zooniverse.org/projects/cmcbrain/axonal-pathfinders
Project Lab Link: https://www.zooniverse.org/lab/25108
Static PR: https://github.com/zooniverse/static/pull/387
> Add FEM redirect for Axonal Pathfinders

- app/classifier/tasks/survey/editor.cjsx
Staging branch URL: https://pr-7267.pfe-preview.zooniverse.org
Closes #7168 .
Supersedes #7184 . 
- for FEM project, edit survey task thumbnail setting descriptions
FEM project workflow with survey task:
- https://local.zooniverse.org:3735/lab/1634/workflows/2434
- https://pr-7267.pfe-preview.zooniverse.org/lab/1634/workflows/2434?env=staging
PFE project workflow with survey task: 
- https://local.zooniverse.org:3735/lab/1608/workflows/3319
- https://pr-7267.pfe-preview.zooniverse.org/lab/1608/workflows/3319?env=staging
> Edit survey task thumbnail setting descriptions for FEM lab

- .github/dependabot.yml
Editing the dependabot config to disable opening of PRs. The config [docs](https://docs.github.com/en/code-security/dependabot/dependabot-security-updates/customizing-dependabot-security-prs) say it’s possible to set open-pull-requests-limit to 0 in dependabot.yml
Security alerts are still available in the Security tab of this repo. Handling auto-generated dependabot PRs is not part of our frontend team maintenance.
> Turn off dependabot PRs

- .github/workflows/deploy_staging.yml
Without an argument,`gh pr view` displays infor about the PR associated with the current branch. Since this is a master branch push event, this lets this action grab the PR number from outside any `github.event` actually associated with the PR.
This rearranged action allows the local runner to pull the PR number from a new job local to this event and pass it to the reusable workflow in a separate job.
> Rearrange staging deploy action to fix branch deploy removal

- .github/workflows/deploy_staging.yml
The branch deploy removal shared workflow requires credentials to be passed to it to ensure that the calling action has access to them.
> Include creds in branch deploy remove shared workflow

- .github/workflows/deploy_staging.yml
When a PR is merged, the branch is immediately deleted. This means that the previous way I was pulling the associated PR number wasn't working. Instead, just parse the git log: grab the most recent commit on the trunk and pluck the PR ID from the body.
> Parse git log for PR number

- webpack.build.js
- webpack.dev.js
Closes #7295
Staging branch URL: https://pr-7298.pfe-preview.zooniverse.org/lab/1982/workflows/editor/3711?env=staging
This PR updates the build process so that bundled image files are served from the `/lab` subpath, instead of the more sensible `/` root. Why change the path? Because we've configured the `www.zooniverse.org` domain to serve PFE code and FEM code on different paths, and the `/` root path is now the domain of FEM. Why the 'lab' subpath? Because in practice the only part of PFE that still uses bundled image files is the new Pages Editor.
- Changes are made to webpack.build.js (used for `www.zooniverse.org`) and webpack.dev.js (used on our local dev servers, i.e. on npm start)
- The changed subpath works properly on local, will work properly on the PFE staging link, but we …
> Webpack: serve bundled image files from /lab subpath

- app/pages/project/index.jsx
Staging branch URL: https://pr-7309.pfe-preview.zooniverse.org
Fixes:
- https://github.com/zooniverse/panoptes/security/advisories/GHSA-73mp-cxwx-hrgm
- https://zooniverse.freshdesk.com/a/tickets/19069
- remove slug from project error messages
- [opinion] preventing issue noted in links above outweighs any benefit to including slug in error messages
> Refactor project error state messages

- app/components/ExternalLinksBlock/components/ExternalLink/ExternalLink.jsx
- app/lib/nav-helpers/socialIcons.json
- app/pages/lab/social-links-editor.jsx
Fixes: #7312
Related: zooniverse/front-end-monorepo#6908
Staging branch URL: https://pr-7313.pfe-preview.zooniverse.org
This PR fixes an issue where Bluesky links were going to the wrong URLs, i.e. the Bluesky links should go to `bsky.app/PROFILE/accountname`, not `bsky.app/accountname`
Changes made:
- socialIcons.json: the idea of "siteSubpath" has been introduced to the our array of social media links.
- siteSubpath is optional, and currently only used by bsky.app
- ExternalLink.jsx (seen on Projects home page): modified to apply siteSubpath, if any.
- SocialLinksEditor.jsx (see in Edit Project Details page):
- modified to display siteSubpath, if any.
- 🆕 siteSubpath is now saved to the `projectResource.urls[x]` object
- Edit a test project, e.g. …
> Fix Bluesky External Links

- app/locales/en.js
- app/rubin-2025/register-form.jsx
- app/rubin-2025/rubin-page.jsx
- app/rubin-2025/rubin-page.spec.js
- app/rubin-2025/sign-in-form.jsx
- css/new-accounts-page.styl
Part of: Rubin 2025 Landing Page (#7310)
Follows: #7314
This PR is part of a project that adds a special landing page for the Rubin 2025 project. The scope of Part 3 is to add proper content to the Rubin page (i.e. telling visitors about Rubin & the Zooniverse), and update the styles, and improve the accessibility.
...and apply a bunch of "minor" fixes to the Registration form, even though that was supposed to be mostly done in part 2, because I keep finding new things to improve. I'm sorry.
Styling:
- In general: Rubin Landing Page will be updated to have a hybrid FEM-PFE visual design (colours, etc).
- Layout: content has a max width of 720px, container has a max width of 1440px.
- (Sean will be checking if this is up to par.)
Localisation:
- Most localised strings/translations (mostly …
> Rubin 2025 Landing Page pt3: style UI, add content, improve accessibility

- app/pages/project/index.jsx
Staging branch URL: https://pr-7316.pfe-preview.zooniverse.org/projects
Iteration on #7309, see https://github.com/zooniverse/Panoptes-Front-End/pull/7309#issuecomment-2932544667
Describe your changes:
- removes slug from loading message when project is loading
> Remove project slug from project loading message

- app/rubin-2025/register-form.jsx
- app/rubin-2025/rubin-page.jsx
- app/rubin-2025/rubin-page.spec.js
- app/rubin-2025/sign-in-form.jsx
- css/new-accounts-page.styl
Part of: Rubin 2025 Landing Page (#7310)
Follows: #7318
Also: fixes #7319 
This PR is part of a project that adds a special landing page for the Rubin 2025 project. The scope of Part 4 is to improve accessibility even further (notably for the RegisterForm, taking notes from feedback in 7318), clean up the HTML of the register forms, (and probably clean up the CSS too,) and apply various fixes.
Now that the [Rubin page is live](https://www.zooniverse.org/rubin), a _meta-goal_ for Part 4 is the **prepare the code for back-porting the Sign In and Register functionality to the /accounts page**.
RegisterForm:
- Improve accessibility:
SignInForm:
- Improve accessibility:
Rubin Page:
- Improve accessibility:
Optional for this PR (can postpone for later part):
- ❌ ~~fix tests~~
Other changes: …
> Rubin 2025 Landing Page pt4: improve html+accessibility, various fixes 

- app/pages/accounts/README.md
- app/pages/accounts/accounts-page.jsx
- app/pages/accounts/index.jsx
- app/pages/accounts/register-form.jsx
- app/pages/accounts/rubin-page.spec.js
- app/pages/accounts/sign-in-form.jsx
- app/router.jsx
This PR updates & fixes the rather borked Sign In & Register page (i.e. https://www.zooniverse.org/accounts), using fixes & improvements from the recent Rubin Landing Page project. 
- We're backporting the fixes and improvements from the new `/rubin` page into the old `/accounts` page.
- Notes on code changes:
- since the code in `/app/rubin-2025` is mostly self-contained, the code we see in `/app/pages/accounts` is mostly a copy-paste of that folder, with non-Rubin-specific content replaced.
- The only other code change would be in the `router.jsx`, as the `/accounts` path now routes to the new AccountsPage.
- `/app/pages/sign-in.jsx`, `/app/partials/sign-in-form.cjsx`, and `/app/partials/register-form.cjsx` are now obsolete... _but I'm going to run a bunch of double checks to ensure …
> (New) Accounts Page

- app/pages/lab/data-exports-batch-aggregations/batch-aggregations-dialog.jsx
- app/pages/lab/data-exports-batch-aggregations/batch-aggregations-results.jsx
- app/pages/lab/data-exports-batch-aggregations/batch-aggregations.jsx
- app/pages/lab/data-exports-batch-aggregations/components/accordion.jsx
- app/pages/lab/data-exports-batch-aggregations/components/aggregation-item.jsx
- app/pages/lab/data-exports-batch-aggregations/components/aggregation-summary.jsx
- app/pages/lab/data-exports-batch-aggregations/components/aggregations-list.jsx
- app/pages/lab/data-exports-batch-aggregations/components/expandable-container.jsx
- app/pages/lab/data-exports-batch-aggregations/components/workflow-item.jsx
- app/pages/lab/data-exports-batch-aggregations/components/workflows-export-checker.jsx
- app/pages/lab/data-exports-batch-aggregations/components/workflows-list.jsx
- app/pages/lab/data-exports-batch-aggregations/helpers/checkIsWorkflowValid.js
- css/data-export-batch-aggregations.styl
Part of: Batch Aggregation UI for Project Builder (#7326)
Follows: #7331
This PR is part of a project that adds "Batch Aggregations" to the Project Builder -> Data Exports page.
In part 3, we're finally getting rid of the basic grey boxes and putting in proper UI/visual design, based on the [Figma design](https://www.figma.com/design/NNCUlpRxNoOXjI86DVQ7QH/Data-Exports?node-id=0-1&p=f&t=KB0NRg7yaHZhMTIU-0).
Features & Scope:
- Expect a lot of content and design updates.
- Notably, this PR is much more thorough with visually displaying components in their various states. e.g. AggregationsSummary shows when it's "checking..." if the workflow has an existing aggregation, and when it's "generating..." a new one. 
- **No** new features or functionality are intended in this PR.
Notes:
- for …
> Batch Aggregations pt3: improved UI (prettier visuals)

- app/fem-shared/components/caesar-status.jsx
Affects: Caesar Status Indicator (see #7346)
This PR changes the behaviour of the "Caesar badge". Clicking on the Caesar badge (link) will now open the corresponding Caesar workflow page ([example](https://caesar-staging.zooniverse.org/workflows/3711)) in a **new browser window/tab,** instead of the _current_ browser window/tab.
Staging branch URL: https://pr-7356.pfe-preview.zooniverse.org/lab/1982/workflows/3711?env=staging
Ready for review 👌
> Caesar Status Indicator: Caesar badge now opens in new window/tab

- app/monorepoUtils.js
FEM Project Redirects Batch 5
https://pr-7361.pfe-preview.zooniverse.org/projects
[Google Doc](https://docs.google.com/spreadsheets/d/1wmWFa51FDu-kS0OtSN1IcPdCR8iJXvPcI0oSu8-IshE/edit?gid=1028467830#gid=1028467830)
Static PR: https://github.com/zooniverse/static/pull/408
> FEM Project Redirects Batch 5
