app/components/loading-indicator.cjsx, app/lib/promise-to-set-state.coffee, app/pages/sign-in.cjsx, app/partials/register-form.cjsx
This generally cleans up the registration form and fixes the bug where entering a previously used email address would appear to sign in, but actually fail.
Closes #48.
=> Fix registration form

app/lib/title-mixin.coffee, app/pages/project/classify.cjsx, app/pages/project/index.cjsx, app/pages/project/science-case.cjsx, app/pages/projects.cjsx, app/pages/sign-in.cjsx, public/index.html
Let's try this. It assumes `componentDidMount`s fire in order, but I think that's pretty safe to assume.
Closes #65.
=> Start on a way to handle page titles for #65

app/api/client.coffee, app/main.cjsx, app/pages/build.cjsx, app/pages/project/home.cjsx, app/pages/project/index.cjsx, app/partials/project-card.cjsx
Changes project URLs to `/projects/:owner_login/:project_display_name`.
=> Project paths are now by owner and name, not ID

app/api/classification.coffee, app/api/mock-data/aggregate.coffee, app/classifier/classification-summary.cjsx, app/classifier/drawing-tools/aggregate-mark.cjsx, app/classifier/drawing-tools/circle.cjsx, app/classifier/drawing-tools/delete-button.cjsx, app/classifier/drawing-tools/ellipse.cjsx, app/classifier/drawing-tools/line.cjsx, app/classifier/drawing-tools/point.cjsx, app/classifier/drawing-tools/polygon.cjsx, app/classifier/drawing-tools/rectangle.cjsx, app/classifier/drawing-tools/root.cjsx, app/classifier/index.cjsx, app/classifier/mock-data.coffee, app/classifier/subject-viewer.cjsx, app/classifier/tasks/drawing.cjsx, app/classifier/tasks/generic.cjsx, app/classifier/tasks/multiple.cjsx, app/classifier/tasks/single.cjsx, app/components/aggregate-view.cjsx, app/components/subject-viewer.cjsx, app/lib/draggable.cjsx, app/main.cjsx, app/pages/project/classify.cjsx, css/classification-summary.styl, css/drawing-tool.styl, package.json, public/index.html
Introduces the aggregate view (not complete or used yet).
Standardizes annotations in {task, value} format.
=> Aggregate view

app/api/auth.coffee, app/api/classification.coffee, app/api/client.coffee, app/classifier/index.cjsx, app/components/aggregate-view.cjsx, app/lib/handle-prop-changes.coffee, app/lib/model.coffee, app/lib/promise-to-set-state.coffee, app/pages/build.cjsx, app/pages/edit-project.cjsx, app/pages/new-project/data.coffee, app/pages/project/classify.cjsx, app/pages/project/home.cjsx, app/pages/project/index.cjsx, app/pages/projects.cjsx, app/partials/project-card.cjsx, package.json
This allows the user to choose their workflow from the project home page and in general better defines the classify page/classifier responsibilities.
Mentioned in #70.
Also closes #94.
=> Choose workflow

app/classifier/subject-viewer.cjsx, app/components/tooltip.cjsx, app/partials/register-form.cjsx, app/partials/sign-in-form.cjsx, css/buttons.styl, css/common.styl, css/dialog.styl, css/forms.styl, css/layout.styl, css/main.styl, css/markdown-editor.styl, css/tooltip.styl, css/typography.styl
This makes forms look good.
Closes zooniverse/Panoptes-Design#4
=> Form style

app/classifier/drawing-tools/circle.cjsx, app/classifier/drawing-tools/ellipse.cjsx, app/classifier/drawing-tools/line.cjsx, app/classifier/drawing-tools/rectangle.cjsx, app/classifier/drawing-tools/root.cjsx, app/classifier/subject-viewer.cjsx, app/classifier/tasks/drawing.cjsx, css/classify.styl
* Displays the current count of each tool
* On initRelease, checks to see if a tool is valid
=> Drawing task improvements

app/pages/project/classify.cjsx
Was broken when classifying a specific workflow
=> Fix classify page

Dockerfile
Note that this increases the Docker build time to an hour (or more), so we'll want to change this once binaries are available.
=> Phantomjs update

app/components/subject-viewer.cjsx, app/lib/get-subject-location.coffee
Just exposing the function that finds the locations we know how to display from a subject.
=> Expose function to get subject image location

app/pages/project/classify.cjsx
Make this thing more readable, since it's not entirely obvious where it gets all its data.
=> Clean up classify page

app/api/talk.coffee, app/main.cjsx, app/pages/user-profile.cjsx, app/partials/account-bar.cjsx, app/talk/inbox-conversation.cjsx, app/talk/inbox.cjsx, app/talk/init.cjsx, app/talk/private-message-form.cjsx, css/dashboard.styl, css/dialog.styl, css/inbox.styl, css/layout.styl, css/main.styl, css/talk.styl
**Working**
- You should be able to navigate to another users profile, send over a message, and then they'll get a filled-in envelope in their navigation until they've read the message.
- Adding messages to the conversation once started.
**Todo**
- Still needs validations and more email-style interaction niceties , but I think this is just enough for a basic inbox to start tinkering with
- Improve empty states
=> Add initial inbox functionality

app/main.cjsx, app/pages/not-found.cjsx
Kinda gross, but good enough for now.
=> Not-found page removes trailing slashes, close #33

app/lib/draggable.cjsx, package.json
Dependency upgrade to react 0.13.2
=> Update react to 0.13

css/project-page.styl
Just a dumb CSS thing I messed up at some point. Closes #186.
=> Add active state for buttons on a project page

app/pages/lab/index.cjsx
For when you've got lots and lots of projects.
Also ensures new project names are unique.
=> Paginate lab view, close #167

app/components/retirement-rules-editor.cjsx, app/pages/lab/subject-set.cjsx, app/pages/lab/workflow.cjsx, css/project-page.styl
The automatic split-into-columns trick I was using doesn't work very well for most lengths of text. Too bad.
**Weird thing**: This is branched off the branch in #249, so those commits show up here. I wonder if when you merge that, this one'll work itself out. Let's see.
Closes #225.
=> Single column intro

app/pages/lab/subject-set.cjsx
Looks like I forgot to set the subject upload input as multiple. Way to go Brian!
Closes #280.
=> Upload multiple, duh

app/pages/lab/project.cjsx
Project lab pages weren't checking to make sure that a user is signed in and they have permission to edit the project. Now it does.
Closes #270.
=> Project lab page checks to make sure the user has permission to edit the project

app/api/client.coffee, app/pages/lab/subject-set.cjsx, app/partials/subject-uploader.cjsx, css/dialog.styl
Adds a super basic list of subjects to the subject set lab page. Allows previewing and removing individual subjects. Improves feedback during subject upload process.
Closes #200, closes #211.
=> Improve subject uploading

app/classifier/mock-data.coffee, app/classifier/subject-viewer.cjsx, app/components/subject-viewer.cjsx
Adds a play button and preloads subject images so it works, closes #284.
The subject viewer now handles its own frame state, passing it up on change via a callback.
=> Play button

app/classifier/tasks/generic.cjsx
Here's all I meant by wrapping up the help dialog content. Sorry for being so picky @chrissnyder and @rogerhutchings, just trying to keep things as consistent when it's easy.
Closes #234, closes #238, closes #256.
=> Wrap up tasks' help dialog content

app/classifier/subject-viewer.cjsx, app/classifier/tasks/generic-editor.cjsx, app/pages/lab/workflow.cjsx
Allows choosing a first task (close #308)
Hides drawing task details popup unless details exist
Makes the help input bigger (close #304)
=> Improve workflows

app/pages/project/classify.cjsx, app/partials/sign-in-prompt.cjsx
Prompt to sign in after however-many classifications.
Closes #173.
=> Prompt to sign in

app/pages/lab/project-details.cjsx, app/pages/project/index.cjsx, app/pages/settings.cjsx
Allows setting project avatars and background images
=> Enable image selection for project avatar and background image

css/buttons.styl, css/typography.styl
Scopes button and color styles that I added with the home page updates to home page only. Fixed #334 and #335
=> Scope button and color styles to home page

app/collections/favorites-button.cjsx, app/partials/sign-in-prompt.cjsx
=> Add sign-in prompt to favorite button

app/pages/settings.cjsx
Adds per-project email subscription checkboxes to the settings page.
Closes #262.
=> Email settings

app/pages/lab/project-details.cjsx
To remove previously entered static links for a project.
=> Add remove link button to project links editor

app/pages/lab/project-details.cjsx
Add a button so project owners can request a project's data.
Closes #203.
=> Export classifications

app/partials/main-footer.cjsx, app/partials/main-header.cjsx, css/layout.styl, css/main-footer.styl, css/main-header.styl
- Updated styles for header and footer for consistency on other pages besides home. 
- Renamed Discuss in header and footer to Talk to fix #360
=> Header footer v2

app/classifier/subject-viewer.cjsx, app/components/subject-viewer.cjsx, app/lib/session-subjects.coffee, app/pages/project/classify.cjsx, css/classify.styl
This'll show a little flag on
- retired subjects
- subjects the user has already seen
- subject seen in the current session (for non-logged-in users)
Closes #312, closes #368.
=> Show subject status

bin/config.sh, package.json
Adds a script to deploy to http://preview.zooniverse.org/panoptes (as production).
Also allows running the dev server on a custom `PORT`.
=> New deploy script

app/pages/lab/index.cjsx, app/pages/project/home.cjsx, app/pages/project/index.cjsx, app/partials/project-card.cjsx
`<Link to="project-*">` are now by owner and project slug.
Closes #197.
=> Update project-* links to use slugs, fix lab links

app/api/auth.coffee, app/main.cjsx, app/pages/reset-password.cjsx, app/partials/register-form.cjsx, app/partials/sign-in-form.cjsx
@edpaget this should be okay to merge once the URLs are fixed in the email.
=> Reset password page

app/pages/projects.cjsx, css/all-projects-page.styl, css/main-header.styl
- Refactoring to make project page's header and hero styles reusable for all secondary pages.
=> Secondary page header

app/pages/lab/subject-set.cjsx
Ensures things appear as they were entered.
Closes #421.
=> All metadata values are strings

app/components/image-selector.cjsx, app/main.cjsx, app/pages/lab/media.cjsx, app/pages/lab/project-details.cjsx, app/pages/lab/project.cjsx, css/edit-media-page.styl, css/main.styl
Implement a basic project media library. Closes #306.
Also caches that `classifications_exports` request on the details page.
=> Add project media library

app/classifier/index.cjsx, app/pages/project/index.cjsx, app/partials/main-footer.cjsx, app/partials/main-header.cjsx
For beta.
Did I get all the outward-facing Talk links, @aweiksnar?
=> Remove talk links on production

app/pages/project/classify.cjsx
Should take care of #441. @edpaget might have a better idea down the line.
=> Throw out newly fetched subject when it's the one that's just been loaded

app/partials/project-card.cjsx, css/project-card.styl
- Refactored project card component to get project avatars
- Fixed #439
=> Get project avatars.

app/pages/home.cjsx, app/pages/projects.cjsx
Updates featured projects on production.
Shows appropriate (for now) projects on the projects listing page.
=> Update project lists

app/partials/main-header.cjsx
Removes the lab link from the main navigation as requested by @mrniaboc.
=> Lose the lab link

app/api/auth.coffee, app/partials/register-form.cjsx
Credited name wasn't saved with registration.
Closes #444.
=> Include credited name in registration

app/pages/lab/project-details.cjsx
Switch `classifications_exports` to `classifications_export`.
Provide a link to the most recent data.
=> Singular classifications export

app/partials/subject-uploader.cjsx
Display errors that come up during subject creation.
Once we learn what errors people are having, maybe we can give them something more human-readable.
Close #438.
=> Make sure errors are reported when creating subjects

app/collections/favorites-button.cjsx, app/collections/manager-icon.cjsx, app/collections/manager.cjsx, app/collections/show.cjsx, app/components/subject-viewer.cjsx, app/subjects/index.cjsx, css/collections.styl, css/subject.styl
- Adds an interface to manage which collections a subject is a member of
- Adds an icon to manage presenting that interface to the user
- Adds the icon to the subject-viewer
=> Collections manager icon

app/pages/project/science-case.cjsx
=> Translate expert role

app/classifier/index.cjsx, app/main.cjsx, app/subjects/index.cjsx
- Moves the route for the subjects discussion page under the project
- The CSS to fix the button spacing in the subject-viewer is in #466
=> Move url for subject discussions under project

app/pages/lab/subject-set.cjsx
Works around zooniverse/Panoptes#932.
Closes #463.
=> Don't use `include` with set_member_subject request

app/pages/project/classify.cjsx
The classify page now waits for two seconds after receiving the "No queue defined for user. Building one now, please try again." error, then requests subjects again.
Closes #310.
=> Try to fetch subjects again when the server says to

app/talk/init.cjsx, app/talk/lib/project-linker.cjsx
- Adds a component for people to jump between project talks
- I'm not sure what the ideal params for the request will be, just a get to the projects resource for now
- A small piece for #380
=> Add project talk linker

app/components/subject-viewer.cjsx
=> Fix subject-viewer icon spacing

app/talk/comment.cjsx, css/talk.styl
- Trying to use components/subject-viewer whenever possible
- Bumped the display to full width, I'll chat with @DarrenMcRoy when he's back next week and see if he has any input from users on preferred comment image rendering size
=> Use subject-viewer in comments

app/partials/main-header.cjsx
Reenabled and relabelled the Lab button as requested by @mrniaboc.
=> Relabel and reactivate the lab button

app/components/user-search.cjsx, app/pages/lab/collaborators.cjsx, bin/build.sh, bin/serve.sh, css/main.styl, css/user-search.styl, package.json
=> Talk roles

app/pages/lab/workflow.cjsx
Link the demo subject set to the workflow, not the project.
Closes #387.
=> Link demo subject set to workflow

app/pages/project/classify.cjsx
When querying for subjects to classify:
- Stop sending `project_id`.
- Send a `subject_set_id` when querying with grouped workflows. Random for now, since `grouped` isn't yet exposed as an option for workflows.
- Send `sort=queued` instead of `sort=cellect`.
I believe this is just waiting on back-end deploy (cc @camallen).
=> New subject params

app/talk/board.cjsx, app/talk/discussion.cjsx, app/talk/init.cjsx, app/talk/lib/moderation.cjsx
- Activates the placeholder moderation component
- Moderation component now takes in a section for context 
- Admins are moderators everywhere
- The discussion.cjsx/board.cjsx changes are just destructuring, indendation, & passing in the section prop to the moderation component
=> Activate moderation component

app/main.cjsx, app/pages/lab/project-details.cjsx, app/pages/lab/project.cjsx, app/pages/lab/visibility.cjsx
Add a "Visibility" tab to the project editor where you can toggle private/public, live/not live, and apply for beta and launch status.
Closes #240.
=> Project visibility editor

bin/config.sh, bin/serve.sh
Once zooniverse/Panoptes#961 is in, this should let you access the local server from any address.
=> Serve from 0.0.0.0

app/subjects/index.cjsx, css/subject.styl
- Link to individual talk comments from subject page
- ~~Also fix rounding error on getting a comment's page number~~
=> Link to talk comments from subject page

app/talk/comment-link.cjsx
=> Update discussion request in comment link

app/talk/index.cjsx, css/talk.styl
- Add some css to improve the style of the talk search input
- Add placeholder text
=> Style talk search form

app/api/config.coffee, app/api/talk.coffee, app/classifier/index.cjsx, app/pages/project/index.cjsx, app/partials/main-footer.cjsx, app/partials/main-header.cjsx
=> Determine the Talk host the same way we determine the Panoptes host

app/components/user-search.cjsx, package.json
=> Use patched react-select to close on select

app/pages/lab/collaborators.cjsx, app/subjects/index.cjsx, app/talk/discussion-new-form.cjsx, app/talk/mixins/current-section.coffee
I'm not sure if the project request is still necessary as the format only requires the id.
=> Use section project-\d+ naming.  Related to zooniverse/Talk-Api#39

app/classifier/subject-viewer.cjsx, app/lib/seen-this-session.coffee, app/lib/session-subjects.coffee, app/pages/project/classify.cjsx
=> Track seen-this-session subjects with their workflow

app/pages/lab/project.cjsx
I bet this link got lost in a big ol' help-text merge, because I don't remember ever having any help text for it.
Closes #306 again.
=> Add link to media library

app/pages/projects.cjsx, app/partials/project-card.cjsx
Reduces project load times by about a second on my machine, by
including the owner. Still working out how to do the same for the avatar
=> Speed up project load by including the owner

app/pages/lab/collaborators.cjsx, app/subjects/index.cjsx, app/talk/comment-box.cjsx, app/talk/comment-image-selector.cjsx, app/talk/comment.cjsx, app/talk/discussion-new-form.cjsx, app/talk/discussion.cjsx, app/talk/lib/project-section.coffee, app/talk/mixins/current-section.coffee
- Noticed it was a pain to update in #558
- Removes some promise renderers to get the name for the old format
- Renames `focusImage` to `subject`
=> Export projectSection

app/pages/project/classify.cjsx
=> Add utc_offset to classification metadata

app/main.cjsx
- Keeps the main nav collections link active on the sub pages
=> Nest collections routes to preserve active class

app/pages/home.cjsx
imagePromise needs the image src, not the avatar.
=> Fix home page project avatars

app/classifier/subject-viewer.cjsx
Store sizeRect and toolRect in component state.
Use stored sizeRect to calculate scale and details tooltip properties.
This should fix the React warning in #564
=> Don't access @refs during render()

app/talk/board.cjsx, app/talk/init.cjsx
- Make talk board descriptions editable
- Also set the default checked to 'all' when creating a board
- Closes #608
=> Make talk board descriptions editable

app/talk/discussion.cjsx
=> Typo fix in sign in prompt

app/partials/main-footer.cjsx
Add links for everything in the footer. I removed 'Education' since we
don't have a page for that yet. And 'Other Talk' since I'm not sure what
it's for. Let me know if those should be added in and where they should
point to.
=> Fill in footer links

app/pages/lab/project-details.cjsx
Always indicate what a project's URL will be under the name field so
people know that editing the name will change it.
Closes #603
=> Disable name change for live projects.

app/api/auth.coffee, app/pages/settings.cjsx, app/partials/register-form.cjsx
=> Add beta email checkbox to registration form.

app/partials/login-change-form.cjsx, app/partials/login-dialog.cjsx
Triggered by a user.login_prompt field on serialized response
Closes #598
=> Add prompt to set login name for migrated users

app/talk/board.cjsx
=> Redirect to appropriate talk after board deletion

app/classifier/index.cjsx
=> Disable tasks until subject is loaded

app/main.cjsx, app/pages/project/talk.cjsx, app/subjects/index.cjsx, app/talk/comment-link.cjsx, app/talk/lib/parse-section.coffee, css/talk.styl
- Takes the current zooniverse wide search and uses it in the project scope
=> Enable project searching

app/talk/inbox.cjsx, css/inbox.styl
- Adds unread status icon to inbox messages (css class + icon)
- Adds loading indicator to conversations list
- Fixes an issue where users with no conversations in their inbox would still see the paginator
=> Unread inbox

app/talk/init.cjsx
=> Add loading / empty state to talk boards page

app/pages/lab/project-details.cjsx, app/partials/data-export-button.cjsx
=> Add button to create subject data export

app/partials/sign-in-form.cjsx
...on the sign in form. People should be able to click reset without
having to messup their login
=> There should always be a reset password link

app/components/owned-card-list.cjsx, app/pages/collections.cjsx, app/pages/projects.cjsx, app/partials/owned-card.cjsx
- Closes #637 
- Add `FlexibleLink` component to determine if card should link to an internal or external link.
- Switch `<OwnedCard />` from using `<Link />` to `<FlexibleLink />`
=> Add ability for cards to link to internal or external urls

app/components/image-selector.cjsx, app/pages/profile/customize-profile.cjsx, css/image-selector.styl, css/settings.styl
Makes sure the text is always centered inside the component
Closes #432
=> Fixes sizing of the image drop component

app/subjects/index.cjsx, app/talk/discussion-new-form.cjsx, app/talk/discussion.cjsx
This field is required if focus_id is set.  Talk will have a validation shortly to enforce this.
=> Use and set focus_type on comments about subjects

css/dialog.styl
=> Fix scrolling in IE

css/main-header.styl
- Closes #667 
- I'm getting a bit lost at the purposes of all the different `on-some-page` selectors, but I think this is the only page where this would be a problem.
=> Declare position and z-index for main header on project page

app/pages/lab/science-case.cjsx
=> Update science page help text

app/pages/lab/project-details.cjsx, app/pages/project/home.cjsx, css/project-page.styl
=> A styles to project page and workflow_description

app/components/user-search.cjsx
I made a small backend change. This fixes user search for it
=> Add asterisk to display_name to trigger search

app/classifier/index.cjsx, app/classifier/subject-viewer.cjsx, app/collections/favorites-button.cjsx, app/collections/get-favorites-name.cjsx, app/components/subject-viewer.cjsx
Also has the favorites button make fewer requests
=> Fixing favorite button to set flag

app/pages/profile/account-information.cjsx
=> Add project communicate email

app/pages/lab/project-details.cjsx, app/pages/project/index.cjsx
=> Use consistent talk naming

app/partials/main-header.cjsx
=> Edit main navigation text

app/partials/main-footer.cjsx
=> Add Jobs link to footer

app/pages/profile/index.cjsx, css/user-profile.styl
- Made a working background image for the profile hero
- Fetched profile_header for the profile being viewed by params
- Also retrieving display_name for the profile being viewed if logged out or if current user does not match the params
=> Fetch and display profile header image

app/components/owned-card-list.cjsx, app/partials/owned-card.cjsx, css/owned-card.styl, css/owned-list-pages.styl
- Made project card avatars square for #728
- Added descriptions and removed owners for #662 
- Updated button styling for #688 
- Styled pagination buttons for #703
=> Updated styling for resource cards

app/talk/index.cjsx
=> Zooniverse Talk copy edit

app/pages/about/team-page.cjsx
=> Update Lucy Fortson bio

app/pages/about/team-page.cjsx
=> Update bio text, requested in #757

css/owned-card.styl
- Minor css fixes for owned resource cards
- Fixed #709
=> Fixed minor style issues with resource cards

app/talk/lib/project-linker.cjsx
=> Clean talk project list

css/dialog.styl, css/layout.styl, css/main-header.styl
=> Ensure dialogs are always above any other content

app/components/owned-card-list.cjsx, app/pages/projects.cjsx
=> Clearer owned card list count results display

app/partials/main-footer.cjsx, app/partials/main-header.cjsx
- Added daily zoo and blog links to header and footer for #698
=> Added Daily and Blog links

app/partials/register-form.cjsx
=> Fix link to User Agreement/Privacy Policy

app/main.cjsx, app/pages/about/contact-page.cjsx, app/pages/about/index.cjsx, app/partials/main-footer.cjsx
- Added contact us page component. Fixed #592
=> Contact us page

app/talk/comment-link.cjsx, app/talk/discussion.cjsx, css/paginator.styl, css/talk.styl
- Some minor stylistic updates for #531
- Makes the sidebar layout collapse for small screens
- Establishes a better board page hierarchy  
- Increases page size to 10
=> Talk stylistic updates

app/main.cjsx, app/pages/lab/index.cjsx, app/pages/lab/lab-policies.cjsx, css/secondary-page.styl
- Added lab policies page component with content.
- Fixed #781
=> Lab policies page

app/pages/home.cjsx
=> Add Planet Four: Terrains to homepage

css/main-header.styl
- Some comments about it in #785
- To accomodate new links additions (daily-zoo, blog)
- @heathv approved
=> Decrease nav links spacing

app/pages/lab/subject-set.cjsx
=> Copy change

app/collections/collaborators.cjsx, app/collections/create-form.cjsx, app/collections/manager-icon.cjsx, app/collections/manager.cjsx, app/collections/settings.cjsx, app/collections/show-list.cjsx, app/collections/show.cjsx, app/components/collection-search.cjsx, app/components/owned-card-list.cjsx, app/components/subject-viewer.cjsx, app/components/user-search.cjsx, app/lib/set-toggle.coffee, app/main.cjsx, app/pages/collections.cjsx, app/pages/lab/project-details.cjsx, app/pages/lab/visibility.cjsx, app/partials/display-name-slug-editor.cjsx, app/talk/lib/paginator.cjsx, css/collections.styl
- Closes #740 
- Closes #493 
- Adds:
- Ability to create a collection from the collections icon 
- Ability to add a subject to a collection
- Ability to view all collections
- Ability to view your own collections and make settings/collaborator changes to them
=> Collections manager

app/pages/lab/index.cjsx
- Fixed #780 
- Added the basic standard-button class for a bit of styling
=> Added how to link and button styling

app/main.cjsx, app/pages/about/education-page.cjsx, app/pages/about/index.cjsx
=> Add Education page

app/lib/featured-projects.coffee, app/pages/home.cjsx, app/talk/lib/project-linker.cjsx
- Closes #812
- Fixed incorrect variable name in `setProjects` callback
=> Only display filtered projects in Talk project-linker

app/components/promise-renderer.cjsx
- Opt-in to the loading state instead of out
- Prevents jumpiness during loading
- @edpaget, @brian-c You guys cool with this?
=> Change PromiseRenderer default pending to null

css/owned-card.styl
=> Adjusted margin to fix #777

app/pages/profile/private-message.cjsx
=> Changed transitionTo to replaceWith

app/talk/init.cjsx, app/talk/lib/project-linker.cjsx
=> Use title as default value for project linker

app/collections/collaborators.cjsx, app/talk/comment-preview.cjsx
=> Convert urls to links in md, and add breaks

app/talk/board.cjsx, app/talk/discussion-preview.cjsx, app/talk/discussion.cjsx, app/talk/lib/moderation.cjsx, app/talk/sticky-discussion-list.cjsx, css/talk.styl
This adds a toggle and ordering for talk discussion stickies.
=> Add talk sticky discussion ordering

app/collections/collaborators.cjsx, app/collections/create-form.cjsx, app/collections/settings.cjsx, app/collections/show-list.cjsx, app/collections/show.cjsx, app/components/user-search.cjsx, css/collections.styl
- Closes #857
- Closes #852
- Closes #834
- Closes #832
- Closes #828 
- Closes #827
=> Collections bugfixes

app/partials/main-footer.cjsx, css/main-footer.styl, css/main-header.styl, package.json
This adds an "Admin mode" checkbox to the footer when a user has `admin: true` set. While that's checked, the client will send `admin: true` as a param with every request, like:
PUT things:
```json
{
"admin": true,
"things": {...}
}
```
=> Admin mode

app/talk/discussion.cjsx
=> Fix replies: ensure all lines in reply are quoted

app/talk/board-preview.cjsx
=> Link board preview user to latest commenter

app/talk/discussion.cjsx
=> Preserve current page when editing comments

app/talk/inbox-form.cjsx, app/talk/inbox.cjsx, app/talk/lib/message-subject-validations.coffee, app/talk/lib/message-validations.coffee, css/talk.styl
- Adds a form to send new private messages to the inbox page
- Closes #748
- Using user search for selection, so related to https://github.com/zooniverse/Panoptes/issues/1034
=> Inbox private message form

css/talk.styl
=> Set max image width on talk comments

app/talk/board-preview.cjsx, app/talk/comment-link.cjsx, app/talk/comment.cjsx, app/talk/discussion.cjsx, app/talk/inbox-conversation.cjsx, app/talk/init.cjsx, app/talk/lib/get-page-of-comment.coffee, app/talk/popular-tags.cjsx, app/talk/search-result.cjsx, app/talk/search.cjsx, app/talk/subject-display.cjsx
- Closes #831
- Adds PopularTags component
=> List popular tags in sidebar

app/pages/reset-password.cjsx
=> Update password reset form

app/pages/lab/how-to-page.cjsx
=> Fix folder link

app/talk/lib/paginator.cjsx, css/main.styl, css/paginator.styl
- 1c9bebd Closes  #887
- 982f70d Closes #906 
- 1dafd81 Closes #912
=> Add pagination behaviors

app/talk/quick-subject-comment-form.cjsx
=> Typecast discussion ID

app/api/auth.coffee, app/main.cjsx, app/pages/unsubscribe.cjsx
html form based email unsubscription for users that can't login. We may end up pulling this and just use the API GET with uniq token links but for now this will save some effort.
=> unsubscribe all zoo emails via html form

app/pages/lab/how-to-page.cjsx, app/pages/lab/lab-policies.cjsx, app/pages/lab/project-details.cjsx, app/pages/lab/project.cjsx
=> Builder help text update

app/pages/projects.cjsx
does what it says on the tin, allow users in admin mode to view all projects.
=> show all projects when admin user mode is active

app/components/collection-search.cjsx, app/components/user-search.cjsx
This depends on https://github.com/zooniverse/Panoptes/pull/1075
=> Update user search syntax for new search method

app/talk/comment-box.cjsx, app/talk/comment.cjsx, app/talk/quick-subject-comment-form.cjsx, css/talk.styl
=> Only show positive feedback after a server submit

app/api/auth.coffee, app/pages/unsubscribe.cjsx
Depends on https://github.com/zooniverse/Panoptes/pull/1085
=> Unsubscribe page fixes

app/talk/quick-subject-comment-form.cjsx, css/talk.styl
=> Improve comment adding styling

app/components/markdown.cjsx, app/talk/comment-preview.cjsx
Markdown features should be the same across the site.
=> Only one component should render Markdown

app/api/config.coffee, app/pages/lab/education.cjsx, app/pages/lab/faq.cjsx, app/pages/lab/results.cjsx, app/pages/lab/science-case.cjsx, app/pages/project/education.cjsx, app/pages/project/faq.cjsx, app/pages/project/index.cjsx, app/pages/project/results.cjsx, app/pages/project/science-case.cjsx, app/partials/project-page-editor.cjsx
Depends on zooniverse/Panoptes#1082
=> Project pages

app/components/markdown.cjsx
=> Catch getParams for markdown in alert elements

app/talk/discussion-preview.cjsx, app/talk/search-result.cjsx
=> Link search results to section's talk

app/components/classifications-ribbon.cjsx, app/main.cjsx, app/pages/profile/index.cjsx, app/pages/profile/stats.cjsx, app/pages/settings/profile.cjsx, css/classifications-ribbon.styl, css/main.styl, css/stats-project-icon.styl
Kinda like the old one, with a ribbon and project icons. Needs some polish, but it's a start.
Closes #633.
=> Add a stats page

app/talk/inbox-conversation.cjsx, app/talk/inbox.cjsx, css/inbox.styl
- Closes #738
- Adds usernames, timestamps and some improved styling to the inbox view and individual  conversations
=> Add usernames to inbox, some styling

app/pages/lab/workflow.cjsx, css/workflow-editor.styl
=> Constrain width of workflow first task select tag to it's column

css/secondary-page.styl
The whole secondary-page-css business needs a re-work, but this'll close #1038.
=> Set max-width on secondary-page images

app/pages/settings/account.cjsx, app/pages/settings/email.cjsx
Closes #1000 - I couldn't help myself when i saw it was the 1000th issue.
=> consolidate all email preferences to the email settings page

app/components/markdown.cjsx
...when inside a project.
Closes #882
=> Link to talk subjects with just ^

app/talk/inbox-form.cjsx
=> Add rows to inbox message textarea

app/pages/lab/subject-set.cjsx
=> Adjust text in subject set uploader target.

Dockerfile
To speed up build/deploy times.
=> Split dependencies into separate Docker image

app/pages/lab/project.cjsx, app/pages/lab/subject-set.cjsx
- Closes #870
- Delete `app/pages/create-project.cjsx` which has been empty for awhile
=> Better behavior surrounding empty subject set names

app/pages/collections.cjsx
=> Fix collection paging

app/pages/collections.cjsx, app/partials/owned-card.cjsx
Depends on https://github.com/zooniverse/Panoptes/pull/1123 to show the lock
=> Collections cleanup

app/components/subject-viewer.cjsx
=> Hide some metadata, render the rest as Markdown

app/collections/collaborators.cjsx, app/components/tag-search.cjsx, app/components/user-search.cjsx, app/pages/lab/collaborators.cjsx, app/pages/lab/project-details.cjsx, css/user-search.styl
...in the Project Lab details page
=> Add autocompleting field for tagging projects

app/pages/lab/collaborators.cjsx, app/talk/comment.cjsx, app/talk/discussion.cjsx, app/talk/lib/moderation.cjsx
- Increase page_size of requests for a user's roles
- For #1083
=> Increase role limit for user role requests

app/talk/lib/moderation.cjsx
=> filter roles by project section and zooniverse wide

app/pages/lab/project-details.cjsx
=> set checkbox checked value

app/pages/lab/media.cjsx
=> Increase max media count to 30

app/pages/lab/subject-set.cjsx
Addressing https://github.com/zooniverse/Panoptes-Front-End/issues/1095
...If I did it right
=> update help text to reference limits

app/partials/account-bar.cjsx, css/main-header.styl
Adds an expandable button control to make the account menu accessible from the keyboard.
Enter/Space: toggle menu on/off
Up/Down keys: navigate menu when expanded.
Adds aria attributes for VoiceOver too.
=> Accessible account menu

app/partials/main-footer.cjsx, css/main-footer.styl
- Closes #899 
- Also moves privacy policy and jobs links to below the rest of the site nav.
=> Move links around in the footer

app/talk/inbox.cjsx
- Closes #1036
- Deletes `.main.js` from  #1094
=> Set conversation last updated at from last message

app/talk/comment-box.cjsx, app/talk/discussion-new-form.cjsx, app/talk/discussion.cjsx, app/talk/quick-subject-comment-form.cjsx
- Small thing that popped up from #1094
=> Pass user to comment-box

app/collections/show-list.cjsx, css/collections.styl
=> Link to subject pages from collection

app/subjects/index.cjsx
- Tiny fix after #1094
- Closes #1110
=> Pass user to subject page forms

app/partials/account-bar.cjsx
Looks like this got moved while resolving a merge conflict.
=> fix onKeyDown handler: broke during a merge conflict

app/components/manifest-view.cjsx, app/pages/lab/subject-set.cjsx, app/partials/subject-uploader.cjsx
=> Prevent files larger than 600kb from being uploaded

app/talk/board-preview.cjsx, app/talk/board.cjsx, app/talk/discussion-preview.cjsx, app/talk/latest-comment-link.cjsx, app/talk/search-result.cjsx, css/talk.styl
=> Use discussion link comment for board preview

test/project-creation.coffee
...since that's been moved to a separate resource
=> Remove science case param

app/pages/settings/index.cjsx
=> Wrap user settings page in a change listener

app/talk/active-users.cjsx, app/talk/board-preview.cjsx
=> Change 'users' to 'participants'

app/pages/project/index.cjsx, css/project-page.styl
=> Add disclaimer to non-approved projects

app/talk/discussion.cjsx, css/talk.styl
=> Add ability to lock discussions

app/main.cjsx, app/talk/breadcrumbs.cjsx
=> Catch breadcrumbs for unpermitted boards

css/stats-project-icon.styl
=> Fix stats badge

app/components/retirement-rules-editor.cjsx
...variables so they always reflect the current workflow
Closes #1122
=> Listen to workflow changes before setting criteria

app/talk/inbox-conversation.cjsx, app/talk/inbox-form.cjsx, css/inbox.styl, css/user-search.styl
=> Use markdown and comment editor boxes in Inbox

app/talk/inbox.cjsx
Makes sure inbox messages are updated on page changes
=> Fix for inbox pagination changes

app/talk/board.cjsx, app/talk/discussion.cjsx
- Closes #955
- Closes  #1150
- Closes #1046
- Closes #1121
=> Improve discussion and board pagination

app/pages/lab/subject-set.cjsx
=> Show Filename metadata if it exists

app/talk/board-preview.cjsx, app/talk/board.cjsx, app/talk/search-result.cjsx, app/talk/search.cjsx
- Makes it so the latest comment links correctly go to the last page 
- #873
=> Sort linked comments in latest comment previews

app/subjects/index.cjsx, app/talk/comment.cjsx
=> Pass user prop to subject viewer in talk

app/api/auth.coffee
Use X-CSRF-Token header instead of a token in the body
Closes #1205
=> Convert faked DELETE into a real one

app/talk/discussion.cjsx
=> Include navigation above comments in Talk

app/pages/project/classify.cjsx, app/pages/project/home.cjsx
=> Only select from Active Workflows

app/components/subject-viewer.cjsx
=> Use info icon for metadata

app/talk/comment-box.cjsx
=> Activate loading state on comment submit

app/talk/discussion.cjsx, css/talk.styl
=> Add sign in prompt to bottom of discussions page

app/pages/profile/private-message.cjsx, app/talk/private-message-form.cjsx, css/main-footer.styl, css/project-page.styl, css/talk.styl, css/user-profile.styl
=> Use markdown in profile private message form

app/talk/comment-box.cjsx, app/talk/discussion.cjsx
=> Scroll to bottom on click reply

app/pages/reset-password.cjsx, app/pages/settings/account.cjsx, app/partials/register-form.cjsx, app/partials/sign-in-form.cjsx
Closes #1230, but I'd love to know what's causing this.
=> Explicitly set forms with password fields to POST

app/talk/comment-box.cjsx, app/talk/comment-image-selector.cjsx
=> Rename featured image to linked image

app/talk/moderations.cjsx
- Closes #1203 
- Eliminates some wonky-ness in that request by just reading section from params
=> Improve roles fetching for moderations page

app/talk/discussion.cjsx
=> Prompt to sign in on click reply if not signed in

app/subjects/index.cjsx, css/main.styl, css/subject-page.styl, css/subject.styl, css/talk.styl
=> Make subject images & viewer smaller in talk

app/talk/inbox-conversation.cjsx
=> Update page state on conversation user changes

app/talk/comment-help.cjsx
=> Update help text subject mentioning syntax options

app/talk/comment-link.cjsx, app/talk/discussion.cjsx
This PR would allow comments to be linked to without including the page number.
=> Refactor comment links

app/classifier/index.cjsx
=> Advance classifier to next image after navigating

app/talk/discussion.cjsx
@parrish I missed this in #1248
=> Fix comment id check

app/pages/lab/how-to-page.cjsx, app/pages/lab/lab-policies.cjsx
The line breaks in the raw files were being rendered in Markdown and they looked weird. I've made it so that all text from the same paragraph is on the same line.
closes #1232
=> remove line breaks from paragraphs

app/talk/search-result.cjsx, app/talk/search.cjsx
- Closes #1256
- Params needed to be passed to user link component to link correctly
from project
=> Fix project search

app/talk/search.cjsx
=> Encode URI components on search querys

app/talk/board-preview.cjsx
=> Sort board preview request by updated_at

css/project-page.styl
...to make sure call to action text is centered in the page
Closes #1193
=> Workaround wonky IE Flexbox model

app/talk/quick-subject-comment-form.cjsx
Make sure project is loaded correctly
Closes #1299
=> Fix quick subject comment

app/components/markdown.cjsx
=> Catch markdown parsing errors and return unparsed input

app/talk/comment-link.cjsx
=> Fix project comment links, use page-less style

app/talk/moderations.cjsx
=> Change destroy to delete

app/partials/account-bar.cjsx, css/main-header.styl
- Tested for positioning in FF, Chrome, Safari
- For #995
=> Add red dot to unread envelope

app/partials/avatar.cjsx
=> Set default avatar on error loading avatar

app/api/auth.coffee, app/partials/register-form.cjsx
...when registering
Closes zooniverse/Panoptes#1231
=> Make sure project_email_communication flag is set

app/partials/sign-in-form.cjsx
=> Add or email address to sign-in-form

app/talk/discussion-new-form.cjsx, app/talk/discussion-preview.cjsx, css/talk.styl
- Closes #1166
- For subject_default discussions
=> Subject default discussion thumbnail previews

app/talk/discussion.cjsx
I think these need the `sort_linked_comments` to be set explicitly
=> Fix permalinks

css/secondary-page.styl
- Closes #1287
- Closes #1328
@chrissnyder font size look good?
=> Increase font size on secondary pages

app/classifier/index.cjsx, app/classifier/mock-data.coffee, app/classifier/tasks/drawing.cjsx, app/classifier/tasks/multiple.cjsx, app/classifier/tasks/survey.cjsx
This fixes finding the next task, which I broke in #1364. It's already emergency-deployed.
Closes #1365.
=> Fix next task

app/subjects/index.cjsx, css/talk.styl
=> Add sign-in prompt to subject page

app/talk/discussion.cjsx
=> Allow discussions to be moved

app/talk/lib/display-roles.cjsx
=> Ensure roles are not listed twice

app/talk/comment-help.cjsx
=> Add space to help text

app/talk/init.cjsx
=> Update boards on user changes

app/talk/init.cjsx
=> Fix prop change hander args usage

css/talk.styl
- Much better looking this way :surfer: 
- #1280
=> Change yellow color of linked comments to blue

app/talk/moderations.cjsx
- Mentioned in post-merge discusion of #1251
=> Change moderator destroy button text to 'delete'

app/talk/config.coffee
=> Increase discussion page size to 20

app/talk/moderations.cjsx
=> Show open reports as default

app/collections/favorites-button.cjsx, app/collections/manager-icon.cjsx, app/components/subject-viewer.cjsx
=> Add titles to buttons in subject viewer

app/talk/discussion.cjsx
=> Add input type to moderation input

app/talk/board-preview.cjsx, css/talk.styl
=> Style private board previews

app/pages/profile/stats.cjsx
=> Link directly to external projects from stats page

app/talk/moderations.cjsx
=> Show author of reported comments

app/talk/discussion.cjsx
=> Set comments meta on comment submit

app/classifier/tasks/survey/choice.cjsx, app/classifier/tasks/survey/editor.cjsx, css/classify.styl
"No questions" column for survey task choices, merging because urgency.
=> No further questions

app/talk/discussion-preview.cjsx
- This got changed at some point, Since the first comment is
the one that sets the focus of the discussion this pulls the thumb
from that
- #1338
=> Get thumbs from first comment instead of latest

app/partials/main-footer.cjsx, css/secondary-page.styl
I cleaned up Alex's git history from #1322
=> Spacing pr

app/talk/discussion.cjsx, css/talk.styl
- Lets owners of discussions edit their titles
- Closes #813
=> Editable discussion titles

app/talk/board.cjsx, app/talk/discussion.cjsx, app/talk/inbox.cjsx
- Closes #1418
- Also fixes the logged out state from the title editing branch
=> Add prompts to sign in, add user check

app/partials/display-name-slug-editor.cjsx
=> Fix url in the project lab details page

app/talk/comment-box.cjsx, app/talk/discussion.cjsx
=> Prepend replies to text instead of having separate

app/collections/get-favorites-name.cjsx
- Keeps collection name unique, but is more descriptive
- Closes #1357
=> Use slug for favorites naming

app/components/owned-card-list.cjsx, app/pages/collections.cjsx, app/pages/profile/index.cjsx, app/partials/account-bar.cjsx, app/router.cjsx
...and account bar
Closes #1225
=> Separate page for favorites and links from profile

app/pages/lab/how-to-page.cjsx, app/pages/lab/project-details.cjsx
=> Remove reference to right clicking to bring up

app/talk/latest-comment-link.cjsx, app/talk/moderations.cjsx, css/moderations.styl
- Add logging of actions taken
- Let users attach a message to their action
- Attach filter state to URL query
- Closes #1388
- Closes #1395
- Closes #1387
=> Update moderations interface

app/talk/latest-comment-link.cjsx
=> Remove titles from discussion previews

css/inbox.styl
- This will probably change on the next redesign, but since it was
a quick change, closes #1030
=> Highlight unread inbox messages more prominently

app/pages/home.cjsx
=> Remove line break in home page copy

app/collections/favorites-button.cjsx, app/components/subject-viewer.cjsx, app/talk/comment.cjsx, app/talk/discussion.cjsx
- Also hides these buttons in zooniverse-wide talk
=> Get favorites working from project talks

app/talk/discussion.cjsx
=> Update discussions on changes from moderation pane

app/pages/sign-in.cjsx, app/router.cjsx
http://zooniverse.org/signups was busted.
=> fix old register redirect

app/classifier/index.cjsx, app/lib/session.coffee, app/partials/app.cjsx, app/router.cjsx
That gets submitted as classification metadata to track classifiers that
log in part way through their sessions
Closes zooniverse/Panoptes#1248
Closes zooniverse/Panoptes#866
=> Adds a session identifier

app/pages/settings/email.cjsx, css/settings.styl
This lets a user manage their email preference for talk.
This is good to go for staging ~~, but not production yet~~ and production.
=> Adds talk email preference management to the settings page

app/talk/inbox-conversation.cjsx, css/talk.styl
=> Allow conversations to be destroyed

app/components/subject-viewer.cjsx
Sorry, I think #1437 actually dropped the play button entirely. I believe the intention was to not show the play button when the subject's locations are of different types, which is what this function'll check for.
=> Restore the play button for multi-location image subjects

app/pages/profile/private-message.cjsx, css/user-profile.styl
This lets uses block each other.
A block prevents the blocked user from messaging the user.
Additionally, a user cannot message the user they blocked.
=> Adds user blocking

app/classifier/subject-annotator.cjsx
- Add fallbacks for scrollX in winternet explorer
=> Add scrollX fallbacks for internet explorer

app/collections/favorites-button.cjsx
Closes #1356
Needs to filter favorite collections belonging to the current user
=> Fix favorites button in classification interface

app/components/owned-card-list.cjsx, app/pages/about/about-home.cjsx, app/pages/about/contact-page.cjsx, app/pages/about/education-page.cjsx, app/pages/home.cjsx, app/pages/lab/how-to-page.cjsx, app/pages/lab/lab-policies.cjsx, app/pages/lab/landing-page.cjsx, app/pages/profile/comment-link.cjsx, app/pages/unsubscribe.cjsx, app/partials/avatar.cjsx, app/partials/display-name-slug-editor.cjsx, app/partials/main-header.cjsx, app/partials/owned-card.cjsx, app/partials/register-form.cjsx, app/partials/sign-in-form.cjsx, app/router.cjsx, bin/serve.sh, bin/server.js
This remove the need to use the hash fragement for URLs.
I'm working on a corresponding update to the nginx static server.
=> Remove hash

app/pages/project/index.cjsx
Closes zooniverse/wildcam-gorongosa#90
=> Hide page links from redirectable projects

app/router.cjsx
- Noticed it got lost in the latest routing changes
=> Add talk-moderations route back in

app/classifier/drawing-tools/polygon.cjsx, app/classifier/tasks/drawing/index.cjsx
Closes #1310, which closes #1118.
=> Record auto-closing of polygons

app/subjects/index.cjsx, app/talk/board.cjsx, app/talk/discussion.cjsx, app/talk/inbox.cjsx, app/talk/init.cjsx, css/talk.styl, css/user-profile.styl
=> Replace spans with buttons for sign in prompts

app/router.cjsx
fix `/accounts/sign-in & /accounts/register` routes
=> name the routes correctly

app/pages/lab/workflow.cjsx
=> Use router to figure out workflow preview URL

app/talk/search.cjsx
=> Fix search paging for hashless urls

app/classifier/tasks/drawing-task-details-editor.cjsx, css/workflow-editor.styl
The task deletion button use to be a within the task, then it was moved out to the workflow. Sub-tasks weren't updated.
Closes #1498.
=> Add delete button to drawing subtasks

app/pages/settings/email.cjsx
Forgot to add this when adding that preference.
=> Hide the moderation report preference (always immediate)

app/talk/search.cjsx
After zooniverse/Talk-Api#71 deploys, this should be good to go.
=> Replace searches fetch with a standard API resource

app/talk/discussion.cjsx, app/talk/follow-discussion.cjsx
=> Set discussion following status on mount

app/talk/comment-box.cjsx, app/talk/comment.cjsx, app/talk/discussion.cjsx, css/talk.styl
- Provides link to reply author and comment
- Closes #1434
- Closes #1435 (not relevant anymore)
- Some examples on dev at `/talk/38/92`
=> Use referenced replies instead of quoted text

app/pages/settings/email.cjsx, app/talk/comment-help.cjsx
I'm opening this just to get it up, but the backend is going to only be deployed to staging for the moment.
I'll comment/assign when it's ready for production.
=> Add notification preference and help text for group mentions

app/talk/follow-discussion.cjsx
Aside from being generally informative, it helps with #1490.
=> Add subscription email digest to the description

app/talk/recents.cjsx, css/talk.styl
Closes #1514 
The backend is already deployed for this
=> Adds a subject notes filter to recents view

app/talk/lib/paginator.cjsx
=> Get path from location

app/talk/comment.cjsx, css/talk.styl
=> Disable subject viewer and comment tools for deleted comments.

app/talk/comment.cjsx, app/talk/discussion.cjsx
Closes #1572
Renders the focus in a comment if
- it's not a focused discussion and this comment has a focus
- it's a focused discussion and this is the first comment
- it's a focused discussion and this comment is about a different focus
=> Duplicate focuses

app/pages/lab/data-dumps.cjsx
depends on https://github.com/zooniverse/Panoptes/pull/1376, once this is in then it's appropriate we provide some messaging for users.
=> messaging around rate limited dump workers

app/talk/comment-image-selector.cjsx
=> Fix recents linking

app/pages/lab/data-dumps.cjsx
=> better messaging around exports

app/talk/comment.cjsx
Don't show an image if it doesn't exist.
=> Fix logic around showing focuses

app/talk/comment.cjsx
No rush, this just feels a bit more understandable.
=> Refactor focus rendering logic

app/pages/about/publications-page.cjsx
=> Chage publications page asset catch path

app/pages/lab/subject-set.cjsx
=> Allow users in admin-mode to upload video subjects

app/pages/about/publications-page.cjsx
Fixed #1321 by modifying the markup of the layout.
=> Fixed #1321

app/talk/search-result.cjsx
=> Pass project to search result markdown

css/talk.styl
=> Prevent markdown 'code' lines from overflowing in comments

app/components/project-icon.cjsx, app/lib/is-admin.coffee, app/pages/admin.cjsx, app/pages/admin/create.cjsx, app/pages/admin/project-status-list.cjsx, app/pages/admin/project-status.cjsx, app/pages/lab/subject-set.cjsx, app/partials/main-header.cjsx, app/router.cjsx, css/settings.styl
This creates an admin area. Currently this is only used for viewing project statuses and changing them. The log of changes depends on zooniverse/Panoptes#1380, but this should still work without it.
=> Admin area

app/pages/project/home.cjsx, app/pages/project/metadata.cjsx, css/project-page.styl
- Adds in the available metadata fields on a project to its home page
@brian-c Just putting this one out there, feel free to reject if you've got other plans for these stats
=> Add project metadata statistics to project page

app/talk/discussion-preview.cjsx, app/talk/latest-comment-link.cjsx, css/talk.styl
- Adds comment plain-text content snippet to discussion previews
- Closes #1426
=> Discussion latest comment previews

app/pages/lab/subject-set.cjsx
=> Fix allowed types in subject uploader

package.json
=> Update to markdownz@3.0.0

app/pages/admin/project-status-list.cjsx, app/pages/admin/project-status.cjsx
add ability to modify the project workflow activation setting for admin. also handle empty project lists from applied filters.
=> project workflow activation on project admin page

app/subjects/index.cjsx
=> Enable favoriting and collecting on subject page

app/pages/lab/data-dumps.cjsx, app/partials/data-export-button.cjsx
Also add ready state to buttons to indicate new data is being generated,
closes #1257
=> Add aggregations export button

app/classifier/tasks/drawing/marking-initializer.cjsx
Fixes issues https://github.com/zooniverse/Panoptes-Front-End/issues/1618.  Circles/ellipses/boxes that fail initValid are automatically removed.
=> fixes issues 1618

app/talk/comment-box.cjsx, app/talk/comment-image-selector.cjsx, css/talk.styl
- Some suggestions from #1581
- Adds a dedicated 'search' button to the image selector form
- If there is one match that comes back it will automatically set it as the focus image
=> Add image search submit button, improve selection

app/pages/lab/subject-set.cjsx
=> subject counts and limit message

app/talk/lib/project-linker.cjsx
- Closes #1645 
- Example on dev is fossil-finder
=> Treat empty string redirects as not having one

app/lib/get-subject-location.coffee
=> Supply frame for thumbnails src in discussion link

app/talk/config.coffee, app/talk/recents.cjsx
=> Increase recents page size

app/pages/lab/data-dumps.cjsx, app/partials/data-export-button.cjsx
remove admin only view for aggregation dumps, instead change the UI to signal this a new experimental feature.
=> ui update for aggregation experimental feature

app/pages/project/talk.cjsx, app/talk/index.cjsx, app/talk/search-input.cjsx, app/talk/search.cjsx
=> Add a back button to search, Make component

app/pages/admin/project-status.cjsx
save api devs work...allow most of the admin stuff to be done here.
=> allow admin to set the project external redirect

app/api/auth.coffee, package.json
Depends on zooniverse/json-api-client#14
=> Update auth client to handle response from superagent

css/owned-card.styl
Adds a min-height to card button so it's consistent. Fixed #1307
=> Fixed height on card button

app/pages/project/classify.cjsx
Quick fix for broken classifier
=> Disable gold_standard flag for a minute

app/classifier/index.cjsx, app/pages/project/classify.cjsx
=> Delete the gold_standard key instead of setting false

css/dialog.styl, css/main-footer.styl
- Fixed #1296 by moving the close button to the right of the dialog container
=> Moved close button to outside of dialog

app/components/owned-card-list.cjsx, app/pages/settings/email.cjsx
- Added pagination to email preferences in settings modeled after how it's done in the project builder and on talk
- Fixed a styling issue for the project page pagination when on the first page
=> Added pagination for email prefs. Fixed styling on project pagination

app/pages/lab/lab-policies.cjsx
update lab docs to have the correct limits
=> per user limits, not per project.

app/subjects/index.cjsx, app/talk/comment-link.cjsx, app/talk/comment.cjsx, css/talk.styl
=> Use standard comment container on subject page

css/talk.styl
=> Break words in discussion previews

app/pages/lab/workflow.cjsx
=> user imported makeHref function

app/collections/show-list.cjsx
=> Use response meta field over query param for collection pagination

app/subjects/index.cjsx
=> Show newest subject comments first

app/main.cjsx
Closes zooniverse/Panoptes-Front-End#1716
=> Fix url redirects

app/pages/about/education-page.cjsx
- So it's not parsed as a user
=> Fixes zoo teach link on education page

app/pages/admin.cjsx, app/pages/admin/create.cjsx, app/pages/admin/user-settings.cjsx, app/router.cjsx
started on an admin user page, it only currently allows subject_limits to be fetched / updated (in admin mode). 
One note: and you can't edit yourself as it got weird when updating props on the logged in user (avatar req's fired off and i couldn't type into the limit box. Any thoughts on this appreciated and happy to mould this any way you like.
=> Admin allow to set user limits

app/collections/show.cjsx
=> Remove disabled Talk link.

app/lib/markdown-help.cjsx
=> Add react require

package.json
=> Roll back markdownz version

package.json
Reverts zooniverse/Panoptes-Front-End#1735
=> Revert "Roll back markdownz version"

app/talk/moderations.cjsx
- Also adds more presentation labels to actionTaken object
- Closes #1674
- Mentioned a bit in #1395
=> Present 'closed' state of moderations as 'deleted'

app/talk/moderations.cjsx
- Renders destroyed comments correctly
- Removes invalid state parameter 'all'
=> Fix talk moderation display bugs.  Closes #1385

app/pages/lab/talk.cjsx, app/talk/init.cjsx, app/talk/lib/create-board-form.cjsx
=> User role-name displays

app/classifier/tasks/single.cjsx, app/pages/lab/collaborators.cjsx, app/pages/project/research.cjsx, app/talk/moderations.cjsx, css/moderations.styl
Addresses the following issues:
1. change text "Scientist" to "Researcher"
2. parse markdown in classification summary
3. include timestamp in moderation logs
=> Misc fixes

app/pages/project/talk.cjsx, app/talk/search-input.cjsx, app/talk/tags.cjsx
- Searches are triggered by having a '#' as the first character
- Closes #1748
=> Route tag searches to tags results page

app/pages/project/talk.cjsx, app/talk/footnote.cjsx, app/talk/index.cjsx, css/talk.styl
=> Add talk footnote

bin/config.sh, views/index.ejs
=> Record deployed commit

app/talk/discussion.cjsx
Closes #1765 
I think this might be a regression from a5c465aad1
This also fixes the transition to the new board.
=> Fix discussion move

app/pages/project/index.cjsx, app/talk/board.cjsx, app/talk/discussion.cjsx, app/talk/index.cjsx, app/talk/init.cjsx, app/talk/search.cjsx, app/talk/tags.cjsx, css/talk.styl
Organizes talk sidebars and makes them consistent throughout talk.
Closes #892 
Related to #1017
=> Talk sidebar

app/talk/comment.cjsx, app/talk/lib/comment-context-icon.cjsx, app/talk/search-result.cjsx, css/talk.styl
Closes #1651 
- Adds a lock icon for comments coming from locked discussions.
- Adds a eyeslash icon for comments coming from private boards
=> Adds context icons to comments

app/talk/comment-report-form.cjsx
=> Close comment report form after submission

app/components/single-submit-button.cjsx, app/talk/board.cjsx, app/talk/comment-box.cjsx, app/talk/comment-image-selector.cjsx, app/talk/comment.cjsx, app/talk/discussion.cjsx, app/talk/follow-discussion.cjsx, app/talk/inbox-conversation.cjsx, app/talk/init.cjsx, app/talk/lib/create-board-form.cjsx, app/talk/lib/create-subject-default-button.cjsx
Closes #1759 
This is probably generally useful too.
Only caveat is that when the button is a `<button type="submit">` it still needs an `onClick` handler to call the form submission.  (Apparently react kills the form submit event if there's a click event handler)
=> Add a component to prevent multiple form submissions

app/classifier/index.cjsx
In addition to experts, closes #1770.
=> Allow owners to make gold standard classifications

app/talk/latest-comment-link.cjsx, css/talk.styl
=> Show user roles in comment previews

app/pages/lab/subject-set.cjsx, app/pages/lab/workflow.cjsx
Fixed #1124 by adding display_name and id as header to workflow editor and subject set editor.
=> Add name and id as header

app/pages/project/classify.cjsx
If saving a classification fails, the classification's data is stored in localStorage and saved when the next classification save is successful.
Test with a query string like `?simulate-classification-save-failure=1`.
=> Queue failed classification saves

app/talk/board.cjsx
=> Hide the new discussion link on subject default (notes) boards

app/talk/inbox-conversation.cjsx
Fixed #1034 by adding "Back to Inbox" link.
=> Added back to inbox link

app/components/subject-viewer.cjsx, app/subjects/index.cjsx, app/talk/comment.cjsx
- Adds links to full res subject images in discussions and subject page
- Closes #979
=> Add links to full size subjects in talk

app/talk/lib/project-linker.cjsx, app/talk/search.cjsx
- Fixes an error where the search results would sometimes refresh itself
=> Only run search request when query has changed

app/partials/login-bar.cjsx, css/main-header.styl
=> Add explicit spacing between login bar sub elements

css/project-roles.styl, css/talk.styl
- Decreases specificity so the role p's don't conflict here
- Closes #1786
=> Prevent css font color conflict in board preview

app/talk/init.cjsx
=> Paginate boards list, increase request size

app/partials/main-header.cjsx, css/home-page.styl, css/main-header.styl, public/assets/hamburger.svg
- Adds a :hamburger: style mobile navigation for smaller screens
- I'm not crazy about having a fixed breakpoint vs fluid nav, but I
think this is a nice compromise with the way the css/global state is
right now, and will be a usability improvement
=> Add hamburger nav menu, improve homepage collapse

package.json
Adds modal form scrolling. Closes #1631.
=> Bump modal form version

app/subjects/comment-form.cjsx, app/subjects/comment-list.cjsx, app/subjects/index.cjsx, css/subject-page.styl
The subject index page was getting pretty huge, so before I added anything else to it, I wanted to try to start breaking out some components.
I also tried to clean up and refactor a bit too.
=> Organize subject components

app/classifier/drawing-tools/circle.cjsx, app/classifier/drawing-tools/ellipse.cjsx, app/classifier/drawing-tools/line.cjsx, app/classifier/drawing-tools/point.cjsx, app/classifier/drawing-tools/polygon.cjsx, app/classifier/drawing-tools/rectangle.cjsx, app/classifier/drawing-tools/root.cjsx, app/classifier/mock-data.coffee
Adds an `_inProgress` property to marks. When it's false, the details will show. Closes #1804.
=> Show drawing tool details when the shape is not in progress

app/subjects/index.cjsx, app/subjects/mention-list.cjsx
Depends on #1855 and #1856 (merge those first)
Same deal as the discussion list, I'm just grabbing the 20 most recent.
=> Subject mentions

app/classifier/index.cjsx, app/classifier/tutorial-button.cjsx, app/components/media-card.cjsx, app/lib/tutorial.cjsx, app/pages/admin/project-status.cjsx, app/pages/lab/project.cjsx, app/pages/lab/tutorial.cjsx, app/router.cjsx
This switches the tutorial from being baked into the project's config to being linked as a separate resource.
There's also a rudimentary editor in place. I'm working with this to figure out a good way to organize components and data with Redux in the future.
The editor can be activated in a project's admin settings.
=> Tutorial editor

css/talk.styl
=> Constrain width of images in notifications

app/talk/board.cjsx
=> Use window.prompt to confirm board deletion

app/collections/manager.cjsx, app/components/collection-search.cjsx
closes #1846 and also remove unused project_id filter and cleaned up some unsued code.
=> only update selected collections from options array

app/pages/lab/visibility.cjsx, css/color-label.styl, css/common.styl, css/main.styl
Add feature to display current approval status of a project (resolves #1516)
=> Project approval status

app/talk/comment.cjsx
=> Ensure a comment has focus when edit is clicked

app/pages/about/team-page.cjsx
It has been an absolute pleasure @chrissnyder. Thought I'd give you one last chance to use the "won't fix" label.
=> Gives Grant his proper full name

app/pages/about/team-page.cjsx
=> Update team page

app/components/image-selector.cjsx, app/pages/lab/project-details.cjsx, app/pages/settings/profile.cjsx
@aweiksnar mind giving this a shot? It works on a new account I just created, but on my usual dev account deleting my avatar _appears_ to replace it with an older avatar resource. @camallen any idea off hand why that might be happening?
Closes #1903.
=> Add clear button to user profile media

app/collections/favorites-button.cjsx
closes #1894 but is waiting on https://github.com/zooniverse/Panoptes/pull/1474
=> correct favourite filtering and collecting

app/classifier/tasks/survey/choice.cjsx, app/classifier/tasks/survey/chooser.cjsx, css/survey-task.styl
- Added lots of styles and changed some markup for the survey task that'll be used for Wildlife Watch USA (aka Snapshot Wisconsin). 
- It was mostly borrowed from what I did for Wildcam. 
- :+1:  by @jwbmartin.
=> Survey task styles

package.json, views/index.ejs
Switch `stage` script from pushing to demo.zooniverse.org/panoptes-front-end to preview.zooniverse.org/panoptes-front-end.
Heads-up to all @zooniverse/developers.
=> Stage to preview

app/partials/main-header.cjsx, css/main-header.styl, css/owned-card.styl, css/owned-list-pages.styl, css/secondary-page.styl, css/settings.styl, css/typography.styl, css/user-profile.styl
- Real-estate is getting pretty tight in the main nav. The external
links are probably not essential to always be visible, so this moves them to a
dropdown modal
=> Move external links in main nav to triggered modal

app/pages/lab/subject-set.cjsx
=> Bump subject file size limit

app/partials/main-header.cjsx
=> Add title text to globe nav icon

app/talk/discussion-new-form.cjsx
=> Remove subject default option from subject page

app/pages/project/finished-banner.cjsx, app/pages/project/index.cjsx, css/project-page.styl
This is a quick little "All done" message for projects that've run out of subjects.
Here's how you can see it locally on a production project: http://localhost:3735/projects/vrooje/galaxy-zoo-bar-lengths/classify?env=production
=> Add a banner to completed projects

app/classifier/index.cjsx, app/classifier/mock-data.coffee, app/classifier/subject-annotator.cjsx, app/classifier/tasks/crop/index.cjsx, app/classifier/tasks/drawing/index.cjsx, app/classifier/tasks/index.coffee, app/classifier/tasks/multiple.cjsx, app/classifier/tasks/single.cjsx, app/classifier/tasks/survey/index.cjsx, app/classifier/tasks/text/index.cjsx, app/lib/test-classification-quality.coffee, app/pages/lab/workflow.cjsx, css/typography.styl, package.json
When the Classifier loads a subject and workflow, it'll also check for a gold standard classifications for the pair.
When the classification is submitted, it's given a "quality" score (which is how closely it matches the gold standard). All task modules have a new `testAnnotationQuality` comparison function. These can probably use some iteration.
The summary screen either says "great job" or "keep going" (we can play with wording here) depending on the quality. The summary UI will be updated in the future, for now it allows the user to flip between their classification and the expert's.
@chrislintott Current phrasing is: "Keep at it, all classifications are useful!" and "Keep up the good work!" Is that fine for now? I don't think too many projects have gold standard data, so it'll …
=> Classification feedback

app/talk/comment-help.cjsx, css/talk.styl
Markdown help window expansion.  Closes #1517.
=> Markdown tutorial

app/classifier/index.cjsx, app/classifier/tutorial-button.cjsx
=> Move and re-label tutorial button

app/components/owned-card-list.cjsx, app/pages/projects-disciplines.cjsx, app/pages/projects.cjsx, css/owned-card.styl, css/owned-list-pages.styl
=> Add View by discipline link

app/partials/owned-card.cjsx, css/owned-card.styl
:copyright: @jwbmartin's wireframes
=> Add project card hover/reveal effect

app/pages/lab/gold-standard-importer.cjsx, app/pages/lab/workflow.cjsx
Adds a simple importer for gold standard classifications, and a toggle for optional classification feedback.
Please review after zooniverse/Panoptes#1524 is merged for the toggle to work.
=> Gold standard import

app/components/subject-viewer.cjsx
=> bugfix: listen to the correct event when video loads

app/classifier/drawing-tools/curve.cjsx, app/classifier/drawing-tools/drag-handle.cjsx, app/classifier/drawing-tools/index.coffee, app/classifier/drawing-tools/poly-curve.cjsx, app/classifier/tasks/drawing/icons.cjsx, css/drawing-tool.styl
Here is a new curve drawing tool I have been working on for one of the Portsmouth based projects (galaxy zoo 3D).
=> Adds a new drawing tool for curves

app/classifier/tasks/generic-editor.cjsx, app/lib/markdown-help.cjsx, app/pages/lab/project-details.cjsx, app/partials/markdown-help.cjsx, app/partials/project-page-editor.cjsx, app/talk/comment-box.cjsx, css/markdown-editor.styl, css/talk.styl
Add markdown table to help button within Project Builder.  Addressing full scope of #1517 and partial completion of issue #1969 .
=> add markdown help table to project builder

app/components/user-search.cjsx
- Prevents the user search box from hanging in the empty state
=> Ensure user search callback is called

app/talk/comment-link.cjsx
This is the only place I found a broken link, so I'm pretty sure this should close the issue.
=> Fixes links from comment notifications.  Closes #2004

app/subjects/comment-form.cjsx, app/talk/quick-subject-comment-form.cjsx
=> Fix params read on quick comment form

app/components/tag-search.cjsx, app/components/user-search.cjsx
onInputChange passes the input value, not an event.
Closes #2010
=> Fix broken tag select

app/talk/comment-box.cjsx, package.json
=> Reset commentbox to edit mode after submission

app/pages/admin/project-status-list.cjsx
=> Fix admin project links

app/classifier/subject-annotator.cjsx, app/components/subject-viewer.cjsx, css/subject.styl
Towards #1976
Depends on #1977
By the way, don't merge this branch until it's been updated for react 0.14
=> Add a custom play/pause button for video

app/pages/lab/workflow.cjsx
Looks like something got screwed up with workflow deletion at some point and confirmation and state/error reporting was removed. This restores it. Also entirely possible it was never in there.
Cc @DarrenMcRoy.
=> Confirm workflow deletion

app/components/subject-viewer.cjsx, css/subject.styl
Use a range slider for the scrubber.
Fix inline styles in the subject tools markup.
Fixes #2036
=> Video control fixes

.mention-bot
- Available options listed here: https://github.com/facebook/mention-bot/blob/master/CONFIG.md
- Started out with just the zooniverse org
=> Add .mention-bot config

app/partials/markdown-help.cjsx, css/markdown-editor.styl
Clean-up markdown table nesting issues.
=> Validate markdown help table nesting

app/classifier/index.cjsx
=> Disable done & talk button until classification complete

app/components/collection-search.cjsx
=> Clean up collections manager react-select

app/components/user-search.cjsx
As suggested in #2069, here's the user search manually debounced.
I was trying to store the options in the UserSearch component where they belong and pass them as `options` to the Select component (I still think this is the proper way to do it, I'm not sure why react-select wants to handle async data itself). This worked fine, except the Select lost whatever text was typed into it whenever the parent updated. To work around that I tried storing that text and passing it as a `value` into the Select's `inputProps` (again, mostly correct, in my opinion), but the Select wouldn't know to clear its placeholder. Sooo: yeah, this works!
=> Manually debounce user search

app/partials/main-header.cjsx
Closes #2057.
We could look into making this a more elegant/general thing, but then it'd probably all change in the next version of react-router anyway.
=> Fix mobile nav

css/tables.styl
=> Apply existing table styles to markdown tables

app/components/owned-card-list.cjsx, app/pages/projects.cjsx, app/partials/owned-card.cjsx
:warning: This depends on zooniverse/Panoptes#1552.  Don't merge until that's live.
=> Uses optimized /projects?homepage=true endpoint and eliminates unnecessary API calls

app/classifier/tasks/flexible-survey/choice.cjsx, app/classifier/tasks/flexible-survey/chooser.cjsx, app/classifier/tasks/flexible-survey/index.cjsx, css/survey-task.styl
These are a set of small behavior and style changes to support the flexible survey tool requested by Wisconsin Wildlife Watch. The effects of these changes should be contained to the flexible survey tool, an experimental task that lets different "choices" in the first step of a survey result in different "questions" in the second step of a survey.
1. Users of the flexible survey tool must make at least one choice before submitting a classification
2. Users must answer at least one question in order to complete an identification, even if none of the individual questions are marked as required
3. The choices should be laid out by column, not by row.
=> Flexible survey

app/classifier/index.cjsx, app/classifier/mock-data.coffee, css/classify.styl
This makes the Pulsar Hunters classifier bypass the normal gold-standard feedback display and display its own info based on the subjects' metadata `#Class` field.
I haven't actually been able to test it in the project, since I can't actually find any subjects with a #Class.
=> Hardcode stargazing feedback from subjects

app/pages/privacy-policy.cjsx
Just noticed this is outdated.
=> Update Chris's title in privacy policy

bin/run-through-docker.sh, package.json
Added docker staging scripts from #2072 (thanks @astopy).
=> Add staging scripts for Docker

app/partials/main-footer.cjsx
Also make privacy policy title case to match other links.
=> Add link to status page to footer

app/lib/tutorial.cjsx
This'll check if the tutorial has been completed during the current session instead of checking the user's preferences. Should help toward fixing #2115, which I still can't reproduce.
=> Record tutorials

app/pages/project/metadata.cjsx
=> Localise project metadata counts

app/partials/main-footer.cjsx
=> Whoops, actually hide dev classifier link in production

app/components/subject-viewer.cjsx
Add `aria-label` and `title` to unlabelled buttons.
Closes #2161
=> Add labels to subject buttons

app/pages/lab/actions/project.js, app/pages/lab/index.cjsx, app/pages/lab/landing-page.cjsx, css/lab.styl, package.json
Brand new project builder index, with consistent sort order and separate sections for owned projects and collaborations.
CC: @aliburchard
=> Lab index cleanup

app/pages/security.cjsx, app/partials/main-footer.cjsx, app/router.cjsx
cc @zooniverse/developers @zooniverse/team-zooniverse Any final comments/suggestions for this?
=> Add security page

app/router.cjsx
Welp there goes a solid half an hour.
=> Remove duplicate route

app/pages/admin.cjsx
Small change to refine view for non-admins.
=> refine view for admin page

app/pages/lab/best-practices/great-project.cjsx, app/pages/lab/best-practices/index.cjsx, app/pages/lab/best-practices/introduction.cjsx, app/pages/lab/best-practices/launch-rush.cjsx, app/pages/lab/best-practices/resources.cjsx, app/pages/lab/best-practices/the-long-haul.cjsx, app/pages/lab/index.cjsx, app/pages/lab/landing-page.cjsx, app/router.cjsx, css/best-practices-page.styl, css/landing-page.styl, css/main.styl
Currently deployed to https://preview.zooniverse.org/panoptes-front-end/best-practices/
Pending review from @jwbmartin
=> Adds the labs: best practices page

README.md
Detailed documentation of annotations.
Also some general README.md updates and cleanup.
Viewable here: https://github.com/zooniverse/Panoptes-Front-End/blob/annotation-documentation/README.md#format-of-annotation-values
For #2155
Cc: @ggdhines, @chrislintott, @srallen, @eatyourgreens
=> Annotation documentation

app/classifier/frame-annotator.cjsx, css/survey-task.styl
=> Show survey annotations above the subject image

app/pages/profile/stats.cjsx
=> Add Correct Display Name when Visiting Stats of Other User

css/secondary-page.styl
=> Add Overflow to Markdown Boxes

app/classifier/tasks/generic-editor.cjsx, app/classifier/tasks/survey/editor.cjsx
Closes #2275
Closes #2278
Also makes some conditions in generic editor a bit clearer.
CC @aliburchard
=> Add required checkboxes to text and survey tasks

app/pages/lab/workflow.cjsx
=> Ensure subject set lists are sorted by display name

app/pages/lab/project-details.cjsx, app/pages/project/finished-banner.cjsx, app/pages/project/index.cjsx, css/project-page.styl
This just adds a super basic banner for project announcements.
In the future we might integrate this with Talk/notifications/project subscriptions, but for now it's just some text stored in the project configuration.
=> Project announcements banner

app/classifier/frame-annotator.cjsx, app/classifier/warning-banner.cjsx
Just adding a little bit of DRY to the classifier.
=> WarningBanner component for subject badges

app/pages/lab/tutorial.cjsx, app/partials/project-modal-editor.cjsx, css/main.styl, css/project-modal-editor.styl, css/tutorial-editor.styl
Super minor bit of polish to the project modal editor. Possibly not even worth the trouble of rebasing, but hey, I had it lying around!
If this throws a wrench in anything you're doing, let me know and we can scrap it and I'll do a separate PR with the new lab/tutorial page content.
=> Tutorial editor style update

app/pages/lab/index.cjsx, app/pages/lab/landing-page.cjsx
=> Adds button link to project builder Talk board on lab landing page

app/components/subject-viewer.cjsx
Quick fix for #2337.
More generally, design-wise: the SubjectViewer shouldn't be aware of a workflow, that's the SubjectAnnotator's job. Might look into this in the future.
=> A workflow isn't passed into the subject viewer for talk

bin/build.sh, bin/serve.sh
So's we don't take down the site.
=> Have shell scripts exit on errors

app/classifier/tasks/survey/editor.cjsx, app/components/media-area.cjsx, app/lib/put-file.coffee, app/pages/lab/field-guide/actions.js, app/pages/lab/project-details.cjsx, app/pages/settings/profile.cjsx, app/partials/project-modal-editor.cjsx, app/partials/subject-uploader.cjsx
=> Allow headers to be specified on file uploads

app/classifier/tasks/survey/chooser.cjsx, app/pages/dev-classifier/index.cjsx, app/pages/dev-classifier/mock-data.coffee, css/survey-task.styl, package.json
This sorts items in the survey task into columns using the sort function from Serengeti (which I've pulled out into a separate module).
In the process, I've explicitly decoupled thumbnail size from column count to simplify the CSS a bit.
Cc @aliburchard
Closes #2245
Closes #2085
Closes #2024
=> Survey sort into columns

app/classifier/warning-banner.cjsx
Trying out the new syntax for stateless components in React 0.14.
=> Stateless component for WarningBanner

app/pages/admin/user-settings.cjsx
Building on what @camallen started, this fixes the UI updating and simplifies the user admin page a bit.
Also, Cam: why are all these other checkboxes disabled? Should we remove them?
Closes #2339.
=> Add upload whitelist checkbox (part 2)

app/classifier/tasks/survey/chooser.cjsx, app/pages/dev-classifier/mock-data.coffee, css/classify.styl, css/survey-task.styl
Closes #2380:
- Widens the task to 60 characters so items in Wisconsin Wildlife Watch don't wrap
- Thumbnails only appear when there are three columns
- Thumbnail aspect ratio is fixed to 1.25.
CC: @aliburchard
=> Fix survey display

app/classifier/tasks/dropdown/dropdown-dialog.cjsx, app/classifier/tasks/dropdown/dropdown-list.cjsx, app/classifier/tasks/dropdown/editor.cjsx, app/classifier/tasks/dropdown/index.cjsx, app/classifier/tasks/index.coffee, app/pages/admin/project-status.cjsx, app/pages/dev-classifier/mock-data.coffee, app/pages/lab/workflow.cjsx, css/dropdown-task.styl, css/main.styl
Issue #2128 
Post initial merge to-dos:
- styling clean-up
- CSV import
- presets
- and more!
=> dropdown task

app/classifier/tasks/survey/editor-help.cjsx, app/classifier/tasks/survey/editor.cjsx
=> Update help for choices.csv

css/project-page.styl
Reverts a change from #2374 which has broken the display of smileys in Talk.
cc. @camallen
=> Fix emoji sizes in Talk comments

css/talk.styl
=> Remove transparent background from project roles

app/classifier/tasks/survey/chooser.cjsx
Off by one!
Closes #2380 again.
=> Sync survey icons to columns

views/index.ejs
No longer necessary with new preview URLs: https://remove-base-href.pfe-preview.zooniverse.org
=> Don't set base href to DEPLOY_SUBDIR

app/components/project-card-list.cjsx, app/pages/projects.cjsx
=> Ignore launch_approved in admin mode

app/components/project-card-list.cjsx
=> Fix project page pagination

app/components/owned-card-list.cjsx, app/pages/collections.cjsx
Resets the owned card list back to master. I think this fixes the collections and favourites pages.
=> Restore master version of owned card list

app/components/collection-search.cjsx
This should fix adding subjects to collections.
=> Revert collections-search to master

app/classifier/index.cjsx, app/classifier/tasks/drawing/hide-previous-marks-toggle.cjsx, app/classifier/tasks/drawing/index.cjsx, app/classifier/tasks/drawing/markings-renderer.cjsx, app/classifier/tasks/generic-editor.cjsx, app/pages/admin/project-status.cjsx
=> Quick hide marks toggle

app/pages/lab/results.cjsx, app/pages/project/results.cjsx
Please merge with the deploy of zooniverse/Panoptes#1735.
=> Switch "Result" page to "Results"

app/pages/project/index.cjsx
My bad, this should have been part of #2395.
=> Find results page when building navigation

app/components/project-card-list.cjsx, app/pages/projects-disciplines.cjsx, app/pages/projects.cjsx, css/project-list-pages.styl
To fully address #2362 and to partially address #2423
* Remove unused duplicate message translations
* Ensure uniform colouring and styling on both nav bars
* Improve pagination message
* Make pagination conditional - if no results, or only one page, don't show buttons.
=> [project page branch] PR: Pagination fixes

app/components/project-card-list.cjsx
Set page to 1 when the sort param changes
Fixes #2372
=> [project page branch] WIP: Fix project sort issues

app/classifier/tasks/dropdown/dropdown-dialog.cjsx, app/classifier/tasks/dropdown/editor.cjsx, app/classifier/tasks/dropdown/index.cjsx
nothing major here, just a little clean-up, but please take a look and let me know if any questions. more substantial updates (CSV import, presets, etc.) will be separate pull requests.
=> cleanup variables, markdown-help, other misc

app/components/disciplines.cjsx, app/components/project-card-list.cjsx
* Disable humanitarian category for now, as short term fix for #2423 
* Only show pagination nav when it is needed (more than 1 page)
=> [project page branch] PR: Project page tweaks
