zooniverse/Panoptes-Front-End

index.coffee, package.json
Publishes auth and api/client modules as `panoptes`.
Close #80.
=> Prep for publishing to npm, export something from main

README.md, app/api/auth.coffee, app/api/client.coffee, app/lib/promise-to-set-state.coffee, app/pages/build.cjsx, app/pages/edit-project.cjsx, app/pages/new-project/review.cjsx, app/pages/project/classify.cjsx, app/pages/project/index.cjsx, app/pages/projects.cjsx, app/pages/user-profile.cjsx, app/partials/main-header.cjsx, app/partials/register-form.cjsx, app/partials/sign-in-form.cjsx, bin/build.sh, bin/serve.sh, package.json, test/auth.coffee, test/project-creation.coffee, test/runner.coffee
I made some big changes to the json-api-client lib to make it more predictable and less clumsy to work with.
The JSON-API lib no longer attempts to handle errors on its own, instead promises for failed requests are simply reject with the request. The rejected requests are no processed by the api client instance (/app/api/client) to work around the fact that different back end modules pass errors in different ways. A bad request now now consistently throws an `instanceof Error`, with a simple string `message` property (multi-line if needed) that's the best attempt at how to express the error.
These changes also lead to some refactoring of the auth module and the PromiseToSetState component mixin.
=> Update the API layer

app/api/auth.coffee, app/partials/register-form.cjsx
Include `credited_name` when registering. Closes #134.
=> Save credited_name after registration

app/api/auth.coffee
Sessions expire after two hours. This refreshes the bearer token ten seconds before that.
Closes #154.
=> Refresh bearer tokens

app/pages/edit-project.cjsx, app/pages/edit-workflow.cjsx
Clicking the new subject set button on the lab page would sometimes render an error about duplicate display names, this just removes the ones that conflict with the new lab pages, and match the corresponding workflow page to those
=> Fix displayName conflict

app/components/promise-renderer.cjsx
This makes it so that when a previously-rendered PromiseRenderer gets a new promise, it shows its old data until the promise resolves instead of blanking out.
The tradeoff is that sometimes old data is displayed for a while. I think it's worth it, but just close this if I'm wrong.
=> Don't render "pending" promise if an old value exists

app/classifier/drawing-tools/root.cjsx, app/lib/draggable.cjsx, app/main.cjsx
Just piggybacking the usual mouse events.
Tested in iOS simulator (works okay, a little sluggish), Android Chrome (works freakin' great) and Android Firefox (functional but awful, not sure what we can do about it).
Haven't tried on a real iOS device.
Closes #184.
=> Add touch events to drawing tools

app/pages/lab/subject-set.cjsx, app/partials/subject-uploader.cjsx
File types on subject creation were being looked up by file extension, but the mime type info is already part of the file object so we should just use that.
Closes #196, which was a bug in the RegExp matching the extension.
=> Get image type from the file object, not its name

app/classifier/index.cjsx
This adds behavior for the "required" property on single- and multiple-type tasks, which hadn't actually been implemented.
Closes #164.
=> Fix "required" question behavior

app/talk/home.cjsx, app/talk/init.cjsx, app/talk/lib/roles.coffee, css/talk.styl
The talk-api now expects `section` values to be formatted as project_id-project_name. This also adds permissions assignment when creating a board
=> Update board section key for api, Add roles inputs

app/classifier/drawing-tools/polygon.cjsx
The polygon tool previously allowed for open and closed shapes based on how you finished it. The UI was confusing, and that decision shouldn't be made by the user anyway, it should be made by the project creator. So now the polygon tool just makes closed polygons.
@simensta This will probably screw up the multi-point-line tool you were working on, sorry. I think I find it hard enough to extend tools like this that the hassle of setting them all up just right outweighs the benefit of sharing any drawing code. I'd just make it a standalone thing.
Closes #180.
=> Polygon tool always draws a closed shape

app/pages/lab/project-details.cjsx, app/pages/project/home.cjsx
Allow project owner to specify a single or per-workflow button-to-classify on a project's home page.
Will test when zooniverse/Panoptes#760 is deployed.
Closes #189.
=> Project owner can configure allowing user choice of workflow

app/pages/project/home.cjsx
Project descriptions are plain text, not Markdown.
Closes #233.
=> Project descriptions are plain text

app/components/retirement-rules-editor.cjsx, app/pages/lab/subject-set.cjsx, app/pages/lab/workflow.cjsx
Retirement rules now are now per-workflow instead of per-subject_set.
"Reload Cellect" button no longer needed.
Closes #246.
=> Workflow retirement rules

package.json
Fixes preventative npm warning:
npm WARN peerDependencies The peer dependency coffeeify included from panoptes will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
Also updates json-api-client to 0.2.6
=> Move coffeeify to devDependencies

app/classifier/index.cjsx, app/pages/project/classify.cjsx
The classifier can get into a state between ending one classification and starting another where the old classification's workflow is still loaded but the new classification tries to render.
This PR resets the classifier's workflow and subject when a different classification is loaded. Also removes some of my mixins to make things more explicit.
Closes #289.
=> Simplify classifier wrapper, reset state between classifications

app/classifier/index.cjsx, app/components/workflow-tasks-editor.cjsx
This
- Does a better job of cleaning out references to tasks when deleting them
- Allows the classifier work around workflows with references to deleted tasks just in case
Not entirely sure what was going on with the first one, but it should be fixed now, and the second one will make sure the classifier doesn't lock up in the event that it does happen.
Closes #289.
=> Better task removal

app/components/image-selector.cjsx, app/lib/put-file.coffee, app/pages/settings.cjsx, app/partials/account-bar.cjsx, app/partials/subject-uploader.cjsx, css/tables.styl, package.json
This adds a drag-and-drop avatar field on the user settings page. This component can be used for project avatar and background image (coming soon).
Neat stuff: it optionally auto-crops images if you give it an aspect ratio (`1` is square) and optionally scales them down until they're under a size limit (in bytes).
Also preps for other user settings (email preferences to come real soon).
Probably needs some CSS work, but so does literally everything (again, soon).
=> Add user avatars

app/pages/lab/project-details.cjsx, app/pages/project/index.cjsx
Allows adding external links to projects' navigation. Editor is barebones for now, just crammed onto the project details page.
Links without labels get a sweet icon.
=> Project links

app/collections/create-form.cjsx, app/collections/favorites-button.cjsx, app/collections/get-favorites-name.cjsx, app/collections/home.cjsx, app/collections/index.cjsx, app/collections/show.cjsx, app/components/subject-viewer.cjsx, app/main.cjsx, app/pages/project/home.cjsx, app/talk/board-preview.cjsx, app/talk/board.cjsx, app/talk/comment-image-selector.cjsx, app/talk/comment.cjsx, app/talk/discussion.cjsx, app/talk/inbox-conversation.cjsx, app/talk/inbox.cjsx, app/talk/init.cjsx, app/talk/private-message-form.cjsx, app/talk/subject-display.cjsx, css/collections.styl, css/main.styl, css/talk.styl
- Adds a favorite button 
- It takes in a single 'subject' prop and handles itself from there
- The code for this feels overly verbose / fragile. Any objections if I try bringing in flux or some other layer for components like this?
- Lets users (moderators) edit the permissions of their board via a group of radio buttons 
- Standardizes a bunch of errors to just throw the error message
- A very raw collections view (/collections or collections/:id), just a paginated list of subjects right now
- You should see a favorites collection pop up here with any added subjects
- the form here was for dev, but I'd like to build it out it for general collections use
=> Add favoriting, and start working towards collections features

app/collections/favorites-button.cjsx
Screwed up the branching here, sorry.
The sign-in prompt just needed a way to trigger that an action has been taken.
=> Allow the sign-in prompt to close

app/pages/lab/workflow.cjsx, app/pages/project/classify.cjsx, package.json
This should fix zooniverse/Panoptes#839.
The API lib was not triggering "change" on resource refreshes, which made the save button active when no changes were made.
Also makes sure the classify page doesn't store an empty list of workflows for a project.
=> Links shouldn't affect workflow state

app/partials/account-bar.cjsx, css/main-header.styl
Hey @srallen do you think this looks cool? 
It adds a quick opacity transition to the account-menu and removes the default 'loading' text of promise-renderer for that case
=> Add transition, remove load state of account menu

app/components/image-selector.cjsx, css/image-selector.styl, css/main.styl
Not a perfect solution, but it's fine for where we're using this component right now.
=> Quick fix for Firefox's handling of images in flexed containers

app/api/auth.coffee, app/pages/settings.cjsx
Allows users to change their passwords from the settings page
Closes #333.
=> Add change-password form

app/pages/lab/index.cjsx
Allows a visitor to the lab page to see all the projects they're allowed
to edit.
Closes #276
=> Use current_user_roles filter for lab pages

app/pages/project/index.cjsx
I think switching to slugs might have totally broken project loading and I somehow didn't notice.
This fixes that.
=> Make project access more explicit

app/lib/log-deployed-commit.coffee, app/main.cjsx
Here's a neat little function that'll log how far behind master the currently deployed back end is.
It uses the new `fetch` function, but no worries if it doesn't run (i.e. IE).
=> Log if the deployed back end is up to date

app/pages/project/home.cjsx, app/pages/project/index.cjsx
Projects with a `redirect` field should link to their external site instead of their classify page.
=> Replace classify links for redirected projects

app/main.cjsx, app/partials/account-bar.cjsx, app/partials/avatar.cjsx, app/subjects/index.cjsx, app/talk/board.cjsx, app/talk/breadcrumbs.cjsx, app/talk/comment-box.cjsx, app/talk/comment-image-selector.cjsx, app/talk/comment.cjsx, app/talk/discussion-new-form.cjsx, app/talk/discussion.cjsx, app/talk/inbox.cjsx, css/main.styl, css/subject.styl, css/talk.styl
- Object page
- View the subject
- Favorite Button
- Display comments mentioning that subject
- Form to start a new discussion shown if there are boards for that project and you are logged in
- Pre-filled the discussion comment with that image as the focus
- Some renaming
- Form fixes
- Setup subject mentioning selector to handle subject_id querys
- Default avatar
=> Add viewing page for subjects, other talk updates

app/api/auth.coffee, app/pages/project/classify.cjsx, app/partials/login-dialog.cjsx, app/partials/register-form.cjsx, app/partials/sign-in-prompt.cjsx
If a user registers because they were prompted to while classifying, the project is now sent along with the registration.
Cleans up the check for available display_name and email before registration.
Cc: @camallen.
Closes #372.
=> Send project_id with registration

app/partials/register-form.cjsx
Resolves React warning by removing a getDOMNode reference from the registration form. Makes the render method a pure function again.
=> Remove getDOMNode from render method

app/pages/lab/subject-set.cjsx, app/partials/subject-uploader.cjsx
Keep track of subject creation separately from file uploads. Display both numbers afterward.
Closes #485.
=> Fix post-subject-creation counts

app/pages/lab/workflow.cjsx
When a project doesn't have any subject sets, this will add a "use a demo" button the workflow's "subject sets" section that'll add an example subject set (cats!) to the project and link it to the workflow.
Closes #387.
=> Include demo subject set

app/partials/account-bar.cjsx, app/partials/avatar.cjsx, css/avatars.styl, css/talk.styl
This will keep avatar from making the same failing request over and over again when a user doesn't have an avatar set.
=> Keep the avatar component in sync with its user

app/talk/init.cjsx
- Fixes an issue with project-linker where the boards list was not
updated when changing between projects
=> Reset boards list when props are received

app/talk/comment-link.cjsx, app/talk/comment.cjsx, app/talk/discussion.cjsx, css/talk.styl
- You should be able to click the ':link: Link' button under a comment to get a route for that individual comment
- The individual comment routes distinguish the comment by giving it an 'active' class (gold background)
- TalkCommentLink component updates
- The big if/else clause in comment-link isn't my favorite piece of code, but I think it's worth isolating that project/owner params promise to project comment links
- Takes in a comment resource prop. Should be usable for the search page too!
- Closes  #374
=> Linking to single talk comments

app/main.cjsx, app/pages/project/talk.cjsx, app/talk/home.cjsx, app/talk/index.cjsx, app/talk/mixins/current-section.coffee, app/talk/search-result.cjsx, app/talk/search.cjsx, css/talk.styl, package.json, public/index.erb
- Adds basic search page. Closes #375 
- Adds `current-section` mixin for easy checking on whether you are on a project-specific or Zooniverse-wide Talk.
- Adds the `fetch` polyfill, as there are incompatibilities with the way `makeHTTPRequest` formats array params to what the Talk-Api expects.
Note `<CommentLink />` doesn't do much now, so you can't actually click through to the result, though the discussion bit is active.
=> Basic search page

app/pages/lab/subject-set.cjsx
- Added another if statement to `handleFileSelection` when Windows returns and empty string for file.type
- Fixed #479 
- When initial browser detection fails, it falls back to OS and in this case Windows uses its system registry keys. If registry key doesn't exist, it returns an empty string for file.type which is why it is failing regardless of browser in Windows. More details:
- http://stackoverflow.com/questions/1201945/how-is-mime-type-of-an-uploaded-file-determined-by-browser
- http://stackoverflow.com/questions/26149389/mime-type-missing-for-rar-and-tar
- http://stackoverflow.com/questions/11182968/determining-unknown-content-types-with-the-html5-file-api
=> Added simple file ext comparison when Windows fails to detect MIME type

app/talk/comment.cjsx
- Scrolls the window to comments if they are linked to, will be more useful as page-sizes grow
=> Scroll to comments if being linked to

app/classifier/subject-viewer.cjsx
Classifier scale depends on the image's natural size states, so this just ensures they're set in series.
Closes #230.
=> Store classifier scale in state, update on load and resize

app/api/config.coffee, app/classifier/subject-annotator.cjsx
Allow workflow name changes, use the id now. Also allow the workflow Id be configurable by the env.
@eatyourgreens - can you take a look?
=> Retina workflow by id not name

app/pages/lab/collaborators.cjsx
I think it was confusing not seeing the project owner on the Roles list
at all, so this just adds them back with all the checkboxes
disabled. This also disables the owner checkbox when creating new roles
since there can only be a single owner.
Closes #548
=> Disable owner role checkbox and add owner back

app/partials/owned-card.cjsx
Close #579.
These new "OwnedCards" seem to be conflating some pretty unrelated stuff. Why use the same component to represent projects and collections?
=> Project cards are now owned cards

app/pages/lab/subject-set.cjsx, app/pages/project/classify.cjsx
Two things trigger emptying the queue of subjects to classify:
- Sign in or out, because a user might have seen or not seen the queued-up subjects.
- Adding or removing from a subject set, because a queued-up subject might have just been removed, or a user might have seen all the existing subjects and they want to see the classification interface after they've added more.
I'm not crazy about firing off a custom event in the second case, but it works for now. Maybe the subjects-to-classify queue should be broken out into a separate module in the future.
Closes #561.
=> Empty subject queue on auth change and subject set edit

app/classifier/index.cjsx, app/components/subject-viewer.cjsx
- Renders the /dev/classifier page even though it doesn't have a project or owner
- Reduces the speed of subject frame playing
- Stops frame playing after three loops
=> Limit subject looping

app/talk/comment.cjsx, app/talk/discussion.cjsx, app/talk/lib/display-roles.cjsx
- Display user role titles under avatar in talk comments
- `Zooniverse Team`, `Researcher` & `Moderator` are the initial set per @DarrenMcRoy 
- `Researcher` is a term that umbrellas project-admins, scientists, & project-owners
- Closes #578 
- Closes #553
=> Roles in talk user display

app/main.cjsx, app/partials/io-status.cjsx, package.json
This is just a little box that pops up when there's a server connection open that tells the user how many requests the front end is waiting on. I think it'll help reduce confusion about when things are saving. I'd like to see what folks think.
Depends on a new version of the JSONAPIClient, so `npm install`.
Ran into some nasty behavior solved by the noted timeout. I'm thinking it has to do with the router, but I couldn't track it all the way down. I think the timeout is fine for now.
=> Show open connections

app/classifier/drawing-tools/polygon.cjsx, app/classifier/index.cjsx
Tools can now define a `forceComplete` function that'll run on any unfinished marks when switching tools.
Currently only applies to the polygon tool. Closes #228.
=> Force polygon completion when switching tools

app/pages/projects.cjsx
I think this is right. Projects can't be `launch_approved` without being `live`, correct?
Try `/?env=production#/projects` on a locally-running client to see this with some projects.
=> Update projects listing query

app/partials/io-status.cjsx
The IOStatus component now listens on `beforeunload` to prevent the user from leaving the page in the middle of a write and potentially losing data.
=> Prevent leaving the page while writing

app/partials/register-form.cjsx, css/buttons.styl
Makes sure it's the same as the backend's validation. Make the
error messages a little better, and make the form bet invalid when the
username is blank.
Darken the disabled button state, which is hard to see on some monitors.
Closes #631
=> Update registration form username validation

app/talk/comment.cjsx, app/talk/discussion.cjsx
This supports the use case of a collaborator needing a role, but not wanting to be publicly identified as that role -- e.g. a scientist needs moderation access, but only wants to be known as a researcher.
=> Filter talk roles by visibility

app/components/image-selector.cjsx
Image uploader no longer tries to switch formats. It should end up with more sensible images, so this closes #655. We can re-open if it doesn't help, but then the only thing we can do is reject images that's too large, which I feel like would be annoying.
=> Fix image uploaders

app/partials/subject-uploader.cjsx
- Closes #510 
- The catch block should trigger when any error in thrown during the upload process. If this happen, delete the subject from the subject set.
=> Delete subject if an error occurred in creation steps

app/pages/lab/project.cjsx, app/pages/lab/workflow.cjsx
Here's a quick hack for disabling workflow editors on live projects.
We should go back later and disable these controls for real, or replace the editor with something else.
Closes #673.
@edpaget I think this should be enforced on the back end too.
=> Disable live workflow editing

package.json
- Version update cause of #763 #765 and possibly #764
- https://github.com/zooniverse/json-api-client/issues/5
=> Lock json-api-client to v3.0.0 until fixed

package.json
JSONAPIClient _should_ be good now.
0.3.1 is unpublished, too.
=> Unlock json-api-client version

app/main.cjsx, app/pages/profile/index.cjsx, app/pages/profile/private-message.cjsx, app/partials/account-bar.cjsx, css/main-header.styl, css/owned-card.styl
- Hides feed and stats out of nav
- Pulls private message into its own component and sets it as default route
- Redirects to a user's collections if logged out
- Redirects to inbox if logged in and name param matches current user
- Fixed #797, fixed #749
=> Hide empty feed and stats pages. Redirect depending on current user

app/pages/projects.cjsx
- `project.redirect` somes back sometimes as `null`, sometimes as an empty string. This handles both those cases.
=> More durable external link checking

app/subjects/index.cjsx, app/talk/comment-link.cjsx, app/talk/comment.cjsx, app/talk/discussion.cjsx, app/talk/inbox.cjsx, app/talk/init.cjsx, app/talk/lib/get-page-of-comment.coffee, app/talk/lib/parse-section.coffee, app/talk/quick-subject-comment-form.cjsx, css/project-roles.styl, css/subject.styl
- Quick last minute hacking for #660, I tried to keep most of the terribleness to `quick-subject-comment-form.cjsx` so it can be refactored later
- Adds a form for adding subject comments to a default board - titled 'Notes', but editable
- Mods need to click a "Activate Talk Subject Comments Board" in the mod controls on a talk boards page in a project to create the default board for subject comments, since they are the only ones who can create boards
- After that there should be 2 tabs on the bottom of the object page, one to leave a comment in the subject's discussion in the default board, and one to start a new discussion
- I'll keep pushing to this branch until we deploy
=> Form for quick object comments

app/talk/board.cjsx
- It currently displays `There are currently no discussions in this board.` while loading, this makes it display the loading indicator instead of that
- Same as #668 but different page
=> Improve board loading state

css/owned-card.styl
I couldn't get it to reproduce super consistently, but this should close #752.
=> Owned cards are inline-block

app/talk/comment-preview.cjsx, package.json
...mainly in Chrome for windows. Can eventually be removed
Closes #835
=> Use twemoji to workaround emoji support issues

app/talk/inbox-conversation.cjsx
- Closes #932
- Api returns a string now, so need to convert to int now to pass validation and submit to conversation
=> Update conversation_id type

app/pages/lab/workflow.cjsx
Add a "view" link from the workflow editor to a new window.
I was adding more "view" links around the other project editor pages, but then I realized that they don't reload, so the second page will see old data. That's why there's a `reload=0` param. So for now, there's just a link from the workflow editor. It might be possible to generalize this in the future.
Closes #253.
=> View workflow

app/pages/lab/collaborators.cjsx
- Closes #920 
- I believe the root cause of this is adding additional roles to the project owner, which causes confusion as to what role should take precedence. So for the FE, I removed the row to toggle different roles on the owner.
- I also removed the owner checkbox on collaborators because it was disabled anyway.
=> Remove owner and owner role options from collaborators page

bin/config.sh
Command has a different name on OS X vs Linux
Closes #984
=> Fix md5 vs md5sum

app/pages/lab/project-details.cjsx, app/pages/lab/project.cjsx
Refreshes the project after setting an avatar or background to get the full link before re-rendering.
Get the media resource instead of just its `src` to prepare for a delete button and better feedback.
Closes #341.
=> Fix rendering of new project avatar and background

app/classifier/index.cjsx, app/classifier/subject-viewer.cjsx, app/pages/project/classify.cjsx
This adds some metadata to classifications:
- The viewport size (on classification submission) as `metadata.viewport.width` and `.height`
- Each subject frame's actual size as `metadata.subject_dimensions.(frame index).naturalWidth` and `.naturalHeight`, and displayed size as `.clientWidth` and `.clientHeight`. This is recorded after viewing the frame; if the user never actually loads a frame of a multi-`locations` image, no dimensions are recorded for it.
Closes #986.
=> Record subject dimensions

app/talk/lib/display-roles.cjsx
For #817 
Not everyone on the team needs admin rights but they should be labelled as Zoo Team on talk. We now just need to setup the zooniverse section team talk roles for everyone.
=> display zooniverse section team roles as 'Zooniverse Team'

app/main.cjsx, app/pages/profile/feed.cjsx, app/pages/profile/index.cjsx, app/pages/profile/private-message.cjsx, app/partials/account-bar.cjsx, app/talk/lib/paginator.cjsx, css/main.styl, css/profile-feed-comment-link.styl
This does a couple things, sorry:
- Restores the feed to the user profile page. It's just a list of user comments for now. In the future it could include "Created a collection" and "Added to this collection" and that type of event, I think. I think there was an issue for this but I can't find it now.
- Adds a default `onPageChange` to the paginator, which updates the hash's `?page=n` param, which I think is what we'll want 90% of the time, right?
- The "Message" link now brings up the form to send that user a message. Before it had all kinds of redirects (to inbox and collections), which was sorta confusing. If I've misunderstood something here, let me know.
=> Better user profiles

package.json
Roll back to react-select to 0.4.9.
Might reopen #528.
=> Quick fix for site not showing in Safari.

app/classifier/drawing-tools/polygon.cjsx, app/classifier/subject-viewer.cjsx, css/drawing-tool.styl
- Adds a line that follows the mouse while marking a polygon. Useful for both training new users and allowing veterans to be more precise.
- Closes #650 maybe?
Pinging @aliburchard and @mkosmala for confirmation, demo at http://demo.zooniverse.org/panoptes-front-end/polygon-hint/#/dev/classifier
=> Polygon hint line

app/components/dialog.cjsx, app/lib/alert.cjsx
Labels the close button so it's read as 'close', not 'times', by VoiceOver.
Adds the dialog role to the containing div. Should be announced by VoiceOver.
Fixes the keydown handler so that focus cannot leave the dialog when it is open.
=> a11y fixes for dialogs

app/pages/project/index.cjsx
If someone created a page but hasn't added content don't show it
Closes zooniverse/Panoptes#1100
=> Don't show empty pages on project nav

css/user-search.styl
...to hint that you can scroll for more on OSes that don't include
scrollbars
Closes #1132
=> Partially cut off final option in search fields

css/classify.styl, css/subject.styl
Limit subject width in flex container (https://bugzilla.mozilla.org/show_bug.cgi?id=1113645).
Closes #1172.
=> Fix subject scaling for Firefox

app/pages/reset-password.cjsx
Closes #1153 - stop the one time token being used multiple times and provide better user messaging around the sequence of events when resetting the password.
=> disable multi form submissions on password reset via token

app/pages/unsubscribe.cjsx
Linked to https://github.com/zooniverse/Panoptes/pull/1183
Panoptes token unsubscribe via get will redirect to front end with ?processed=true param. This will notify users that their request was received and processed. Without the query param it will display a form for email unsubscribe. This setup will allow new unsubscribe functionality and preserve existing behaviour with links in the wild.
=> report unsubscribe success on when url params exists

app/classifier/subject-viewer.cjsx
Prevents already seen flag from trigger later in the subject viewer
lifecycle
Closes #1109
=> Decide already seen flag when component mounted

app/talk/init.cjsx
This fixes a really subtle bug.  Currently, the subscription flow is
- visit #/projects/user/name
- pages/project mounts --  subscribes to project-123
- visit #/projects/user/name/talk
- talk/init mounts -- subscribes to project-123
- visit #/projects/user/name
- talk/init unmounts -- unsubscribes from project-123 even though the user is still active on the project
Basically, the talk/init component only needs to handle notification channel subscriptions when visiting the zooniverse global talk (it's the only time when the talk/init component mounts without the pages/project component).
=> Only (un)subscribe from the talk component when (un)mounting the zooniverse talk section

css/talk.styl
- Prevent opacity from compounding on nested blockquotes
-  Closes #1228
=> Improve reply legibility

css/classify.styl, css/subject.styl
I believe this fixes most complaints with the classifier layout. Subject and task always appear side by side on screens wider than 900px, and the task wraps down if necessary on smaller screens.
Closes #218, closes #1236.
=> Only wrap the classification interface on smallish screens

app/partials/main-footer.cjsx, css/main-footer.styl
- Plops `params.admin` into localStorage for retrieving.
- Also makes the admin toggle a bit more noticeable, since it's easier to leave it on now.
=> Store admin toggle state between refreshes

app/talk/comment.cjsx, app/talk/discussion.cjsx
- Closes #916
- Right now only from projects ~ #1020
- Can be seen on demo at
- `#/projects/alex-panoptes/test-proj/talk/42/51`
- `#/talk/20/82`
- I've got another branch up called `link-to-subjects-in-discussion-titles` where the links happen in titles, but I think this is a bit cleaner
=> Link to subjects when in project and set as focus

app/components/dropdown-form.cjsx, app/components/file-button.cjsx, app/components/media-area.cjsx, app/components/thumbnail.cjsx, app/pages/lab/media.cjsx, css/dropdown-form.styl, css/main.styl, css/media-area.styl
This is phase one of the survey task editor. Surveys have images, and we needed a decent way to manage 'em, so this is a generic interface for working with resources' `linked_images`.
Here it replaces the project lab's Media page.
The Thumbnail component uses our cool little thumbnail auto-generator.
The FileButton component is like a `<select type="file" />`, but it passes its value straight into `@props.onSelect` instead of storing it.
I don't think the FileDropTarget is quite square yet, but once it is we can use it to simplify a few other components.
I can see the Thumbnail component being extended in the future to support Media resources and Subjects directly. To-do for later.
=> Use a generic MediaArea component for projects

app/components/markdown.cjsx
- Closes #1269
- Prevents conflicts with hashed URLs and slugs
- Supports all of the following cases/delimiters
- `#test-tag`
- `#test_tag`
- `#test/tag`
- `http://docs.panoptes.apiary.io/#reference/user/users-collection/list-all-users`
=> Improve tag regex boundaries in markdown

app/classifier/tasks/generic-editor.cjsx
Make sure the help text for a task is refreshed when the selected task
changes since a undefined property doesn't cause React to rerender
Closes #1090
=> Return empty string if task help is blank

app/pages/lab/subject-set.cjsx
Adds 1-line description on the subject uploader page about the existence of private fields in manifest.
Closes #1327.
=> add private field info to subject uploader

app/components/dropdown-form.cjsx, css/dropdown-form.styl, package.json
Here's my stab at pulling out a mini module. https://github.com/zooniverse-ui/modal-form
Zuul and Sauce are pretty much exactly how I've always wanted to run tests. I wrote them in tape because I'm used to it, but I can switch to mocha. Anyway, they're super sloppy, and no Travis yet.
=> Break out DropdownForm into its own module

app/classifier/mock-data.coffee, css/classify.styl
Make the task area fixed width, because survey tasks show up in a three-across grid, and we can't have the width shifting around randomly between tasks.
cc: @aliburchard
=> Fix task area at 50ch

app/classifier/index.cjsx, app/classifier/subject-annotator.cjsx, app/classifier/subject-viewer.cjsx, app/components/svg-image.cjsx, app/components/svg.cjsx
Work towards zooming subject images for #278 
- renames SubjectViewer to SubjectAnnotator, to avoid confusion with the shared SubjectViewer component
- adds an SVG image for image subjects
- sizes SVG elements to scale with the subject image
- adds a crop method to crop the view box to x, y, width, height
=> Scaleable subject

css/classify.styl
For IE.
Close #1333, close #1359.
=> Set drawing tool icon width explicitly

app/classifier/index.cjsx, app/classifier/mock-data.coffee, app/classifier/subject-annotator.cjsx, app/classifier/tasks/drawing.cjsx, app/classifier/tasks/multiple.cjsx, app/classifier/tasks/single.cjsx, app/classifier/tasks/survey.cjsx
This begins a big cleanup and refactor of the classification interface. The eventual goal is for the classifier to become a dumb subject-and-workflow display with a bunch of hooks for tasks to be able to be able to inject appropriate stuff where they need it.
This PR makes each task responsible for knowing when one of its annotations is complete. In the process I added support for the `required` property for surveys and drawing tasks, and drawing details subtasks can be marked required too. None of this is exposed in the task editor yet, since the volunteer-facing interface will need some work to make it obvious that a task isn't complete unless you do _x_.
=> Delegate annotation completion check to its task

app/talk/comment-image-selector.cjsx
- Closes #1264 
- Currently only on panoptes staging I believe, so should be ok to merge on the next production deploy
=> Show recents first in talk image selector

app/talk/discussion.cjsx
- Fixes issue where if users click a comment link url it would go to
page 1 instead of the comment's page
- To test:
1. Click the link to the url of a comment
2. It should keep you on the page of the comment, instead of taking you to the first page
=> Fix comment linking issue

app/classifier/tasks/survey/chooser.cjsx, css/survey-task.styl
The survey task previously loaded its choices' thumbnails in `<img` tags, set to `display: none` when not shown. They loaded anyway, for whatever reason. It ends up being like 30MB on a 50-choice project.
This switches them to be `background-image`s with a `display: none` parent, as described [here](http://timkadlec.com/2012/04/media-query-asset-downloading-results/). so they only load when they're viewed. This also allows up to crop them to all be the same size.
Used on #/projects/brian-testing/ghosts/classify for dev.
=> Fix choice thumbnails loading, crop to the same size

app/classifier/index.cjsx
Single-type tasks were falling back to the task's `next` when the answer's `next` was empty (which should've ended the classification). It can get to that state if "multiple" is checked at some point and a task-`next` is defined there.
Closes #1429.
=> Fix finding the next task key

app/talk/popular-tags.cjsx
- Closes #1420
- Also changes tags to be block level so they display in a single column. I played around with 2 columns, but most longer tags didn't fit well without ellipsis
- Uses `id`s as keys for tags, since they're now a resource
=> Increase tags count

app/pages/lab/project-details.cjsx, app/pages/project/education.cjsx, app/pages/project/faq.cjsx, app/pages/project/home.cjsx, app/pages/project/research.cjsx, app/pages/project/results.cjsx, app/partials/project-page-editor.cjsx, app/talk/comment-box.cjsx, app/talk/comment-help.cjsx, app/talk/comment.cjsx, app/talk/discussion.cjsx, app/talk/search-result.cjsx, package.json
- Updates to correspond with markdownz@2.0.0 release
=> Markdown project prop

app/talk/discussion.cjsx, app/talk/follow-discussion.cjsx, css/talk.styl
This lets a user manage subscriptions (participating and followed) for discussions.
I'm not 100% on how we want to align this on the page though.
This is good to go for staging ~~, but not production yet~~ and production.
=> Followed discussions

css/talk.styl
- Since the comment-preview comment was removed, this updates the css
class name to correspond
=> Update comment markdown classname

app/talk/discussion.cjsx
- To prevent having to click the back button twice when navigating the
browser to single comments
=> Fix comment links Navigation function

app/pages/lab/data-dumps.cjsx, app/pages/lab/project-details.cjsx, app/pages/lab/project.cjsx, app/router.cjsx
closes #1045 - added separate page for data dumps and linked up the workflow & contents export. 
Please check i've included only the necessary requires for the data-dump page and i haven't removed too much in the project-details one.
=> add data exports page to projects

app/talk/data-export-button.cjsx
To be more explicit about how long the data request is available for.
=> Add talk data export expiration

app/pages/project/index.cjsx
closes https://github.com/zooniverse/AnnoTate/issues/179
Ensure we have correct classify links on external projects regardless of the project redirect suffix.
=> ensure clean redirects to our non pfe projects

app/pages/lab/project-details.cjsx
Unnecessary nested AutoSave element was losing its event, so it was impossible to remove external project links. cc: @aliburchard.
=> Remove nested AutoSave

app/talk/init.cjsx, app/talk/lib/project-linker.cjsx
- Fetches sidebar projects from user prefs, or falls back to launch
approved projects
- Short-term solution so that list isn't hard-coded anymore
- Wouldn't mind extra eyes on this in case I'm missing something ; dev projects are pretty different from production ones
=> Fetch sidebar projects list from user prefs

css/talk.styl
- Mimics the same behavior of github issue previews hover state
- This should accomplish the goals of #1123 without changing the design
=> Add more prominent hover state to board previews

app/components/project-icon.cjsx, app/pages/home.cjsx, app/pages/profile/stats.cjsx, app/talk/lib/paginator.cjsx, css/home-page.styl
Returning users will now see the four projects they most recently
classified on and the four featured projects instead of seeing the
explanation of the Zooniverse like they do now.
=> Slightly customize the home page for users

app/pages/lab/how-to-page.cjsx
This makes images paths on the how-to page absolute. Closes #1574.
=> Quick-fix some image paths

app/talk/active-users.cjsx, app/talk/lib/paginator.cjsx, app/talk/lib/project-linker.cjsx, css/talk.styl
- Populates the sidebar project list with any projects that are non-redirected
- Bit of work to get here on the frontend, but essentially keeps requesting/filtering until it gets 10 projects , unless it's at the last page
- Updates the ui in batches of 10
- Sidebar just holds a list of collapsible project links instead of the previous dropdown, should be less clicking this way
=> Change sidebar dropdown to links, improve request

app/main.cjsx, app/partials/account-bar.cjsx, app/partials/main-header.cjsx
Closes #1540 
Since we don't have hashchange events anymore, I'm just dispatching a fake event on route changes.
I think `new Event` and `.dispatchEvent` don't have compatibility issues, but somebody may want to double check me.
=> Synthetic replacement for hashchange events

app/main.cjsx
Changed from `Event` to `CustomEvent` object because [IE 11 doesn't support it](http://stackoverflow.com/questions/26596123/internet-explorer-9-10-11-event-constructor-doesnt-work). Since Edge is out, I'm assuming I don't need to worry about adding the polyfill for older IE browsers. Also checked Edge and it's ok there.
I have a few modern.ie VMs setup, so ping me if anyone needs me to check support for IE/Edge.
=> Change to CustomEvent for IE 11

app/talk/comment-image-selector.cjsx
Currently only recents can be linked.
It feels kind of hacky to have to specify the type on the resource, but it doesn't look like the api client is setting/exposing the type correctly.  This seems like the most straightforward way to conditionally handle it.
=> Handle both subjects and recents in comment image selector

app/classifier/tasks/crop/summary.cjsx
Whoops, moving past a crop task without cropping anything would break at the summary screen.
=> Render null crop summary

app/talk/lib/project-linker.cjsx
- The api stores some of these as `null` and some as empty strings, so
this will add Planet four and Wildebeest Watch to the list of projects
for #1596
=> Treat empty redirects as false in project list

app/subjects/index.cjsx
- Notifies volunteers earlier if there is no subject default board setup
- Since adding the steps to setup talk in the project builder too, hopefully this will be a less common case
- Closes  #1344
=> Improve empty state of subject page

app/classifier/drawing-tools/root.cjsx, app/classifier/tasks/crop/index.cjsx, app/classifier/tasks/drawing/index.cjsx, app/classifier/tasks/generic.cjsx, app/classifier/tasks/multiple.cjsx, app/classifier/tasks/single.cjsx
For #1563:
This disables the "OK" button in the drawing subtasks popup until required subtasks are complete.
It does **not** prevent the user from interacting with the page (this would make it impossible for users to modify or delete the selected mark, for example) so it's still possible to create a new mark while the current subtasks are incomplete.
I believe preventing this would require a fairly big rewrite of how drawing is handled. We can do that in the future.
Instead I've darkened the page behind the subtasks popup to discourage interaction until the "OK" button is pressed, and I've added a "this task is required" note to any required tasks.
=> Require subtasks

app/talk/board.cjsx, app/talk/discussion.cjsx, app/talk/index.cjsx, app/talk/init.cjsx, app/talk/lib/moderation.cjsx
- The moderation component does not hold the button / open-closed state anymore
- It just renders children if the supplied user is a moderator for the section
- This looks like a big diff, but is mostly markup indentation
- Closes #1556
=> Defer moderation loading until opened

app/talk/comment.cjsx, app/talk/discussion.cjsx, css/talk.styl
- Only disables action buttons in locked discussions instead of the
whole thread, so people can still follow links
- Closes https://github.com/zooniverse/scribeAPI/issues/395
=> Only disable action buttons in locked discussions

app/classifier/index.cjsx, app/pages/project/classify.cjsx
This adds a section to the classification interface below the task for expert users to change expert classification settings.
Currently gold-standard mode is the only option. A demo/throwaway mode should be coming soon.
@aliburchard: In demo mode, did you want the classifications saved with a `throwaway: true` flag, or should they not be saved at all?
=> Gold standard mode toggle

app/talk/init.cjsx, css/talk.styl, package.json
This allows boards to be ordered by most recent activity or in a static/manual order.
Closes #1665.
This is currently broken in Firefox until zooniverse-ui/drag-reorderable#1 is merged.
Also, touch support is currently missing.
=> Board positions

app/classifier/index.cjsx, app/pages/project/classify.cjsx
Admins and project owners and collaborators can now enter "demo mode", where classifications aren't actually saved.
I moved the demo mode and gold standard toggles into their own dropdown in the classification interface.
Demo mode persists across classifications (presumably presenters will want to go through a few), but there's a little warning in the interface where you can turn it off.
=> Throwaway classifications

app/api/auth.coffee, package.json
Reverts zooniverse/Panoptes-Front-End#1439
Merged too quickly. With additional testing, json-api-client is not passing errors back correctly, resulting in confusing or otherwise incorrect error messages. Try registering a user with a username thats already taken, or inputting a login and compare to live.
=> Revert "Update auth client to handle response from superagent"

app/pages/lab/subject-set.cjsx
As discussed at https://github.com/zooniverse/panoptes-subject-uploader/pull/3#issuecomment-145567220
=> Add longer `.jpeg` extension to those permitted in subject set uploader

app/pages/projects.cjsx
Adds a fallback for projects without an avatar. Noticed these went away at some point but couldn't find anything indicating why in the git history
=> Provide fallback card image

app/classifier/tasks/generic.cjsx, css/classify.styl
This hides tasks' "required" warning if they appear in subtasks for #1666. This is a hack. We eventually need a real solution than this.
=> Hide subtasks' "required" warning

app/router.cjsx, app/talk/popular-tags.cjsx, app/talk/tags.cjsx, css/talk.styl
Provides a subject search by tag.  Closes #1648
I'm linking project popular tags to this (subjects tagged with #tagname)
Non-project popular tags still link to text search.
I *think* that's probably the right thing to do.
=> Tag search

app/api/talk.coffee
- Fix for #1052, which *seems* to be due bearer-tokens syncing between clients
- I tested this out by refreshing the token every second and am consistently able to submit comments
- This is how the client was originally setup. It seems the move away from this style may have been intended to fix an unrelated problem
=> Use apiClient headers as talkClient headers

css/workflow-editor.styl
Fixed #1725 by adding max-width to column class when under edit-workflow-page class. Flex-shrink is a bit buggy in Firefox, so this may pop up elsewhere.
=> Add max-width to column under edit-workflow-page

css/talk.styl
As discussed in #1681
I reduced the avatar image size to match the height of the comment box without the toolbar buttons.
=> Reduce the height and opacity of deleted comments

css/classify.styl
I got this reversed the first time.
For #1666.
=> Switch where we show the "required" task messaging

app/talk/search.cjsx
Don't think this is causing any harm, but am doing some debugging on the search page and think that `nextQuery` doesn't need to directly assign to props
=> Assign search query to new object instead of props

app/pages/lab/project.cjsx, app/partials/account-bar.cjsx
Fixed #1125 by adding a transitionTo to the lab index page if on a lab editor page with projectID when signing out.
=> transitionTo lab index page if signed out of project builder.

app/talk/lib/display-roles.cjsx, package.json
Closes #1806 
I probably missed something here, but putting it out there anyway.
This PR does two things:
1. Remove section filtering from the roles display component. Bit worried about this part, but it doesn't look like anything was actually being filtered out?
2. Uniquely filters the given roles by whatever display name would be output.
=> Uniquely filter roles based on display name

app/pages/notifications/moderation.cjsx
This fixes a bug that is causing moderation report notifications on projects to break.
=> Pass params to moderation notifications

app/pages/notifications.cjsx
- Notifications#markAsRead only needs to be called if a user is logged
in
=> Fix notifications page when not logged in

app/collections/collaborators.cjsx, app/collections/settings.cjsx, app/lib/collection-role.coffee
closes #1812 closes #1821
turns out most collection private settings are null (will add a default in the api) and were displaying as public but weren't. modified the display here so users can decide. Also added a role check for collection settings / collab pages before render.
=> private collections

app/pages/project/metadata.cjsx
Volunteer Count isn’t looking at ip addresses. Changing to ‘registered
volunteers’ makes it a bit clearer what value is being reported
closes #1628
=> closes  #1628 - Changed volunteers to registered volunteers on project landing page

app/pages/lab/subject-set.cjsx
At the moment, uploading subjects doesn't work if you have admin mode turned on. What's happening is the regex looking for the file field in the manifest can't find a valid entry, tries to treat every field as an image location, and can't find any subjects.
This matches anything that looks like a filename with a 2-4 character extension and uses that.
Thanks to @camallen for helping me solve this one :)
=> Fix file upload regex check in admin mode

app/subjects/comment-list.cjsx, app/subjects/discussion-list.cjsx, app/subjects/index.cjsx, css/subject-page.styl
Depends on #1855 (merge that one first).
I'm also not attempting to paginate the subject discussion list.  Aside from having to dance around multiple page query params, I doubt we really care about anything but the 20 most recent discussions about a subject.  Happy to change later on if that becomes an issue.
=> Subject discussion list

app/subjects/discussion-list.cjsx
pretty sure this fixes the issue @vrooje reports [here](https://github.com/zooniverse/Panoptes-Front-End/issues/1894#issuecomment-155027541) but make sure i got this right.
> When I click from that subject page to go to the Subject Notes thread in GZ Bar Lengths, it actually takes me to the Notes thread as a Zooniverse Talk page instead of a project Talk page, and I can't favorite it at all:
=> pass props down to discussion preview component

app/pages/lab/project.cjsx
During the Zoominar today it came up that the project builder was maybe not the most intuitive looking page of our sites. I figured the least we could do was make it easy to get help.
=> Add help section to PB sidebar

css/tutorial.styl
- Added a couple of styles to the `tutorial-dialog` class: 
- `border-radius` to copy how the slide tutorial looks in older custom projects. 
- `max-width` to keep the modal from being _slightly_ larger than the tutorial slide content. The modal form was a few decimal points larger in width causing a little white border on the right side.
=> Styles for slide tutorial

app/components/collection-search.cjsx
closes #1950 - bump default collection page size and exclude fav's by default
@aweiksnar perhaps we should add a checkbox to include / exclude favs (default to exclude) as the fav button makes sense for fav collecting.
=> collection search list defaults

app/pages/project/classify.cjsx, app/pages/project/finished-banner.cjsx, app/pages/project/home.cjsx, css/project-page.styl
Let's try again.
This time I'm skipping `redirect`ed projects and projects with no active workflows, and using the proper (for now) `Link` component.
It now only appears on the landing and classify pages.
There's also a "dismiss" button that'll hide it for three days, which is arbitrary but sane, I think.
=> Return of the finished project banner

app/classifier/tasks/generic-editor.cjsx
To make editing and previewing task help text easier in the workflow editor.  Address https://github.com/zooniverse/Panoptes-Front-End/issues/1727
=> Use markdown editor for help text in the workflow editor

bin/postinstall.sh, package.json
Closes #1896. From what I can tell, in Linux `npm run-script` uses `sh` instead of the user's shell. I just pulled out the script the uses brace expansion and explicitly made it a bash script (and tweaked another one).
=> Fix Linux scripts

Dockerfile, bin/postinstall.sh
It wasn't running before because of a permissions issue (npm drops privs
by default, whereas Docker builds as root by default).
Also make sure postinstall.sh fails on errors.
**This is dependent on the [pfe-base build currently running on Docker Hub](https://hub.docker.com/r/zooniverse/pfe-base/builds/bz9x3hfdaxxbiqrx9neuufg/). Don't merge until that's finished.**
=> Allow running postinstall in docker

app/talk/latest-comment-link.cjsx
- Links to last comment/page of discussions instead of the first, mentioned in #2004
=> Add query back to latest-comment-link

app/classifier/index.cjsx, app/classifier/tasks/generic.cjsx, app/classifier/tutorial-button.cjsx, app/lib/tutorial.cjsx, css/modal-form.styl, package.json
~~To merge after zooniverse-ui/modal-form#13 and a minor version bump.~~ Ready.
This:
- Relabels the task "help" button "Need some help with this task?" and relabels the tutorial button "Show the project tutorial".
- Moves the tutorial button onto its own line. (In the future, I think people want it next to the task help button, that's more work than I can invest in this at the moment though).
- Makes the tutorial dialog `required`, which means it can't be closed by clicking off the dialog
- Adds the new standard dialog close box.
- Closes #1967.
=> Tutorial dialog and button changes

app/classifier/mock-data.coffee, app/classifier/tasks/flexible-survey/annotation-view.cjsx, app/classifier/tasks/flexible-survey/choice.cjsx, app/classifier/tasks/flexible-survey/chooser.cjsx, app/classifier/tasks/flexible-survey/editor-help.cjsx, app/classifier/tasks/flexible-survey/editor.cjsx, app/classifier/tasks/flexible-survey/index.cjsx, app/classifier/tasks/flexible-survey/summary.cjsx, app/classifier/tasks/flexible-survey/utility.coffee, app/classifier/tasks/index.coffee, app/components/workflow-tasks-editor.cjsx, app/pages/admin/project-status.cjsx, app/pages/lab/workflow.cjsx
This adds a new survey-related task to the system, "flexibleSurvey." FlexibleSurvey works like a regular survey, but adds the ability to specify which questions belong to which choices by the way that an additional field is filled out in the questions csv file.
It's of course silly to have two survey tasks, but it was considered too risky to modify the existing task directly because we have deployments who are consuming it.
I'm looking to merge this onto master tomorrow so that we can deploy it for WiscWildWatch
[sample spreadsheet](https://github.com/zooniverse/Panoptes-Front-End/files/69062/surveyTask-spreadsheets-inclHumanNnothing-multiQuestions-v2.xlsx)
=> Flexible survey

app/pages/project/classify.cjsx
Fixes #2048. @vrooje @eatyourgreens this addresses the issue in a non-hacky way, and retains the same subject (and any unfinished classification) when returning to "classify" from any other project route (research, talk, etc).
As [mentioned](https://github.com/zooniverse/Panoptes-Front-End/issues/2048#issuecomment-166705181) the fix is pretty simple: `@state.workflow` is restored in `componentDidMount` (which is called when hopping back to the classify page). Maybe this is helpful in general too.
Also addressed is @eatyourgreens concern that the Done & Talk calls `@loadAnotherSubject` without waiting for `@saveClassification`. Would have separated these but my laptop was dying and just needed to push the changes up before it went completely (writing this on other half's Windows laptop)!
=> Ensure workflow on mount

package.json
Something was complaining enough to prevent installation, react-router I think.
I believe this is because we prefix our dep versions with `~` instead of `^`, but I'm still not convinced that's wrong. I don't know, I could go either way at this point.
=> Bump history verison to allow installation

app/pages/lab/how-to-page.cjsx, app/pages/lab/media.cjsx
Removed incorrect media limit upload from help document and added what types of images are supported on the media page 
The media limit is well above 20, and I found that confusing when I checked the help documentation to see what things I had to do prepare Comet Hunters for the request for official Zooniverse approval 
I had tried previously to add a tiff and then realized after attempting to upload that it probably wasn't supported since it wasn't supported for subjects @brian-c I emulated what you did for the subject-set page, but since I don't have the set up can't test it 
@aliburchard I just deleted the line about the 20 image media upload limit .Seems like it's large enough it's not an issue and maybe doesn't need a mention there or at least temporarily would avoid the confusion I …
=> Media related help text suggested updates - closes #2012

app/classifier/index.cjsx, app/lib/session.coffee
Closes #2058, and fixes session ID lookup (looks like classifications' metadata.session was never actually set to anything).
It'd also be super cool to remove the 90KB `crypto` module too, so let me know if `Math.random()` is good enough.
=> Session storage fallback

app/components/user-search.cjsx
Using debounce with react-select gives me a component that is stuck in search
This is not ideal and just removes the debounce function since it breaks the react-select async component similar to what’s described here, https://github.com/JedWatson/react-select/issues/614#issuecomment-159513545. I think the debouncer just returns a busted promise or none-at all unless it meets the criteria to run. 
I'd be supper happy to see this one closed for a working throttle / debouncer that feeds nicely to react-select in the context of #1936.
=> fix busted user search by removing debounce function

app/pages/lab/subject-set.cjsx
Fixing a bug I ran into while trying to use the subject uploader UI as an admin. Previously, if an admin tried to upload a set of subjects with metadata that included numerical values with decimal places, the regex checking for file extensions would match this metadata as a file and error that there are missing files to upload. The updated regex checks to make sure the first character in the extension is not a digit.
=> fix subject uploader regex for admins

css/layout.styl
Fixes #1948 
I did a quick trawl through the various different pages. Apart from research, the column classes seem to be used mainly on the lab/user settings pages, and I didn't see any adverse impacts there.
=> Constrain images within columns

app/pages/about/publications-page.cjsx, app/pages/collections.cjsx, app/pages/home.cjsx, app/pages/projects.cjsx, app/talk/lib/project-linker.cjsx
Mainly cutting down on redundant API calls on `/`, `/about/publications`, and `/collections`.
`/collections` could probably use some server-side improvements.
`/projects` now uses the `cards=true` param for consistency.
@camallen If we merge this, then we can just settle on that serializer and remove the other.
=> More optimizations

app/pages/projects.cjsx
and always use the cards route for pages, even when admin.
=> only include launch approved projects by default

app/pages/admin/project-status-list.cjsx, app/pages/home.cjsx
use the sort indexes on the api, restpack supports - for desc and nothing for asc sort orders. https://github.com/RestPack/restpack_serializer#sorting
=> proper sort params for the api

app/classifier/index.cjsx, app/pages/project/classify.cjsx
This is an attempt to cut down on the number of API requests on the classify page.
Most of the requests will still end up being resent on each classification because of the relationship between the Classifier and ClassifierWrapper components (Classifier is unmounted/remounted between each classification).
Project roles and the requests for each user with a role on the project have been filtered and limited down to one request per page load.  Duplicate workflow requests have been cut down on initial page load.
Project preferences, the tutorial, 2 workflows requests, favorite collection, and favorite collection subjects will still run for each classification.  I'm hesitant to change that since everything except the tutorial could change between classifications.
I'm open to suggestions.
cc …
=> Optimize classify

app/lib/tutorial.cjsx
I believe the issue of the tutorial popping up when it'd already been seen was due to the user's project_preferences resource not existing yet. Thanks for spotting that error @srallen!
=> Create project_preferences to track tutorial completion if none exists

app/classifier/tasks/flexible-survey/chooser.cjsx, css/flex-survey-task.styl, css/main.styl, css/survey-task.styl
Unfortunately, Ali noticed that the style changes to re-order the items in the flexible survey task leaked out and affected the regular survey task. I don't know how high-priority this pull request is, but I've separated the style changes out into a separate file so as to un-break an existing project she said was having trouble with the new style.
The changes to chooser.cjsx pull new styles that reorder the flexbox; the new file flex-survey-task.styl implements those styles. The changes to main.styl pull in the new .styl file, and the changes to survey-task.styl simply revert the edits that were affecting both tasks.
=> aren't we all tired of flexible-survey yet?

app/classifier/mock-data.coffee, app/classifier/tasks/crop/index.cjsx, app/classifier/tasks/drawing/index.cjsx, app/classifier/tasks/drawing/marking-initializer.cjsx, app/classifier/tasks/generic-editor.cjsx, app/classifier/tasks/multiple.cjsx, app/classifier/tasks/single.cjsx, app/lib/draggable.cjsx, css/classify.styl
Allow setting a min and max number of marks per drawing tool.
Involved some refactoring of answer buttons and their css to show the user the right status.
Cc: @aliburchard, this'll be available when merged, no admin flag or anything. Existing projects won't be affected.
=> Min and max drawing tool marks

app/classifier/drawing-tools/circle.cjsx, app/classifier/drawing-tools/ellipse.cjsx, app/classifier/drawing-tools/line.cjsx, app/classifier/drawing-tools/point.cjsx, app/classifier/drawing-tools/poly-curve.cjsx, app/classifier/drawing-tools/polygon.cjsx, app/classifier/drawing-tools/rectangle.cjsx, app/classifier/drawing-tools/root.cjsx, app/classifier/frame-annotator.cjsx, app/classifier/index.cjsx, app/classifier/mock-data.coffee, app/classifier/tasks/crop/index.cjsx, app/classifier/tasks/drawing/index.cjsx, app/classifier/tasks/drawing/marking-initializer.cjsx, app/classifier/tasks/drawing/markings-renderer.cjsx, app/classifier/tasks/flexible-survey/index.cjsx, app/classifier/tasks/multiple.cjsx, app/classifier/tasks/single.cjsx, app/classifier/tasks/survey/index.cjsx, app/classifier/tasks/text/index.cjsx, app/components/frame-viewer.cjsx, app/components/subject-viewer.cjsx, app/lib/workflow-allows-flipbook.cjsx, app/lib/workflow-allows-separate-frames.cjsx, app/partials/main-footer.cjsx
(Changes from #2137) Tasks are now responsible for passing updated annotations up to their parent, instead of updating the annotation in place and telling the classifier that it changed.
This allows task components to be used in contexts other than as direct children of the classifier.
cc: @itsravenous
=> Tasks now pass up updated annotation through onChange

app/components/subject-viewer.cjsx
Should fix React warnings when the new side-by-side image viewer is actually used.
My bad: I completely missed this when reviewing #1965
=> Add optional keys to the frame viewer

app/classifier/tasks/drawing-task-details-editor.cjsx, app/classifier/tasks/generic-editor.cjsx, app/pages/lab/workflow.cjsx
This PR adds the text tool as an option when creating subTasks in the workflow editor. This option is only available for projects with the experimental text tool enabled.
@brian-c, @mcbouslog: thoughts?
=> text tool option for subTask

app/components/frame-viewer.cjsx
Use `offsetHeight` and `offsetWidth` when `naturalHeight` and `naturalWidth` are undefined.
Should fix the drawing surface dimensions being set to 0 for video subjects.
=> Fix SVG dimensions for videos

app/components/frame-viewer.cjsx
Closes #2135 
Uses `canPlay` rather than `canPlayThough` and sets `preload=auto` to force Firefox to download the mp4 file.
=> Fix video loading in Firefox

app/classifier/frame-annotator.cjsx, app/components/subject-viewer.cjsx
Restores badges to the annotator component. Also removes the toggle button for multi-image subjects by default.
Closes #2169 
Closes #2170
=> Restore the Already Seen and Finished badges

package.json
The last deploy was mysteriously broken (`process.env.NODE_ENV` was replaced with `"production"` like usual, but the new panoptes-client lib didn't pick it up).
The `npm test` failed, so maybe things got sorta half deployed?
This keeps the tests from failing (they've actually been moved to the panoptes-client lib).
Will investigate running dependencies' tests from the app.
=> Add notification of moved tests

app/components/frame-viewer.cjsx, app/components/subject-viewer.cjsx, css/frame-annotator.styl
When I did the multi frame stuff, I migrated the SVG-stretching styles from the component to CSS, and absentmindedly switched from `top: 0; left: 0; width: 100%; height: 100%` to `top: 0; left: 0; bottom: 0; right: 0;`. I had no idea there was any difference, but you learn something new every day.
=> Ensure SVG stretches over original subject size when cropping. Fixes #2180

app/components/subject-viewer.cjsx, css/talk.styl
Buttons aren't valid content for link elements: just style the link as a button instead.
Set a named link target so external image link only opens one new tab then reuses it.
Add aria-label since the link element has no text content.
=> Talk: External image link uses invalid HTML

app/pages/notifications/notification.cjsx, app/pages/notifications/started-discussion.cjsx, app/pages/settings/email.cjsx, app/talk/board.cjsx, app/talk/follow-board.cjsx, css/talk.styl
This allows users to subscribe to new discussions on a board.
We should coordinate deploys before merging.
This is currently staged at http://preview.zooniverse.org/panoptes-front-end/started_discussions-preference/
@srallen, would you mind taking a look?
=> Started discussions preference

app/classifier/index.cjsx
...and swap the done and done-and-talk buttons, as requested by @aliburchard.
=> Hide the back button for single task workflows

app/pages/about/team-page.cjsx, app/pages/lab/workflow.cjsx
I added subject set id number to workflow checkbox. Also noticed team members page wasn’t up to date. Updated to be consistent with
http://blog.zooniverse.org/2016/01/16/darren-dzm-new-horizons/
=> added subject set id number to workflow checkbox - closes #2182

app/pages/lab/field-guide/actions.js, app/pages/lab/field-guide/article-list.cjsx, app/pages/lab/field-guide/index.cjsx, css/field-guide-editor.styl
Fixes a bug where creating a project's field guide wouldn't actually load it until the page was reloaded. Also adds a "loading" state and cleans up some other visual bits.
For #2140
=> Load field guide after creation

app/components/field-guide.cjsx, app/pages/lab/field-guide/actions.js, app/pages/lab/field-guide/article-list.cjsx, app/pages/lab/field-guide/index.cjsx, app/pages/project/potential-field-guide.cjsx, css/field-guide-editor.styl
To merge after #2148.
This prevents existing field guides from showing up if they have no items and allows fully deleting a field guide with no items.
I'm not sure the user should have to think about the difference between having a field guide with no items  and not having a field guide at all. Might be worth revisiting in the future.
=> Better handling of empty field guides

css/lab.styl
I love the new lab screen (#2188) but one thing I noticed is that on a large screen, the edit & view buttons are a LONG way from the text they correspond to, which makes the grid a little hard to use.
I suggest a small CSS tweak like this to highlight the current line as you hover.
Deployed it at https://preview.zooniverse.org/panoptes-front-end/lab-page-tweak/?env=production (then click Build a Project)
We might also consider making the project name and icon itself clickable (left click to edit, hold down to popup a menu that offers you Edit or View) - (i'm thinking in particular of touch screen users)
=> Highlight the current line of the lab projects list on hover

app/talk/lib/paginator.cjsx
closes #2210 - do not truncate the path data when no query param is present.
=> push correct path data to history

app/components/frame-viewer.cjsx
Fixes zooniverse/Panoptes#1670. The frame wasn't being passed up to the classifier on load, which broke recording the image dimensions in the classification.
=> FrameViewer should pass frame up on load

app/pages/project/potential-field-guide.cjsx
Just stumbled across this when trying to track down a different bug
=> Don't fetch field guide images unless the guide exists

app/classifier/tasks/flexible-survey/index.cjsx
when we're initializing a new choice, it shouldn't be immediately marked as InProgress or else we'll never be allowed to complete the task
this basically completely breaks the task as nobody is ever able to complete the classification
=> fix _choiceInProgress

app/talk/discussion.cjsx
It was possible to set commentsMeta to undefined after deleting a post, which then prevents the discussion page from re-rendering.
Closes #2171
=> Fix undefined commentsMeta after deleting a comment

Dockerfile
There's finally a binary version of phantomjs, which was the only reason
we separated these before.
@brian-c I'm assuming phantomjs 2.1 is OK (we were previously using 2.0)
=> Move pfe-base back into main Dockerfile

app/pages/dev-classifier/mock-data.coffee
Quick fix for Mixed Content warnings that stop the example images from loading.
=> Fix: dev/classifier images don't load over HTTPS

app/classifier/tasks/survey/chooser.cjsx, app/classifier/tasks/survey/editor.cjsx
Choices were being created with an `image` property instead of `images`. This would break if no images were specified to override it.
Closes #2267.
=> Fix default images

app/classifier/tasks/survey/editor.cjsx
Survey editor was unable to display confused pairs.
=> Fix survey editor display of confused pairs

app/classifier/frame-annotator.cjsx, app/components/frame-viewer.cjsx, app/components/subject-viewer.cjsx, app/pages/admin/project-status.cjsx, app/pages/dev-classifier/index.cjsx, app/pages/dev-classifier/mock-data.coffee, bin/postinstall.sh, css/frame-annotator.styl, css/subject.styl, views/index.ejs
This PR address Issue #2130 by introducing a pan and zoom feature for images in the subject-viewer. An admin will need to opt-in to this feature on a project-by-project basis. 
**WIP:**
=> pan & zoom feature for images

app/classifier/drawing-tools/root.cjsx
In master, the subTask modal is render with a non-transparent underlay. This PR proposes to make that underlay transparent in order to give participants the clearest and most consistent view of a subject during a subTask. 
Example with non-transparent underlay:
Example with transparent underlay:
This PR will not change the underlay style for the "Need some help" modals.
=> transparent underlay style for subTask

app/classifier/frame-annotator.cjsx, css/subject.styl
Changes pan-and-zoom to use flexbox.
Restores `subject` class on SVG marking surface.
Fixes #2285
=> Subject viewer styling

css/frame-annotator.styl
This fixes #2285. Tested in Chrome & Firefox & Safari. Also checked Pan & Zoom tool still aligned correctly in Dev Classifier
=> Prevent images from overlapping the frame in Firefox

app/pages/admin/project-status.cjsx, app/pages/lab/mini-course.cjsx, app/pages/lab/project.cjsx, app/partials/project-modal-editor.cjsx, app/router.cjsx
In anticipation of the mini course being added, zooniverse/panoptes#1726, I've abstracted out the tutorial editor into `project-modal-editor` in partials and added it to the list of experimental features. The only thing I really changed from the original tutorial editor was adding a `type` prop. How it will look and function in a project itself will come in a separate PR.
=> Mini course editor

app/components/frame-viewer.cjsx, app/components/subject-viewer.cjsx, app/components/video-player.cjsx
Work towards #2144 
Moves the video player into its own component and tidies up the flipbook code for subjects with multiple images.
Might affect projects that use video or projects that use the flipbook slideshow for subject images, or projects that use pan-and-zoom.
=> Video player

css/classify.styl
Got notified by WWW team that the subjects in the classifier weren't displaying at all in IE. Explicitly stating the `flex` prop on the child items fixes this. Tested in Chrome, Firefox, Safari, IE 11, and iOS Safari and this doesn't seem to break anything. 
I looked in MS Edge, but it appears to have some other issues that I'll have to take a look at later.
=> Explicit flex prop on child items. Fixes subject viewer in IE 11

app/components/subject-viewer.cjsx, css/classify.styl, css/subject.styl
Fixed #2329 by feature detecting for IE11 and only applying `flex: 1 1 auto` to the subject viewer when it is IE11. Flex-grow must be set to 1 for the subject viewer to display correctly in IE11. I tried out ideas with setting max-width to the parent element or possibly setting max-width of the viewer to the naturalWidth of the subject image, but both of those didn't entirely solve the issue or had unintended consequences.
Deployed as a feature branch: https://preview.zooniverse.org/panoptes-front-end/fix-2329
@alexbfree or @eatyourgreens care to take to look to make sure I'm not inadvertently breaking something somewhere. I checked chrome, FF, IE11, safari, and iOS safari and it looked alright to me. IE11 will still possibly have the black background behind subjects with large viewports, …
=> Feature detect IE11 and only apply flex prop when detected

app/pages/collections.cjsx
The collections index was throwing if it tried to get an image from a collection with no items in it.
=> Fix empty collections throwing from their card

css/tutorial.styl
Close issue #2100 
Default left margin caused the tutorial modal to be pushed too far to the right on small screens. Increasing the top margin pushed the modal down far enough to reveal the close button.
=> Adjust Margins on Tutorial Modal

app/pages/admin/project-status-list.cjsx
Sorry for the delay, but #2280's root cause is project-status-list attempting to use a url param that doesn't exist rather than an issue with the paginator.
=> Paginate /admin/project_status via the response metadata.

app/classifier/frame-annotator.cjsx, app/components/frame-viewer.cjsx
This PR:
- scales drawn marks correctly when zooming in on a subject
- removes some unnecessary state variables, methods, and setTimeout calls.
I think the next step is to move pan & zoom into its own component, but this PR will fix the above issues in the meantime.
=> Pan Zoom Revisions: Scale drawn marks when zooming

app/classifier/drawing-tools/circle.cjsx, app/classifier/drawing-tools/delete-button.cjsx, app/classifier/drawing-tools/delete-if-out-of-bounds.coffee, app/classifier/drawing-tools/ellipse.cjsx, app/classifier/drawing-tools/line.cjsx, app/classifier/drawing-tools/point.cjsx, app/classifier/drawing-tools/poly-curve.cjsx, app/classifier/drawing-tools/polygon.cjsx, app/classifier/drawing-tools/rectangle.cjsx, app/classifier/tasks/drawing/marking-initializer.cjsx, app/lib/is-in-bounds.coffee
This adds a check after the "main" drag of each drawing tool to see if the its element's bounding box has left the bounds of the subject image. If so, its associated mark is deleted from the annotation.
The same behavior is added to the `initValid` check of the point tool, which is the only tool that can be _initialized_ out of bounds.
Closes #2125.
=> Auto delete out-of-bounds marks

css/project-page.styl
Based on https://github.com/zooniverse/Panoptes-Front-End/pull/2331, which this PR replaces
Key features:
* White background (85% opacity) and black text on all project pages
* Small padding (5px) above and below embedded images
* Change owner/collaborator to tags to be readable on white background (slight increase to padding, change colours)
I have reviewed this with all project pages on all published-to-the-homepage public project builder projects, all seem readable.
(Happy to change colours of role markers if anyone has better suggestions!)
=> "Quick fix" to improve readability

Dockerfile
because BitBucket is unreliable
=> Use local mirror of PhantomJS package

app/pages/about/publications-page.cjsx
Boyajian+15 was initially submitted to the arXiv as "Planet Hunters X", when it should have been "Planet Hunters IX" (only the ninth in the series). I also changed the link to point to the correct MNRAS version of the paper (which is open access), rather than the arXiv preprint.
=> Fix the title and numbering for recent Planet Hunters paper. 

css/project-page.styl
Following up on #2374 I found the links slightly to light. I've switched them over to the same colour as the owner tag in the sidebar.
=> Make links on the white page contents slightly darker.

css/project-page.styl
This PR darkens the color of the home-page-description text to increase readability. @jwbmartin, thoughts?
Original text color:
Proposed text color:
=> darker text color for home page description

app/classifier/tasks/survey/chooser.cjsx, css/common.styl, css/survey-task.styl
Firefox apparently [cannot display buttons as flex at all](https://bugzilla.mozilla.org/show_bug.cgi?id=984869).
Also finally found a decent solution to removing Firefox's focus ring padding from buttons.
Closes #2401.
=> Fix survey chooser buttons in Firefox

bin/postinstall.sh
Presumably the GitHub releases URL will stick around.
=> Font awesome moved

app/classifier/tasks/generic-editor.cjsx
The `<GenericTaskEditor />` editor needs to check for a `@props.project` before checking if `'hide previous marks' in @props.project.experimental_tools`, otherwise the subTask editor freezes as documented in Issue #2422.
=> resolves frozen subTask editor - fixes #2422

app/talk/lib/paginator.cjsx, app/talk/lib/update-query-params.cjsx, app/talk/recents.cjsx
Extracts/refactors query param updating used by the paginator.
Also refactors the paginator to accept a key param to allow paginating multiple resources on the same page.
Closes #1869.
=> Persist recent subject notes toggle

app/components/project-card-list.cjsx, app/pages/projects.cjsx
Resets the page to 1 when discipline changes.
Resets the discipline filter for All Disciplines.
Fixes #2419
Fixes #2372
=> Fix projects page filters

app/components/project-card-list.cjsx
In light of emerging consensus on #2424, set sort order to launch date for now. Will leave ticket open in case we change it.
=> Change default sort order to launch date.

app/components/disciplines.cjsx
... so that it encompasses "Planetary Science" too. Per @mschwamb's suggestion in https://github.com/zooniverse/Panoptes-Front-End/issues/2373 - @mrniaboc and I both agreed it is a good idea - and Space is what it used to be called on old Zoo home.
=> [project page branch] Rename "Astronomy" category to "Space"

css/owned-card.styl, css/owned-list-pages.styl
@alexbfree commented that these files possibly shouldn't be changed by the project page PR.
Do we have different styles now for project cards and owned cards?
=> Revert owned card styles to master

app/pages/lab/index.cjsx, css/lab.styl
In the labs project index, the whole row is now clickable. I know this was driving you nuts, @alexbfree. Me too!
Also converted it to BEM-style CSS, which makes nice CSS but ugly HTML.
=> Labs project list: make the whole list item clickable

app/pages/lab/workflow-viewer/workflow.cjsx
This fixes https://github.com/zooniverse/Panoptes-Front-End/issues/2356
The issue was caused by the `next` key being and empty string on a task, it is only an empty string if the user initially sets it the `next` value for a task/answer and later changes it back to `(end of workflow)` in the workflow editor.
=> fixes 2356

app/components/filmstrip.cjsx, css/filmstrip.styl
Tidy up the filmstrip component.
Remove absolute positioning and animated transition from filmstrip CSS.
Fixes #2433 but adds horizontal scrollbars to the filmstrip.
=> Scroll the filmstrip by animating scrollLeft

css/disciplines-slider.styl
Removes flex from the list.
Displays the list items as inline blocks.
Uses line-height hack to centre buttons vertically.
=> Fix overlapping filmstrip list items in Safari

app/pages/profile/comment-link.cjsx, app/talk/moderation/actions.cjsx, app/talk/moderation/comment.cjsx, app/talk/moderation/reports.cjsx, app/talk/moderations.cjsx, css/moderations.styl
This closes #2166 and also closes #2167.
I also tried to cleanup code sprawl by extracting components to isolate state.
The change to pages/profile/comment-link are to prevent linking to deleted boards or discussions as mentioned in #2167.
Feedback welcome.
=> Fix issues with talk moderations

app/components/project-card-list.cjsx
Fixed #2470. The issue is that the `project.redirect` prop is a an empty string in the production db whereas it's null in dev. I've fixed the conditional to check for both. This will fix search result redirects for projects that do not have an external redirect set.
Branch can be viewed here: https://fix-project-page-search.pfe-preview.zooniverse.org/projects
=> Fix conditional for redirect

app/classifier/index.cjsx, app/pages/project/classify.cjsx, app/pages/project/index.cjsx, app/partials/app.cjsx, package.json
user, project, workflow, and subject are now exposed to the context by the PanoptesApp object; the child components that are responsible for them use callbacks (also exposed on the context) to keep these values in sync
this means that anywhere in the application can inspect these values by adding
contextTypes:
user: React.PropTypes.object
and then looking at the value @context.user
this way all of these things will be available for all of our logging.
=> setting up context

app/components/subject-viewer.cjsx
Checks `workflow.configuration.disable_favorites` and renders the Fav button only if the value isn't `true`
=> render favorites button unless workflow configuration states otherwise

views/index.ejs
@alexbfree Adds some default open graph tags so sharing links on FB is slightly richer. 
Ref #2107
=> Add default OG tags

package.json
This'll fail hard when trying to use incompatible Node versions.
=> Check engines before starting dev server or building

app/classifier/index.cjsx, app/classifier/tasks/combo/index.cjsx, app/classifier/tasks/drawing/index.cjsx, app/classifier/tasks/multiple.cjsx, app/classifier/tasks/single.cjsx, app/classifier/tasks/text/index.cjsx, css/classify.styl
This PR:
-  places a unique name on each drawing tool input, so that a user can tab through the drawing tools 
- cleaned up some of the autoFocus evaluations on other tools. 
- adds autoFocus to the Next button of the Classification Summary
=> name each drawing input

app/pages/project/classify.cjsx
For #2491
Still to come: dealing with malformed classifications in the queue.
=> Don't access local state when queueing classifications

app/classifier/world_wide_telescope.cjsx
Image rotation was adjusted to align with Worldwide Telescope. We may need to change this later if they update their API. The render method was also changed so the paragraph line only appears if a valid chart with link appears, and the link now opens in a tab.
=> Adjust Rotation for WWT

package.json
I thought it would be useful if when you run `npm run stage-branch`, it shows you the URL where it has been deployed to (to save you typing it).
Example output:
```
...
Finished in 10.78 seconds
Deployed to http://yourbranch.pfe-preview.zooniverse.org/
```
=> Add some output to show correct deployment path

package.json
⚠️ Depends on zooniverse/markdownz#37 being merged and deployed. ⚠️
=> Update markdownz to 4.1.2

app/collections/manager-icon.cjsx, css/dialog.styl
Extending #2522, this switches to modal-form Dialog component to allow the collections dropdown to extend beyond the dialog bounds.
Closes #2522, which closes #2056.
=> Allow collections manager dialog overflow

app/main.cjsx
Apparently assigning the window object the require directly was throwing a `zooAPI is undefined` error in the console.
=> Set window object to variable

css/classify.styl
Fix from @itsravenous. Follows on from #2535. Vertically centers the svg rectangle not just the text.
(the 1.5em matches the height of the svg el within so this should work on all projects regardless of image height and label height)
=> Update tool label styling

app/pages/admin/project-status.cjsx, css/admin-page.styl, css/main.styl
Adds an `admin-page` stylus file with a few styles for the project status admin page and some better markup. Started to use BEM here too. The experimental feature list is getting unwieldily; this makes it a bit more pleasant to look at.
=> A more pleasant project-status admin page

app/pages/project/index.cjsx, app/router.cjsx
Just realized this branch is totally named wrong, sorry. This is a refactor of the root project page. It removes any `ChangeListener` and `PromiseRenderer` components and makes accessing resources more explicit.
Also set up a redirect for /projects/owner/name**/home** back to /projects/owner/name, so there's only a single URL per page. Feels kinda hacky but I just could not get react-router to behave.
Just FYI @srallen, this is in preparation for my change for storing the last selected workflow as a state on the project root page.
=> Big cleanup of the root project page

app/classifier/tasks/drawing/summary.cjsx, package.json
Fixes https://github.com/zooniverse/Panoptes-Front-End/issues/2536 and improves classification summary for drawing tasks.
=> Remove any markdown from tool labels when summarising classification

app/collections/favorites-button.cjsx, app/collections/manager-icon.cjsx, app/components/subject-viewer.cjsx, app/pages/dev-classifier/index.cjsx, app/pages/project/classify.cjsx, css/classify.styl
This removes the "You should sign in" pop-up between _n_ classifications and replaces it with a button under the subject. When the subject changes, the button jiggles tantalizingly for a couple seconds.
Right?
In the process, I cleaned up the look of all the under-subject buttons by removing default system style and fixing icon widths.
Also removed a `willReceiveProps` method in the SubjectViewer that was broken and never called anyway. Probably a typo (it would've been `componentWillReceiveProps`).
=> Less obnoxious sign-in suggestion

app/classifier/tasks/multiple.cjsx, app/classifier/tasks/single.cjsx
This PR address Issue #2563 by removing the autoFocus attribute from the `<SingleChoiceTask />` and the `<MultipleChoiceTask />`.
Examples:
- [Sample workflows with multiple task types](https://limit-autofocus-fix-2563.pfe-preview.zooniverse.org/projects/markb-panoptes/focus-testing-project)
The 'Next' button,  not the 'Talk' button, is still focused at the end of the classification. Does that also need to be changed?
CC: @eatyourgreens, @alexbfree, @aliburchard, @mschwamb
=> removes autoFocus on first answer for single and multiple answer tasks

app/pages/lab/subject-set.cjsx
Important note: this issue and solution applies to non-Admin users on PFE, please disable Admin access when testing.
The NfN team had an issue while trying to upload a manifest file that included the following metadata:
`http://bisque.iplantcollaborative.org/image_service/image/00-uCGZDUoynWLhtoRqMKanoQ?resize=4000&format=jpeg`.
The subject uploader within Project Builder wanted to interpret `00-7Uj9yBZYiBPzSstLjMTpo7?resize=4000&format=jpeg` as a filename.
So on inspection of the related code it appears our intent of filtering certain extensions (line 18, VAR_SUBJECT_EXTENSIONS) or characters (line 19, INVALID_FILENAME_CHARS) wasn't behaving as intended, or more specifically once the filters made their way to the regex on lines 277 and 278 they weren't being interpreted literally, so …
=> Subject uploader regex update

app/classifier/index.cjsx, app/classifier/mini-course-button.cjsx, app/classifier/tutorial-button.cjsx, app/components/step-through.cjsx, app/lib/mini-course.cjsx, app/lib/tutorial.cjsx, app/pages/lab/mini-course.cjsx, app/pages/lab/tutorial.cjsx, app/pages/lab/workflow.cjsx, app/pages/project/classify.cjsx, app/partials/project-modal-editor.cjsx, css/main.styl, css/mini-course-dialog.styl, css/project-modal-editor.styl, css/tutorial.styl, css/workflow-editor.styl
Apologies for the size of this PR. This superceded #2399 and brings in the workflow tutorial functionality as well as mini-courses
- Mini-course pops up every X number of classifications and uses similar logic to the old sign-in prompt on the `classify` project page. Currently the mini-course pops up every 2 classifications until it is complete for easy testing.
- Mini-course has its own view in `lib` with it logic to track the which slide to start on, whether or not someone has opted out, and when the mini-course is completed. Sometime in the future, some logic may be added to have the mini-course pop up to non-signed-in users, but that was punted for later. This is why there are many `if user?` type checks
- Project builders can create multiple tutorials or mini-courses if those have …
=> Mini-course and workflow tutorials

app/pages/project/home.cjsx, app/pages/project/index.cjsx
~~WIP for~~ Closes #2565.
The user's workflow selection from the project landing page is now stored in their project preferences and passed into the "Classify" link in the project nav. Not-signed-in users get a temporary project preferences resource that's thrown out when they switch projects or reload the page.
~~I want to play with it a little more, but~~ I think this is just about ready. Any thoughts @mrniaboc? @srallen, is this something you can work with for #2534?
=> Store workflow in prefs

app/talk/comment-box.cjsx, app/talk/lib/get-caret-position.cjsx, app/talk/suggester.cjsx, css/talk.styl
This closes #1884
Usernames are autocompleted by login or display name with priority based on
1. Frequently mentioned users
2. Frequently messaged users
3. Group names (e.g. moderator, researcher, admin)
4. All users
By default it will show top results from priorities 1 - 3.
Tags are autocompleted by name (trigram fuzzy searching) with priority based on
1. Similar suggested tags
- Separate PR ~~in the works~~  in #2582 for managing suggested tags.
2. Similarity scaled by the number of unique user usages
By default it will show the suggested tags.
The changes to comment-box are just wrapping the component in a relatively positioned container and adding the suggester.  [Cleaner diff here](https://github.com/zooniverse/Panoptes-Front-End/pull/2580/files?w=0#diff-3a7c3905094f87ae89efe812119705 …
=> Adds username and tag autocompletion to talk

app/components/workflow-toggle.cjsx, app/pages/admin/project-status.cjsx, app/pages/lab/project.cjsx, app/pages/lab/visibility.cjsx, app/pages/lab/workflow-create-form.cjsx, app/pages/lab/workflow.cjsx
1) adds same workflow active/inactive management currently in admin settings of a project to Visibility section within Project Builder
2) allows editing of inactive workflows
3) allows creation or copying (within project) of new workflows, which are set as active if project in development (current setup) or inactive if project live.
a new workflow active status is set within the workflow-create-form.cjsx. i believe it's duplicative to set the workflowActiveStatus prop's default to false ([line 12](https://github.com/mcbouslog/Panoptes-Front-End/blob/467d8c28c147b39587febd6bd7bae5c8eef24ca7/app/pages/lab/workflow-create-form.cjsx#L12)) and set the active property to false if the prop is undefined ([line 39](https://github.com/mcbouslog/Panoptes-Front-End/blob/467d8c28c147b39587febd6bd7bae5c …
=> manage, edit and create workflows in Project Builder rgdless if project live

app/talk/active-users.cjsx, app/talk/popular-tags.cjsx
As mentioned in #2580.  Fixes duplicate key errors in popular tags and traps the oddly intermittent bug in `ActiveUsers#userIdsOnPage`
=> Cleans up errors in Talk

app/subjects/comment-list.cjsx, app/talk/comment.cjsx
This is something of a temporary fix.  If subjects are actually used from multiple project contexts, this becomes a bit funky unless we maintain the project path in the route.
This fixes #2366.  It triages some of #2253.
=> Add project context to subject page comments

app/classifier/index.cjsx, app/classifier/mini-course-button.cjsx, app/classifier/tutorial-button.cjsx, app/lib/mini-course.cjsx, app/lib/tutorial.cjsx, app/pages/lab/tutorial.cjsx
Now that workflow tutorials are in production and Marten reran the rake task yesterday to link all of the pre-existing tutorials, we can now remove the fallback call to fetch tutorials by project id only. This prevents the possible scenario of a project builder creating two tutorials, but since they are unlinked to a workflow, we don't know which they intended to have pop up. The call to fetch by project id will just fetch the first one in the response array. I also bolded the instructions on the editor to go to the workflow editor for linking.
=> Only fetch workflow tutorials

app/pages/project/stats/charts.cjsx, css/project-stats-page.styl
Closes https://github.com/zooniverse/Panoptes-Front-End/issues/2587
Adds on-focus and on-hover labels to the bar charts on the stats page.  The labels are displayed along the top to make sure no bars are drawn over the top of them.
@eatyourgreens if you have time could you take a look at this.
=> add hover and focus labels for bar graphs

app/talk/lib/get-caret-position.cjsx, app/talk/suggester.cjsx
`document.querySelector` was breaking in cases where textarea-mimic-div ids contained non alphanumeric characters.  One of these cases was triggered by editing a comment.
This closes #2618
=> Fix comment editing

app/classifier/tasks/drawing-task-details-editor.cjsx, app/classifier/tasks/text/editor.cjsx, app/classifier/tasks/text/index.cjsx, css/main.styl, css/text-task.styl
Fixes Issue #2576. 
This PR introduces text tagging functionality for transcriptions, similar to the text tagging feature in [AnnoTate](https://anno.tate.org.uk/#/). Find the staging branch with sample workflow [here](https://transcription-metadata-tags.pfe-preview.zooniverse.org/projects/markb-panoptes/focus-testing-project/classify?workflow=2359).
A volunteer should be able to 1) highlight a portion of their transcription, 2) click the input associated with the desired tag, which surrounds the selection text with the metadata tag.
In the project builder, any project with access to the text tool has access to the three metadata tags. In a future iteration, the project builders will be able to create there own tags, instead of choosing between "Insertion", "Deletion", and "Unclear". The …
=> Transcription Metadata Tags

app/pages/lab/workflow.cjsx
Part of completing #2534 and building on top of #2572, this allows project builders to set a default workflow on the workflow edit page. I also fixed a bug I found where the state of the checkbox of the new default workflow input as well as the hide classification summaries input did not clear when switching between different workflow edit pages.
@brian-c feel free to punt to someone else if you're busy.
=> Default workflow feature

app/classifier/tasks/dropdown/dropdown-dialog.cjsx, app/classifier/tasks/dropdown/index.cjsx
fixes the following issues:
1. in editor dialog - options for upstream conditional answers not showing labels
2. showing task title and dropdown label when the same
3. improperly keeping conditional dropdown disabled when custom answer provided and allow create enabled
4. adding placeholder text for when dropdown is purposefully disabled
closes #2544
=> dropdown bug fixes

app/talk/lib/project-linker.cjsx
Simplifies the project listing in talk by using the talk resource instead of Panoptes.
Panoptes doesn't differentiate between projects with off-site urls and projects without .org talk (e.g. Ouroboros projects).
The Talk endpoint only lists projects that are launched and have Talk setup.
This closes #2138
=> Use the talk-api projects resource for talk project links

app/classifier/index.cjsx, css/classify.styl
Fixes Issue #2611. This PR warns users that pressing the back button deletes the annotations for the current task. The warning will only show when a user hovers over or focuses the back button. See it in action [here](https://back-button-warning.pfe-preview.zooniverse.org/).
@mrniaboc, @aliburchard: If merged, this PR will introduce a slight change to the classify interface. What messaging would need to happen for the project builder? Also, opinions about copy?
=> warning onFocus or hover for task back button

app/components/frame-viewer.cjsx
add Firefox +/- keyCodes, dynamically increase pan-able area.
will revisit how panEnable toggles off, trackpad pinching and cross-browser issues in different pull requests.
sorry, still looks like more edits than actually made, per Brian's previous comment:  add `?w=0` to the URL of the diff on GitHub and it'll ignore whitespace.
[branch staged here](http://pan-zoom-edits.pfe-preview.zooniverse.org/).
=> pan and zoom update

package.json
Bump to modal-form 2.4.0, which takes overflow into account when determining target dimensions.
=> Bump modal-form

css/buttons.styl, css/project-page.styl
This PR extends the styling for :hover to :focus for buttons specified in `buttons.styl`. Related to, but not dependent on PR #2621.
=> Focus Style for Main Buttons

app/components/frame-viewer.cjsx
addresses focus and when pan-able, keeping the following use cases in mind:
1. keyboard only - tab to pan & zoom controls to pan or zoom (or attempt to >:( on Safari) then tab away. once tabbed away from pan & zoom controls pan-able should be disabled.
2. mouse with drag and wheel - click cross-arrows so can pan & zoom, drag label to center, mousewheel to zoom in, maybe drag a bit more to re-center. once clicked away from pan & zoom controls pan-able should be disabled.
3. mouse with drag and click +/- buttons - click cross-arrows so can pan & zoom, drag label to center, click + button to zoom in (either hold down or click multiple times), maybe drag a bit more to re-center. once clicked away from pan & zoom controls pan-able should be disabled.
[branch staged …
=> update focus and when image pan-able

app/pages/project/stats/charts.cjsx
This just removes a workaround that is no longer needed since the move to webpack.
=> remove browserfy workaround from stats page now that webpack is used

app/pages/lab/workflow-viewer/workflow.cjsx
Fixes https://github.com/zooniverse/Panoptes-Front-End/issues/2632
The code now checks that a drawing tool's `details` exist before looping over it.
=> check drawing tool details exist before looping over it

.babelrc, dev-server.js, package.json, webpack.dev.js
Yay, a contentious PR!
Since it's really just down to developer preference, this allows hot-reloading to be optionally enabled.
`npm start` to serve without it and `npm run start-dev` to serve with it.  Happy to flip those around or rename based on preference.
cc/d everybody assigned from #2656.
=> Makes hot-reload optional

app/pages/lab/project.cjsx
Allow admins access to project builder on all projects.
Deployed to https://allow-admins-into-project-builder-on-all-projects.pfe-preview.zooniverse.org/ for testing. Add the production environment parameter to test on production projects.
To test, go into admin mode, then add a project ID to the end of 
`https://allow-admins-into-project-builder-on-all-projects.pfe-preview.zooniverse.org/lab/`
Usecases and background in https://github.com/zooniverse/rfc/issues/4
=> Fixes #1780

app/components/owned-card-list.cjsx, app/components/project-card-list.cjsx, app/partials/owned-card.cjsx, css/owned-card.styl
When project cards and owned cards were separated, the CSS was not cleanly split and still shared the same CSS class. Possibly because of this, or for another reason, owned cards are wrongly stretched vertically to 175px. This change separates out the CSS classes to avoid accidental collisions like this in future, and stops the 175px height from applying to owned cards
Also adding some space below collection titles as the text was too close to the button.
Changes owned cards from this
to this
=> Clean up display of owned cards (collections, favourites etc)

app/pages/project/stats/index.cjsx
Adds the message "Project statistics are currently unavalible and we are working to fix the issue" as the stats page while the stats server is being fixed.
=> add holding page while stats server is being fixed

app/lib/get-workflows-in-order.coffee, app/pages/lab/project.cjsx, app/pages/project/home.cjsx, css/nav-list.styl
Allows setting workflow order in the project builder and displays workflows in that order on the project home page.
@camallen I'm storing this order on the project configuration. There's no way to store it in the project's workflow links, correct?
Closes #2510.
=> Allow workflow reordering

app/classifier/tasks/text/index.cjsx
update text task textarea element, row attribute, based on content typed (specifically by comparing scrollHeight to offsetHeight).
staging site here:  https://text-task-auto-height.pfe-preview.zooniverse.org.
in Firefox the textarea will only increase up to 5 rows, while other browsers (Chrome, Safari, in process of testing on Edge) will increase indefinitely.
please let me know what you think, thanks!
=> Dynamically increase text task textarea height

app/partials/project-modal-editor.cjsx, css/project-modal-editor.styl
Closes #2629. This adds `drag-reorderable` to the project modal editor that handles the tutorial and mini-course editing interface. This also makes the UI a bit more consistent with the field guide editor. 
Staged at https://reorder-tutorial-slides.pfe-preview.zooniverse.org/
=> Reorder tutorial slides

app/components/subject-viewer.cjsx, app/pages/dev-classifier/mock-data.coffee, css/classify.styl, css/subject.styl
This replaces the IE-specific `flex: 1 1 auto` on the SubjectViewer with `flex: 0 1 auto` for all browsers. That means the element will try to be as wide as it needs to display its content (`flex-basis: auto`, shrink if there's not enough room (`flex-shrink: 1`), and (this is the change) not grow any larger than it needs (`flex-grow: 0`), which means the black bars from #2329 won't be a problem. I also removed the potential for black bars in grid view.
I've put some a few various image sizes and proportions in the dev classifier mock data to demo what each of them looks like.
Also includes a button style fix that's been buggin' me.
=> More appropriate subject image flex rules

app/classifier/tasks/dropdown/index.cjsx
fixes issue where if dropdown set as required, selection made, but then cleared, volunteer allowed to proceed even though they shouldn't be without providing answer to required dropdown
- [staged branch](https://dropdown-req-clear-fix.pfe-preview.zooniverse.org/)
- [project on staging for testing](https://pfe-preview.zooniverse.org/projects/markb-panoptes/nfn-testing) - Single Dropdown Required Workflow, Single Dropdown NOT Required Workflow or Dropdown Workflow (only country required) to help test
=> fix bug req dropdown cleared allow proceed

app/classifier/index.cjsx, app/pages/project/classify.cjsx, css/classify.styl
This PR creates a classifier layout that supports larger (i.e., not-height-contained) subject images and a smaller task area. This version of the classifier layout is engaged when `workflow.configuration.image_layout` contains `'no-max-height'`.
In addition, I made some adjustments to the scroll behavior for the classifier component. Instead of scrolling to the middle of the subject image, the page scrolls to just above the classifier component.
Check out the staged version with an example workflow [here](https://wrkflw-config-for-large-image-format.pfe-preview.zooniverse.org/projects/markb-panoptes/focus-testing-project/classify?reload=0&workflow=2359).
=> workflow config for large image layout

app/classifier/tasks/text/index.cjsx
fixes issue with back to back text tasks (including within combo) where if first text task resized, second text task inherits resized height instead of reseting to default height.
- [staged branch](https://text-task-autoheight-fix.pfe-preview.zooniverse.org/)
- [project on staging for testing](https://pfe-preview.zooniverse.org/projects/markb-panoptes/nfn-testing) - Text Workflow to help test
=> fix text task autoheight reset

app/components/frame-viewer.cjsx
This makes it consistent with Google Maps and Photoshop (and probably most of the world).
=> Scrolling up on the mouse wheel should zoom in

app/partials/display-name-slug-editor.cjsx
Fixes #2720 by using `window.location.origin` instead of `document.baseURI.slice(0, -1)` to build url link to project.
=> Use window.location.origin on project details page

app/partials/account-bar.cjsx, app/partials/main-header.cjsx
Looks like a rough merge left some components with a multiple `contextTypes` defined (and the last defined wins).
Ran [`grep -o -c contextTypes ./app/**/*.* | awk -F: '{if ($2 > 1){print $1}}'`](http://stackoverflow.com/questions/23961056/grep-files-containing-two-or-more-occurrence-of-a-specific-string) to find all cases.
Gonna merge myself real quick, but CC: @srallen.
=> Fix components with multiple contextTypes defined

css/field-guide.styl
Fixes #2724, _Field Guide tab transparent in IE11_.
=> add explicit background color for field guide tab

app/components/subject-viewer.cjsx, app/partials/sign-in-prompt.cjsx
This is pretty gross because `alert` from modal-form/dialog doesn't provide a way to close things (since it expects a form, which was a pretty fundamental design mistake). Gonna have a think about a better way to alert things.
Closes #2722.
=> Convert SubjectViewer dialogs to modal-form/dialog

app/components/pass-context.cjsx, app/layout/account-bar.jsx, app/layout/admin-toggle.jsx, app/layout/index.jsx, app/layout/site-footer.jsx, app/layout/site-nav.jsx, app/partials/app.cjsx
- Render while the initial load is happening. Show a spinner in place of the login/account area.
- Update layout-level components to use the app context's `user`.
=> Render while initial-loading

app/lib/geordi-logger.coffee, app/partials/app.cjsx
Fixes part of #2742 . `@state.env` wasn't being set correctly in PFE when `NODE_ENV` is set at the shell.
=> Correctly get shell environment

app/classifier/tasks/dropdown/dropdown-dialog.cjsx, app/classifier/tasks/dropdown/editor-help.cjsx, css/dropdown-task.styl
Closes #2385 
[Staged branch here](https://dropdown-handle-lists.pfe-preview.zooniverse.org/).
Adds:
1. Ability to copy and paste a list of option labels into textarea option add input. Will work from file types CSV, TXT, and XLS.
2. Disabling of option add input and button if Options For not selected.
=> dropdown - add list of options, disable if conditions not selected

app/partials/app.cjsx
Possible bug fix for reported issue here: https://www.zooniverse.org/projects/adrianevans/fossil-finder/talk/49/63272?page=1
This instantiates the Geordi client in `componentWillMount` and updates it on auth change.
Also removed the extraneous `updateUser`
=> Ensure geordiLogger is set before mount

app/classifier/tasks/dropdown/index.cjsx
update dropdown task to match only at start of option label when filtering, not any character in option label.
typing “N” in a list of states will filter to Nevada, Nebraska, New Hampshire..., instead of the current setup where it would search the entire label and filter to Arizona, Arkansas, California...
replaces pull request #2756
=> update dropdown search match only at start

package.json
This'll just prevent us from serving/deploying with bad dependencies, like it does with bad node or npm versions.
=> Fail if dependencies aren't installed

app/lib/geordi-logger.coffee, app/partials/app.cjsx
Update the stored user ID for Geordi logging without overwriting any existing stored data, such as the project token or subject ID.
=> Update Geordi user on login/logout

app/components/classifications-ribbon.cjsx, app/pages/profile/stats.cjsx
The stats ribbon will now ignore projects with no classifications.
Closes #2777.
=> Ribbon skips projects with no classifications

app/components/subject-viewer.cjsx, package.json
This just makes showing the sign-in prompt a state of the subject viewer, removing the weird CustomEvent hack that apparently didn't work in Firefox.
Closes #2763.
=> Fix hacky sign-in prompt dialog

css/subject.styl
Creates a new stacking context for video player controls with `position: relative`.
Should ensure that the slider control for scrubbing a video can be clicked with a mouse.
=> Stack video play controls above other elements

app/layout/index.jsx, app/pages/project/index.cjsx
If there's no user when the project page mounts, the site header is revealed.
👍'd by @jwbmartin. Closes #2748, closes #2733.
I've also tweaked the project-not-found message, so this closes #1792.
=> Initially reveal the site header on the project page when not signed in

app/layout/site-nav.jsx
Noticed this while looking over #2788. This should probably be `removeEventListener` on component unmount.
=> removeEventListener on unmount

app/pages/project/stats/index.cjsx, app/pages/project/stats/stats.cjsx
This just updates the "missing stats" message on the stats page to indicate all stats before Jun-09-2016 are currently unavailable.
@mcbouslog can you look over this?
=> Change the "missing stats" message on stats page

app/pages/project/stats/stats.cjsx, css/project-stats-page.styl
add stats page `stats-text-content` class/styling similar to previous stats page styling.
my apologies for not catching in recent related pull request review, but in recent commits the `project-text-content` class was reduced. I've added a `stats-text-content` class that extends the current `project-text-content` class and adds the same css as before.
sorry for the white space removal from my text editor, adding `?w=1` (or `&w=1` if already a param) to the url makes it easier to review on GitHub.
=> add stats text-content styling

app/pages/about/publications-page.cjsx
Closes #1850. Adds a `openAccess` property to the publications object and displays it next to the original href. Staged at: https://publication-page-open-access.pfe-preview.zooniverse.org/about/publications
@willettk, @mrniaboc is this ok? This supercedes #2511
=> Publication page open access

app/classifier/frame-annotator.cjsx, app/components/frame-viewer.cjsx, app/components/modified-image.cjsx, app/components/subject-viewer.cjsx, app/pages/admin/project-status.cjsx, app/pages/lab/workflow.cjsx
The invert tool allows users to invert the colors of an image/subject in order to more easily notice objects. This branch was tested and should be working on all browsers (IE, Safari, Firefox, Chrome). I tried to abstract the invert into a modification property to allow the `ModifiedImage` component to be more flexible with other filters in the future.
Staged branch at https://invert-tool.pfe-preview.zooniverse.org/projects/wgranger-test/invert-testing/classify
=> Add Invert Image Tool

package.json
I assume `awk`  is ok to use here. 
This PR fixes a problem i just came across where the domain name of the staged URL is case insensitive and browsers will downcast them before requesting the URL. However our static proxy takes the subdomain and uses it as an s3 bucket path which may not match the branches actual case. This PR will force the bucket path to lowercase to match the domain case via the browser.
=> downcase the branch name on stage deploy

app/components/subject-viewer.cjsx, app/subjects/index.cjsx, app/talk/comment.cjsx
Currently, subject metadata keys prefixed with `#` are hidden from the user.
This expands that to a customizable list and adds `!` as a prefix that is hidden unless the subject viewer is displayed in talk.
If we come up with more conditions later on we can just expand the list
=> Customizable filtering of subject-viewer metadata.  Closes #1281.

app/classifier/drawing-tools/grid.cjsx, app/classifier/index.cjsx, app/classifier/tasks/drawing/grid-buttons.cjsx
Originally, cell rows and columns were mapped with component unmount, which was occurring after the classification was sent to the exporter. Cells are now mapped before a classification is sent.
=> Allow Grid Tool to Map Cells Before Classification Sent

app/pages/home-logged-in.cjsx, css/home-not-logged-in.styl, css/layout.styl
Closes #2829 
This also
- removes the not-logged-in conditions from the logged-in page.
- moves `.flex-container` to `layout.styl` (I imagine it's more generally useful)
=> Fix logged-in homepage flex box in IE

app/talk/search-input.cjsx
Closes #2830
Oddly enough, it was an undefined component ref that was causing #2830. 
To reproduce the original issue
And the fixed version:
=> Prevent undefined ref from disrupting navigation.

app/lib/get-workflows-in-order.coffee, app/pages/admin/project-status.cjsx, app/pages/lab/project.cjsx, app/pages/lab/visibility.cjsx, app/pages/lab/workflow.cjsx, app/pages/project/classify.cjsx, app/pages/project/finished-banner.cjsx, app/pages/project/home.cjsx, app/pages/project/stats/index.cjsx, app/pages/project/stats/stats.cjsx
Temporary solution to issue #2819.
API workflow response limited to 20 items, NfN has over 20 active workflows, so new workflows not showing up in Project Builder.
Temporary solution is to increase page_size param from 20 (default) to 50.
=> increase page_size in workflows request to API

app/pages/project/stats/stats.cjsx
This fixes #2655 
The code will now render the text `There is not stats data available at this time.` instead of an empty graph when there is no data for a projects.
=> fixes navigation on empty stats page

app/main.cjsx, app/talk/lib/paginator.cjsx, package.json
Closes #2762 and #2719 by adding react-router-scroll middleware.
=> Add react-router-scroll and basic scroll to top functionality

app/pages/home-logged-in.cjsx
Filter a user's recent projects for those with activity count > 0.
Also removes a couple of PromiseRenderers from the logged-in home page.
Closes #2865
=> Only display recent projects that have user classifications

app/pages/lab/project.cjsx
Remove the first user check since we should wait until the auth request has happened.
Fixes #2767
=> props.user is always undefined on first mount

app/classifier/drawing-tools/circle.cjsx, app/classifier/drawing-tools/ellipse.cjsx, app/classifier/drawing-tools/line.cjsx, app/classifier/drawing-tools/poly-curve.cjsx, app/classifier/drawing-tools/polygon.cjsx, app/classifier/drawing-tools/rectangle.cjsx
Fixes #649 
This fix keeps delete buttons from being placed over drag handles for shapes. The buffer size (44 pixels) seemed appropriate and adhered to some guidelines for finger size. The buffer is a bit larger in the polygon because there is an additional outer circle along one handle.
Staged at: https://adjust-delete-button.pfe-preview.zooniverse.org/
=> Adjust delete button

app/pages/admin/project-status.cjsx
This adds a UI for admins to add an arbitrary workflow "level" to the workflow configuration that will be used in the experimental workflow promotion feature for gravity spy. This is so that I don't have to hard code specific workflow ids into the classifier. Closes #2643. Staged at https://workflow-levels.pfe-preview.zooniverse.org/
=> Workflow levels

app/classifier/tasks/survey/editor.cjsx, css/survey-task.styl
Closes #2686.
Partially addresses #2687.
@aliburchard 
[staged here](https://survey-task-editor.pfe-preview.zooniverse.org).
I have a test project (1634) with a fully populated survey task and a test survey task. If you'd like, let me know your preview username to add as a collaborator.
[See here](https://www.zooniverse.org/projects/aliburchard/cameratraptest/about/faq) for Ali's instructions on the survey task.
As compliments (embarrassments?) to the proper files downloadable in Ali's instructions above, also attaching files with errors or omissions to aid in testing - [survey-task-files-errors-omissions.zip](https://github.com/zooniverse/Panoptes-Front-End/files/419641/survey-task-files-errors-omissions.zip).
Errors (prevent Apply)
- Characteristic “Hair” misspelled
- Confused …
=> edit survey task editor

app/classifier/index.cjsx, app/classifier/world_wide_telescope.cjsx
Closes #2861 
This PR mainly fixes two issues:
1.  Selects only drawing tasks from annotations and uses them in the WorldWide Telescope (WWT) component, thus making WWT more flexible to different workflows. Also, all annotations are run through a try, so we shouldn't see any more freezes.
2. The X and Y axes are now found using a slope formula. This allows users to mark inside a chart, if necessary, and the WWT link should still accurately appear.
=> Allow WWT to support new workflow

app/pages/admin/project-status.cjsx, app/pages/project/home.cjsx
For Gravity Spy: This adds a feature that filters the workflow buttons on the project home page based on the user's level. If logged out, then the standard 'Get Started' button will show and the default workflow will load.
I also refactored the home page to not use `PromiseToSetState` or `HandlePropChanges`. These abstracted away the lifecycle of the component making it difficult to reason about what was happening and difficult to debug since errors were set in the state instead of logging to the console.
Staged at: https://workflow-level-buttons.pfe-preview.zooniverse.org/projects/srallen086/workflow-assignment-testing
When you're ready to test this out, let me know because I will need to modify your user account's project preference's settings via the python client so you can see what …
=> Show buttons for workflows on the home page based on level

app/pages/lab/project.cjsx
Temporary solution to #1136, #2752.
Better solution still Generalized Pagination #2852, which if I have time I'll try and start asap, but if not done before ZTM, something to keep in mind for then.
@camallen, @srallen - similar to recent workflow API call change I know this isn't ideal, but helps until pagination implemented. This change is for only within the Project Builder, subject sets left side bar list; smaller scope than workflow call change.
=> Edit lab side-bar subject sets list API call

.eslintrc, app/classifier/index.cjsx, app/components/workflow-assignment-dialog.jsx, app/lib/tutorial.cjsx, app/pages/project/classify.cjsx, app/pages/project/index.cjsx, css/main.styl, css/workflow-assignment-dialog.styl
This adds the dialog UI for workflow assignment/promotion as well as a bug fix for the Tutorial and removed a redundant API call. Also, updated the eslint file and changed it to `.eslintrc` so it would work with Sublime.
Still need to:
- Finalize copy for the dialog
- Finalize any styling for the dialog
- Do some additional testing when I can successfully get Project Preferences of another user and promote them (via python client)
This leaves out the potential opt out feature. I think that's gonna take more thought and time if we do it at all. FYI @trouille 
Staged at: https://workflow-assignment-dialog.pfe-preview.zooniverse.org/projects/srallen086/workflow-assignment-testing
=> Workflow assignment dialog

app/classifier/index.cjsx, app/pages/admin/project-status.cjsx, app/pages/lab/workflow.cjsx, app/pages/project/classify.cjsx
[staged branch and testing project here](https://gs-gold-standard-notice.pfe-preview.zooniverse.org/projects/markb-panoptes/gravity-spy-gold-standard-notice-test-project).
let me know staging user and I'll add to test project. the test project has a test gold standard subject set and a test regular subject set.
even though there should only be one selection made, if user makes multiple selections, should `match` be strict (`.every`) or forgiving (`.some`, current setup)?
currently, `hide_classification_summaries` is needed to be checked to hide a regular subject's summary, but that's easily change-able if preferred.
possible ToDo - in wrong response, link references to Tutorial and Field Guide. Though there maybe an argument to leave as is so primary action is to click Next and continue …
=> add gravity spy gold standard feedback

app/pages/project/classify.cjsx, app/pages/project/index.cjsx
This PR fixes an issue with the Classify button not fully loading for non-signed in users in Chrome, and for Safari and Firefox, generally. 
I added a few more checks for the existence of the preferences object, which seems to have fixed the button.
=> Fix for classify button

app/classifier/index.cjsx, app/classifier/world_wide_telescope.cjsx
Fixes #2929 .
In order for WorldWide Telescope to work, it needed a unique name for each link. Originally, the username was included with this unique name, however, this isn't necessary and a hash will suffice. By removing the username, a non-logged-in user can complete classifications.
https://fix-2929.pfe-preview.zooniverse.org/
=> Remove Username From Hash Compute

README.md
Fixes # 2940.
[guide](https://toddmotto.com/react-create-class-versus-component/) replaces (guide)[https://toddmotto.com/react-create-class-versus-component/]
=> Fix link markdown in the README.

app/pages/project/classify.cjsx, app/pages/project/home.cjsx, app/pages/project/index.cjsx
Fixes some issue discussed in the front end channel.
This fixes the following scenarios:
- A logged out user clicks 'Get Started' and the project has a default workflow set, the default workflow id is now passed as a param. Before a random workflow was selected.
- A user navigates directly to a project's classify page. If logged in and there is a selected workflow passed down as a prop, then load that workflow.
- Do not show the workflow assignment dialog if the workflow query is undefined
This does not fix when a user browses directly to the classify page and is not logged in, then random workflows are still being loaded. I'm working on another branch to do some refactoring since I'm starting to dislike some of the dependency on the workflow query in the URL and there are redundant API …
=> Use default workflows

app/classifier/tasks/drawing/markings-renderer.cjsx, app/components/multi-image-subject-options-editor.cjsx
Fixes #2888 
Removes `when parseInt(mark.frame) is parseInt(@props.frame)`, if the clone markers option is selected.
=> Add workflow configuration for cloning markers on multi-image subjects.

app/pages/project/classify.cjsx
This removes the animated scroll on load of the classify page. It doesn't entirely make sense anymore with the project navbar redesign and it's a bit annoying. Change 👍 by @jwbmartin 
Staged at: https://remove-animated-scroll.pfe-preview.zooniverse.org/
=> Remove scrollIntoView

css/dialog.styl
Fixes #2965  .
Increases dialog z-index to display over all other content.
=> Position dialogs over other content

css/survey-task.styl
* Fixes the gargantuan size of the Survey task when viewed in IE11, by changing `survey-task-choice`'s `display: flex` to `display: block`
Issue: When viewing a Survey Task on IE11, it looks like...
_The "Nothing Here" choice goes on for 2 pages of nothing there._
Example: https://zooniverse.org/projects/zooniverse/wildcam-gorongosa/classify
Analysis:
* Examining the structure of the HTML component...
```
div.survey-task-choice  //display:flex
div.survey-task-image-flipper
div.survey-task-choice-content  //flex-grow: 100
div
```
* ...we see a rather weird interaction. In IE11, the first and last divs assume `flex: 1` (because... IE) so it stretches to fit the parent container. And because IE11 is insane, it always has this weird issue where the parent container's size is dependent on the …
=> Fix Survey size in IE11

css/owned-card.styl, css/owned-list-pages.styl, css/project-list-pages.styl
Fixes #2990 .
Removes pagination padding and replaces with margins on the project card listing.
=> Add top/bottom margins to the project card listing

app/pages/profile/comment-link.cjsx, app/talk/comment-link.cjsx
Fixes #2798 .
Replaces `<a>` with `<Link>` for internal links, so that the page doesn't reload when the link is followed.
=> Fix internal links for comments

app/components/cropped-image.cjsx, app/talk/add-zoo-team-form.cjsx, app/talk/comment.cjsx
`React.findDOMNode` was deprecated in React 14, and removed completely in 15.
=> Remove React.findDOMNode

app/classifier/tasks/survey/chooser.cjsx, css/survey-task.styl
Fixes #2996
This updates the css for `survey-task-chooser-choice-button>*` so survey task buttons look the same on firefox as other browsers.
Staged at: https://fix-2996.pfe-preview.zooniverse.org/
Note: I have not tested this on Edge.
=> update css for survey-task-chooser-choice-button children

app/classifier/tasks/survey/choice.cjsx, css/survey-task.styl
Fixes #2999.
Fixes the CSS for the image flipper pips since position on top of the image was hiding the x-axis info in the image for Gravity Spy.
https://fix-2999.pfe-preview.zooniverse.org/projects?env=production
=> Move image flipper pips to relative positioning below image

app/main.cjsx
Should fix markdown footnote links, discussed here on Talk: https://www.zooniverse.org/talk/18/87732?comment=164609&page=1
and tested here: https://www.zooniverse.org/talk/13/18624?comment=164558&page=2
Turns off scroll-to-top if the hash changed in the window location.
=> Don't scroll for links to document fragments

app/classifier/index.cjsx, app/components/subject-viewer.cjsx, app/components/workflow-assignment-dialog.jsx, app/pages/project/classify.cjsx, app/pages/project/home.cjsx, app/pages/project/index.cjsx
This is a refactor on how the workflows are selected and fetched for projects. The goal is to reduce the number of API calls for workflows since now it is no longer fetched after every classification. This also moves the code into the index file of the project (`ProjectPageController` and `ProjectPage` components) which I think will get us one step closer to eventually refactoring to use a store or observables based framework (Redux, Rx.js, and/or MobX). In addition, this necessitated a refactor on some of the code I wrote for the workflow promotion for Gravity Spy.
The workflow selection will now be consistent whether a user is logged in or not, navigates directly to a project's `/classify` page, navigates from a project's talk, or uses the button(s) available on the project home page. …
=> Refactor workflow selection

app/pages/admin/project-status.cjsx, app/pages/project/index.cjsx
- add "allow workflow query" option as experimental tool in project's admin page
- add conditional for setting workflow that if workflow query in url and experimental feature enabled, then set workflow to query
=> add allow workflow query admin option

css/modal-form.styl
Fixes #3006. The subject metadata modal and the subTask modal in the workflow editor were hidden behind other modals. 
I increased the z-index for the modals.
=> increase z-index for metadata and subtask modal

app/components/wrapped-markdown.jsx, app/talk/comment.cjsx
Fixes #2798 (finally?) and should address angry comments  complaining that the site randomly zooms in and out when following links from Talk subjects.
Wraps Markdown in a listener that overrides default link behaviour for internal links.
=> Use History.push for internal links in Talk comments

app/classifier/index.cjsx, app/pages/admin/project-status.cjsx
Related to #2923. This adds back the expert classification comparison summary part of the previous gold standard classification import feature, but now behind a feature flag. I've turned on the feature for MWP and Microscopy Masters. It can be tested with the Pickers Practice workflow on Microscopy Masters:
https://expert-comparison-summary.pfe-preview.zooniverse.org/projects/jbrugg/microscopy-masters/?env=production
Note: This does not add back in the classification quality calculations which would involve touching a lot more of the code base to add back in.
=> Expert comparison summary

app/components/subject-viewer.cjsx
Fixes #3034 
Issue: In IE11, images in Camera CATalogue appeared tiny. This turned out to be caused by the PFE rendering multiple _empty_ subject images... for certain projects on certain browsers.
Analysis: In `app/components/subject-viewer.cjsx`, the CoffeeScript line `for frame of @props.subject.locations` doesn't behave the expected way.
* Given that subjects.locations is an Array, we expect `for X of Y` to return the array indexes: 0, 1, 2, 3, etc.
* In IE11, for subjects from Camera CATalogue, this would instead return "0", "entries", "key", "values".
* In Chrome 53, this would return "0", "values. (Although Chrome's flex rules would hide the empty subject images)
* In Firefox 48, this would return "0", which is the only correct behaviour.
Solution:
* The `for X of Y` construct …
=> Fix multiple, empty subject images bug in subject-viewer ("for X of Y" bug)

app/classifier/tasks/drawing/min-max-editor.jsx, app/classifier/tasks/generic-editor.cjsx
Fixes #3014 .
Deletes max/min keys from a drawing tool when their value is an empty string.
Sets some sensible minimum values for min and max number of points.
=> Fix min/max for drawing tools

app/classifier/index.cjsx, app/lib/experiments-client.coffee, app/lib/experiments-config.coffee, app/lib/geordi-logger.coffee, app/lib/intervention-config.coffee, app/lib/intervention-monitor.coffee, app/lib/intervention.cjsx, app/pages/project/classify.cjsx, app/partials/app.cjsx, package.json
This adds a notification framework such that the Experiment Server can post interventions and experiment progress to Sugar, PFE can pick that data up, and act accordingly.
This adds an experiment for Volcrowe using the following projects at different stages:
1. Initial testing on staging - Planet Four Terrains (`mschwamb/planet-four-terrains`) => try it at http://sugar-notify-to-user.pfe-preview.zooniverse.org/projects/mschwamb/planet-four-terrains/classify
2. Testing on production - Comet Hunters HSC Prototype (`mschwamb/hsc-comet-hunters-prototype`) => will happen automatically with the merge of this PR.
3. Going live on production - Comet Hunters (`mschwamb/comet-hunters`) => will be a couple of small tweaks to this code as a 2nd PR => #3037   (to turn off afterwards: #3038 )
The …
=> Sugar Experiment Framework, and Launch Volcrowe Experiment on HSC Prototype

app/pages/lab/field-guide/index.cjsx
I took a stab at closing #2964
Moving the first paragraph of the help to the header, so it always appears no matter what step/stage of site guide building someone is in. Currently there's no description that appears when you click on the site guide tab of the project builder. 
I tried moving the paragraph with its <p> text <p> to the header. so it always appears no matter what step/stage of site guide building someone is in.
=> Moving help text for field guide

app/collections/settings.cjsx, app/collections/show-list.cjsx
As the History mixin is deprecated as of `react-router` 2, I'm replacing it with `context.router` throughout. To keep the PRs small and easily testable, I'm creating them by area of function; this is for collections.
Related: #2705
=> Swap out History mixin in collections

app/pages/admin/project-status-list.cjsx, app/pages/lab/project.cjsx, app/pages/lab/subject-set.cjsx, app/pages/lab/workflow-viewer/index.cjsx, app/pages/lab/workflow.cjsx, app/pages/project/stats/index.cjsx
Removes the History mixin from all page components and swaps in `context.router`
Related: #3018, #3020
=> Remove History mixin from pages

app/partials/markdown-help.cjsx
#3060 accidentally broke the markdown help with a whitespace error. This should fix it.
=> Fix indentation errors

app/classifier/tasks/generic-editor.cjsx
Fixes a conditional in the workflow editor so that the column rectangle tool shows up correctly if enabled for a project.
https://fix-column-rectangle.pfe-preview.zooniverse.org/ 
I can add you to a testing project to see this fix.
=> Fix conditional so column tool shows up in dropdown

app/components/frame-viewer.cjsx
Fixes the iOS half of #2937 .
Mobile Safari never fires the `canplay` event to indicate that a video subject is available to play, so I've deleted the loading animation for video subjects, in favour of letting the browser indicate video loading via the `<video>` element.
=> Remove the loading overlay from video

app/partials/markdown-help.cjsx
forgot to add the line break so the two examples show up on the same line for superscript and subscript. This PR fixes that.
=> adding in line break needed in markdown help

app/components/pass-context.cjsx, app/lib/notifications-counter.js, app/pages/notifications.cjsx, app/partials/app.cjsx, app/talk/lib/notifications-link.cjsx
Fixes #2951.
This moves notification counting into a separate class and adds that to the app context.
=> Adds a notification counter to application context

app/pages/project/classify.cjsx, app/pages/project/home.cjsx
This adds `You've unlocked level ` directly to the buttons on the home page and I will remove from the workflow display names once merged. Some volunteers thought they should have some levels unlocked that they weren't at yet because of the display name on the stats page.
This also adds `Please try again. Something went wrong:` when there's an error loading the classification and subject queue. Maybe this is slightly more friendly, but I'm open to suggestion.
=> Gravity Spy UI improvements

.github/PULL_REQUEST_TEMPLATE.md, app/pages/dev-classifier/index.cjsx, app/pages/dev-classifier/mock-data.coffee
Some recent changes to the classifier, including my own, have broken the dev classifier. This fixes the dev classifier as well as add a checkbox to the PR template to remind us to check that it is working.
=> Fix dev classifier

app/talk/latest-comment-link.cjsx
Fixes #3067 .
Updates the latest comment link state if the comment props change.
Also rips out a PromiseRenderer that was requesting user roles from the API on every re-render.
=> Update user details for latest comment links

app/talk/board.cjsx, app/talk/breadcrumbs.cjsx, app/talk/discussion.cjsx, app/talk/inbox-conversation.cjsx, app/talk/inbox-form.cjsx, app/talk/inbox.cjsx, app/talk/latest-comment-link.cjsx, app/talk/lib/paginator.cjsx, app/talk/lib/update-query-params.coffee, app/talk/moderations.cjsx, app/talk/private-message-form.cjsx, app/talk/quick-subject-comment-form.cjsx, app/talk/recents.cjsx, app/talk/search-input.cjsx, app/talk/search.cjsx, app/talk/tags.cjsx
Swap out the History mixin for `context.router` in Talk.
Related to #3018
=> Swap out History mixin in Talk

app/collections/show-list.cjsx, app/pages/lab/workflow-viewer/index.cjsx, app/pages/lab/workflow.cjsx, app/talk/latest-comment-link.cjsx, app/talk/lib/update-query-params.coffee
Fixes uses of `createHref` where multiple arguments were passed in instead of a location object. Also just took out some instances where `createHref` was being used to create a string to pass into `push`, as `push` will just take a location object.
Needs #3020 merging first and rebasing.
=> Fix create href

app/classifier/index.cjsx
This fixes the annoying unique key React warning that would show up with the Classifier. I've added a key prop to the `HookComponent` in the `coverable-task-container` div.
=> Fix unique key warning in classifier

package.json
As a prerequisite to merging zooniverse/markdownz#45.
=> Add babel-plugin-transform-object-assign to devDependencies

app/components/wrapped-markdown.jsx, package.json
Updates markdownz to include anchors for H1 and H2, so that `[[toc]]` will generate working links.
Adds a babel plugin that markdown-it-anchor needs.
Doesn't override default link behaviour if we stay on the same page, so that the browser will scroll to the specified heading.
=> Update markdownz to support table-of-contents links

css/collections.styl
Fixes #2400 .
Partially (mouse-click)blocked delete-button on collected items.
Simple direct z-index fix.
Although the "*collection-subject-viewer-delete-button*" class is used after/in the "*subject-container*" class.
The "*subject-link*" class is applied(*[html part](https://github.com/zooniverse/Panoptes-Front-End/blob/ea6131abc4e7c09f363c326562723fc7795da33a/app/collections/show-list.cjsx#L81)*) after the button, which is *probably* the reason for the partial blocking of the delete button.
(*note: Chrome only user + no code testing available on this side*)
=> collected-item delete-button z-index fix.

app/layout/index.styl
Fixes #3047  
Applies .9 opacity to children of the project page, except Talk pages.
=> Slight transparency for project pages, except Talk

app/pages/project/stats/charts.jsx, css/project-stats-page.styl
This PR is dependent on #2682 and replaces #2650.
Adds labels for the currently select date range, labels for the start and end dates, and a reset button for the range.  It closes both #2592 and #2588.
=> Add date range labels and reset button to stats page

app/pages/admin/project-status.cjsx, app/pages/lab/workflow.cjsx
Decided during ZTM: invert is now publicly available.
=> Removed invert from experimental tools

app/pages/project/index.cjsx
Fixes #3076 where a volunteer has an inactive workflow id in their preferences.
I refactored the workflow selection to first check the workflow id then clear it out of the preferences and try again if the workflow id is not active. 
@eatyourgreens I think you mentioned you were having this issue in MWP? Could you check if this fixes it for you: https://fix-prefs-workflow-selection.pfe-preview.zooniverse.org/?env=production
=> Fix prefs workflow selection

.mention-bot
Stops mention-bot from bugging Zoo alums when making a PR.
=> Add Zoo alumni to ignore list for PRs

css/landing-page.styl
Fixes #3068 .
Removes the `height: 100%` that was applied to `.landing-page`, which breaks the page layout when the content is longer than the viewport height.
=> Remove 100% height for small screens

app/classifier/index.cjsx, app/components/cache-classification.js, app/pages/admin/project-status.cjsx, app/pages/dev-classifier/mock-data.coffee, app/pages/lab/workflow.cjsx
Fixes #2956. This adds the annotation persistence if the back button is clicked by storing it in a temporary cached classification resource separate from the classification in the classifier and then checking for and loading a cached annotation when the next button is clicked if the workflow is configured to use annotation persistence and `persist annotations` is added to a project's experimental tool's array.
This should be the functionality needed for NfN but also keep it from breaking if branching logic is added later. Annotations in the classifier are popped off as expected when back is clicked, re-added if it exists in the cache. This can be seen with the branching logic of the dev classifier.
Should be tested with the NfN project. I've added `persist annotations` to its experimental …
=> Persist annotations utility

app/classifier/tasks/dropdown/index.cjsx, app/classifier/tasks/text/index.cjsx
Fixes #2945.
The `autoFocus` attribute only works on initial page load, so component updates don't trigger intended focus. Examples of focus not working as intended...
- [back to back text task workflow](https://master.pfe-preview.zooniverse.org/projects/markb-panoptes/focus-testing-project/classify?reload=3&workflow=2428)
- [back to back combo tasks](https://master.pfe-preview.zooniverse.org/projects/markb-panoptes/focus-testing-project/classify?reload=2&workflow=2426) (2nd and 3rd tasks, with dropdown tasks as first task within combo tasks)
Examples on staged branch, working as intended...
- [back to back text task workflow](https://edit-focus-text-dropdown.pfe-preview.zooniverse.org/projects/markb-panoptes/focus-testing-project/classify?reload=3&workflow=2428)
- [back to back combo …
=> edit focus for text and dropdown tasks

app/classifier/tasks/survey/choice.cjsx
Fixes #3046.
- Changed survey task Identify button disabled logic.
- Changed behavior when clicking already checked radio button (previously nothing happened, now will uncheck and clear from answer)
demonstration of issues here: [https://master.pfe-preview.zooniverse.org/projects/markb-panoptes/survey-task-test-project/classify?reload=0&workflow=2658](https://master.pfe-preview.zooniverse.org/projects/markb-panoptes/survey-task-test-project/classify?reload=0&workflow=2658)
- note once clicking Human, can't click Identify, even though Wow! is not required
- Wow! can not be un-clicked
same workflow, working as intended, on staged branch here: [https://survey-task-fix-require.pfe-preview.zooniverse.org/projects/markb-panoptes/survey-task-test-project/classify?reload=0&workflow=2658](https://s …
=> Survey task fix require

app/pages/settings/account.cjsx
At the moment, when you sign up, you're asked for your 'Real Name', but on the settings page this is referred to as 'Credited Name'. This suggested change would alter the reference on the Settings page to 'Real Name' so that they match up.
It doesn't change anything deeper than what is displayed in the web page though, and it looks like in the code in other places it might still be being referred to as credited name. At the moment, I've no idea how to change any of that.
This suggestion is a result of the glossary that Meg and I are writing - it was in defining the term in the glossary that we noticed that they're called different things in the two places.
=> Changing Credited Name to Real Name on the Settings Page

app/pages/settings/email.cjsx
I added in a slight wording change to the beta project email tick box in the Settings, to try to make it clearer that that's how you can become a beta tester - or rather get the emails that enable you to do the beta testing and therefore become one.
The change is inspired by talking to my uncle who is a big Zooniverse fan and volunteer, and hadn't realised that that's what that tick box does.
=> Clarification of How to Become Beta Tester

app/pages/admin/project-status.cjsx, app/pages/lab/data-dumps.cjsx, app/pages/lab/workflow.cjsx
Decided during ZTM. This makes the text task type public with an added note on the data exports page that it cannot be aggregated at this time.
=> Make text tasks public

app/classifier/tasks/generic-editor.cjsx, app/pages/admin/project-status.cjsx
Decided at ZTM: Make column drawing tool public.
=> Make column drawing tool public

app/pages/admin/project-status.cjsx, app/pages/lab/workflow.cjsx
Decided at ZTM. This makes the survey task public. There are still more improvements that can be made to the survey task, but none of those are blocking.
=> Makes survey tasks public

app/classifier/tasks/drawing-task-details-editor.cjsx
Missed a conditional that hid the text task for sub-tasks.
=> Make text task available to sub-task

app/classifier/tasks/drawing/summary.cjsx, app/classifier/tasks/multiple.cjsx, app/classifier/tasks/single.cjsx
Currently question text containing markdown formatting is not correctly rendered when the question text is repeated as part of the classification summary.
This PR adds code that enables markdown rendering in this situation
=> Added markdown rendering to repeated question in classification summary.

app/components/classifications-ribbon.cjsx, app/components/project-icon.cjsx, app/lib/get-all-project-preferences.js, app/lib/get-color-from-string.js, app/lib/get-user-classification-counts.js, app/pages/home-logged-in.cjsx, app/pages/profile/stats.cjsx
Refers to #2998 
Changes made in this PR speed up the API call to fetch project classifications for the stats page. This also reflects changes that will be made with the new signed in home page. Some refactoring was also made to handle redundant code, and the `ProjectIcon` component was made to handle a project resource card.
https://stats-avatars-move.pfe-preview.zooniverse.org/
=> Speed up stats API call

app/classifier/tasks/survey/chooser.cjsx, app/classifier/tasks/survey/index.cjsx, css/survey-task.styl
Fixes my confusion where I don't notice that my selection actually got remembered.
While classifying, highlight survey choices in yellow if they've already emitted one annotation value. I don't particularly like having to pass in the annotation to the `Chooser`, open to suggestions.
Branch at: https://survey-highlight-chosen-options.pfe-preview.zooniverse.org/projects/aliburchard/wildcam-gorongosa/classify
=> Highlight already used choices in the survey task

app/lib/get-workflows-in-order.coffee
Notes from Nature, currently (October 20th-23rd) participating in a special event called WeDigBio, hit the workflow response `page_size` max (50).
[Please review previous related pull request here](https://github.com/zooniverse/Panoptes-Front-End/pull/2820). As part of the previous pull request the workflow calls were optimized utilizing the `fields` param, and NfN is I believe the only project this additional increase will actually apply to.
Again, this is not the ideal solution, my apologies for not properly fixing, but this will solve the problem for the event currently underway.
I'll discuss with the Chicago team Monday (October 24th) to re-prioritize a proper solution.
Increases default workflow `page_size` from 50 to 75.
=> increase default workflows page_size

app/pages/lab/visibility.cjsx
This fixes a bug encountered with the Understanding Animal Faces project described on slack. The default workflow was made inactive and new visitors to the project's classify page would try to load the default workflow which produced an error as well as a loop to try to assign a workflow it couldn't.
Instead of tasking the classifier with clearing out an inactive default workflow, I think it makes more sense to have this action happen when the workflow is made inactive in the project builder. I also added a note for project builders so they know that the default setting for the project will be removed if the default workflow is made inactive. 
One issue is that the asterisk indicating the default won't disappear until the page is refreshed or they navigate to cause a reload of the sidebar …
=> An inactive workflow shouldn't be a project's default

app/lib/pusher-env.js, app/pages/project/metadata.jsx, app/partials/app.cjsx
Since deploying this, we've been going over our daily message cap. We're also seeing a lot of connects/disconnects. I wonder if it's counting connects and disconnects as "messages". Disabling this on production will stop going over the cap (if it's PFE that is causing that), and restore functions for other parties like SOCIAM.
=> Disable pusher in production while we debug issues

app/pages/collections/list.cjsx, app/partials/collection-card.cjsx, css/owned-card.styl
Fixes #2791  .
Places a subject count badge for collection cards so users can see how many subjects are contained without opening the collection. This is visually similar to how we display the number of classifications a user has done per project.
https://fix-2791.pfe-preview.zooniverse.org/
=> Reveal Subject Count Badge

app/pages/notifications/started-discussion.cjsx, app/subjects/mention-list.cjsx, app/talk/breadcrumbs.cjsx, app/talk/comment.cjsx, app/talk/data-export-button.cjsx, app/talk/discussion-new-form.cjsx, app/talk/discussion-preview.cjsx, app/talk/discussion.cjsx, app/talk/inbox-conversation.cjsx, app/talk/inbox.cjsx, app/talk/lib/create-subject-default-button.cjsx, app/talk/lib/moderation.cjsx, app/talk/lib/zoo-team.cjsx, app/talk/popular-tags.cjsx
This makes a start at removing the PromiseRenderer component from Talk.
=> Remove PromiseRenderer from Talk components

app/partials/collection-card.cjsx
Fixes #3176 .
Defines some propTypes that were set on `FlexibleLink` rather than `CollectionCard` and sets some default values for them.
=> Fix props defined on the wrong component

app/pages/lab/workflow.cjsx, app/pages/project/stats/stats.jsx
Address the concerns brought up in the talk thread: https://www.zooniverse.org/talk/14/118004
This allows project builders to select between "classification count" or "retirement count" for calculating the completeness for each workflow that is presented on the project stats page.  It defaults to "retirement count" since that is the method returned by the backend.  It also adds help text describing how each method is calculated:
Note: after this change goes live I think we should notify the project builders for live projects to let them know this is an option available to them.
@camallen feel free to re-assign this if you don't have time to look at it.
https://completion-stats-toggle.pfe-preview.zooniverse.org/
=> add option to change completeness calculation

css/secondary-page.styl
Fixes # .
I've altered the size of the header, because there was a lot of space in it - @mschwamb raised an issue about it  - [#3156](https://github.com/zooniverse/Panoptes-Front-End/issues/3156)
I wasn't too sure what the min-height bit did, but shrinking it stopped having a visual effect on the header at 190px so that's what I've set it as in this PR.
=> Alteration of Header Size

app/partials/sign-in-prompt.cjsx
Looks like a lot of the components we talked about in the Zoominar yesterday have counterpart in already...
=> Add counterpart to sign-in-prompt

package.json
Updates node to 6.9.1 and npm to 3.10.8. Resolved the peer dependency warnings. Works locally and on staging: https://update-node.pfe-preview.zooniverse.org/
Also removed babelify which probably got missed when we switched to webpack.
=> Updated node version and fixed peer deps

app/pages/lab/workflow.cjsx
Adds missing `push` method when confirming a workflow delete. Previously, the delete was successful but threw a `_this.context is not a function` error without redirecting.
Ref #1156
=> Add missing .push method when deleting workflows

app/classifier/index.cjsx, app/classifier/tasks/drawing/summary.cjsx
Fixes #3171  .
Doesn't display the back button if there is only one task and the experimental shortcut. I also noticed when testing this change that the drawing task summary needed to handle when a value wasn't present in the annotation (if, for example, the shortcut or "Nothing Here," is used. (See screenshot, with "Test" being the example drawing tool)
https://fix-3171.pfe-preview.zooniverse.org/
=> Fix Back Button Bug with New Shortcut

app/pages/lab/visibility.cjsx, app/pages/lab/workflow.cjsx
Fixes #3190 
This moves the "workflow completeness statistic" option to the lab's visibility page.  This also has the nice side effect that this option can now be changed while a workflow is active.
Staged at: https://move-stats-type.pfe-preview.zooniverse.org/
@camallen feel free to re-assign if you don't have time to look at this.
=> move stats completeness settings to visibility tab

app/components/step-through.jsx
Fixes #3213 .
Stops the `StepThrough` component from running `preventDefault` on all keypresses, rather than just the left and right keys.
=> Don't swallow all keypresses in the StepThrough component

app/pages/lab/external-links-editor.jsx, app/pages/lab/external-links-editor.spec.js
Fixes #1730.
Only shows the external links table if there are links, stops props from being modified, update tests.
=> Hide external links table if there are no links in project builder

app/components/thumbnail.cjsx, app/talk/tags.cjsx
Fixes #3211 - uses a scaled video element for thumbs and thumbnail service for image media. 
Not sure about preloading on this and bandwidth use, etc. Staged here, https://video_thumbs.pfe-preview.zooniverse.org
These are useful links to test:
https://video_thumbs.pfe-preview.zooniverse.org/projects/zooniverse/arizona-batwatch/talk/tags/insect?env=production
https://video_thumbs.pfe-preview.zooniverse.org/projects/mschwamb/planet-four-terrains/talk/tags/spiders?env=production
=> handle video thumbnails

app/pages/projects/project-filtering-interface.jsx, app/pages/projects/projects-search-selector.jsx
Fixes #3228 - Allow external links to navigate correctly and avoid double lookups via the api.
=> Fix project search external links

app/collections/show.jsx
Fixes #3227 
Fixes #2906 
Fixes the base URLs for favourites collections so that the index, settings and collaborators links work again.
=> Fix the settings and collaborators links for Favourites

app/classifier/tasks/dropdown/index.cjsx
Fixes #2952.
Mistake on my part when originally building the dropdown task - `key` defined as `Math.random()`. When a select's input was updated it triggered `onChange` which updated state and re-rendered the entire component, throwing focus back to the first select (when multiple selects present), regardless of which select tabbing out of.
Setting `key` to the select's index fixes.
Here are a few workflows to test on:
- [simple](https://dropdown-tab-fix.pfe-preview.zooniverse.org/projects/markb-panoptes/focus-testing-project/classify?reload=0&workflow=2306)
- [combo](https://dropdown-tab-fix.pfe-preview.zooniverse.org/projects/markb-panoptes/focus-testing-project/classify?reload=0&workflow=2732)
=> fix dropdown task tab sequence

app/components/frame-viewer.cjsx, app/pages/admin/project-status.cjsx, app/pages/dev-classifier/mock-data.coffee, app/pages/lab/workflow.cjsx
Makes pan and zoom a workflow config and public. Should not be merged until zooniverse/Panoptes#1991 is resolved.
=> Pan and zoom as workflow config and make public

app/pages/project/classify.cjsx, app/pages/project/home-workflow-buttons.jsx, app/pages/project/home-workflow-buttons.spec.js, app/pages/project/home.jsx, css/project-page.styl
This adds the UI piece for the first a/b split test for Gravity Spy. The experiment is a 50/50 split between _new_ users to the project. One half will see the standard buttons and will start with the beginner workflow. One half will see the 'Get Started!' button and on click will have their project preferences updated to load the level 4 workflow aka apprentice workflow.
This PR depends on #3242, the experiment setup in Seven-Ten production, and Geordi integration, so it's labeled WIP. Once #3242 is merged, I'll rebase and clean up the commit history. 
https://gs-split-setup.pfe-preview.zooniverse.org/
=> [WIP] Gravity Spy split setup

app/pages/project/stats/charts.jsx
Fixes the progress chart on the stats page to cap at 100%.
Example page it fixes: https://fix-over-100-percent-stats.pfe-preview.zooniverse.org/projects/vrooje/project-gaia/stats/?env=production
=> cap project stats page progress chart at 100%

package.json
@eatyourgreens I've bumped markdownz to v5.0.0 after merging your react 15 PR there, and this will bump the markdownz version here
=> Bump markdownz to v5

views/index.ejs
Fixes #3275 .
Adds Array.prototype.includes to the polyfills.
Updates the polyfill.io URL from v1 to v2.
=> Update polyfill to add Array.includes()

app/collections/show.jsx
Fixes #3277 .
Fetches collections from the API when the user prop changes for collection pages.
Should fix the case of private collections incorrectly showing/not showing.
=> Fetch collections again on user change.

app/talk/discussion.cjsx
Fixes #3279 .
Returns a discussion from `setDiscussion`, avoiding a case where `componentWillMount` runs before `this.state.discussion` has been set.
Fixes #3279
=> Return a discussion from TalkDiscussion.setDiscussion

app/pages/project/index.cjsx
Makes the Geordi logger semi-aware of experimental splits set up by seven-ten.
=> final version--tell geordi to remember the first active experiment

app/pages/home-for-user/my-builds.jsx
Similar to #3244, I found a place in the new home page to batch some requests. Previously, requests were made individually through a `.map()` to get project avatars, this gets them all in one go.
=> Batch avatars call in my-builds

app/classifier/index.cjsx, app/pages/dev-classifier/mock-data.coffee
Fixes the broken dev classifier by adding existential operators to the instances of conditionals that check for `experimental_tools` on projects and adds an empty `experimental_tools` array to the mock project.
https://fix-broken-dev-classifier.pfe-preview.zooniverse.org/dev/classifier
=> Fix broken dev classifier

app/pages/project/home-workflow-button.jsx, app/pages/project/home-workflow-buttons.jsx, app/pages/project/home-workflow-buttons.spec.js
This updates which workflows are being used, hides active workflows that do not have an assigned level, updates tests, and fixes a minor bug where the buttons would flash while the preferences for a user were still loading and then would switch to the 'Get started!' if the user was a part of that split group.
https://gs-split-workflow-setup.pfe-preview.zooniverse.org/projects/srallen086/workflow-assignment-testing
=> Gravity Spy workflow assignment split updates

app/components/step-through.jsx, app/lib/tutorial.cjsx
v5.0 changed how options are passed to react-swipe.
Fixes #3291
=> Fix react-swipe-options

app/components/wrapped-markdown.jsx
Fixes #3048 .
Checks for `e.button` and doesn't override links if it exists and is greater than 0, or if `e.ctrlKey` or `e.metaKey` are set.
=> Don't override Talk links for middle and right mouse buttons

app/pages/lab/visibility.cjsx, app/pages/project/stats/index.jsx
This adds a workflow configuration setting to hide a workflow from the project's statistics page. Use case is if a project is using an active workflow for a specific a/b split and it doesn't make sense to make the stats for that workflow visible to volunteers. Gravity Spy currently has a split going on using an active workflow that will be made inactive once the experiment is done. Conceivably there may be other use cases for project builders to hide an active workflow from the stats page.
workflow id `3063` should not now be visible on Gravity Spy's stats page with this update:
https://hide-stats.pfe-preview.zooniverse.org/projects/zooniverse/gravity-spy/stats?env=production
=> Add workflow stats visibility setting

package.json, webpack.build.js, webpack.dev.js
Use the new transpiled version of markdownz.
https://update-markdownz.pfe-preview.zooniverse.org/
=> Update to use transpiled markdownz

app/components/frame-viewer.cjsx, app/components/text-viewer.jsx
Adds a really simple viewer to load in a text file and render the contents.
To test, there's a file with text content as the second frame for this Diagnosis London subject.
https://text-subjects.pfe-preview.zooniverse.org/projects/eatyourgreens/diagnosis-london/talk/100/47640?env=production
A really simple viewer to load and render the contents of a text file.
=> Add support for text files as subjects

app/pages/admin/project-status.cjsx, app/pages/admin/project-status/version-list.jsx
This starts on the refactor of the project status admin page. It breaks out the version list to a new ES6 component and removes the PromiseRenderers. I wanted to keep PRs small, and it's a bit of a beast of a component, so I'll do a section at a time.
=> Breakout version list, remove PromiseRenderer

app/collections/show-list.cjsx
Fixes #1652 .
Passes a project prop to the subject viewer, which should enable the project and collections buttons.
=> Pass a project to collection subject viewer

app/pages/project/about/about-nav.jsx, app/pages/project/about/index.jsx, app/pages/project/about/team.jsx
Adds Research and Team as default about pages after a request on Talk - Research is the default page, and Team should be visible for the collaborators list even without content
cc @eatyourgreens 
=> Add default pages back to about project

app/pages/project/stats/charts.jsx, css/project-stats-page.styl
Fixes the stats page bar graph to look better on small screens.  It also removes some `eslint` warnings from the stats code.
Example (view on mobile or small screen widths):  https://stats-on-android.pfe-preview.zooniverse.org/projects/mozerm/snow-spotter/stats/?env=production
=> Stats on android

app/pages/home-for-user/news-pullout.jsx
Minor tweaks to the Zooniverse News Section on the logged-in user Zooniverse hompage - Addresses #3193 by shifting the Publications to the bottom of the list and changed  'Updated projects' --> 'Participated Project Updates'  which address most of #3191
=> Slight Reordering and rewording on Zooniverse News Section

app/classifier/tasks/survey/editor.cjsx
Fixes #3290 (front-end issue, back-end issue [2066](https://github.com/zooniverse/Panoptes/issues/2066) pending).
Only applies to subsequent survey tasks, or subsequently re-imported survey tasks.
Historically with the survey task editor, to create the object keys for choices, characteristics and questions - vowels and whitespace were removed from the related human-readable label/string, and the string was capitalized.
This PR edits the regex to keep the vowels from the human-readable label/string, and leaves the removal of whitespace and capitalization as is.
This makes the keys more human-readable (as requested per #3290), and also makes the keys more unique (i.e. previously "Bear" and "Boar"'s keys would both be `br`, which would cause Boar's values to replace Bear's).
=> edit survey task keys to include vowels

app/pages/project/index.cjsx, app/pages/project/potential-field-guide.cjsx
Fixes #[2397](https://github.com/zooniverse/Panoptes-Front-End/issues/2397)
This removes the Field Guide tab from the right side of the project landing page. The tab will still be available on other project sections: Talk, About, Classify, Collect.
https://field-guide-landing.pfe-preview.zooniverse.org/
=> Remove Field Guide from Project Homepage

app/pages/home-for-user/recent-messages.jsx, css/recent-messages.styl
On the landing page, longer messages are overflowing out of their parent DIV for smaller screens. This was first noticed on a Android with a larger screen (hence the branch name). CSS and screen size cutoff was changed.
https://android-view.pfe-preview.zooniverse.org/
=> Fix Message Overflow for Small Screens

app/collections/preview.cjsx, app/talk/discussion-preview.cjsx, app/talk/tags.cjsx
Needs a backticked ES6 import to use in Coffeescript components
=> Fix import of the Thumbnail component

app/subjects/comment-form.cjsx
Removes the only instance of the History mixin left, ref #3218
=> Remove History mixin

app/pages/lab/workflow.cjsx, app/partials/project-modal-editor.cjsx
Fixes #2959.
Adds text input to add or edit title for tutorials and mini-courses (both are a tutorial resource).
In workflow editor, tutorial/mini-course sections, displays tutorial/mini-course titles in list of options.
=> add UI to add-edit tutorial and mini-course title

app/pages/lab/project-details.cjsx
fixes #2318
took a stab at adding the markdown editing toolbar to the Announcements textbox
=> Adding in markdown toolbar to Announcements textbox

app/pages/project/home-workflow-buttons.jsx, app/pages/project/home-workflow-buttons.spec.js
This removes the code specific to the a/b split that just ended for Gravity Spy.
https://gs-split-remove.pfe-preview.zooniverse.org/projects/zooniverse/gravity-spy?env=production
All logged in users should see all five workflow buttons, with some disabled if they haven't reach that level yet. Logged out should see 'Get Started!' button.
=> Remove code for Gravity Spy split

app/components/thumbnail.jsx, app/components/video-player.jsx, css/subject-viewer.styl
This allows the ability for a video to play when clicking on the still image. A boolean prop is also added to give the component the ability to hide controls, if needed. Bat detective has video subjects to test functionality.
https://video-click-play.pfe-preview.zooniverse.org/
=> Play video on click

.eslintrc
Missed in the eslint rule update. This adds the browser env to the config so that global variables like `window` or `location` aren't flagged as undefined.
=> Add browser env to eslint config

app/lib/get-notification-data.js, app/pages/notifications.jsx, app/pages/notifications/comment.cjsx, app/pages/notifications/data-request.cjsx, app/pages/notifications/message.cjsx, app/pages/notifications/moderation.cjsx, app/pages/notifications/notification-section.jsx, app/pages/notifications/notification.cjsx, app/pages/notifications/started-discussion.cjsx, app/talk/lib/notifications-link.cjsx, app/talk/search-result.cjsx, css/notification-section.styl
This makes three changes to the new notifications page.
1) Changes styling for unread notifications
2) Removes project-specific notification page from header
3) Adds error handling for failed notification requests
https://notifications-update.pfe-preview.zooniverse.org/
=> Notifications update

app/pages/notifications/comment.cjsx, app/pages/notifications/message.cjsx, app/pages/notifications/moderation.cjsx, app/pages/notifications/notification-section.jsx, app/pages/notifications/started-discussion.cjsx, css/notification-section.styl
This adds a "Mark All as Read" button to the notifications page. This was a suggestion brought up by a volunteer on general talk. This PR also adjusts how the unread count appears, as numbers over 99 were appearing off center.
https://mark-all-read.pfe-preview.zooniverse.org/
=> Mark all read

app/pages/collections/list.cjsx, app/pages/settings/email.cjsx
Fixes #1489 
Fixes #2455 
Adds `sort: 'display_name'` to the API calls for email project preferences and collections.
=> Sort collections and email preferences by display_name

app/classifier/drawing-tools/circle.cjsx, app/classifier/drawing-tools/column-rectangle.cjsx, app/classifier/drawing-tools/delete-button.cjsx, app/classifier/drawing-tools/drag-handle.cjsx, app/classifier/drawing-tools/ellipse.cjsx, app/classifier/drawing-tools/grid.cjsx, app/classifier/drawing-tools/line.cjsx, app/classifier/drawing-tools/point.cjsx, app/classifier/drawing-tools/poly-curve.cjsx, app/classifier/drawing-tools/polygon.cjsx, app/classifier/drawing-tools/rectangle.cjsx, app/classifier/drawing-tools/triangle.cjsx, app/classifier/frame-annotator.cjsx, app/classifier/tasks/drawing/markings-renderer.cjsx, app/components/pan-zoom.jsx, app/components/pan-zoom.spec.js
Addresses #2867 by adding a rotate feature to PanZoom and scaling drawn marks, handles, and delete buttons using a SVG transformation matrix. Staged [here](https://rotate-and-draw.pfe-preview.zooniverse.org/dev/classifier).
**frame-annotator.cjsx**: added methods for scaling marks using an SVG transformation matrix.
**[drawing_tool_name].cjsx**: uses a new method from frame-annotator, #normalizeDifference(), to scale the difference when the component is dragged. 
**pan-zoom.cjsx**: added a rotate feature. The reset button should also reset the rotation.
**delete-button.cjsx, drag-handle.cjsx**: scales SVG elements using a transformation matrix.
=> Rotate and Draw

app/components/thumbnail.jsx, app/talk/discussion-preview.cjsx
Fixes #3352 .
Video subjects were not showing on the talk discussion preview. This is apparent when looking at Bat Detective, for example.
https://fix-3352.pfe-preview.zooniverse.org/
=> Allow Video Subjects to Show with Discussion Preview

app/pages/lab/media-area/media-icon.jsx
Fixes #3375.
Add missing closing square bracket.
=> add missing closing square bracket

app/pages/lab/project-details.cjsx
This is basically a quick fix for #3356.
I spent a bit of time playing with a single input for discipline/other tags, but I never got anything to feel less confusing.  In the meantime, this at least fixes the bug.
https://fix-project-tags.pfe-preview.zooniverse.org
=> Fix broken project tags in project builder

app/pages/lab/project-details.cjsx
This adds the Researcher Quote field to the project lab page. It also allows for a primary researcher to be selected, whose avatar will appear on the project landing page. This should probably be merged concurrently with #3368.
https://researcher-quote.pfe-preview.zooniverse.org/
=> Add Researcher Quote to Project Lab

app/pages/project/about/team.jsx, css/project-page.styl, css/team-page.styl
Fixes #2218.
Changes aside of team members (users associated with project through Panoptes) to look and behave like Talk comment user avatar and names. Shows team member login for easy referencing in Talk, and links to team member's project comments.
=> Team page aside restyle

app/pages/lab/project-details.cjsx
Removes the promise-renderer component from project-details.cjsx and, instead, stores the avatar and background in state. 
**Questions:**
1. What's the best way to handle the promise errors? [Currently, the errors are logged.](https://github.com/zooniverse/Panoptes-Front-End/blob/remove-promise-renderer-project-details/app/pages/lab/project-details.cjsx#L44) 
2. Firefox returns the avatar and background resource as an object, but Chrome and Safari return the resource in an array. [Is there a better way to handle this issue?](https://github.com/zooniverse/Panoptes-Front-End/blob/remove-promise-renderer-project-details/app/pages/lab/project-details.cjsx#L38)
=> Remove promise renderer from project-details.cjsx

app/pages/admin/project-status/version-list.jsx
On the project status page, if there's a whodunnit missing for a version, the version changes fail to load (first noted on Snapshot Wisconsin). This adds in a fallback to stop that from happening.
https://fix-project-log.pfe-preview.zooniverse.org/admin/project_status/zooniverse/snapshot-wisconsin?env=production
cc @trouille
=> Fix version data not showing when there's no whodunnit

app/classifier/tasks/generic-editor.cjsx
Ugh, my bad - thanks for catching that @wgranger 
Freehand tools should now only appear when enabled.
=> Make sure freehand tools only appear if enabled

app/pages/lab/project-details.cjsx
Fixes #3390  .
Removes the catch() from the Promise for the project avatar and background images, which prevented both from being set if either one was missing.
=> Catch errors individually for project avatar and background requests

app/pages/lab/project-details.cjsx, css/lab.styl
There was an issue with this dropdown. The input box below it (announcement banner) had a z-index applied to it, so the dropdown above was displaying behind that box. This was only apparent if there were enough researchers to cause the height of the dropdown to cascade under the announcement banner input.
https://researcher-css.pfe-preview.zooniverse.org/
=> Add Z-index to Dropdown

app/components/project-icon.jsx, app/pages/admin/project-status-list.jsx
Allow project icons to link to URLs other than the default project URL.
=> Fix project icon links

app/pages/home-for-user/index.jsx, app/pages/home-for-user/recent-projects.jsx, app/pages/profile/user.jsx
Fixes #3392  .
Adds a stats link back to the user profile.
Adds some scrolling behaviour to the user home page when the location hash changes.
Removes a forceUpdate() in favour of setting component state.
=> Restore user profile stats

app/pages/lab/media-area/media-area-view.jsx
Fixes #1092 by moving the select file button to the top of the unordered list the media area.
https://fix-1092.pfe-preview.zooniverse.org?env=production
=> Move select files button for media area

app/components/multi-image-subject-options-editor.cjsx
I know the infinite loop PR was recently merged, but after talking with Laura, we decided having this descriptive text in the editor would more easily inform the project owner that deleting a value would cause an infinite loop.
=> Add Loop Help Text

app/collections/collaborators.cjsx, app/components/user-search.cjsx, app/pages/admin/user-settings-list.jsx, app/pages/lab/collaborators.cjsx, app/talk/add-zoo-team-form.cjsx, app/talk/inbox-form.cjsx
Adds methods to get the selected user(s) from `UserSearch` and clear the select control.
Removes the DOM queries that got the values directly from hidden form inputs generated by `react-select`.
=> Remove DOM queries from user search

app/pages/project/home.jsx
Now that the new project landing page has been displayed for several days, and project owners are familiar with the Words from the Researcher section, the section can now be hidden if the field is blank. This removes the default text that existed before.
https://remove-quote.pfe-preview.zooniverse.org/
=> Remove Researcher Quote Section When Empty

app/pages/admin/project-status/experimental-features.jsx, app/pages/lab/workflow.cjsx
Fixes #3396 .
"Enable Subject Flags" is now available as an experimental feature. It will also need to be toggled in the project builder.
https://fix-3396.pfe-preview.zooniverse.org/
=> Add Subject Flags as Experimental Feature

app/subjects/comment-form.cjsx, app/talk/discussion-new-form.cjsx
Fixes #3410 
~~I kind of think this has probably been broken since the React 15 upgrade.~~  Introduced [here](https://github.com/zooniverse/Panoptes-Front-End/commit/b91ed4c985929b09553b409750938c9a848ac0a4#diff-1c41117089744eb55872cae99e45d23dL34) when upgrading from `history.pushState` to `router.push`
Staged at https://fix-discussion-create.pfe-preview.zooniverse.org
=> Fix new discussion routing

package.json
New version breaks the build.
See also zooniverse/modal-form#27
=> Specify modal-form 2.4.3

css/mini-course-dialog.styl, css/tutorial.styl
Fixes #3419.
Two Issues here: Smaller images were not being centered on tutorials. Also, larger images were showing outside of their container Div, hence the `max-width` change.
https://fix-3419.pfe-preview.zooniverse.org/
=> Fix Image Appearance on Tutorials

app/pages/notifications.spec.js, app/pages/notifications/notification-section.spec.js, package.json
Fixes the notification tests.
Uses `coffee-react` to parse cjsx components.
=> Fix broken notification tests

app/classifier/classification-summary.cjsx, app/classifier/index.cjsx
Adds a 7-10 message for the first user to classify a subject.
Staged at https://first-to-classify.pfe-preview.zooniverse.org/projects/parrish/a-project/classify
We should also take care that this gets picked up in #3319
=> Add first-to-classify subject split testing

app/talk/discussion-comment.jsx, app/talk/discussion-comment.spec.js, app/talk/discussion.cjsx
Fixes #2973 .
Rewrites the discussion thread comment box in ES6 and moves it from the very bottom of the page to the bottom of the list of comments.
=> Move discussion reply box (and convert to ES6)

app/classifier/drawing-tools/point.cjsx, app/classifier/drawing-tools/rectangle.cjsx, app/classifier/frame-annotator.jsx, app/classifier/index.cjsx, app/classifier/tasks/crop/initializer.cjsx, app/classifier/tasks/drawing/icons.cjsx
This rewrites the `FrameAnnotator` component into ES6. There were a few bugs that arose while writing this code that are also addressed in this PR. Those include:
- **Crop Tool**: Making the tool visible and scale correctly for drag functionality
- There was a bug in the classifier concerning drawing tools. If you make a mark on a subject with a drawing tool, navigate away from the classifier, and return to the same workflow and subject, the classifier will hang because the `getSizeRect()` is returning null, and the mark you made previously doesn't know the width, height, x, y, etc. of null.
- **Triangle Tool**: The dev classifier used `class` instead of `className` for this icon.
https://frame-rewrite.pfe-preview.zooniverse.org/
A couple warnings persist, but they …
=> Frame Annotator Rewrite into ES6

app/pages/notifications.jsx, app/pages/notifications.spec.js, app/talk/lib/notifications-link.cjsx, css/notification-section.styl
This adds back the route to a project specific notifications page based on user feedback. The project specific page does two things: 
- Double checks that the project notifications are present, if available.
- Automatically opens the section associated with that project.
https://open-section.pfe-preview.zooniverse.org/
=> Add Back Project Specific Notifications Page

app/classifier/drawing-tools/freehand-helpers.coffee, app/classifier/drawing-tools/freehand-line.cjsx, app/classifier/drawing-tools/freehand-segment-line.cjsx, app/classifier/drawing-tools/freehand-segment-shape.cjsx, app/classifier/drawing-tools/freehand-shape.cjsx, app/classifier/drawing-tools/index.coffee, app/classifier/tasks/drawing/icons.cjsx, app/classifier/tasks/generic-editor.cjsx, app/pages/admin/project-status/experimental-features.jsx, app/pages/dev-classifier/mock-data.coffee
Adds multi-step freehand drawing tools for larger freehand shapes, and refactors the existing ones to return an array of coordinates instead of a path string to make them consistent with the existing drawing tools.
The tools can be tested out at https://freehand-segment.pfe-preview.zooniverse.org/projects/rogerhutchings/etch-a-cell
cc @hrspiers
=> Add segmented freehand tools, refactor existing freehand tools to return points array

app/talk/search-result.jsx
Fixes an error that's thrown if you search Zoo Talk (where `project_slug` is undefined.)
=> Fix 'cannot read property split of null' in search results

app/collections/create-form.cjsx
Fixes #3433  .
It looks like everything was already set up to show the error on the front end. I think the problem was that the `.then` statement would always be returned (even if there was an error) causing the modal to close without the error being seen. Moving the `.catch` to the end of the API call will keep the modal open when an error is returned.
https://fix-3433.pfe-preview.zooniverse.org/
=> Fix Collections Error Handling

app/talk/discussion-preview.cjsx, app/talk/discussion-preview.spec.js
Fixes search on top-level Zoo Talk, where project slugs are undefined.
=> Fix another 'cannot read property split of undefined' bug

css/survey-task.styl
Fixes #3360  .
This is a pretty simple CSS change to increase the label size in survey projects. I just increased the label a bit so that it's more obvious without obstructing the subject.
https://fix-3360.pfe-preview.zooniverse.org/
=> Increase Size of Label in Survey Projects

app/classifier/warning-banner.cjsx, app/classifier/warning-banner.jsx, app/classifier/warning-banner.spec.js
Converts the classifier's `warning-banner` to ES6 and adds tests.  These are the "Already seen!" and "Finished!" banners that show up on the top left of an image.  This is split off from #3319.
=> convert warning-banner to es6 and add a test

app/pages/home-for-user/index.jsx, app/pages/home-for-user/news-pullout.jsx
This section is blank at the moment, because `state.updatedProjects` was removed in #3321
=> Restore the updated projects list to news section

app/pages/home-for-user/news-pullout.jsx
Recent projects is broken on the home page now: projects are listed in the wrong order because the news pullout is re-sorting the array. This fixes that by forcing the news pullout to make a copy of the projects array before sorting it.
=> Bugfix: sort a copy of the updated projects list

app/classifier/tasks/combo/index.cjsx
Fixes the broken combo task introduced in #3456 
Test with dev classifier or with:
https://fix-combo-task.pfe-preview.zooniverse.org/projects/zooniverse/notes-from-nature/classify?reload=1&workflow=3068&env=production
=> Fix taskTypes require

app/classifier/tasks/single.jsx
Quick fix for single task summary when the annotation value is zero.
=> fix single task summary for annotation value=0

app/classifier/tasks/single.spec.js
This adds some tests for the single task summary (and removes eslint warnings).
=> add tests for single task summary

app/pages/lab/subject-set.cjsx
Adding in a line about how to contact the Zooniverse team to get your subject upload allowance increased. I had gotten an email from an astronomer interested in using the Zooniverse project builder, but didn't know how to get the allowance increased, so adding a line here like what is on the policies page asking the project owner to contact the Zoonvierse team so it's clear. Not sure if I did the href correctly.
=> Adding in line about how to get your allowance uploaded

app/classifier/tasks/drawing-task-details-editor.cjsx
Fixes a bug where the question subtask wouldn't show up in the workflow editor.
=> Fix import for subtask in workflow editor

app/classifier/frame-annotator.spec.js
This is a start to testing the frame annotator. I've mostly covered what is rendered, but there should be additional tests added later to test the SVG matrix transformations and other class methods. 
Staged at https://fa-tests.pfe-preview.zooniverse.org/
I'm refocusing on the organizations lab this week, so I wanted to get this at least reviewed and merged.
=> Frame Annotator tests

css/field-guide.styl
Fixes #3485 .
Adds some padding to field guide item text, to avoid awkward text wrapping for long item titles.
=> Fix text wrapping in field guide items

app/classifier/tasks/dropdown/index.cjsx, app/classifier/tasks/dropdown/index.spec.js
Related to #3497.
- Not sure this helps, but pulls out `optionsKey` craziness to it's own function.
- Removes magical `@syncAnnotations` that didn't belong, related to... 
- `getDisabledAttribute` refactored. `getDisabledAttribute` shows the input as enabled or disabled, which for select's with `allowCreate = true` we want always enabled, but for select's with `allowCreate = false` we only want enabled if condition answered with a provided answer (`option = true`).
- edits test to reflect initial `annotation.value` array of null/false answers after mount
=> edit options and optionsKey

app/classifier/tasks/generic-editor.cjsx
Fixes #621
Updates the task choice textareas to use the same classes as other text inputs in the workflow editor
=> Add .standard-input.full classes to task choice inputs

app/components/subject-viewer.cjsx
Fixes #3464.
Respects a `default_frame` property if set in a multi-frame subject's metadata so the flipbook starts on that frame.
Also fixes a bug where flipbook loops would finish on the next frame, not the current frame.
Can be tested at https://default_frame.pfe-preview.zooniverse.org/projects/rogerhutchings/default-frame-test/classify, default frame should be ~~4~~ 3, now the property is 1-indexed
cc @hrspiers
=> Allow a default frame to be set for flipbooks

app/talk/comment.cjsx, app/talk/discussion.cjsx, app/talk/recents.cjsx
Fixes load on the API caused by requests for users, subjects and user roles from the `Comment` component.
Moves the queries for comment authors, subjects and roles up to their parent components.
=> Request comment authors and subjects in batches

app/pages/project/stats/index.jsx
This fixes the issues where if you click on a link to another project's stats page from talk it will load the wrong workflows (e.g. Grants link in this post on the NfN talk https://www.zooniverse.org/projects/zooniverse/notes-from-nature/talk/484/70346?comment=322033).
This PR adds a `componentWillReceiveProps` to the stats page so it properly handles that change in project context.
I have set up a test case for this on the staged link: https://project-stats-context.pfe-preview.zooniverse.org/projects/cmk24/test-project-2/talk/149/234?comment=1241
This talk post links to a different project's stats page.
=> add componentWillReceiveProps to stats index

app/components/subject-viewer.cjsx
While doing #3498, @shaunanoordin discovered that different browsers handle the timeouts for the flipbook slightly differently, causing them to not complete a full loop in some cases. This uses a recursive function instead.
https://flipbook_counter.pfe-preview.zooniverse.org/projects/rogerhutchings/default-frame-test/classify
=> Use flip count instead of timer to handle flipbook playing

app/pages/project/index.cjsx
Fixes #3501
Uses the `Thumbnail` component to resize small avatars to 48px square.
=> Use Thumbnail for small avatars

app/pages/project/index.cjsx, css/project-page.styl, css/tabbed-content.styl
Fixes #3404 
Fixes #3481 
Three main changes:
- Visual indicator on main project button when under beta review
- Border around page when project is under beta review
- Add the "not an official Zooniverse project" disclaimer for projects under beta review
https://beta-review.pfe-preview.zooniverse.org/
=> Indicate When Project is Under Beta Review

app/talk/board-preview.cjsx, app/talk/board.cjsx, app/talk/discussion-preview.cjsx, app/talk/init.cjsx, app/talk/latest-comment-link.cjsx
Consolidates the individual API requests for board  and discussion previews into single requests in their parent containers.
=> Consolidate Talk board and discussion previews

app/talk/board.cjsx, app/talk/init.cjsx
Fixes: Gravity Spy Talk currently fails to load because they have a new, empty discussion.
Check for latest discussion (and latest comment) before rendering authors and roles.
=> Fix display of empty discussions

app/collections/collaborators.cjsx, app/components/collection-search.cjsx, app/main.cjsx, app/pages/collections/collection-card.jsx, app/pages/collections/list.cjsx, app/pages/home-for-user/recent-collections.jsx
Fixes #3263  .
Collections now have a `contributor` role that allows a user to add new subjects to a collection and nothing more. This is accessible from the collection's collaboration settings by the owner. 
* Logged in users looking at their own collection lists now see all of the collections that they are either an owner, collaborator, or contributor to. 
* If the collection is not owned by the logged in user, there's a little icon near the owner's name when viewing their own list.
* All owner names are now visible.
Staged at https://collab-collections.pfe-preview.zooniverse.org/
=> Collection Contributions

app/pages/dev-classifier/index.cjsx, app/pages/dev-classifier/mock-data.coffee
Adds a quick and simple toggle for setting the workflow config for persist annotations in the dev classifier. Few projects use this experimental feature, so having it defaulted to off and having a toggle is probably better for manual testing.
=> Toggle for persist annotations in the dev classifier

app/pages/project/index.cjsx
Improves workflows response size on project index.
- edits `getAllWorkflows` to add `fields` filter to get only workflow attributes needed for index, home, home-workflow-buttons and home-workflow-button
- edits `getWorkflow` to get selected, uncached, workflow
Not sure this is the best solution, and as an integral part of the volunteer/classification process this will need thorough review.
=> Add fields filter to project index workflows request

app/components/tutorial.cjsx
This should have been a part of #3455. This removes a bit of code where the tutorial would create preferences, however, this is not necessary since the project index started handling preference fetch/creation. Bug found while working on the workflow selection refactor.
https://tutorial-preferences.pfe-preview.zooniverse.org/
=> Tutorials don't need to create preferences

app/pages/lab/workflow.cjsx
The API has always had a small list of things you can't do. Mostly you can't change tasks, but text changes and linking subjects is absolutely fine.
=> Only disallow making changes to tasks while live

app/partials/app-status.jsx, app/partials/app.cjsx, css/app-status.styl, css/main.styl, package.json
Closes #3530
* New feature: a "status banner" is displayed on zooniverse.org, if PFE detects a status message on a secondary location.
* Mechanism: PFE checks static.zooniverse.org for a static resource (expecting to find a simple .txt or .html file). If the resource exists, the status banner appears and displays the contents of the file to the user. (Final static resource URL not finalised: see Notes)
* Zooniverse admins will need to manually add/edit the static resource. (e.g. via the AWS CLI) We're going for _a simple and primitive, but reliable_ solution.
* The static "app status" resource will be hosted on static.zooniverse.org, as that would make it scalable to the number of PFE users. (Each active user will ping the resource once per loading of Zooniverse.org, whether or not …
=> Add "App Status" banner

app/pages/project/finished-banner.jsx, app/pages/project/home.jsx, app/pages/project/index.cjsx, app/pages/project/metadata.jsx, app/pages/project/metadata.spec.js
Fixes #3062.
The state is being set to true at > 0.99 complete because Computer Vision: Serengeti is currently being shown as complete and its completeness isn't actually 100. Not sure why that is, so made it true for > 0.99 for backwards compatibility.
The banner should appear on the home page and classify page. This is the only project that is finished: https://use-project-completeness.pfe-preview.zooniverse.org/projects/alexbfree/computer-vision-serengeti?env=production
@shaunanoordin feel free to remove yourself as a reviewer if you're busy, but I thought you might like to see other parts of the codebase that are made to show status banners.
=> Use project completeness

app/classifier/frame-annotator.jsx, app/classifier/index.cjsx, app/collections/favorites-button.cjsx
Fixes #3543  .
Mounts the Classifier once, then reacts to subject and classification changes when props change.
There could be components that relied on the old behaviour, so there may still be component code, dotted through the classifier components, that needs to be changed to run on `componentWillReceiveProps` or `componentDidUpdate` as well as on `componentWillMount` or `componentDidMount`.
=> Fix classifier mount

app/pages/lab/project.cjsx, app/pages/lab/workflow.cjsx
Backyard Worlds and Gravity Spy have over 100 subject sets. In the Project Builder the list of subject sets in the side nav and in the workflow editor needs to be increased from 100 until better UI/UX is established. 
This PR changes the related `subject_sets` API requests' `page_size` from `100` to `250`.
Better pagination and improved UI/UX as it relates to the areas of the Project Builder noted have been identified as a post SGL priority. See #2852.
Rationale of 250 - Backyard Worlds has over 100 subject sets in less than 3 weeks. While it won't continue at the same rate post initial launch, it's estimated a `page_size` of 250 will give enough room to work with until a better solution can be implemented within the near future.
=> increase lab subject_sets request page_size

app/lib/seen-this-session.coffee, app/pages/project/classify.cjsx
Don't fetch the subject when we already have its ID.
Fixes #2158 .
Removes the subjects API call after classifying, since we already have the subject ID for the seens array.
=> Fix 'seen this session'

app/collections/show.jsx, app/pages/collections/collection-card.jsx
Fixes #3519 .
Some collections have display names that don't produce URL slugs eg. ??? or !!!.
This PR falls back to using collection ID if the name part of the slug is empty.
=> Falls back to using ID if collection slug is malformed

app/pages/lab/visibility.cjsx
Now you can directly link and unlink subject sets from the workflows section of the project builder for active workflows. So removing this help text as it's not needed to make the workflow inactive anymore.
Fixes # .
=> removing outdated line about how to add subject sets from visability help text

.babelrc, app/pages/lab/apply-for-beta-form.jsx, app/pages/lab/apply-for-beta-form.spec.js, app/pages/lab/visibility.cjsx, package.json
Following on from a first crack at this in #3523, this adds validation before allowing a beta review submission. It uses `set_member_subjects_count` which is known to be wrong for some projects (zooniverse/Panoptes#2155), ~~so this PR is blocked until that bug is fixed~~ but we're ignoring it for now.
Adds the babel-rewire plugin to allow mocking the `apiClient`, so will need an `npm install` before testing locally.
=> Validate project before allowing beta submission

app/components/flexible-link.jsx, app/pages/home-not-logged-in/promoted.cjsx
Fixes #3557
Replaces `Link` with `FlexibleLink` in the promoted projects component.
Updates `FlexibleLink` to accept an optional `className` property.
=> Don't use Link for external project URLs on the home page

app/classifier/tasks/shortcut.cjsx, app/classifier/tasks/shortcut.spec.js
Fixes broken task rendering for Backyard Worlds, which is throwing an error for an undefined value in the shortcut task.
Adds a test for the bug.
Sets default props for task, workflow and annotation.
=> Fix shortcut defaults

app/lib/get-collection-covers.js, app/pages/collections/collection-card.jsx, app/pages/collections/list.cjsx, app/pages/home-for-user/recent-collections.jsx
Fixes #3550  .
Fix the subject call on collections to use an array or ids instead of making an API call for each subject. Also fixed some linter warnings on the components that were changed.
https://collections-promise.pfe-preview.zooniverse.org/
=> Optimize API call on Collection Cards

app/classifier/drawing-tools/freehand-helpers.coffee, app/classifier/drawing-tools/freehand-line.cjsx, app/classifier/drawing-tools/freehand-segment-line.cjsx, app/classifier/drawing-tools/freehand-segment-shape.cjsx, app/classifier/drawing-tools/freehand-shape.cjsx
Related to #3551, removes duplicate coordinates from freehand annotations.
=> Filter out dupe coords

app/pages/lab/workflow.cjsx, css/lab.styl
This disables the checkbox for setting a workflow as default for live projects and inactive workflows. I can't think of a scenario where a project builder would want to do this purposely and it also breaks the workflow selection causing an infinite loop attempt to fetching a workflow that isn't active. 
I also added `classnames` to manage this and the inline styles added in #3517 
https://inactive-default-workflows.pfe-preview.zooniverse.org/
=> Prevent inactive workflows on live projects from being set as default

app/pages/project/index.cjsx
Fixes #3561. I changed the conditional slightly to check if the `selected_workflow` property exists first before trying to refetch for the workflow. Also fixed a bug introduced in #3545 where certain resources that weren't changing between sign in/out like the project, its background, avatar, etc were being set back to null when fetching the new project data. I've reverted it back to the old behavior. This is still not ideal since on user change we should probably just be fetching for just the preferences, not all the project data, but I'll change that in a separate PR.
Fix can be tested with this test project: https://fix-3561.pfe-preview.zooniverse.org/projects/cmk24/test-project-2/classify
=> Only retry fetching workflow if selected_workflow exists

app/pages/lab/workflow.cjsx
modifying the help text for active worflows for live projects so people know they can swap subject sets and retirement rules
=> Updating the help text for live active workflows

app/collections/favorites-button.cjsx
Fixes #3494  .
Uses the `subject.favorite` flag to set favourited status.
Removes API call to check for subject in collection.
=> Use subject.favorite to get favourited status

app/classifier/task.jsx
Fixes #3578.
The wrong onChange context was being passed into the `taskHookProps`.
This can be tested out with the `Bars` or `Spiral` workflows for this project: https://fix-hide-previous-marks.pfe-preview.zooniverse.org/projects/klmasters/galaxy-zoo-3d/?env=production
=> fix onChange context for taskHookProps

app/classifier/expert-options.jsx, app/classifier/index.cjsx, app/classifier/task.jsx
Part of #3522. Forked to make reviewing changes easier. Removes `renderExpertOptions` from the classifier, in favour of an `ExpertOptions` functional component.
Staged at https://classifier-expert-options.pfe-preview.zooniverse.org/
=> Extract renderExpertOptions to an ExpertOptions component

app/classifier/task.jsx
closes #3581
`classification.update` should be called without arguments in the persistent task hooks.
=> Fix the Hide Previous Marks button

app/partials/data-export-button.cjsx
Fixes #963
added in 'previously' to give context to the 'Never requested' text.
=> updated help text for data export button

app/partials/register-form.cjsx
Adds a node to the registration form making it clear that the username is public.
=> Make it clear the username is public

app/classifier/index.cjsx
Fixes #3582 
Removes demoMode and gold_standard props on projects when user signs out.
https://fix-3582.pfe-preview.zooniverse.org/
=> Remove demoMode and gold_standard on signout

app/classifier/task-nav.jsx
Fixes #3591 .
Updates the Task Nav component when the classification prop changes, rather than on first mount.
=> Update TaskNav component when props change

app/classifier/tasks/survey/choice.cjsx, css/survey-task.styl
Towards #2132 
Autofocus the survey image flipper when the choice first mounts, allowing images to be changed with the cursor keys.
Autofocus the confusions popup when that opens, so that it can be dismissed from the keyboard if required.
Add a visual style to question answers when those radio buttons have focus.
=> Improve keyboard control for survey task choices

app/pages/project/stats/stats.jsx
This replaces the project stats page label for `Recent Classifications` to `Classifications Yesterday` to better reflect what that number is.
=> update label for recent classifications

app/partials/avatar.cjsx
**Needs Panoptes to be deployed first.**
Panoptes will start emitting the avatar src directly as a field in the user json. This PR takes advantage of that, removing one API call for most page-loads (fetching the current user's avatar), and removing lots of API calls on talk discussion pages (to load each individual user's avatar).
Tagging @camallen who will coordinate the deploy of this feature to Panoptes production on Monday, and is happy to merge this afterwards (if approved).
Closes https://github.com/zooniverse/Panoptes/issues/2204
=> [WIP] Use user.avatar_src instead of fetching seperately

app/classifier/index.cjsx, app/pages/project/classify.cjsx
Fixes #3598 
Moves the tutorial load into classifier index, after workflow selection has finished.
=> Wait for workflow before loading tutorials

app/classifier/index.cjsx, app/pages/project/classify.cjsx
Reverts zooniverse/Panoptes-Front-End#3599
I missed this, but moving the mini-course the classifier index state breaks launching it. These lines needed to be moved/reworked with it: https://github.com/zooniverse/Panoptes-Front-End/blob/master/app/pages/project/classify.cjsx#L315-L320
=> Revert "Wait for workflow before loading tutorials"

app/classifier/drawing-tools/root.cjsx, app/classifier/tasks/generic.jsx, app/components/dialog.cjsx, app/components/modal-focus.jsx, app/lib/alert.cjsx
Extracts modal keyboard behaviour from `Dialog` into a reusable `ModalFocus` component.
Adds ModalFocus to drawing details forms as a test. It should also work with the sign-in/register forms, which use the Dialog component.
=> Modal focus

app/collections/collaborators.cjsx, app/collections/show.jsx, app/components/collection-search.cjsx, app/pages/collections/list.cjsx, app/pages/home-for-user/recent-collections.jsx
Fixes #3435 
Allows collection collaborators to also have access to "Settings" and "Collaborators" tabs of collections.
_Also changes the functionality of other user roles on collections_:
**Viewer**: can view a collection (even if private) but cannot add to the collection.
**Contributor**: can add to/view a collection but cannot edit settings
**Collaborator**: can add to/view/edit a collection
**Owner**: owns the collection and can do everything
https://edit-access-collections.pfe-preview.zooniverse.org/
=> Edit Access to Collaborated Collections

app/pages/collections/list.cjsx
Fixes #3606 .
The way the conditional was written was evaluating as true when no user was logged in. Added a check for user so the intended boolean value is returned.
https://fix-3606.pfe-preview.zooniverse.org/
=> Only show the collaboration icon to logged in users

app/pages/project/classify.cjsx
This adds a simple filter to the subjects array to remove the already seens. If the array is empty, then it falls back to the original response. This is a step toward a more intelligent handling of the subject queue. I still want to take some time to think about when the subject queue end point should be requested again.
https://skip-already-seen.pfe-preview.zooniverse.org/
and in production: https://skip-already-seen.pfe-preview.zooniverse.org/projects/zooniverse/gravity-spy/classify?env=production
=> Add simple filter for already seens

app/pages/project/classify.cjsx, app/pages/project/index.cjsx
Fixes #3619 
Sets the `loadingSelectedWorkflow` flag back to true on preference change, before loading the workflow. This signals to child components not to load subjects, launch tutorials etc.
=> Set loadingSelectedWorkflow flag on preference change.

app/pages/home-for-user/circle-ribbon.jsx, app/pages/home-for-user/index.jsx
As a follow up to #3576, this removes the separate user avatar API call that was on the signed in home page. 
https://remove-avatar-fetch.pfe-preview.zooniverse.org/
=> Remove API call for user avatar in favor of using user.avatar_src

app/pages/project/home/index.jsx, app/pages/project/home/project-home.jsx, app/pages/project/index.cjsx, app/pages/project/project-page.cjsx
Builds on #3545. This refactors the workflow fetch to be in the project page controller component. I still need to do some work on it, but wanted some initial thoughts. I wanted to eliminate as much as possible fetching for all active workflows that has an arbitrary page size number. For getting a random workflow, I've decided to just pick out of the `project.links.workflows` array, trying to fetch it with the `active: true` param and if it comes back undefined, try again. But I'm not sure if this is better than current behavior. 
https://optimize-all-workflows-request.pfe-preview.zooniverse.org
=> Optimize all workflows request

app/pages/project/index.cjsx
Fixes #3625.
https://fix-3625.pfe-preview.zooniverse.org/projects/zooniverse/notes-from-nature/classify?workflow=2808&reload=true&env=production
=> We dont need to fetch the workflow for nextProps location queries

app/components/mini-course.cjsx, app/components/tutorial.cjsx
Addresses the tutorial and mini-course portion of #3492.
- adds `include: 'attached_images'` to tutorial/mini-course request
- on start checks if there are `attached_images`, else resolves Promise
- gets `attached_images` based on `include` cache in apiClient, not stringed `.get` on tutorial/mini-course resource like previously
this [test project](https://refactor-tutorial-media-requests.pfe-preview.zooniverse.org/projects/markb-panoptes/nfn-test-mb)'s workflows 1 and 2 have separate tutorials and mini-courses with media, workflow 3 has no media.
=> Refactor tutorial media requests

app/classifier/index.cjsx, app/components/field-guide.cjsx, app/components/potential-field-guide.cjsx, app/pages/lab/field-guide/index.cjsx, app/pages/project/project-page.cjsx
This PR addresses the field guide portion of #3492 and replaces PR #3535.
The PotentialFieldGuide component is now required in the `/classifier/index` instead of the `pages/project/index`.
The request for the field_guide has been moved to the ClassifierWrapper (see `loadFieldGuide()`), where the field_guide data and icons are set in state and passed to the Classifier and PotentialFieldGuide as props.
The icons for the field guide are not requested via an `include` on the original request because of the page_size issue identified in #3535. I've set the page_size on the request for the field guide, but I wasn't sure what number to specify. Any input on what the page size should be?
=> Move field guide to classifier

app/classifier/tasks/survey/choice.cjsx, app/classifier/tasks/survey/chooser.cjsx, app/classifier/tasks/survey/index.cjsx
If a choice has been chosen, focus that button when the chooser mounts.
Add backspace to remove the currently selected choice.
Add up/down keys to navigate the choice list, when focused.
=> More survey task keyboard improvements

app/collections/show-list.cjsx, app/pages/collections/list.cjsx, css/paginator.styl
Fixes # .
The collections page doesn't use a paginator, and each page is listed as a link. This takes up space and is bad UI. I also added some margins to the page selector in the paginator because it was butting up against the buttons.
https://collections-pagination.pfe-preview.zooniverse.org/
=> Add Pagination to Collections Page

app/pages/lab/subject-set.cjsx
Removes the PromiseRenderer from subject-set.cjsx, related to #3216. Staged [here](https://subject-set-remove-promise-render.pfe-preview.zooniverse.org/).
=> Remove PromiseRenderer from subject-set.cjsx

app/pages/project/classify.cjsx
Fixes #3632 .
Adds retired subjects to the filter for already seen subjects.
=> Filter retired subjects from the subject queue

app/pages/lab/visibility.cjsx
Adds `fields: active,display_name,configuration` param to workflows request for Project Builder Visibility section. `configuration.stats_completeness_type` and `configuration.stats_hidden` handles **Completeness statistic** and **Statistic visibility** columns in Visibility section, respectively.
Fixes long load-time for NfN Project Builder Visibility section.
=> add fields param to lab-visibility workflows request

package.json
This makes HTTP status codes available with API errors, as `error.status`.
During SGL, this should allow us to put up a `service unavailable` message for endpoints that are temporarily offline (returning 503 status codes.)
=> Bump panoptes-client to 2.6

app/pages/project/index.cjsx
"Test workflow" button from inactive workflow lab goes to classify page that doesn't load due to `active: true` param on workflow request in project/index.cjsx.
This adds conditional where unless user is owner/collab `active: true` is added to workflow request, if they are owner/collab, it does not add `active: true` to workflow request.
=> fix owner/collab access to inactive workflow via "Test workflow" button

app/pages/project/index.cjsx
Fixes issue loading classification interface.
Reverting `getWorkflow` to before "Test Workflow" button edits.
=> revert test worklfow fixes

app/partials/app-status.jsx, css/app-status.styl
* There are two issues, reported by @astopy on Slack at 8am today (GMT+0):
* The App Status component is unreadable on individual Project pages, as the text becomes white.
* If the [status text file](https://static.zooniverse.org/zooniverse.org-status.txt) consists of only a newline, the App Status component thinks there's a message.
* This PR fixes both issues by...
* _overriding the colour overrides_ on Project pages.
* `trim()`-ing any text the App Status compo receives - this eliminates not just stray newlines, but any sort of whitespace that serves no purpose.
* Tested with OSX+Chrome - but note that due to the external resource (a text file on `zooniverse-static`), testing had to be done under localhost conditions with an [external test …
=> Fix App Status component - better colours on Project Page and no more 'empty' text

app/classifier/classification-summary.jsx, app/pages/admin/project-status/experimental-features.jsx, app/pages/lab/workflow.cjsx
This is for the SGL planet hunters project. They have sim subjects and want to notify the volunteers in the summary that it was a sim. 
https://sgl-planets-metadata-feedback.pfe-preview.zooniverse.org/projects/srallen086/sgl-tester/classify
The flower subject is the only subject with metadata for a true sim. The hurricane is sim false. The others are missing that subject metadata.
~~It's WIP because I need to put in the messaging they actually want.~~ At some point in the future, we may want an interface in the lab so projects and put in the message they want.
=> SIM subject classification summary notification

app/pages/project/index.cjsx
**Temporary Alternative**: see branch [`disable-test-workflow`](https://github.com/zooniverse/Panoptes-Front-End/compare/disable-test-workflow)
Fixes broken Test Workflow button from workflow editor in lab.
If a workflow query in url and admin/owner/collaborator remove `active: true` from workflow request to allow viewing of inactive workflow, i.e. via Test Workflow button from lab.
If a workflow query in url and project settings allow workflow queries, try to get requested workflow, but if inactive then remove query and proceed through other workflow determining steps.
=> Edit workflow request when queried depending on role or project setting

app/classifier/drawing-tools/freehand-line.cjsx, app/classifier/drawing-tools/freehand-segment-line.cjsx, app/classifier/drawing-tools/freehand-segment-shape.cjsx, app/classifier/drawing-tools/freehand-shape.cjsx, css/drawing-tool.styl
When using the freehand tools, the cursor could flip rapidly between pointer and crosshair. This forces the cursor to crosshair while actively drawing.
=> Stop cursor from changing to pointer while drawing freehand

app/pages/lab/index.cjsx, app/pages/lab/project.cjsx, app/partials/lab-status.jsx, css/app-status.styl
* New feature: a "status banner" is displayed on zooniverse.org's **Lab (aka Build a Project) page**, if PFE detects a status message on a secondary location.
* This is a spinoff to the App Status message in #3531 
* The message for the Lab Status banner is taken from a specific file in the `zooniverse-static` AWS bucket.
* [https://static.zooniverse.org/zooniverse.org-lab-status.txt](https://static.zooniverse.org/zooniverse.org-lab-status.txt) for production.
* [https://static.zooniverse.org/zooniverse.org-lab-status-TEST.txt](https://static.zooniverse.org/zooniverse.org-lab-status-TEST.txt) for staging/development.
* As with #3531, devs can change this message by manually replacing the 
* I may need to roll App Status and Lab Status into a single component... I dunno, I'm open to …
=> Add "Lab Status" banner

app/components/mini-course.cjsx, app/components/tutorial.cjsx
Fixes tutorial and mini-course images not loading.
Will update with reference to Panoptes issue once created momentarily, but due to `apiClient.type('tutorials').get workflow_id: workflow.id, kind: "mini-course", include: ['attached_images']` returning all project `attached_images`, not just related tutorial `attached_images`, which with Gravity Spy is more than the 20 returned by default, and doesn't include the requested tutorial media, that media wasn't loading.
Revert back to requesting media not from cache.
=> revert tutorial media request back to non-cached request

app/classifier/index.cjsx, app/collections/favorites-button.cjsx, app/collections/show-list.cjsx, app/components/subject-viewer.cjsx, app/subjects/collection-list.cjsx, app/subjects/index.cjsx
This is the only behavior that came up as a question while doing testing with the features that can be flipped on and off with the API. Features that can be flipped: https://github.com/zooniverse/Panoptes/wiki/Feature-Flags
If `skip_subject_selection_context` is flipped on, then the favorites property will be missing from the subject. Currently, if it is missing, then the fallback behavior is to request the subjects endpoint to check if the subject is present in the collection. I've removed this API call because the only time the favorite property will be missing is if this is flipped on and we're under heavy load. We probably don't want to be making any more API requests during that time if it's not absolutely necessary.
https://flipper-testing.pfe-preview.zooniverse.org/
In order to …
=> If subject favorite property is missing, dont try any other API requests

app/components/thumbnail.jsx
=> Strip static.zooniverse.org/ from thumbnail paths

app/talk/board.cjsx, app/talk/discussion.cjsx, app/talk/recents.cjsx
Fixes # .
Ensures subject and user IDs are unique in Talk API calls for lists of resources by ID.
=> Dedupe author and subject IDs in Talk queries

app/subjects/index.cjsx
This wasn't caught by me in the previous fav button work since I was working with my own favorites collections on staging. If you browse the subject talk page in admin mode, you can get back other users' fav collections and the fav button was showing as a fav'ed when I had not favorited the subject. This fixes this by making sure the favorite collection found actually belongs to the logged in user. 
check it out: https://only-fav-for-logged-in-user.pfe-preview.zooniverse.org/projects/skymap/planet-9/talk/subjects/8360430?env=production
=> Check for subject in favorites that belongs to logged in user

app/pages/project/home/project-home.jsx, css/project-page.styl
Does what it says on the can. For @mrniaboc 
Scopes button link styles just to those links.
Adds links to the Talk preview subjects on the project home page.
=> Link project home subjects to Talk

app/pages/project/stats/charts.jsx
This prevents the y-axis of the charts on the stats page from getting cut off when there are more than 1,000,000 classifications in a day.
Adds left padding to the Chartist.js graph (changed from the default 10px to 15px).
This can be tested by looking at the planet 9 stats page on the staging branch: https://stats-chart-padding.pfe-preview.zooniverse.org/projects/skymap/planet-9/stats/?env=production
=> add more left padding to charts on the stats page

app/talk/active-users.cjsx, app/talk/lib/active-user-cache.js
Fixes: ActiveUsers component spamming Panoptes to look up users
Uses a shared variable to store the user cache.
=> Cache active users in a shared store.

app/partials/app-status.jsx
Fixes #3668 and https://github.com/zooniverse/mobile/issues/104
*  Add a test to check if the fetch() function exists, needed to display in the mobile app webview, for iOS < 10.3.  If fetch() doesn't exist it will perform an XHR instead.
*  Clean up some linter issues (separate commit)
=> Fix fetch for iOS webview on App Status

app/classifier/classification-summary.jsx
The ABC SGL project subject metadata is using a string instead of a boolean for the sim metadata. This adds in a bit of type checking. 
https://sim-feedback-type-bug.pfe-preview.zooniverse.org/projects/ianc2/exoplanet-explorers/classify?env=production
And on staging (flower subject is a sim with a boolean value of true):
https://sim-feedback-type-bug.pfe-preview.zooniverse.org/projects/srallen086/sgl-tester/classify
=> Type checking for sim metadata

app/subjects/comment-list.cjsx
Fixes #3677.
Fetches comment authors and roles in the comment list component.
=> Fetch authors and roles for subject comment lists

app/classifier/classification-summary.jsx
This changes the sim feedback to only show that message and not also the default classification summary. ~~There's a chance that the message itself might change, so I've marked this as WIP.~~ 
https://only-show-sim-feedback.pfe-preview.zooniverse.org/projects/srallen086/sgl-tester/classify
https://only-show-sim-feedback.pfe-preview.zooniverse.org/projects/ianc2/exoplanet-explorers/classify?env=production
=> Only show the sim feedback if subject is a sim

app/classifier/classifier.jsx
Moves the API call back into the conditional for the experiment.
https://fix-load-count-bug.pfe-preview.zooniverse.org/
=> Move subject_workflow_statuses get call back into conditional

app/classifier/task-nav.jsx, app/pages/project/classify.cjsx
Fixes a bug where navigating to Talk leaves a completed classification stored in the project page state, which breaks the classify component on mount.
Adds an event handler to the Talk link so that it behaves exactly like the Next button.
Also takes a bunch of code that was waiting on `classification.save()` and runs it immediately instead.
=> Load the next subject when clicking Talk link

app/classifier/tasks/drawing/markings-renderer.cjsx
Fixes #3132 .
Only shows subtask popups on the original marker.
Note that this might make it difficult to go back and edit subtasks, as you have to remember to click on the original mark that you placed, not one of its copies.
=> Hide mark details unless frame numbers match

dev-server.js, package.json, webpack.dev.js
For more information with our webpack use in development. 
Take note to get scrolling to work: 
> OS X Terminal.app users: Make sure that View → Allow Mouse Reporting is enabled, otherwise scrolling through logs and modules won't work. If your version of Terminal.app doesn't have this feature, you may want to check out an alternative such as iTerm2.
=> Add webpack dashboard

app/partials/lab-status.jsx, css/app-status.styl
* Follows up on #3670 
* The code for Lab Status has been updated to match App Status, in that it uses XMLHttpRequest as a fallback. Logically, we shouldn't need to worry about the Lab being used in an iOS native app environment(...?) but hey, we should keep the code consistent.
* Also, the style for the App Status message has been made more prominent.
In the case of the alert messages, @beckyrother if you have some spare time, I'm keen to know your thoughts about standardising the UI/UX design for 'alert messages', 'info messages', and similar popups/modulars. (Or whatever those component types are called.)
You can see an example of one alert message here on the homepage - https://update-app-status-lab-status.pfe-preview.zooniverse.org/ - and an alert message on the Build a Project/Lab …
=> Update Lab Status to match App Status + improve App Status style

app/classifier/classification-summary.jsx
Adds an annotation check so that SGL exoplanets feedback only shows depending on the answer to the question.
=> Add annotation check to exoplanets feedback

app/pages/home-common/featured-project.jsx, css/home-page.styl
* Follows up from #3615 
* This PR updates the Featured Project on the home page (logged in/out) to highlight this week's Stargazing Live Proejct.
* Some documentation has been added so future archaeodevs will understand what transpired in the development of this component.
* Tagging @beckyrother for design review, tagging @mrniaboc to request a text blurb. Also, is there an external partner website we need to link to for this SGL? (The current link for the "BBC Stargazing Live" text goes to http://www.bbc.co.uk/programmes/b019h4g8 )
Requires a proper text blurb and a design review. Preview is viewable at [https://new-homepage-2017-apr.pfe-preview.zooniverse.org/](https://new-homepage-2017-apr.pfe-preview.zooniverse.org/)
=> Featured Project on Homepage - Stargazing Live April 2017 Edition

app/collections/show-list.cjsx
Fixes favourite button highlighting for any favourites collection, not just your own.
Add a check for collection owner when testing for favourites collections.
=> Check collection owner for favourites

app/classifier/classifier.jsx
Fixes #3697 where stale annotations were stored in classifier state when a new classification loads.
Runs `updateAnnotations()` when a new classification loads, forcing the classifier to update `state.annotations`.
=> Reset state.annotations when a new classification loads.

app/components/frame-viewer.jsx
Fixes #3676. The FrameViewer should only enabled the PanZoom controls if the frame type is image. Long term, the FrameViewer should only rendered the PanZoom component for image frames, which is being addressed in #3695.
=> only enable pan-zoom controls for images

app/pages/lab/visibility.cjsx, app/pages/project/stats/index.jsx
Fixes #3683.
This PR allows inactive workflows to be visible on a project's stats page by setting the visibility in the lab.  This also changes the check box on the lab visibility page from `Hide on Stats Page` to `Show on Stats Page`.  I have used the same `workflow.configuration.stats_hidden` parameters that was being used before, so this *should* not change the current look of any live project's stats pages.
Note: Some of the logic is a bit confusing since it defaults inactive workflows that don't have `workflow.configuration.stats_hidden` to be not visible.
=> allow inactive workflows to be shown on the stats page

app/pages/project/project-page.cjsx
Fixes #3709 .
Uses React router to figure out if we're on a project home page, rather than comparing strings with the window location.
=> Don't use string comparison to figure out home page path

app/classifier/tasks/survey/chooser.cjsx
Fixes #2913 
Adds `else` block to make sure `img` attribute `alt-text` is rendered if file not specified/uploaded.
Test it here against production https://fix-2913.pfe-preview.zooniverse.org/projects/mrniaboc/zooniverse-go/classify
=> Render button even when file not specified

app/components/text-viewer.jsx, css/subject-viewer.styl
Rewrites the text viewer to fix a bug where it manipulates the DOM before it has rendered.
Sets a minimum width of 30em for text subjects.
Adds content caching, by URL, for text subjects.
=> Fix null or undefined DOM node in text viewer

app/components/subject-viewer.cjsx
Fixes #3700 .
Calls `getInitialFrame` if the subject changes in the subject viewer.
=> Reset the default frame on subject change

app/classifier/classifier.jsx, app/classifier/task-nav.jsx
Fixes: the Done button can be clicked, to submit a classification, while the subject is loading.
Adds a `disabled` prop to the `TaskNav` component, which disables the buttons. Sets that prop while the subject is loading.
=> Disable TaskNav component while subject is loading.

app/pages/lab/subject-set.cjsx
Removes subject upload module if subject limit has been reached.
It's a way of getting around https://github.com/zooniverse/Panoptes-Front-End/issues/921
However, the current code means users over the limit need to reload the page to get the upload module back, which is less than ideal.
So, this an interim solution while I work on the refactor of the subject upload related files. Once the flow of props is clearer and `ChangeListener` removed, I believe we can update the view without manual refresh.
If this doesn't seem very helpful/necessary, feel free to close and I'll submit a new PR with the refactor.
=> Remove subject upload module if subject limit has been reached

app/pages/project/index.cjsx
Fixes: field guide disappears from project pages if there are no attached images.
Changes the default value of `guideIcons` from `null` to `{}`
=> Default guideIcons to an empty object

app/components/subject-viewer.cjsx
Fixing a bug found while doing collections work. Can be seen on master staging:
https://master.pfe-preview.zooniverse.org/collections/chrissnyder-test/test
Fix seen here:
https://fix-default-frame-bug.pfe-preview.zooniverse.org/collections/chrissnyder-test/test
=> Fix default frame bug

app/classifier/classification-summary.jsx
When rendering a Worldwide Telescope summary, the classification-summary component was looking for the wrong tag. Because of this, the WWT link was not appearing in the summary.
https://fix-wwt-summary.pfe-preview.zooniverse.org/
=> Adjust WWT Summary Tag

app/pages/lab/subject-set.cjsx
Fixes #3731.
The subject upload drag and drop area shouldn't be hidden for users who have been whitelisted. 
@mschwamb can you upload using this staged link? https://upload-whitelist.pfe-preview.zooniverse.org/?env=production
=> Add check for upload whitelist

app/collections/create-form.cjsx, app/collections/manager-icon.cjsx, app/collections/manager.cjsx, app/collections/show-list.cjsx, app/collections/show.jsx, css/collections-page.styl
WAIT TO MERGE - wait for notice to be given to users before merging.
Fixes #3483.
Changes to general design of a collection.
Add functionality to select then add or remove multiple subjects in a collection.
I've been testing in this project's collections:
https://collections-add-delete-multi-subjects.pfe-preview.zooniverse.org/projects/markb-panoptes/test-project-mb/collections
Remaining Open Items:
=> [Wait to Merge]Add Collection functionality to add-delete multiple items

app/classifier/classifier.jsx, app/classifier/custom-sign-in-prompt.jsx, app/classifier/index.cjsx, app/pages/project/classify.cjsx, app/pages/project/index.cjsx, css/classify.styl, css/common.styl, css/project-page.styl
Fixes #3466
This is the novelty experiment for Gravity Spy. Rather than remove the text split that was setup previously, this adds another kind of visibility split experiment that shows a banner informing the volunteer they are the first to see the subject prior to classification. Labeled as WIP since experiment still needs setting up on Seven-Ten staging. Will add staging link once it is working.
=> First to classify experiment

css/project-page.styl
Fixes an overflow problem for research quotes that contain long words without spaces, such as a url. 
=> fix researcher word overflow

app/components/subject-viewer.cjsx, css/subject-viewer.styl, css/survey-task.styl, css/talk.styl
Fixes #3514.
Adds keyboard support by replacing buttons with named radio inputs, which can be controlled using the cursor keys.
=> Replace slideshow buttons with radio buttons

app/classifier/annotation-renderer/image.jsx, app/classifier/annotation-renderer/index.jsx, app/classifier/annotation-renderer/svg.jsx, app/classifier/frame-annotator.jsx, app/classifier/frame-annotator.spec.js, app/classifier/tasks/crop/index.cjsx, app/classifier/tasks/drawing/index.cjsx, app/components/frame-viewer.jsx
Separate SVG drawings out of the frame annotator so that we can add renderers for annotations for subjects other than images.
=> Break out SVG annotations from frame annotations.

app/classifier/frame-annotator.jsx
Fixes #3750 where the subject viewer is rendered twice.
Children should not be implicitly passed down from `FrameAnnotator` since the child component is self-closing in the JSX code.
=> Don't pass children down with FrameAnnotator props

app/components/pan-zoom.jsx, app/components/pan-zoom.spec.js
Fixes mouse wheel zoom, which has [broken in Chrome](https://www.zooniverse.org/talk/17/302541).
Adds an explicit handler for wheel events.
Removes `e.which` to detect mouse wheel events, since that is unreliable.
=> Fix mousewheel zoom on Chrome

app/pages/lab/subject-set.cjsx
Follow up to https://github.com/zooniverse/Panoptes/issues/1037#issue-91752692
Makes the text on the subject-set delete button less ambiguous.
Also, adds a note to the alert box.
=> Makes clearer that subjects don't get deleted

app/classifier/tasks/survey/chooser.cjsx, app/classifier/tasks/survey/editor.cjsx
Allows a project builder to set if thumbnails should always be shown for the options of a survey task.  Currently thumbnails are only shown if their are fewer than 20 survey options, a setting that makes sense for camera trap projects, but for other use cases small thumbnails might be fine.
Example case: https://always-show-thumbnail-suvey-task.pfe-preview.zooniverse.org/projects/cmk24/test-porject-1/classify?reload=0&workflow=2909
The thumbnails for this survey task are just colors assigned to various emotions.  The emotions are ordered by color, so if the thumbnails are not shown the order does not make much sense.
=> allow project builder to always show thumbnails for survey task

app/pages/project/classify.cjsx
Fixes a regression introduced in #3681 
Log classificationCreated metric after the classification post, so that we have the id.
Staging project with active Seven-Ten split now correctly posts to `/metrics` with a value in the payload: 
https://metric-log-fix.pfe-preview.zooniverse.org/projects/srallen086/workflow-assignment-testing/classify
=> Call split classification log after the post, so we have an id

app/classifier/index.cjsx
Modifying the messaging and adding a geordi log for the Gravity Spy novelty experiment
Staging test project:
https://gs-split-tweaks.pfe-preview.zooniverse.org/projects/srallen086/workflow-assignment-testing/classify
=> Modify banner message and add geordi log for GS split

app/components/file-viewer/index.jsx
Might help fix #3729 .
Adds a default FileViewer component for the case where file type is undefined/unknown on first render.
=> FileViewer should always return a React component

app/components/subject-viewer.cjsx
Fixes #3729.
Stop the slideshow player on subject change, and reset the frame counter.
=> Stop playing on subject change

app/classifier/annotation-renderer/svg.jsx, app/classifier/tasks/combo/index.cjsx, app/classifier/tasks/combo/markings-renderer.jsx, app/classifier/tasks/drawing/markings-renderer.cjsx
Fixes the `fauxClassification` hack in the combo task.
Adds an annotations prop for passing annotations to `MarkingsRenderer`.
Allows the combo task to override the classification and pass its own set of marks to render.
=> Pass annotations explicitly to the markings renderer

app/pages/lab/workflow.cjsx
Fixes a scenario where a project sets a workflow as default and then deletes it. This removes the project workflow default if it is the default. 
https://remove-default-if-deleted.pfe-preview.zooniverse.org/
=> Don't let deleted workflows be default

app/pages/projects/index.jsx, app/pages/projects/status-link.jsx
Fixes #3784 .
Set a default value for the status param instead. Remove the method that updates browser history automatically if the query param isn't present.
=> Don't redirect /projects to /projects?status=live

app/classifier/drawing-tools/full-height-line.cjsx, app/classifier/drawing-tools/full-width-line.cjsx, app/classifier/drawing-tools/index.coffee, app/classifier/tasks/drawing/icons.cjsx, app/pages/dev-classifier/mock-data.coffee
Fixes #1029. I still had my head in drawing tools, and thought I'd knock something up quickly.
https://full-width-line-marking.pfe-preview.zooniverse.org/projects/rogerhutchings/one-click-lines
=> Add full height and width line tools

app/pages/projects/index.jsx, app/pages/projects/status-link.jsx, css/secondary-page.styl
Adds tab roles and states to the Active/Paused/Finished buttons on the Projects page. Styles them according to selected state.
=> Mark up project status tabs as tabs

app/pages/collections/collection-card.jsx
Without this small change, empty collections break the collections list page and preview images don't appear.
=> Check for image src before setting a collection preview

app/classifier/tasks/combo/markings-renderer.jsx
Fixes a couple of warnings that come up when running tests.
=> Fix prop type validation

app/components/subject-sets.jsx, app/pages/lab/project.cjsx, app/pages/lab/subject-set.cjsx, app/pages/lab/subject-sets-container.jsx, app/pages/lab/subject-sets.jsx, app/pages/lab/subject-sets.spec.js, app/pages/lab/workflow-viewer/index.cjsx, app/pages/lab/workflow.cjsx, app/pages/lab/workflows-container.jsx, app/pages/lab/workflows.jsx, app/pages/lab/workflows.spec.js, app/router.cjsx
Fixes #3268 
This creates standalone lab pages for workflows and subject sets rather than having them on the left sidebar. It also adds pagination for both pages. Tests included.
https://new-lab-pages.pfe-preview.zooniverse.org/
=> Create Workflow and Subject Set Lab Pages

app/pages/lab/workflow.cjsx
this info should be on the workflows page (separate pull request in for that), but thought best to keep things separate and put in two pull requests. This one just removes the no longer relevant from each specific workflow page in the project builder.
=> remove help line about sorting order of multiple workflows

app/pages/lab/workflows.jsx
added help text that is on the individual workflow pages which isn't relevant anymore with the redesign and should be on this new workflows page.
Fixes # .
=> added help content to tell people how to reorder workflows

app/components/file-viewer/video-player.jsx, css/subject-viewer.styl
Fixes #3765 
Removes the custom video play button and scrubber, in favour of the native browser controls.
=> Native video

app/pages/project/stats/stats.jsx
Fixes https://www.zooniverse.org/talk/17/331857?comment=553695
don't calc and eta for complete workflows, just report 0. 
This looks like i should be extracting the ETA to a class as i've got a props data clump here. Thoughts on best practice for this instead of just 2 functions to create the html.
=> better ETC for finished workflows

app/classifier/annotation-renderer/svg.jsx, app/classifier/tasks/combo/index.cjsx, app/classifier/tasks/crop/index.cjsx, app/classifier/tasks/drawing/index.cjsx, app/components/frame-viewer.jsx
Fixes #3803 .
Add `pointerEvents: 'none'` to the SVG inline styles if the combo does not contain any drawing tasks.
We should really be using CSS classes instead of inline styles. This is just a quick patch to get Notes from Nature working again.
=> Set pointer events CSS for combo tasks

app/pages/project/stats/stats.jsx
previous refactor ignored other use or a the totalCount param, extracted to a const and passing around where it's needed.
Fixes #3815  linked to #3804
=> ensure param is available everywhere it's used

app/classifier/annotation-renderer/svg.jsx, app/classifier/tasks/combo/index.cjsx, app/classifier/tasks/crop/index.cjsx, app/classifier/tasks/drawing/index.cjsx, app/components/frame-viewer.jsx
Reverts zooniverse/Panoptes-Front-End#3808. This caused a bug by not allowing marking tasks to annotate a subject.
=> Revert "Set pointer events CSS for combo tasks"

app/components/file-viewer/video-player.jsx, css/subject-viewer.styl
Fixes #3818.
This adds the CSS hack to hide the download button for Chrome 57 users and the `controlsList` property for Chrome 58 users. We aren't really going to stop users from being able to download, but this at least hides the button Chrome added recently so it doesn't look like we're promoting downloads. React doesn't support the `controlsList` property yet, so I'm adding it manually on `componentDidMount` using a ref to the element. I've also added a black background color to the video element for small screen sizes. The video can get smaller in the player and can show the project background.
https://fix-3818.pfe-preview.zooniverse.org/projects/zooniverse/arizona-batwatch/classify?env=production
=> hide download button shown in Chrome

app/classifier/tasks/survey/chooser.cjsx
Reduces the amount of tabbing required to navigate the survey task
Treat the choice list in the same way as a dropdown menu for keyboard navigation.
Apply tabindex=0 to a single choice (either the currently focused choice or the first choice.) Tab/shift-Tab then navigates into and out of the menu rather than between choices. Use the up/down keys to select choices when the list has focus.
=> Tab to survey choices as a grouped control

app/classifier/task-nav.jsx
Fixes: Done & Talk isn't showing up on any project that uses it eg. Steller Watch and Gravity Spy
Inverts one of the true/false checks for feedback so that talk is disabled if feedback is active and the current subject has feedback.
=> Fix Done & Talk button

app/layout/account-bar.jsx
Doesn't focus the first menu item when the account menu opens. Instead, enter the menu, from the account button, with the down arrow key.
Also cleans up the account bar javascript and removes `React.CreateClass`.
=> Account menu keyboard focus

app/layout/account-bar.jsx, app/layout/expandable-menu.jsx, app/layout/site-subnav.jsx
Adds keyboard support to the News menu, as per #3826.
Adds an `ExpandableMenu` component which can be used for any button that triggers a popup menu.
=> News menu focus

app/components/pan-zoom.jsx
Removes string refs from the PanZoom component.
Moves the `wheel` and `keyDown` event listeners to the component's root element, so that default scrolling behaviour isn't overridden for the window.
=> Pan zoom refs

app/classifier/drawing-tools/freehand-helpers.coffee, app/classifier/drawing-tools/freehand-line.cjsx, app/classifier/drawing-tools/freehand-segment-line.cjsx, app/classifier/drawing-tools/freehand-segment-shape.cjsx, app/classifier/drawing-tools/freehand-shape.cjsx, package.json
Contributes to #3551. Uses the `lodash.round` function to round coord data to 1 decimal place. This is then filtered for duplicates as normal.
https://freehand-limit-accuracy.pfe-preview.zooniverse.org/projects/rogerhutchings/etch-a-cell/classify
=> Limit accuracy for freehand drawing to 1 decimal place

app/classifier/gs-gold-standard-summary.jsx
In anticipation of the announcement next Thursday, this adds support for subjects that have the specified metadata fields to show a custom message. We should get this merged by Tuesday next week at the latest.
CC @rogerhutchings we'll need to consider adding into the generalized feedback feature a way for projects to show a custom feedback message regardless of the annotation. I would have liked Gravity Spy to use the new generalized feedback feature, but I don't think it is designed to handle this use case even if we had survey task support added. 
This test project has a couple of subjects labelled as 'special' that comes up and has a feedback message that says 'congrats': https://gs-special-event-feedback-message.pfe-preview.zooniverse.org/projects/markb-panoptes/gravity-spy-gold-standa …
=> Add support for another custom Gravity Spy feedback message

app/classifier/feedback/process-feedback-drawing.js, app/classifier/feedback/process-feedback-drawing.spec.js, app/pages/lab/feedback/types/point/point-edit-form.jsx
Fixes #3760. You can test it at https://marking-feedback-dud.pfe-preview.zooniverse.org/projects/rogerhutchings/feedback-test/classify, and choosing the Point Feedback workflow.
cc @aprajita
=> Allow feedback to handle dud subjects

app/classifier/gs-gold-standard-summary.jsx
Adds markdown support for Gravity Spy's custom message. Also renamed the metadata field being used to be close to what will be used more generally (See #3833 )
Can be seen with this test project with the 'special' labelled subjects: https://use-markdown-gs-feedback.pfe-preview.zooniverse.org/projects/markb-panoptes/gravity-spy-gold-standard-notice-test-project/classify
=> Add markdown support for GS custom summary message

app/classifier/task-nav.jsx
Fixes #3836.
Adding `!completed` to the conditional for the Done & Talk button rendering in the Task Nav fixes it for Gravity Spy where they normally hide the summary unless it's a subject that has metadata feedback. 
https://fix-3836.pfe-preview.zooniverse.org/projects/markb-panoptes/gravity-spy-gold-standard-notice-test-project/classify
=> Add check for classification completion for rendering Done & Talk

app/classifier/tasks/combo/editor.cjsx, app/classifier/tasks/combo/editor.spec.js
Fixes #3840 .
Checks `workflow.tasks` for task keys that have been deleted, when the ComboEditor mounts.
=> Combo task editor

app/classifier/frame-annotator.spec.js, app/classifier/tasks/combo/editor.spec.js
Otherwise, this will break other tests that import the mock workflow data.
Fixes tests that were broken in #3847
=> Mutate copies of mock workflow and task data

app/pages/lab/data-dumps.cjsx, app/partials/data-export-button.cjsx
Fixes #3742.
I didn't want to remove code, and the issue did not say to create a experimental feature flag, so I just added `display:none` styling on the button.
=> Hide aggregation export button

app/pages/admin/project-status/experimental-features.jsx, app/pages/lab/data-dumps.cjsx, app/pages/lab/export-workflows-dialog.jsx, app/pages/lab/workflow-classification-export-button.jsx, css/main.styl, css/workflow-export-dialog.styl
Fixes #3693.
- Replace select box with radio button list.
- API request to fetch export media.
- Links to previous exports.
- Only export every 24 hours.
https://workflow-exports-links.pfe-preview.zooniverse.org/lab/1663/data-exports
=> Workflow exports links

app/classifier/drawing-tools/full-height-line.cjsx, app/classifier/drawing-tools/full-width-line.cjsx
The full width and height line tools were using the `containerRect` property to determine valid annotations, causing annotations at the edges to be invalid. This fix changes that to use the `naturalHeight` / `naturalWidth` props instead.
Fixes #3865 .
Staging branch: https://full-height-line-fix.pfe-preview.zooniverse.org
Test project on staging: https://full-height-line-fix.pfe-preview.zooniverse.org/projects/rogerhutchings/one-click-lines/classify
=> Use naturalHeight and naturalWidth to determine validity of full height / width lines

app/classifier/drawing-tools/freehand-line.cjsx
Sets the `pointerEvents` prop to stop clicks inside a shape triggering click the select event, allowing users to draw inside.
Test project: https://freehand-fix.pfe-preview.zooniverse.org/projects/rogerhutchings/etch-a-cell/classify
=> Allow drawing inside freehand lines

app/layout/site-nav.jsx, css/site-nav.styl
Fixes #3880 .
Bolden font-weight on navbar links, as the text was light on Safari/Edge. Also adjusted the mobile navbar breakpoint since the weight affected the width of each link.
https://nav-bar-adjust.pfe-preview.zooniverse.org/
=> Adjust Navbar Weight

css/survey-task.styl
Changes the focus style for survey choice checkboxes and radio buttons to a blue border. The green background currently in use is confusing, since it makes the focussed answer appear to have been selected, even when it hasn't.
=> Change survey focus style to a blue border

app/classifier/tasks/highlighter/index.jsx, app/pages/admin/project-status/experimental-features.jsx, app/pages/lab/workflow.cjsx
Fixes two issues with the highlighter tool in IE11. 
In `#getOffset`, the `for...of` loop is replaced with a `for` loop.
In `#selectableArea`, `parentElement` is replaced with `parentNode`.
=> IE11 fix for highligther tool

app/pages/lab/index.cjsx
The unknown role "workaround" has been spotted by @marten. This seems to be its only instance and it can be removed with no harm to the surrounding ecosystem.
=> Remove the non-existent role 'workaround'

app/pages/lab/project-details.cjsx
Fixes #3862 
Fixes #2317
Updates the state of the `ProjectDetails` component when a new image resource is uploaded so changes are immediately reflected.
https://project-avatar.pfe-preview.zooniverse.org/
=> Force image resources to update in project builder

app/classifier/tasks/combo/editor.cjsx
Removes a log probably missed in review for the combo editor. It was printing during test runs.
=> Removed extraneous log from combo editor

css/talk.styl
Fixes #3895. Adds styles for the subject tools on Talk similar to the styling it has on the classify page.
https://fix-3895.pfe-preview.zooniverse.org/projects/zooniverse/arizona-batwatch/talk/230/368256?env=production
I also checked Gravity Spy and it looks ok there, too. Still needs cross-browser check.
=> Fixes 3895 by fixing tools styling on Talk

app/pages/lab/landing-page.cjsx
Fixes #3900. 
In labLanding.content, I changed `/lab-how-to` to `/help`. I think the way markdown renders the link bypasses the routes setup in `router.cjsx`. Linking to `/help` in `labLanding.content` provides users with an active tab of content instead of no content.
=> use /help instead of /lab-how-to in markdown

webpack.build.js
=> Add JSON loader to production webpack config

app/classifier/world-wide-telescope.jsx, app/classifier/world-wide-telescope.spec.js, css/world-wide-telescope.styl
Astronomy Rewind is launching a workflow soon that uses the WWT. With that, there are a couple changes that were made to the component.
- A hashed string is confusing for the URL title. 'Zooniverse' will suffice
- The WWT button displayed awkwardly and had redundant text
- If possible, use a subject's metadata to find a publication date and determine an epoch
- Any axis point belonging to a unit besides RA/DEC/GLAT/GLON should be tossed out
https://wwt-adjustments.pfe-preview.zooniverse.org/
=> WorldWide Telescope Adjustments

app/pages/project/index.cjsx
Fixing for projects that are close to complete but aren't yet actually. Requested fix from slack chat. Uses `project.completeness is 1.0` instead of `project.completeness > 0.99`
https://use-one-for-project-completeness.pfe-preview.zooniverse.org/projects/panthera-research/camera-catalogue?env=production
=> Use 1 for completeness

app/pages/lab/project-details.cjsx
Fixes #3735 #3897 - API now always returns a list of tags, so use the tag, not a part of it.
=> fix project discipline tags

app/collections/collection-search.cjsx, app/collections/collections-manager.jsx, app/collections/collections-manager.spec.js, app/collections/show-list.cjsx, css/collections-page.styl
Fixes #3821 by preemptively filtering out the ids of the subjects to add array by comparing it to the serialized subjects linked of the collection. This also fixes when the add button is disabled as well as improve the error messaging UI. If all of the selected subjects are already added to the target collection, a clearer message is displayed and the modal doesn't auto-close so the user has a chance to read it.
https://fix-3821.pfe-preview.zooniverse.org/
=> Collections subject adding bug fixes

app/pages/lab/subject-sets.jsx, app/pages/lab/workflows-container.jsx, app/pages/lab/workflows.jsx, app/pages/lab/workflows.spec.js, css/common.styl, css/paginator.styl, css/talk.styl
For #3904.
I've add a button to toggle between a default list view with pagination and a view that uses `DragReorderable`. I've updated the tests to reflect the UI changes. This needs to be checked to see if it works for Notes from Nature.
https://reworked-workflows-ui.pfe-preview.zooniverse.org/
=> Reworked workflows lab page to toggle between reorder and list views

app/pages/about/publications-page.cjsx
* Fixes #3931
* On localhost (i.e. when viewing _staging_ data) the Publications page crashes.
* This crash does not occur when viewing zooniverse.org (i.e. when viewing _production_ data)
* This boils down to the fact that the Publications page expects a list of projects from the Panoptes API that's different between staging and production.
* This PR fixes the issue for localhost.
Tagging @mariamsaeedi for the opportunity to review how a PR is constructed.
In this section of code...
```
67.  {for projectListing in projects
68.    project = @state.projects[projectListing.slug]
69.    <div key={projectListing.name or project.slug}>
```
...there is no guarantee that the `project` variable on line 68 will be defined. `projectListing.slug` will iterate through all the project slugs listed in …
=> Prevent Publications page crashing on staging

app/lib/social-icons.js, app/pages/lab/external-links-editor.jsx, app/pages/lab/project-details.cjsx, app/pages/lab/social-links-editor.jsx, app/pages/lab/social-links-editor.spec.js, app/pages/project/project-page.cjsx, css/lab.styl, css/tabbed-content.styl, test/setup.js
Fixes #489 
This adds a social links editor to the project lab page. More info. can be found in the issue.
This proved to be a bit trickier than I first suspected, since a projects external links and social links are both contained in the same `project.urls` array, and I had to find a way to identify, edit, and separate a project's social links from regular external links. 
https://reveal-social-icons.pfe-preview.zooniverse.org/
=> Reveal Project Social Icons in Lab

app/main.cjsx, app/pages/lab/visibility.cjsx, css/lab.styl
Fixes part of #3904.
- Add paginator component for workflows in project builder visibility page.
- Uses page_size of 20. This can be removed when getWorkflowsInOrder does not override the default page_size.
Staged at https://lab-visibility-paginator.pfe-preview.zooniverse.org/lab/1613/visibility
=> Lab visibility paginator

app/classifier/annotation-renderer/index.jsx, app/classifier/annotation-renderer/svg.jsx, app/classifier/annotation-renderer/text.jsx, app/classifier/frame-annotator.jsx, app/classifier/tasks/generic-editor.cjsx, app/classifier/tasks/highlighter/index.jsx, app/classifier/tasks/highlighter/label-editor.jsx, app/classifier/tasks/highlighter/label-renderer.jsx, app/classifier/tasks/highlighter/selection.jsx, app/classifier/tasks/highlighter/summary.jsx, app/classifier/tasks/index.jsx, app/components/file-viewer/index.jsx, app/components/file-viewer/text-viewer.jsx, app/components/frame-viewer.jsx, app/lib/get-subject-location.coffee, app/pages/admin/project-status/experimental-features.jsx, app/pages/lab/workflow.cjsx, css/highlighter-task.styl, css/main.styl
Work towards #3458.
Requesting feedback on this approach for a highlighting tool. [Example of the highlighting tool](https://highlighter-tool-v2.pfe-preview.zooniverse.org/projects/scribe-2/textsubjectproject/classify?reload=0&workflow=2831).
On the project above, a user highlights some text and then clicks that text selection to record the annotation. That is not a task flow we want in the end product. @eatyourgreens [suggested a task flow of 1) highlighting text, 2) selecting label for the highlighted text (like Diagnosis London)](https://github.com/zooniverse/Panoptes-Front-End/issues/3458). I am working on implementing this structure for the task. 
- Adds a highlighter task to the workflow editor. The highlighter task has a similar structure to the drawing task. …
=> Text Highlighter Task

app/components/file-viewer/audio-player.jsx
Fixes a couple of eslint warnings about long lines
=> Fix a couple of long lines in AudioPlayer for eslint

app/classifier/tasks/survey/choice.cjsx, app/classifier/tasks/survey/index.cjsx
Fixes #3727 .
Replaces https://github.com/zooniverse/Panoptes-Front-End/pull/3946
If the current choice of a survey task already exists, this allows to edit it and submit it as _one_ classification.
=> Survey task: Prevent multiple classifications of same choice

app/classifier/tasks/highlighter/index.jsx
Fixes an issue of inconsistent `range.endOffset` values in IE11 and Edge when highlighting the end of a line. See #3873 and #3738.  
Adds method `#extraNewLineCharacter()` to Highlighter. The method checks the `range.endOffset` value for an extra newline character. If there is an extra newline character included in the `range.endOffset` value, the method returns a value one less than the `range.endOffset`.
=> Highlighter Tool fix for IE11 and Edge

app/partials/markdown-help.cjsx
[Talk discussion about writing links in Markdown](https://www.zooniverse.org/talk/18/403792?comment=673609&page=1) implies the instructions are confusing
Removes the 'URL shortening' wording and tries to clarify internal vs. external links
=> Clarify how to write links in Markdown

package.json
- custom port for dashboard plugin matches the one set in [`webpack config`](https://github.com/zooniverse/Panoptes-Front-End/blob/master/webpack.dev.js#L33)
- staged [here](https://webpack-dashboard-custom-port.pfe-preview.zooniverse.org/)
=> Add webpack dashboard custom port to cli script.

app/pages/project/stats/index.jsx
Towards #3904.
Currently NfN's most recent workflow, 4667 Butterfly_Hummingbird Moths, does not appear on [the project stats page](https://www.zooniverse.org/projects/zooniverse/notes-from-nature/stats) because the `getWorkflowsInOrder` request's `page_size` is 100, and this workflow is over that `page_size`.
This PR changes the stats page `getWorkflowsInOrder` request's `page_size` to the `project.links.workflows.length`, resulting in the inclusion of the recent workflow - https://edit-stats-workflows-request.pfe-preview.zooniverse.org/projects/zooniverse/notes-from-nature/stats?env=production.
=> edit stats workflow request to page_size of project.links.workflows.length

webpack.dev.js
Addition to [PR 3951](https://github.com/zooniverse/Panoptes-Front-End/pull/3951).
- Add comment in `webpack.dev` referencing the webpack dashboard custom port config in `package.json`.
- Staged [here](https://webpack-dashboard-custom-port.pfe-preview.zooniverse.org/).
=> Add comment in webpack config file regarding custom port.

.eslintrc, app/classifier/tasks/highlighter/index.jsx
In the eslint file, I added an exception for the no-underscore-dangle rule, so that we don't get lint errors when using `_toolIndex`.
=> exception for _toolIndex in no-underscore-dangle eslint rule

app/lib/social-icons.js, app/pages/lab/social-links-editor.spec.js
Fixes # .
This PR adds Instagram and Medium as social media icon options on the project builder.
https://add-instagram.pfe-preview.zooniverse.org/
=> Add Instagram and Medium Social Icons

.travis.yml, Dockerfile
Updates Travis and Docker configs to use latest node 8.
=> Use node 8 for CI and Docker builds

app/pages/project/classify.cjsx, css/classify.styl
For #3122 and to support the Intro2Astro use case with the EducationAPI front end being built.
This adds a check for the presence of the url query param `?group=id` and if present, adds the `user_group` id to the classification metadata on create as well as adds a UI notification banner that you are a student classifying with your classroom.
Can be seen working on staging: https://classify-by-group.pfe-preview.zooniverse.org/projects/brooke/i-fancy-cats/classify?group=2534
Note: I'm not validating the id in the query param that it is actually a group that exists nor am I validating that the user is authenticated or that the user is in that group. We may want to consider these validations, but I can add those in subsequent PRs. 
I know we talked in the last retrospective being more strict …
=> Add group query param and group id to classification metadata

app/pages/projects/filtered-projects-list.jsx, app/pages/projects/project-filtering-interface.jsx
Allow the page_size query param to filter to the API call for easy page size modifications from the URL. Useful for testing things like project card listing sizes.
=> respect projects page_size query param

.github/PULL_REQUEST_TEMPLATE.md
This resumes the conversation about the PR template I interrupted by hastily closing https://github.com/zooniverse/Panoptes-Front-End/pull/3963
As suggested by @srallen, I removed the type-check checkbox, because the linter catches that.
=> Remove type-check checkbox

css/slider-task.styl
Fixes #3996.
On wide screens the slider number input satisfied the minimum pixel width (50px) at the specified width (5em), but the padding overcrowded the number. This sets a padding (1em) and width (5em) that I believes scales appropriately.
=> edit slider input number styling

app/classifier/tasks/slider/index.jsx, app/classifier/tasks/slider/slider.spec.js
Fixes #4003 .
Set value properly on annotation prop change.
Set step properly on the number input (though browsers may ignore this.)
=> Sync slider task value and annotation value

app/classifier/annotation-renderer/svg.jsx, app/classifier/frame-annotator.spec.js, app/classifier/tasks/combo/markings-renderer.jsx, css/classify.styl, css/frame-annotator.styl
Fixes #3989 
Some small changes to the subject viewer. Inline styles are moved to the style sheet. Background colour and positioning are applied to a `div`, instead of to the `svg` element.
The combo task now checks whether a task renders SVG before rendering SVG marks.
These changes were made while trying to discover why Firefox 55 isn't displaying SVG images properly in the classifier. Unfortunately, it doesn't fix that bug.
UPDATE: checking the image size before rendering seems to fix the SVG image in FF 55+.
=> Optimise subject viewer CSS and fix Firefox image rendering bug

app/pages/admin/user-settings.jsx
Fixes #4007, adds a checkbox to the user admin page to add the `banned` property to a user.
https://ban-user.pfe-preview.zooniverse.org/
=> Add checkbox to ban a user

app/lib/publications.js
Fixes #3988 .
Moves the Sprinks et al. 2017 paper from climate to meta in the publications list.
=> Move Sprinks et al. 2017 from climate to meta

app/talk/latest-comment-link.cjsx
Adds a check for project slug when constructing a project URL for the latest comment in Talk. Fixes #4016.
https://talk-link-fix.pfe-preview.zooniverse.org/
=> Fix broken latest talk comment link

css/project-page.styl
The Join In button on the project homepage had a defined width that worked for English "join in," but the defined width doesn't work well with other languages. 
Note: On IE, the button width fills the entire section on resize. A further solution can be found if this isn't ideal.
=> Fix Join In Button for Multiple Translations

app/classifier/world-wide-telescope.jsx, package-lock.json
There was an error in the WorldWide Telescope calculations in converting a B1950 epoch into J2000. The correct answer was a bit more involved. In turn, this also fixes plate scale when creating the show image url for WWT.
RA/DEC calculations were tested against [this calculator](http://www.robertmartinayers.org/tools/coordinates.html).
[Staging Branch](https://wwt-coords.pfe-preview.zooniverse.org/)
[Staging Branch w/ Production Env](https://wwt-coords.pfe-preview.zooniverse.org/?env=production)
=> Fix Epoch Calculations With WWT

app/components/frame-viewer.jsx, app/components/pan-zoom.jsx
Fixes #4034.
Removes React.createClass from `PanZoom`.
Deletes the old `componentWillUpdate` method.
Resets the zoom level and rotation if subject or frame width change.
=> Reset PanZoom on subject change

app/classifier/classifier.jsx, app/classifier/task-nav.jsx, app/locales/en.js, app/locales/it.js, app/pages/project/home/metadata.jsx, app/pages/project/home/project-home.jsx, app/pages/project/home/talk-status.jsx, app/pages/project/index.cjsx, app/pages/project/project-page.cjsx, css/project-page.styl
Extract all the English strings, in project UI, to counterpart.
=> Localise project pages

.eslintrc, app/components/pan-zoom.jsx
Checks image height and width for changes before resetting zoom for a new subject.
Fixes some eslint warnings.
Adds an eslint rule for switch/case indentation.
=> Fix a couple of pan zoom bugs

app/classifier/tasks/index.jsx, app/classifier/tasks/index.spec.js, app/classifier/tasks/slider/index.jsx, app/classifier/tasks/slider/slider.spec.js
Refactor slider task to stateless component. Mentioning @eatyourgreens, @tingard and @CKrawczyk. 
IMPORTANT - see PR #4004 for original comments and notes.
Had trouble creating tests to make sure annotation properly updated, related to controlled vs uncontrolled component comments. Added tests for `onChange`, though I'm unsure if that's sufficient. If we can't be comfortable annotation is properly updated with this stateless component, I say we scrap this and leave slider task as is (with state).
I see tests for if task is required, but don't see ability to toggle required in editor?
If there are two slider tasks back to back in a workflow, the second doesn't receive intended focus, unsure how to fix, though I don't think necessary and unrelated to this PR's specific scope, happy to add …
=> refactor slider to stateless component

README.md
- Update readme testing section to address error when Mocha compiles coffeescript files that contain ES6 import statements with template strings.
- Related: https://github.com/zooniverse/Panoptes-Front-End/pull/3428, https://github.com/zooniverse/Panoptes-Front-End/issues/3349
=> Update readme testing text.
